SSAnne_2F_Room5_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
	.string "你去过在浅红市的\n"
	.string "野生原野区吗？\p"
	.string "那里有很多种稀有\n"
	.string "宝可梦。$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
	.string "我和我爸爸觉得\n"
	.string "野生原野区是最棒的！\l"
	.string "我希望我们能再去一次。$"

