SafariZone_North_Frlg_MapScripts::
	.byte 0

SafariZone_North_EventScript_RestHouseSign::
	msgbox SafariZone_North_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips1::
	msgbox SafariZone_North_Text_SecretHouseStillAhead, MSGBOX_SIGN
	end

SafariZone_North_EventScript_AreaSign::
	msgbox SafariZone_North_Text_Area2, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips2::
	msgbox SafariZone_North_Text_ZigzagThroughTallGrass, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips3::
	msgbox SafariZone_North_Text_WinFreeHMFindSecretHouse, MSGBOX_SIGN
	end

SafariZone_North_Text_RestHouse::
	.string "休息屋$"

SafariZone_North_Text_SecretHouseStillAhead::
	.string "训练家贴士\p"
	.string "神秘小屋仍在前方。$"

SafariZone_North_Text_Area2::
	.string "栖息地2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
	.string "训练家贴士\p"
	.string "宝可梦隐藏在高高的草丛中。\p"
	.string "在草丛中区折前行，\n"
	.string "就能把他们找出来。$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
	.string "训练家贴士\p"
	.string "找到神秘小屋就\n"
	.string "能获得免费的秘传机。$"

