SevenIsland_TanobyRuins_Frlg_MapScripts::
	.byte 0

SevenIsland_TanobyRuins_Text_BrandonIntro::
	.string "你知道关于这个\n"
	.string "石头房间的事吗？$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
	.string "那是多余的。\n"
	.string "你不用这么粗鲁。$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
	.string "阿斯卡纳遗迹可以追溯到1500年以前。\p"
	.string "但是它为什么会被建造出来\n"
	.string "仍然是一个谜。$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
	.string "据说有一只神秘的宝可梦\n"
	.string "在里面沉睡。$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
	.string "我不是很擅长战斗。$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
	.string "我听说这儿还有一些\n"
	.string "其他的遗址。\p"
	.string "也许它们是另一些神秘的\n"
	.string "宝可梦的长眠之地？$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
	.string "阿棕正在教我如何画画。$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
	.string "如果我们在这儿吵吵闹闹的，\n"
	.string "可能会陷入麻烦之中。$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
	.string "我说我想画一个古老的建筑。\p"
	.string "所以阿棕就把我带到这儿来了。$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
	.string "今天，除了我们的课程之外，\n"
	.string "我们还要去看看那个石室。$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
	.string "天啊，多么特别啊！$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
	.string "啊，你是在自己学习宝可梦……\p"
	.string "没错，你确实也是个特别的人。$"
