OneIsland_House1_Frlg_MapScripts::
	.byte 0

OneIsland_House1_EventScript_OldMan::
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
	end

OneIsland_House1_EventScript_OldWoman::
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
	end

OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
	.string "在晴天的日子，\n"
	.string "我会去好好地观察火山。\p"
	.string "这是我日常做的事。$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
	.string "让我想想……上一次\n"
	.string "灯火山爆发是什么时候？$"

