SixIsland_WaterPath_Frlg_MapScripts::
	.byte 0

SixIsland_WaterPath_EventScript_HornWantedSign::
	msgbox SixIsland_WaterPath_Text_WantedUltimateHorn, MSGBOX_SIGN
	end

SixIsland_WaterPath_EventScript_RouteSign::
	msgbox SixIsland_WaterPath_Text_RouteSign, MSGBOX_SIGN
	end

SixIsland_WaterPath_Text_RoseIntro::
	.string "我被一阵令人愉快的微风\n"
	.string "一路带到了这儿。$"

SixIsland_WaterPath_Text_RoseDefeat::
	.string "呵呵……你做决定时的样子\n"
	.string "真是可爱。$"

SixIsland_WaterPath_Text_RosePostBattle::
	.string "我想去那边的森林，\n"
	.string "但是……\p"
	.string "那儿有许多虫属性宝可梦。\n"
	.string "我有点儿害怕。$"

SixIsland_WaterPath_Text_EdwardIntro::
	.string "我正在秘密地练习，\n"
	.string "所以没有人能看见我。$"

SixIsland_WaterPath_Text_EdwardDefeat::
	.string "没有人看见我输了，对吧？$"

SixIsland_WaterPath_Text_EdwardPostBattle::
	.string "最为一个演员，\n"
	.string "我不想让人知道我付出的努力。$"

SixIsland_WaterPath_Text_SamirIntro::
	.string "什么，你的意思是你讨厌\n"
	.string "看到像我这样的游泳的人？\p"
	.string "啊，不要这样！$"

SixIsland_WaterPath_Text_SamirDefeat::
	.string "噢，不，别这样。$"

SixIsland_WaterPath_Text_SamirPostBattle::
	.string "我无法消除一个游泳的人\n"
	.string "的耻辱……$"

SixIsland_WaterPath_Text_DeniseIntro::
	.string "我男朋友总是很忙，\n"
	.string "所以我自己出来游泳了。$"

SixIsland_WaterPath_Text_DeniseDefeat::
	.string "啊，我就知道会是这样！$"

SixIsland_WaterPath_Text_DenisePostBattle::
	.string "当我不能和我男朋友在一起时，\n"
	.string "我就和他给我的宝可梦\l"
	.string "一起度过一个人的时光。$"

SixIsland_WaterPath_Text_EarlIntro::
	.string "告诉我，这周围哪里有山？$"

SixIsland_WaterPath_Text_EarlDefeat::
	.string "当我忙于战斗时，\n"
	.string "我迷路了！$"

SixIsland_WaterPath_Text_EarlPostBattle::
	.string "这周围没有山吗？$"

SixIsland_WaterPath_Text_MiuIntro::
	.string "美羽：你好，宝可梦！\n"
	.string "下面是战斗的时间！$"

SixIsland_WaterPath_Text_MiuDefeat::
	.string "美羽：噢，不！\n"
	.string "妈妈！$"

SixIsland_WaterPath_Text_MiuPostBattle::
	.string "美羽：当我们输的时候\n"
	.string "我从心底里感到悲伤……$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
	.string "美羽：美绪和我是双胞胎。\n"
	.string "我们想要一起战斗。$"

SixIsland_WaterPath_Text_MiaIntro::
	.string "美绪：你好，宝可梦！\n"
	.string "下面是战斗时间！$"

SixIsland_WaterPath_Text_MiaDefeat::
	.string "美绪：你太狠了！\n"
	.string "你是坏人，你赢了！$"

SixIsland_WaterPath_Text_MiaPostBattle::
	.string "美绪：噢……\n"
	.string "对不起，我的宝可梦……$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
	.string "美绪：你只有一只宝可梦？\p"
	.string "你不觉得孤单吗？$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
	.string "通缉！\n"
	.string "最后的警报！$"

SixIsland_WaterPath_Text_RouteSign::
	.string "水之步道\n"
	.string "通往遗迹山谷$"

