Route9_Frlg_MapScripts::
	.byte 0

Route9_EventScript_RouteSign::
	msgbox Route9_Text_RouteSign, MSGBOX_SIGN
	end

Route9_Text_AliciaIntro::
	.string "你带着宝可梦！\n"
	.string "你是我的了！$"

Route9_Text_AliciaDefeat::
	.string "你欺骗了我……$"

Route9_Text_AliciaPostBattle::
	.string "这个隧道里面一片漆黑。\p"
	.string "想要穿过山洞的话，\n"
	.string "你需要闪光。$"

Route9_Text_ChrisIntro::
	.string "和那些好看的宝可梦\n"
	.string "一起散步的人是谁？$"

Route9_Text_ChrisDefeat::
	.string "就像一束光！$"

Route9_Text_ChrisPostBattle::
	.string "继续走下去！$"

Route9_Text_DrewIntro::
	.string "我正打算穿过岩山隧道去紫苑……$"

Route9_Text_DrewDefeat::
	.string "无法估计啊……$"

Route9_Text_DrewPostBattle::
	.string "你也是去岩山隧道吗？$"

Route9_Text_CaitlinIntro::
	.string "你竟敢这样对我！$"

Route9_Text_CaitlinDefeat::
	.string "不！\n"
	.string "你太过分了。$"

Route9_Text_CaitlinPostBattle::
	.string "你真的很有天赋。\n"
	.string "祝你好运！$"

Route9_Text_JeremyIntro::
	.string "啊！\n"
	.string "好样的！我很无聊，呃！$"

Route9_Text_JeremyDefeat::
	.string "来这儿吧！\p"
	.string "噢，等等。\n"
	.string "我离开了我的宝可梦！$"

Route9_Text_JeremyPostBattle::
	.string "你确定你有胆量和我对抗，嗯？$"

Route9_Text_BriceIntro::
	.string "哈哈！\n"
	.string "你有一点鲁莽！$"

Route9_Text_BriceDefeat::
	.string "那是什么？$"

Route9_Text_BricePostBattle::
	.string "哈哈！\n"
	.string "小孩子应该坚强点！$"

Route9_Text_BrentIntro::
	.string "我每天都起得很早去\n"
	.string "训练我的宝可梦！$"

Route9_Text_BrentDefeat::
	.string "什么\p"
	.string "多么浪费时间！$"

Route9_Text_BrentPostBattle::
	.string "我必须找到更多虫子\n"
	.string "来使我变得更强大……$"

Route9_Text_AlanIntro::
	.string "哈哈！\n"
	.string "把它带过来！$"

Route9_Text_AlanDefeat::
	.string "呵呵！\n"
	.string "你堂堂正正地战胜了我！$"

Route9_Text_AlanPostBattle::
	.string "哈哈哈哈哈！\n"
	.string "健壮的家伙总是会大笑的！$"

Route9_Text_ConnerIntro::
	.string "去吧，我的超级虫属性宝可梦$"

Route9_Text_ConnerDefeat::
	.string "我的虫子们……$"

Route9_Text_ConnerPostBattle::
	.string "如果你不喜欢虫属性的宝可梦，\n"
	.string "那你就是看不起我$"

Route9_Text_RouteSign::
	.string "9号道路\n"
	.string "华蓝市-岩山隧道$"

