SafariZone_West_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "你不觉得野生原野区\n"
	.string "实在是大得吓人吗？\p"
	.string "浅红的道馆馆主阿桔，\n"
	.string "经常会在原野区里巡逻。\p"
	.string "我们能在这里放心地游玩\n"
	.string "真是多亏了他呢。$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "向宝可梦扔石头\n"
	.string "也许会使他们逃跑，但它们会\l"
	.string "很容易地被抓到。$"

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "使用饵食抓宝可梦会更容易驻留，\n"
	.string "它们可能会忙着去吃那些\l"
	.string "诱饵的话。$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
	.string "我走了很多的路但我没有看到任何\n"
	.string "我想要的宝可梦。$"

