SevenIsland_SevaultCanyon_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Text_CyndyIntro::
	.string "我现在是最佳状态！$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
	.string "呃？\n"
	.string "有些环节出问题了……$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
	.string "我现在在的这条路，\n"
	.string "可能离训练家之塔越来越远了……$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
	.string "如果你偶然拥有了最强的宝可梦，\n"
	.string "那也不要紧……\p"
	.string "若你不能正确地使用它们，\n"
	.string "那你仍然一无是处！$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
	.string "你是这儿的主人！$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
	.string "你一定是经常见到，\n"
	.string "训练家拥有强大的宝可梦\l"
	.string "却不知道如何使用。\p"
	.string "所以在训练宝可梦之前，\n"
	.string "训练家首先自己要成长。$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
	.string "我致力于保护自然环境。\n"
	.string "相应地，大自然也会保护我！$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
	.string "哇！你很强！\n"
	.string "做我的保镖怎么样？$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
	.string "在众多星系之中，\n"
	.string "我们的就如一滴水那么小。\p"
	.string "但是我们想为了每个人\n"
	.string "去保护这滴水。$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
	.string "你穿的那双鞋可真漂亮。$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
	.string "在你可爱的外表下\n"
	.string "隐藏着一颗炽热的心。$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
	.string "你妈妈给你买了这双\n"
	.string "漂亮的跑步鞋？\p"
	.string "她一定很爱你。$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
	.string "你看起来很强大。\n"
	.string "请让我和你战斗吧！$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
	.string "我知道！\n"
	.string "你和我想像的一样强！$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
	.string "你战斗的方式\n"
	.string "给了我许多启发。\p"
	.string "太感谢了！$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
	.string "我受到了最好的教育，\n"
	.string "就是为了变得像今天这样强大。\p"
	.string "我不想输给任何人！$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
	.string "谢谢你。输给你\n"
	.string "使我好像解脱了一样。$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
	.string "有的时候，\n"
	.string "我会因为一些小事感到愤怒。\p"
	.string "我要深呼吸是我自己\n"
	.string "镇定下来。$"

SevenIsland_SevaultCanyon_Text_LexIntro::
	.string "阿力：我亲爱的阿雪，\n"
	.string "一起战斗我们就能赢！$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
	.string "阿力：我刚刚好像太不小心了……$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
	.string "阿力：我想这对于阿雪来说\n"
	.string "是一次好的经历。\p"
	.string "谢谢你。$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
	.string "阿力：你能同时和我们\n"
	.string "两个人战斗吗？$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
	.string "阿雪：我要尽我最大的努力，\n"
	.string "我不会拖我师父阿力的后腿的！$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
	.string "阿雪：噢，不……\n"
	.string "对不起，我……$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
	.string "阿雪：我想我需要更多\n"
	.string "来自阿力的\l"
	.string "调教和指导……\p"
	.string "……所以，阿力，拜托了，\n"
	.string "我可以继续和你呆在一起吗？$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
	.string "阿雪：不好意思，\n"
	.string "我们能来一场2对2的战斗吗？$"

SevenIsland_SevaultCanyon_Text_RouteSign::
	.string "七宝溪谷\n"
	.string "前方是阿斯卡纳遗迹$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
	.string "一个人单独训练\n"
	.string "当然很好。\p"
	.string "但是和一个伙伴一起\n"
	.string "到达顶峰也并不坏。\p"
	.string "甚至是希巴……\n"
	.string "他之前和一个叫做藤树\l"
	.string "的小伙子一起训练。$"
