Route11_Frlg_MapScripts::
	.byte 0

Route11_EventScript_DiglettsCaveSign::
	msgbox Route11_Text_DiglettsCave, MSGBOX_SIGN
	end

Route11_Text_HugoIntro::
	.string "要么胜，要么败，否则就是平手！$"

Route11_Text_HugoDefeat::
	.string "喂！\n"
	.string "别挡了我的路！$"

Route11_Text_HugoPostBattle::
	.string "宝可梦就是生命！\n"
	.string "生命在于竞技！$"

Route11_Text_JasperIntro::
	.string "竞技！\n"
	.string "这一点还满足不了我！$"

Route11_Text_JasperDefeat::
	.string "我还有的是机会！$"

Route11_Text_JasperPostBattle::
	.string "在宝可梦的世界里\n"
	.string "你不能做胆小鬼！$"

Route11_Text_EddieIntro::
	.string "来吧！但不许耍赖！$"

Route11_Text_EddieDefeat::
	.string "嗯？\n"
	.string "这不科学！$"

Route11_Text_EddiePostBattle::
	.string "我尽力了。\n"
	.string "我不遗憾。$"

Route11_Text_BraxtonIntro::
	.string "当心点！\n"
	.string "我正在接电线呢！$"

Route11_Text_BraxtonDefeat::
	.string "电线可是导电的！$"

Route11_Text_BraxtonPostBattle::
	.string "覆盖整个世界运输能源！$"

Route11_Text_DillonIntro::
	.string "虽然我成为训练家没多久。\n"
	.string "但是，这一战我坚信我能赢。$"

Route11_Text_DillonDefeat::
	.string "我的宝可梦还战胜不了你……\n"
	.string "它们还没成长到那个水平吗？$"

Route11_Text_DillonPostBattle::
	.string "刚才发生了什么？\n"
	.string "让我一个人静一静！$"

Route11_Text_DirkIntro::
	.string "哇哈哈哈！\n"
	.string "我从来还没输过呢！$"

Route11_Text_DirkDefeat::
	.string "这是我第一次输！$"

Route11_Text_DirkPostBattle::
	.string "你只是走了狗屎运罢了。$"

Route11_Text_DarianIntro::
	.string "我还从来没赢过……$"

Route11_Text_DarianDefeat::
	.string "我早就想到会是这样的结局了……$"

Route11_Text_DarianPostBattle::
	.string "我的运气还是像往常那样不好。$"

Route11_Text_YasuIntro::
	.string "在班里我是最强的。\n"
	.string "每天早上我都要特训。$"

Route11_Text_YasuDefeat::
	.string "讨厌！\n"
	.string "我的宝可梦要变得更强！$"

Route11_Text_YasuPostBattle::
	.string "那里有一只胖乎乎的宝可梦\n"
	.string "是从山上下来的。\p"
	.string "如果你能收服它\n"
	.string "肯定会得到一个强力伙伴的。$"

Route11_Text_BernieIntro::
	.string "当心电线$"

Route11_Text_BernieDefeat::
	.string "哇哦！\n"
	.string "电火花溅起来了！$"

Route11_Text_BerniePostBattle::
	.string "唉，还是回去工作吧。$"

Route11_Text_DaveIntro::
	.string "我已经精心锻炼了我的宝可梦。\n"
	.string "它们早已为这一刻已做好了准备！$"

Route11_Text_DaveDefeat::
	.string "拜拜！\n"
	.string "谢谢你，有缘再会！$"

Route11_Text_DavePostBattle::
	.string "切……\n"
	.string "我最好还是去找只更强的来！$"

Route11_Text_DiglettsCave::
	.string "地鼠洞穴$"

