gText_ApprenticeChallenge0::
	.string "嗯，我是{STR_VAR_1}的第{STR_VAR_2}号徒弟。\n抽泣……\l这种紧张感快压垮我了……$"

gText_ApprenticeChallenge1::
	.string "我是{STR_VAR_1}的第{STR_VAR_2}号徒弟！\n我们来了！$"

gText_ApprenticeChallenge2::
	.string "我是{STR_VAR_1}的第{STR_VAR_2}号徒弟！\n接受我的挑战吧！$"

gText_ApprenticeChallenge3::
	.string "嗯……我是{STR_VAR_1}的第{STR_VAR_2}号徒弟……\n你觉得像我这样的人能赢吗？$"

gText_ApprenticeChallenge4::
	.string "我是{STR_VAR_1}的第{STR_VAR_2}号徒弟！\n我就让你挑战我吧！$"

gText_ApprenticeChallenge5::
	.string "我忙得要命，但我碰巧也是\n{STR_VAR_1}的第{STR_VAR_2}号徒弟。$"

gText_ApprenticeChallenge6::
	.string "我是{STR_VAR_1}的第{STR_VAR_2}号徒弟。\n很高兴见到你！$"

gText_ApprenticeChallenge7::
	.string "我担任{STR_VAR_1}的第{STR_VAR_2}号徒弟。\n我可以开始了吗？$"

gText_ApprenticeChallenge8::
	.string "呀！我是{STR_VAR_1}的第{STR_VAR_2}号徒弟！\n我会尽力的！$"

gText_ApprenticeChallenge9::
	.string "哟吼！我是{STR_VAR_1}的第{STR_VAR_2}号徒弟！\n放马过来吧！$"

gText_ApprenticeChallenge10::
	.string "我是{STR_VAR_1}的第1000个徒弟！\n其实是第{STR_VAR_2}号啦！我上了！$"

gText_ApprenticeChallenge11::
	.string "没错，我是{STR_VAR_1}的第{STR_VAR_2}号徒弟！\n让我们摇滚起来吧！$"

gText_ApprenticeChallenge12::
	.string "哟吼哟吼！我就是人们所说的\n{STR_VAR_1}的第{STR_VAR_2}号徒弟！$"

gText_ApprenticeChallenge13::
	.string "咳！我是{STR_VAR_1}的第{STR_VAR_2}号徒弟。\n很高兴见到你！咳咳！$"

gText_ApprenticeChallenge14::
	.string "这太紧张了……\n我是{STR_VAR_1}的第{STR_VAR_2}号徒弟。$"

gText_ApprenticeChallenge15::
	.string "我是{STR_VAR_1}的第{STR_VAR_2}号徒弟，\n这可不是骗人的。$"

gText_ApprenticePleaseTeach0::
	.string "你是……{PLAYER}吗？\n哦！抽泣……呜咽……\p哦！对——对不起……\n我太紧张了，忍不住哭了……\p我是{STR_VAR_1}，我真的\n非常崇拜你，{PLAYER}。\p我……我一直梦想着有一天能见到你\n并向你请教关于宝可梦的事。\p求求你，求求你了，{PLAYER}！\n请务必教我关于宝可梦的知识！$"

gText_ApprenticeRejectTeaching0::
	.string "哦……可——可是……\n抽泣……哇啊啊啊！\p求你了！\n我求求你了，拜托！$"

gText_ApprenticeWhichLevelMode0::
	.string "哦，真的吗？你答应了？\n太棒了！太厉害了！嗷呜！\p哦……对不起……\n我太高兴了，又哭了……\p嗯……那么请告诉我！\n是关于对战塔的事。\p对我来说，Lv. 50级\n还是自由等级哪个更好？$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}？\n哇啊啊啊！\p哦！真对不起！\n你替我选择了级别让我很高兴，\l这又让我哭了……\p抽泣……\n太感谢你了！\l请再和我聊聊！$"

gText_ApprenticePleaseTeach1::
	.string "哇哦！你是{PLAYER}，对吧？\n你超强的，对吧？\p我是{STR_VAR_1}！\n我刚成为训练家！\p求你了，{PLAYER}！\n你能当我的老师，告诉我很多\l关于成为训练家的事吗？$"

gText_ApprenticeRejectTeaching1::
	.string "啊，为什么啊？\n哦，拜托？求求你了？\l请当我的老师吧，拜托！$"

gText_ApprenticeWhichLevelMode1::
	.string "耶！太好了！\p我想问你的第一件事是\n关于对战塔的！\pLv. 50级和自由等级的房间……\n哪个最适合我？$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}，是吧？没错！\n我会在那里努力的！\p如果我们在这里再见，请再教我\n点别的，老师！$"

gText_ApprenticePleaseTeach2::
	.string "嗯……你是{PLAYER}吗？\n我的名字是{STR_VAR_1}。\p我想成为一名宝可梦训练家，\n但我不知道该怎么办……\p所以我想也许可以请教你，\n因为你很有名。\p{PLAYER}，\n你能给我一些建议吗？$"

gText_ApprenticeRejectTeaching2::
	.string "哦，但是……\p我是真心想成为一名宝可梦\n训练家的！\p拜托，你能回答我的问题吗？$"

gText_ApprenticeWhichLevelMode2::
	.string "谢谢！\n我马上问第一个问题！\p对战塔有2个级别，\nLv. 50级和自由等级，对吧？\p你觉得哪个级别\n更适合我？$"

gText_ApprenticeLevelModeThanks2::
	.string "哦，挑战{STR_VAR_1}？\n明白了！\p如果我有其他问题，我会\n回来寻求你的建议！$"

gText_ApprenticePleaseTeach3::
	.string "哦？啊？你是……\n不，那不可能是真的。\p像我这样的人不可能\n遇到{PLAYER}。\p……你真的是{PLAYER}？\n真不敢相信我正在和你说话！\p当这么好的事情发生时，\n我知道现在只会发生可怕的事情\l在我身上……\p……对不起……\n我是……{STR_VAR_1}……\p我没什么特别之处可以\n引以为豪……\p我甚至不应该说任何关于\n自己的事，因为你一定会忘记……\p我曾梦想着如果我能遇到\n你，{PLAYER}，也许我就能\l以训练家的身份向你寻求建议。\p但我觉得你不会同意\n那样的事。\p……或者你会好心地\n给我建议吗？$"

gText_ApprenticeRejectTeaching3::
	.string "我就知道会这样……\p这一定是因为我真是个\n无聊的小人物……\p但我以为也许还有机会……\n你不会重新考虑一下，对吧？\p但我不能就这样放弃。\n趁着我运气还在，我要问你！\p拜托，你能好心地给我\n建议吗？$"

gText_ApprenticeWhichLevelMode3::
	.string "真的吗？我不敢相信！\n真不敢相信你会给我建议！\l我……我太高兴了……\p我想问你的其实\n很琐碎，但我无法决定……\p在对战塔，他们让你选择\nLv. 50级或自由等级。\p你觉得哪个级别\n哪怕像我这样的人也可能有机会？$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}？好的！\n但你真的觉得像我这样的人\l会有机会吗？\p我会尽力的，尽管我不\n认为会成功。\p非常感谢你花时间\n陪伴像我这样的人。$"

gText_ApprenticePleaseTeach4::
	.string "哦！你是{PLAYER}{KUN}，对吧？\p我听说你在宝可梦方面很强！\p我是{STR_VAR_1}！\n我会成为你的朋友！\p你知道吗？\p如果你只知道训练家学校教的东西，\n你就无法在对战开拓区获胜。\p我愿意听取你的建议。\n你当然会同意吧？$"

gText_ApprenticeRejectTeaching4::
	.string "嗯？你为什么要拒绝我？\n是我在问你啊！\l你必须重新考虑！$"

gText_ApprenticeWhichLevelMode4::
	.string "好的，所以有件事。\n我想让你替我决定。\p你知道对战塔有\nLv. 50级和自由等级的房间吧？\p你觉得哪个会适合我，\n{PLAYER}{KUN}？$"

gText_ApprenticeLevelModeThanks4::
	.string "好的，{STR_VAR_1}适合我？\n谢谢你！\p知道是你做的决定，\n{PLAYER}{KUN}，就算我输了\l也不会那么难过。\p好的，我会再来向你寻求建议。\n再见！$"

gText_ApprenticePleaseTeach5::
	.string "哦，嗨，你好！{PLAYER}{KUN}！\n我认识你，因为你很有名！\l叫我{STR_VAR_1}！很高兴见到你！\p我是个铁人三项选手，所以我即使\n在培育宝可梦时也保持健康。\p我还参与其他事情，\n比如工作、打盹、交谊舞……\p这么忙，对我来说\n要成为一个像样的训练家\l可不容易。\p所以，我有个提议！\p我们相遇一定有原因。\n所以，{PLAYER}{KUN}，不如你偶尔\l和我分享你的智慧？$"

gText_ApprenticeRejectTeaching5::
	.string "哦，但是，拜托？\n像我这样的人需要你这样的\l人，{PLAYER}{KUN}！\p老实说，我需要你的建议！$"

gText_ApprenticeWhichLevelMode5::
	.string "谢谢你！这才对嘛！\n那么，我们从一个简单的问题开始！\p你知道对战塔的\n2个级别，对吧？\l就是Lv. 50级和自由等级。\p像我这样的大忙人，\n应该为哪个做准备？$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}，是吧？好的，明白了。\n我会想办法找时间试试看的！\p……哎呀，我得去上班了！\n谢谢！回头见！$"

gText_ApprenticePleaseTeach6::
	.string "不可能！呃——呃！\n你该不会是真正的{PLAYER}吧？\p啊哈！太棒了！我是{STR_VAR_1}，\n很高兴见到你！\p{PLAYER}，你很强，\n对吧？\p大家都在谈论你！\p哦！我刚刚有个超棒的主意！\n我要向你请教，{PLAYER}！\l我相信这能让我变强！\p这不是个好主意吗？\n拜托，我想要你的建议！$"

gText_ApprenticeRejectTeaching6::
	.string "啊哈哈哈，你可以假装很凶，\n但你骗不了我！\l你其实是答应的意思，对吧？$"

gText_ApprenticeWhichLevelMode6::
	.string "耶！我就知道你心胸宽广，\n{PLAYER}！\p我该先问你什么呢？\n……哦，我想到了！\p请鼓掌！\n我的问题是……\p如果我要挑战对战塔，\n我该走哪条路？\pLv. 50级还是自由等级？\n哪个更适合我？$"

gText_ApprenticeLevelModeThanks6::
	.string "哦——哦——哦！\n{STR_VAR_1}，你说！\l谢谢你超级酷的回答！\p我想今天要问你的就这些了。\p让我们在这里再见，好吗？\n谢谢！$"

gText_ApprenticePleaseTeach7::
	.string "打扰一下，请问……\n你是{PLAYER}吗？\p我是{STR_VAR_1}，很高兴\n认识你。\p我仰慕你很久了……\p…… … … … … …\p嗯……希望你觉得这个请求\n不会太麻烦，但是……\p我可以成为你的徒弟吗，\n{PLAYER}？$"

gText_ApprenticeRejectTeaching7::
	.string "哦……！\p…… … … … … …\n… … … … … …\p……我一定是震惊得晕过去了。\n对不起，我一定是听错了。\p拜托！请说你愿意\n收我为徒！$"

gText_ApprenticeWhichLevelMode7::
	.string "哦……我很高兴！\p我不想浪费你的时间，\n所以请在这件事上给我建议。\p我计划不久后参加对战塔\n挑战。\p但是，有2个级别……\p哪个最适合我？\nLv. 50级还是自由等级？$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1}是你的选择！\n我明白了。我会尽力的！\p谢谢你，{PLAYER}。\p希望我能再次依靠你。\l请保重！$"

gText_ApprenticePleaseTeach8::
	.string "呀！呀！{PLAYER}！\n你和我说话了！\l我……我太高兴了！\p我！我的名字是{STR_VAR_1}！\n我刚成为训练家！\p我很高兴见到你，{PLAYER}，\n宝可梦界的大名人！\p哦——哦——哦，我知道了！\n我能请你帮个大忙吗，{PLAYER}？\p请收我为徒！\p我想向你学习！$"

gText_ApprenticeRejectTeaching8::
	.string "哇啊啊！\n{PLAYER}拒绝了我……\l这……这是宝贵的经验！\p{PLAYER}，拜托！这次我想听到\n肯定的回答！\p我恳求你的指导！$"

gText_ApprenticeWhichLevelMode8::
	.string "咿耶！{PLAYER}说好！\n{PLAYER}说好！\p我今晚会睡不着觉了……\n太感谢你了！\p那么，这是我的问题！\p在对战塔，什么适合我，\nLv. 50级还是自由等级？$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}！完全明白了！\n我完全明白！\l我高兴得要发狂了！\p希望下次你愿意\n再教我一些东西。$"

gText_ApprenticePleaseTeach9::
	.string "哇！你该不会是……\n难道是……{PLAYER}{KUN}？！\l那个强大又著名的训练家？\l你好，我简直太幸运了！\p你好，我叫{STR_VAR_1}！\p我一直在寻找\n一位宝可梦老师。\p而你来得正是时候，\n{PLAYER}{KUN}！\p所以，就是这样，{PLAYER}{KUN}！\n让我拜你为师吧！$"

gText_ApprenticeRejectTeaching9::
	.string "呱啊啊啊！\n你真是又酷又硬派……\p别这样，拜托。\n我是在请求你！$"

gText_ApprenticeWhichLevelMode9::
	.string "哦，耶！这是坚定的回答！\n太棒了，我得说！\p那么，对战塔的第一个建议\n怎么样？\p如果我要去，哪个更好？\nLv. 50级还是自由等级？$"

gText_ApprenticeLevelModeThanks9::
	.string "嗯哼，{STR_VAR_1}是吧！\n好，A——OK！\l我会去展示我的实力，就像，酷炫！\p好的，我会把你当作我的导师！\n再见！$"

gText_ApprenticePleaseTeach10::
	.string "哦，嘿，{PLAYER}{KUN}，对吧？\n警察在找你！\p…… … …\n当然我是骗你的！\p我呢，我是{STR_VAR_1}。别看我这样，\n我可是宝可梦冠军！\l……那也是骗人的！\p不过接下来不是骗人的。\p我对对战不太在行。\p所以，你来当我的宝可梦万事通\n师父怎么样？$"

gText_ApprenticeRejectTeaching10::
	.string "如果你要表现得这么冷淡，\n我就让你看看我会做什么！\p哇！哇！哇！\n嗝！\p哈哈哈，那是我装的眼泪！\p来吧，拜托你当\n我的宝可梦师父好吗？$"

gText_ApprenticeWhichLevelMode10::
	.string "耶比！\n我会给你买艘船！\p当然我又在撒谎！\n但是……谢谢你，师父！\p你知道对战塔有Lv. 50级\n和自由等级吧？\p我正纠结该挑战\n哪个级别……\p师父你能替我决定吗？$"

gText_ApprenticeLevelModeThanks10::
	.string "好的，所以{STR_VAR_1}更好！\n那我就去另一个级别！\p开玩笑的！\n我会听从你的教导，师父！\p谢谢师父！\p希望你继续教导我！$"

gText_ApprenticePleaseTeach11::
	.string "A——H——O——Y！\n拼出来就是“Ahoy”，意思是“嗨”！\p我就是那个说唱水手！\n现在轮到你了，\l说说你自己吧，试试看！\p嗯哼，嗯哼！\n你叫{PLAYER}{KUN}，\l宝可梦是你的拿手好戏！\p而且你正处在一个微妙的年纪，\n整个世界都是你的舞台！\p总之，我只想说，\n你是我今天交谈过的\l第10位训练家。\p让我们庆祝一下！\p为了纪念，成为我的导师吧！$"

gText_ApprenticeRejectTeaching11::
	.string "但是！\n你必须配合我！\p别这么逗我了！\n请当我的导师吧！$"

gText_ApprenticeWhichLevelMode11::
	.string "就这样！\n{PLAYER}，你有这个精神！\p所以这是我的第一个问题，\n需要你的建议！\p是关于对战塔的，\n这取决于我的实力！\p那里有Lv. 50级和自由等级，\n哪个才是我该选的级别？$"

gText_ApprenticeLevelModeThanks11::
	.string "好的，{STR_VAR_1}，你说！\n我会去的，就在路上！\p如果我需要建议，\n{PLAYER}，你的话我永远听从！$"

gText_ApprenticePleaseTeach12::
	.string "嘿，你不就是{PLAYER}吗？\n我该怎么办？和你说话？\l为什么不呢？我已经在和你说话了！\p{PLAYER}，你对我感到惊讶吗？\n我最好告诉你我是谁！\p{STR_VAR_1}就是我的名字。\p吉他界最亮的星，\n那就是我！\p你收到我的信号了吗？\n你收到了！\p我的运气正处在最佳状态，\n我要向你提出一个请求！\p{PLAYER}，让我当你的手下吧！\p我想让你教我一切！$"

gText_ApprenticeRejectTeaching12::
	.string "你要拒绝我，是吧？\n我只好再问你一次！\p{PLAYER}，我请求当你的手下！\p我需要你教我一切！$"

gText_ApprenticeWhichLevelMode12::
	.string "幸运，耶，呜呼！\n我该问你个问题吗？\p既然我们在对战塔附近，\n不如问个关于它实力的问题？\p在你能看到的选择中，\n哪个才是我该选的？$"

gText_ApprenticeLevelModeThanks12::
	.string "如果{STR_VAR_1}是你建议的，\n那它一定是最棒的！\p嗯，{PLAYER}，我必须自由漫游，\n但你别忘了我。\p再见了，我聪明的朋友！$"

gText_ApprenticePleaseTeach13::
	.string "哦，嗨！那边的你！\n能帮我按摩一下肩膀吗？\p……对，就那里！就是那里！\n哎哟，哎哟！哦，感觉真棒！\p我叫{STR_VAR_1}。\p我在接受空手道训练，但我的身体\n承受不了那种强度……\p我决定去对战宝可梦，\n让自己变强。\p你是{PLAYER}{KUN}，对吧？\p那个宝可梦联盟冠军？\p听着，你能给我点建议吗？$"

gText_ApprenticeRejectTeaching13::
	.string "哦，为什么？\p我保证不会太麻烦，我发誓！\p拜托？$"

gText_ApprenticeWhichLevelMode13::
	.string "谢谢你。你真是太好了！\n……咳！咳！\p呃，我得快点变强……\p我马上就去对战塔，\n但对我来说哪个更好？\lLv. 50级还是自由等级？$"

gText_ApprenticeLevelModeThanks13::
	.string "嗯，好的。那就选{STR_VAR_1}。\p我马上就去那里。\p我希望我能继续向你求助——\l毕竟你是我的导师！$"

gText_ApprenticePleaseTeach14::
	.string "呃……嗯…\n{PLAYER}{KUN}……？\p拜托，别那样看着我。\p你让我很不好意思。\p我……我是{STR_VAR_1}。\p我真的很不好意思说这个，\n但我探索古代遗迹之类的。\p我更不好意思承认\n我对对战开拓区感兴趣。\p{PLAYER}{KUN}，你作为训练家\n很有声望……\p我很难说出口，\p但我有事想请教。\p你能当我的老师，\n给我一些建议吗？$"

gText_ApprenticeRejectTeaching14::
	.string "请不要这样敷衍我！\p我无法忍受这种羞辱。\p请当我的老师！\p我需要你的建议！$"

gText_ApprenticeWhichLevelMode14::
	.string "谢——谢谢你……\p但请不要那样看着我。\p这让我很慌乱。\p请回答我，但别看着\n我的眼睛。\p在对战塔……\p我该尝试哪个级别？$"

gText_ApprenticeLevelModeThanks14::
	.string "哦……好的！\p我会尝试去挑战的。\p我希望我能勇敢地挑战，\n而不会慌乱……\p谢谢你，{PLAYER}{KUN}。\p如果我们再见面，\n我希望你也能像这样帮助我。$"

gText_ApprenticePleaseTeach15::
	.string "嗯？你似乎是{PLAYER}{KUN}……\n但你真的存在吗？\p你可以叫我{STR_VAR_1}。\p我一直在考虑\n拜一位强大的训练家为师。\p所以，我得说我真幸运你来了！\p……你真的是{PLAYER}{KUN}，\n对吧？\p不，不，\n如果你是真的，那就好。\p我只想让你承认\n我是你的徒弟。$"

gText_ApprenticeRejectTeaching15::
	.string "哦？\p但什么会使你拒绝呢？\p我为我质疑你的身份\n道歉。\p请接受我的道歉，\n并收我为徒吧。$"

gText_ApprenticeWhichLevelMode15::
	.string "你真的接受我了？\p我不想过早庆祝。\p如果这是真的，我道歉。\n但现在，我需要你的建议。\p如果我要进入对战塔，\n什么才配得上我？\lLv. 50级还是自由等级？$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}？\p你确定吗？\p我明白了。如果是那样，那好吧。\p谢谢你的时间。\p我意识到我可能烦人，\n但你能接受我让我很高兴。\p让我们再会！$"

gText_ApprenticeWhatHeldItem0::
	.string "唉……呜咽……\n哦，{PLAYER}！\p我完全陷入困境了。\n无法决定该让我的\l{STR_VAR_1}携带什么道具。\p请告诉我，{PLAYER}。\n该让它携带什么道具？$"

gText_ApprenticeHoldNothing0::
	.string "哦，真的吗？我不该让我的\n{STR_VAR_1}携带任何东西？$"

gText_ApprenticeThanksNoHeldItem0::
	.string "哦，好的！很高兴问题解决了！\n太棒了！太厉害了！嗷呜！\p非常感谢你！$"

gText_ApprenticeThanksHeldItem0::
	.string "哦，我太高兴了……\n我想我也有{STR_VAR_1}呢。\p很高兴问题解决了！\n太棒了！太厉害了！嗷呜！\p非常感谢你！$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "哇哇哇！请不要这么刻薄！\p道具{STR_VAR_1}之前已经\n有人推荐过了，呜咽……\p或者你是说我不该让\n我的{STR_VAR_2}携带任何东西？$"

gText_ApprenticeWhatHeldItem1::
	.string "耶！是{PLAYER}！\n太好了！我想问你点事！\p你会让宝可梦携带道具吗？\n我也想让我宝可梦携带，但是……\p什么道具适合\n{STR_VAR_1}携带呢？\p你觉得呢？$"

gText_ApprenticeHoldNothing1::
	.string "嗯？你是说我的{STR_VAR_1}不用\n携带任何东西？$"

gText_ApprenticeThanksNoHeldItem1::
	.string "哦，明白了！我会照做的！\n谢谢你教我！$"

gText_ApprenticeThanksHeldItem1::
	.string "哦，哇！{STR_VAR_1}，是吧？\n好的，我会用那个！\p谢谢你教我！$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "哦，呃，我不是那个意思。\p我想要知道一个\n和我已知道具不同的推荐。\p或者你是说这次我的宝可梦\n不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}，你好！\n是关于我的{STR_VAR_1}……\p我想让它携带个好道具。\n什么适合它呢？$"

gText_ApprenticeHoldNothing2::
	.string "哦，那我的{STR_VAR_1}不需要\n携带任何东西？$"

gText_ApprenticeThanksNoHeldItem2::
	.string "好的，明白了！\n下次见！$"

gText_ApprenticeThanksHeldItem2::
	.string "哦，道具{STR_VAR_1}？\n明白了！\p我会尽力找一个的！\n下次见！$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "有人已经教过我关于\n{STR_VAR_1}的事了。\p我想要我的宝可梦携带\n不同类型的道具。\p或者你觉得{STR_VAR_2}不需要\n携带任何东西？$"

gText_ApprenticeWhatHeldItem3::
	.string "你好，{PLAYER}……\n很抱歉打扰你，但我还有件事想问。\p我觉得自己不够强，\n法独自赢比赛，\l所以想让我的{STR_VAR_1}携带道具。\p但不知道什么才好。\p{PLAYER}，拜托，\n你能替我决定吗？$"

gText_ApprenticeHoldNothing3::
	.string "像我这样的人的宝可梦\n不带道具更好？$"

gText_ApprenticeThanksNoHeldItem3::
	.string "我明白了……\n你是说我不该依赖道具。\l我会尽力不依赖的！\p非常感谢你！$"

gText_ApprenticeThanksHeldItem3::
	.string "道具{STR_VAR_1}，好的。\n我不确定能不能弄到一个……\l不！我会尽力搞到的。\p非常感谢你！$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "哦，但是……\n我想我以前听说过……\p是不是因为我没用好\n道具{STR_VAR_1}？\p或者你是说我不该让\n我的{STR_VAR_2}携带任何东西？$"

gText_ApprenticeWhatHeldItem4::
	.string "哦，{PLAYER}{KUN}。\n有件事我想问你。\p你知道你之前决定了我\n该用哪只宝可梦吧？\p但我没问你它该\n携带什么道具。\p既然你已经给了我建议，\n不如有始有终？\p什么比较好？我想让\n我的{STR_VAR_1}带点东西。$"

gText_ApprenticeHoldNothing4::
	.string "哦！所以我的{STR_VAR_1}应该\n空手上阵做到最好？$"

gText_ApprenticeThanksNoHeldItem4::
	.string "如果你觉得这样最好，我会照做。\p知道是你做的决定，\n{PLAYER}{KUN}，就算我输了\l也不会太难过。\p好的，我会再来向你请教。\n再见！$"

gText_ApprenticeThanksHeldItem4::
	.string "道具{STR_VAR_1}，是吧？\n不错。我会用的！\p知道是你做的决定，\n{PLAYER}{KUN}，就算我输了\l也不会太难过。\p好的，我会再来向你请教。\n再见！$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "嗯？你在说什么？\n你之前已经告诉过\l{STR_VAR_1}的事了。\p或者你是说我的{STR_VAR_2}应该\n空手上阵做到最好？$"

gText_ApprenticeWhatHeldItem5::
	.string "哟，{PLAYER}{KUN}！\p我们都很忙，但似乎经常遇到！\p今天我得做些步行、\n打扫和刷洗。\p我甚至没时间给我珍贵的\n{STR_VAR_1}买任何东西。\p我没时间，所以不如\n给我点建议该让它带什么？$"

gText_ApprenticeHoldNothing5::
	.string "哦，所以像我这样的大忙人，\n你说我的{STR_VAR_1}不需要任何东西？$"

gText_ApprenticeThanksNoHeldItem5::
	.string "好的，知道了。\n我不需要为此花时间。\p今天谢谢了！\n回头见！$"

gText_ApprenticeThanksHeldItem5::
	.string "好的，知道了。\n我会想办法找时间\l找到你推荐的{STR_VAR_1}。\p我很高兴遇到你这样的好导师。\n谢谢！回头见！$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "嗯？我已经知道\n那个{STR_VAR_1}了。\p哦，对了，我懂了。\n所以像我这样的大忙人，\l你说我的{STR_VAR_2}不需要任何东西？$"

gText_ApprenticeWhatHeldItem6::
	.string "嗨，{PLAYER}！是我！\n今天又需要请教你了！\p请给我建议！\p请鼓掌！\n我的问题是……\p如果我想让我的{STR_VAR_1}\n携带道具，该带什么好？$"

gText_ApprenticeHoldNothing6::
	.string "是吗？你是说我的{STR_VAR_1}不需要\n携带道具？$"

gText_ApprenticeThanksNoHeldItem6::
	.string "好的，我会照做的！\p我想今天要问的就这些了。\p让我们在这里再见，好吗？\n谢谢！$"

gText_ApprenticeThanksHeldItem6::
	.string "嗯哼！{STR_VAR_1}。\n多酷的选择！\l我一定会试试的！\p我想今天要问的就这些了。\p让我们在这里再见，好吗？\n谢谢！$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "啊哈哈！真傻！\n你之前已经告诉过\l{STR_VAR_1}的事了！\p你还好吗，{PLAYER}？\p哦，等等！你是说我的{STR_VAR_2}\n不需要携带任何道具？$"

gText_ApprenticeWhatHeldItem7::
	.string "你好，{PLAYER}。希望你一切安好。\p我可以请教你吗？\p最近一次对战中，对手似乎\n让他的宝可梦携带了道具。\p结果，我被打败了……\p我不想落后。\n我也想让我{STR_VAR_1}携带道具。\p如果你能决定\n什么适合我的宝可梦就太好了……$"

gText_ApprenticeHoldNothing7::
	.string "换句话说……我的宝可梦\n不需要携带道具？$"

gText_ApprenticeThanksNoHeldItem7::
	.string "我完全明白了！\n我会继续这样努力的。\p谢谢你，{PLAYER}。\p希望我能再次依靠你。\l请保重！$"

gText_ApprenticeThanksHeldItem7::
	.string "{STR_VAR_1}！\n我马上就去订购。\p谢谢你，{PLAYER}。\p希望我能再次依靠你。\l请保重！$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "你已经告诉过我了，\n而且我已经有了。\p或者你是说……我的宝可梦\n不需要携带道具？$"

gText_ApprenticeWhatHeldItem8::
	.string "呀！{PLAYER}！\n我……又见到你我太高兴了！\p哦——哦——哦！有件事\n我一定要问你，{PLAYER}！\p请决定我的{STR_VAR_1}\n该携带什么！$"

gText_ApprenticeHoldNothing8::
	.string "哦，哇！我没想到这个回答！\n所以，携带道具不是必须的？$"

gText_ApprenticeThanksNoHeldItem8::
	.string "完全明白了！\n我会继续不用道具努力的！\p希望下次你愿意\n再教我些东西。$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}！我会用那个！\p嗯……{PLAYER}，难道你也\n让你的宝可梦携带那个道具？\p我一定会弄到的！\p希望下次你愿意\n再教我些东西。$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "哦？你之前也推荐过\n{STR_VAR_1}。\p或者这是最好的携带物？\n还是说我的{STR_VAR_2}不需要\l携带任何东西？$"

gText_ApprenticeWhatHeldItem9::
	.string "你好！\n我的导师{PLAYER}{KUN}！\p我想请教你关于\n宝可梦道具的建议。\p你觉得什么适合\n我的{STR_VAR_1}携带？\p别害羞。\p直接说出来吧！$"

gText_ApprenticeHoldNothing9::
	.string "哦？所以你是说我的{STR_VAR_1}不携带\n道具也能赢？$"

gText_ApprenticeThanksNoHeldItem9::
	.string "好的，行！\n我会尽力而为，就像，猛击！\p好了，一如既往地感谢！\n再见！$"

gText_ApprenticeThanksHeldItem9::
	.string "嗯哼，{STR_VAR_1}？\n好的，行！\l我会去找一个，就像，砰！\p好了，一如既往地感谢！\n再见！$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "不，不！你之前已经\n告诉过我{STR_VAR_1}的事了。\p哦，现在等等……\n所以你是说我的{STR_VAR_2}\l不携带道具也能赢？$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}，发生难以置信的事了！\p今早我醒来，我的宝可梦\n有10个金珠！\p当然我是骗你的！\p哇哈哈哈！\p不过这不是骗人的。\p我不太擅长考虑\n宝可梦该携带什么道具。\p所以，不如替我决定我的\n{STR_VAR_1}该携带什么，师父？$"

gText_ApprenticeHoldNothing10::
	.string "那是什么意思？\n不让它带任何东西？$"

gText_ApprenticeThanksNoHeldItem10::
	.string "好的，所以不该携带任何东西。\n那么，我最好给它弄点东西！\p开玩笑的！\n我会听从你的教导，师父！\p谢谢师父！\p希望你继续教导我！$"

gText_ApprenticeThanksHeldItem10::
	.string "好的，所以是{STR_VAR_1}！\n我会让它携带除它以外的任何东西！\p开玩笑的！\n我会听从你的教导，师父！\p谢谢师父！\p希望你继续教导我！$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "嗯，你之前告诉过我了，对吧？\p没有别的东西了吗？\p或者你是说，不让我的\n{STR_VAR_2}携带任何东西？$"

gText_ApprenticeWhatHeldItem11::
	.string "A——H——O——Y！\n拼出来就是Ahoy，嗨！\p说唱水手就是我！\n向你提个超酷的问题！\p这是个道具问题\n需要你的建议！\p我的{STR_VAR_1}需要携带道具，\n该带什么好，请告诉我！$"

gText_ApprenticeHoldNothing11::
	.string "是吗？\n我的{STR_VAR_1}不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem11::
	.string "好的，我听到了，当然！\n我的宝可梦也会空手上阵！\p如果我需要建议，\n{PLAYER}，你的话我永远听从！$"

gText_ApprenticeThanksHeldItem11::
	.string "好的，{STR_VAR_1}，\n那就是我要用的。\l让你选是对的！\p如果我需要建议，\n{PLAYER}，你的话我永远听从！$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "好的，{STR_VAR_1}，你说？\n你之前告诉过我了。\l我需要新点子，全新的方式。\p或者，什么，是吗？\n我的宝可梦不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem12::
	.string "嘿，{PLAYER}！\n今天又找到你了！\p我该怎么办？请教你？\n为什么不呢？我已经在和你说话了！\p{PLAYER}，你对我厌烦了吗？\p不，不可能，那不会的。\p你会听我说吗？\n我在寻求建议——这就是\l我在说的。\p是关于我的{STR_VAR_1}\n携带道具的事。\l我的犹豫让我很烦恼。$"

gText_ApprenticeHoldNothing12::
	.string "我的{STR_VAR_1}什么都不需要？\n不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem12::
	.string "如果什么都不带是最好的，\n我会照你说的做！\p嗯，{PLAYER}，我必须自由漫游，\n但别忘了我。\p再见，我聪明的朋友！$"

gText_ApprenticeThanksHeldItem12::
	.string "如果携带{STR_VAR_1}是\n最好的，我会照你说的做！\p嗯，{PLAYER}，我必须自由漫游，\n但别忘了我。\p再见，我聪明的朋友！$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "我没听说过那个\n{STR_VAR_1}吗？\l我肯定听说过，那是肯定的！\p我需要新东西！\n或者我的{STR_VAR_2}什么都不需要？\l不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem13::
	.string "嘎！哎哟！{PLAYER}{KUN}，我的手臂断了！\n别碰它，拜托！\p一定是我在尝试不同道具\n和我的宝可梦伙伴们时弄断的。\p所以，事已至此，\n我需要你替我决定。\p{PLAYER}{KUN}，\n你觉得我的{STR_VAR_1}携带什么好？$"

gText_ApprenticeHoldNothing13::
	.string "哎哟……\p所以你的建议是我的{STR_VAR_1}\n不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem13::
	.string "嗯，好的。\n以我现在的情况，那样更容易。\p我希望我能继续\n这样向你求助。$"

gText_ApprenticeThanksHeldItem13::
	.string "嗯，好的。那就{STR_VAR_1}。\p我的宝可梦手臂没事，\n所以我会让它马上携带那个道具。\p我希望我能继续\n这样向你求助。$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "不，不，你之前告诉过我\n{STR_VAR_1}了，记得吗？\p告诉我些更好的东西怎么样？\p哦，等一下。\p所以你的建议是我的{STR_VAR_2}\n不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem14::
	.string "呃……嗯……\n{PLAYER}{KUN}……？\p拜托，别那样看着我。\p我的宝可梦什么都没有。\p我……我对此真的很不好意思，\n但我真的需要你的建议。\p我无法决定携带什么道具\n能让我的{STR_VAR_1}变强。\p{PLAYER}{KUN}，你觉得\n什么好？$"

gText_ApprenticeHoldNothing14::
	.string "哦……那么，你觉得我的{STR_VAR_1}\n不带道具更好？$"

gText_ApprenticeThanksNoHeldItem14::
	.string "哦……好的！\n我就不带道具了。\p不过这真让人紧张。\n会不会太酷了？\p谢谢你，{PLAYER}{KUN}。\p如果我们再见面，\n希望你也这么帮忙。$"

gText_ApprenticeThanksHeldItem14::
	.string "哦……好的！\n我就用{STR_VAR_1}吧。\p不过这真让人紧张。\n会不会太酷了？\p谢谢你，{PLAYER}{KUN}。\p如果我们再见面，\n希望你也这么帮忙。$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "但——但我已经听说过了。\p请不要这样敷衍我！\p我无法忍受这种羞辱。\p哦……是我太武断了吗？\p你觉得如果我的{STR_VAR_2}不带\n道具会更好？$"

gText_ApprenticeWhatHeldItem15::
	.string "嗯？你似乎是{PLAYER}{KUN}……\n但你真的存在吗？\p也许你是双胞胎？\p哦，不不不，别担心！\p如果你是真的{PLAYER}，\n请原谅我的无礼。\p我想要的是你更多的\n好建议。\p我这里有{STR_VAR_1}，\n想让它携带个方便的道具。\p什么才配得上它？$"

gText_ApprenticeHoldNothing15::
	.string "什么都不带更好？\p你确定吗？$"

gText_ApprenticeThanksNoHeldItem15::
	.string "明白了。如果是那样，那好吧。\p谢谢你的时间。\p让我们再会！$"

gText_ApprenticeThanksHeldItem15::
	.string "{STR_VAR_1}？\p你确定吗？\p明白了。如果是那样，那好吧。\p谢谢你的时间。\p我确实希望我的宝可梦\n能好好利用它。\p让我们再会！$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "不，不，等等。\p我相信你之前教过我了。\p这次我想要你推荐\n不同的东西。\p也许你是建议\n我的{STR_VAR_2}什么都不带？\p你确定吗？$"

gText_ApprenticeWhichMonFirst0::
	.string "呜哇，{PLAYER}！\n我有个两难困境，抽泣……\p我想开始和别人对战，\n但不知道该怎么办。\p我该如何排列我的宝可梦\n才能让它们最强？\p请告诉我，{PLAYER}。\n如果你是我，这些宝可梦中\l你会先派出哪只？$"

gText_ApprenticeMonFirstThanks0::
	.string "我的{STR_VAR_1}应该先上？\n哇啊啊！\p哦！真对不起！\n你替我选择首发宝可梦让我很高兴，\l这又让我哭了……\p太感谢你了！$"

gText_ApprenticeWhichMonFirst1::
	.string "耶！是{PLAYER}！\n太好了！我想问你点事！\p嗯，在我的宝可梦中，\n你觉得哪只应该先出场？$"

gText_ApprenticeMonFirstThanks1::
	.string "我的{STR_VAR_1}？没错。\n好的，我会这么做的！\p谢谢你教我！$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}，你好！\p我觉得在对战中，\n哪只宝可梦先出场非常重要。\p在我拥有的宝可梦中，\n哪只适合先派出去？$"

gText_ApprenticeMonFirstThanks2::
	.string "我的{STR_VAR_1}先上？\n好的，明白了！\p下次见！$"

gText_ApprenticeWhichMonFirst3::
	.string "你好，{PLAYER}……\n很抱歉又打扰你问另一个问题。\p我太没自信了，没有你\n{PLAYER}我都不知道该怎么办。\p可能我连担心都是浪费时间，\n但我就是无法决定一件事……\p我的宝可梦中哪只应该\n在对战中先出场？$"

gText_ApprenticeMonFirstThanks3::
	.string "我的{STR_VAR_1}？\n明白了！\p真不敢相信你会经常\n费心回答我的问题！\p我很感激你甚至愿意\n和我说话……谢谢你！$"

gText_ApprenticeWhichMonFirst4::
	.string "哦，{PLAYER}{KUN}！是我！\n很高兴见到你，因为我有个小问题。\p我无法决定我的宝可梦\n该如何排列。你能替我决定吗？\p哦，你现在不需要决定\n整个队伍。\p不如先替我决定\n首发宝可梦？$"

gText_ApprenticeMonFirstThanks4::
	.string "我的{STR_VAR_1}？太好了！\p知道是你做的决定，\n{PLAYER}{KUN}，就算我输了\l也不会太难过。\p好的，我会再来向你请教。\n再见！$"

gText_ApprenticeWhichMonFirst5::
	.string "嗨，我的老师{PLAYER}{KUN}！\n我今天又很忙！\p我得做些骑车、购物\n和哼歌的事。\p我甚至没时间决定\n如何排列我的宝可梦队伍。\p所以，不如看看我的队伍？\n哪只应该先出场？$"

gText_ApprenticeMonFirstThanks5::
	.string "好的，知道了。\p我至少有足够时间把\n我的{STR_VAR_1}放在队伍首位！\p哎呀，我女朋友在等！\n谢谢！回头见！$"

gText_ApprenticeWhichMonFirst6::
	.string "哟嚯！嗨，{PLAYER}！\n你走路总是看起来很酷！\p听着，我又需要你帮忙了！\n老样子！\p请鼓掌！\n我的问题是关于我的队伍。\p我的宝可梦中哪只应该\n在对战中先出场？$"

gText_ApprenticeMonFirstThanks6::
	.string "嗯哼！\n你说我的{STR_VAR_1}！\l感谢这个超酷的回答！\p我想今天要问的就这些了。\p让我们在这里再见，好吗？\n谢谢！$"

gText_ApprenticeWhichMonFirst7::
	.string "非常感谢你停下来\n和我聊天，{PLAYER}。\p我知道我在利用你的善良，\n但能请教一下吗？\p我想让你决定我的宝可梦\n队伍的顺序。\p如果你能决定哪只宝可梦\n应该先出场就太好了。$"

gText_ApprenticeMonFirstThanks7::
	.string "我的{STR_VAR_1}！\n我会马上把它放在首位！\p谢谢你，{PLAYER}。\p希望我能再次依靠你。\l请保重！$"

gText_ApprenticeWhichMonFirst8::
	.string "呀！我发现了{PLAYER}！\n我……又见到你我太高兴了！\p我的宝可梦变得\n强多了！\p但我并不总是赢。似乎\n取决于哪只宝可梦先出场。\p{PLAYER}，拜托，\n我需要你的帮助！\p请决定我的宝可梦中\n哪只应该先出场！$"

gText_ApprenticeMonFirstThanks8::
	.string "呼……我幸福得要晕过去了……\p能让你替我决定\n就像做梦一样，{PLAYER}。\p但完全明白了！\n我会让我的{STR_VAR_1}先上！\p希望下次你愿意\n再教我些东西。$"

gText_ApprenticeWhichMonFirst9::
	.string "你好，你好！\n我的导师{PLAYER}{KUN}！\l今天再给我些睿智的建议吧！\p你看，我凑齐了3只宝可梦的队伍。\p目前还不错。\p但队伍的出战顺序还没定。\p这就是你出场的时候，\n{PLAYER}{KUN}！\p你决定哪只宝可梦打头阵！\p别害羞。\p直接说出来吧！$"

gText_ApprenticeMonFirstThanks9::
	.string "嗯哼，我的{STR_VAR_1}打头阵！\nOK，A——OK！\l我会重新排序队伍，就像，砰！\p好了，一如既往地感谢！\n再见！$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}，听我说！\n大危机！\p我的宝可梦，3只一起\n冲进战斗！\p当然那是不可能的！\p哇哈哈哈！\p不过这不是骗人的。\p我不太擅长考虑\n如何排列我的宝可梦。\p所以，不如替我决定哪只\n宝可梦应该先出场，师父？$"

gText_ApprenticeMonFirstThanks10::
	.string "好的，所以你选了{STR_VAR_1}？\n我会让任何一只先上，除了那只！\p开玩笑的！\n我会听从你的教导，师父！\p谢谢师父！\p希望你继续教导我！$"

gText_ApprenticeWhichMonFirst11::
	.string "A——H——O——Y！\n拼出来就是Ahoy，嗨！\p说唱水手就是我！\n向你提个超酷的问题！\p这是个队伍排序问题\n需要你的建议！\p这些宝可梦中，哪只应该\n首先出场？$"

gText_ApprenticeMonFirstThanks11::
	.string "好的，我听到了，当然！\n我会调整它们的位置，就这么办！\p如果我需要建议，\n{PLAYER}，你的话我永远听从！$"

gText_ApprenticeWhichMonFirst12::
	.string "哟嚯，{PLAYER}！\n你好吗？\p我该怎么办？直接问？\n嗯哼，我有事要问！\l你收到我的信号了吗？\l你收到了！\p你必须决定，我的宝可梦中\n哪只是第1个上场的！\l我是说进入战斗！$"

gText_ApprenticeMonFirstThanks12::
	.string "我的{STR_VAR_1}？是的！\n这样就行，没有烦恼！\p嗯，{PLAYER}，我必须自由漂泊，\n但别忘了我。\p再见，我聪明的朋友！$"

gText_ApprenticeWhichMonFirst13::
	.string "……呼……哎哟……{PLAYER}{KUN}……\n我的肚子突然好痛……\p……现在好些了……\p一定是我绞尽脑汁思考\n如何排列我的宝可梦伙伴时\l把自己愁坏了。\p所以，事已至此，\n我需要你替我决定。\p{PLAYER}{KUN}，我的宝可梦中哪只应该\n先上场？我是说，才更可能赢。$"

gText_ApprenticeMonFirstThanks13::
	.string "嗯，好的。\n我的{STR_VAR_1}先上。\p等我吃完晚饭\n就按那样调整顺序。\p我希望我能继续\n这样向你求助。$"

gText_ApprenticeWhichMonFirst14::
	.string "呃……嗯……\n{PLAYER}{KUN}？\p拜托，别那样看着我。\p你让我感觉很慌乱。\p嗯……\n我真的需要你的建议。\p我不好意思说这个，\n但我选好了我的3只宝可梦队伍。\l但我无法决定顺序。\p哪只宝可梦应该先出场\n才能让我显得有能力？$"

gText_ApprenticeMonFirstThanks14::
	.string "哦……好的！\n我会用我的{STR_VAR_1}打头阵。\p我希望我能尽力而为\n而不慌乱。\p谢谢你，{PLAYER}{KUN}。\p如果我们再见面，\n希望你也这么帮忙。$"

gText_ApprenticeWhichMonFirst15::
	.string "嗯？你似乎是{PLAYER}{KUN}……\n但你真的存在吗？\p也许是个聪明的替身？\p哦，不不不，别担心！\p如果你是真的{PLAYER}，\n请原谅我的无礼。\p我想要的是你的好建议。\p我这里是我的宝可梦队伍。\p我想让你告诉我哪只\n应该在战斗中先出场。$"

gText_ApprenticeMonFirstThanks15::
	.string "我的{STR_VAR_1}……\p你不是在耍我吧？\p明白了。如果是那样，那好吧。\p谢谢你的时间。\p如你所见，我会尽\n我所能。\p让我们再会！$"

gText_ApprenticeWhichMon0::
	.string "抽泣……\n哦，{PLAYER}！\p来得正是时候！\n有件事我实在拿不定主意……\p我无法决定该用哪只宝可梦。\p在{STR_VAR_1}和{STR_VAR_2}\n之间犹豫不决……\p{PLAYER}，你觉得哪只能让我\n也有机会获胜？$"

gText_ApprenticeMonThanks0::
	.string "抽泣……我…我明白了！\n哦！真对不起！\l你让我太开心，我又哭了……\p我会努力去抓一只\n{STR_VAR_1}！\p太感谢你了！$"

gText_ApprenticeWhichMon1::
	.string "耶！是{PLAYER}！\n来得正好！\l我又需要你的建议了！\p嗯，我完全搞混了——该用\n我的{STR_VAR_1}还是{STR_VAR_2}……\p{PLAYER}，你觉得我该培育哪只？$"

gText_ApprenticeMonThanks1::
	.string "哦，所以我的{STR_VAR_1}更好！\n好的，就这么办！\p谢谢你的教导！$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}，你好！\n有个问题想请教。\p我在纠结该培育{STR_VAR_1}\n还是{STR_VAR_2}。\p你觉得哪只宝可梦\n会更强？$"

gText_ApprenticeMonThanks2::
	.string "你选了{STR_VAR_1}？\n好的，明白了！\p我这就去抓只厉害的\n{STR_VAR_1}！\p下次见！$"

gText_ApprenticeWhichMon3::
	.string "你好，{PLAYER}……\p嗯，你可能已经忘记\n我这样的人了……\p……但如果你能给我建议\n那也没关系……\p我无法决定该培育\n哪种宝可梦……\p范围缩小到了{STR_VAR_1}\n和{STR_VAR_2}，但就在这\l卡住了……\p{PLAYER}，你可能不想费心，\n但请替我决定吧。$"

gText_ApprenticeMonThanks3::
	.string "但野生的{STR_VAR_1}\n会理我吗？\p我会试试的！\p但我能抓到吗……\n不！我会尽力的！\p谢谢你！$"

gText_ApprenticeWhichMon4::
	.string "哦，{PLAYER}{KUN}！见到你真高兴！\n我正要去找你呢！\p你能决定我该用哪种宝可梦吗？\p比如……\n{STR_VAR_1}和{STR_VAR_2}\l怎么样？\p你觉得哪只更适合我？$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}？太棒了！\p只要是你的决定，{PLAYER}{KUN}，\n就算输了我也没那么难过。\p好的，下次再向你请教。\n再见！$"

gText_ApprenticeWhichMon5::
	.string "这不是{PLAYER}{KUN}吗！最近怎样？\n我还是老样子忙得很！\p我也想用好宝可梦，\n但一直没决定该用哪只。\p你看{STR_VAR_1}好像很强？\n但{STR_VAR_2}也不容忽视。\p{PLAYER}{KUN}，\n给我点好建议！\n哪只适合我？$"

gText_ApprenticeMonThanks5::
	.string "好的，明白了。\n我会想办法抓一只\l你推荐的{STR_VAR_1}。\p真高兴遇到你这样的好导师。\n谢谢！回头见！$"

gText_ApprenticeWhichMon6::
	.string "哦！\n是{PLAYER}！\p我立刻就跟朋友们炫耀\n遇到你的事！\p今天又要借用你的智慧了。\n对你来说很简单！\p请击鼓助兴！\n我的问题是……\p如果要培育宝可梦，\n选{STR_VAR_1}还是{STR_VAR_2}？$"

gText_ApprenticeMonThanks6::
	.string "啊啊！\n你说{STR_VAR_1}！\l感谢这超酷的答案！\p今天想问的就这些了。\p我们下次在这里再见，好吗？\n谢谢！$"

gText_ApprenticeWhichMon7::
	.string "哦，是你吗{PLAYER}？\n真高兴又见到你！\p自从成为你的学徒，\n我的信心越来越强了。\p我觉得准备好培育\n自己的宝可梦了！\p{PLAYER}，能麻烦你帮我选\n该培育哪只宝可梦吗？\p选项是{STR_VAR_1}\n或{STR_VAR_2}……\l哪只适合我？$"

gText_ApprenticeMonThanks7::
	.string "就选{STR_VAR_1}！\n我马上去找一只！\p谢谢你，{PLAYER}。\p希望还能依靠你。\p请多保重！$"

gText_ApprenticeWhichMon8::
	.string "呀！{PLAYER}！又见面了！\n我……我太高兴了！\p哦——哦——哦，有了！\n不能错过这个机会！\p{PLAYER}，能帮个大忙吗？\p请替我选只宝可梦！\p{STR_VAR_1}和{STR_VAR_2}，\n哪只更好？$"

gText_ApprenticeMonThanks8::
	.string "哇！你替我决定了！\n我会全力培育这只{STR_VAR_1}！\p希望下次你还能\n多教我一些。$"

gText_ApprenticeWhichMon9::
	.string "嘿，嘿！\n我的导师{PLAYER}{KUN}！\p你好，我一直在找你\n想再听听你的睿智建议！\p哪种宝可梦适合我，\n{STR_VAR_1}还是{STR_VAR_2}？\p别害羞，\n直接说出来吧！$"

gText_ApprenticeMonThanks9::
	.string "嗯哼，就选{STR_VAR_1}！\nOK，没问题！\l我会用精灵球抓一只，就像塞进去！\p好的，一如既往地感谢！\n再见！$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}，听着！大新闻！\n我抓到了幻影宝可梦！\p当然是骗你的！\n哇哈哈哈！\p不过这不是骗人的。\n我不太擅长抓宝可梦。\p所以，不如替我决定\n该抓哪种宝可梦吧，师父？\p哪只更好？\n{STR_VAR_1}还是{STR_VAR_2}？$"

gText_ApprenticeMonThanks10::
	.string "好的，所以你选了{STR_VAR_1}？\n那我就去抓另一种！\p开玩笑啦！\n我会遵从您的教诲，师父！\p谢谢师父！\p希望您继续教导我！$"

gText_ApprenticeWhichMon11::
	.string "A——H——O——Y！\n就是Ahoy的拼法！\p我就是那个说唱水手！\n你肯定记得我是谁吧？\p今天有个宝可梦问题\n需要你的建议！\p我可以在{STR_VAR_1}\n和{STR_VAR_2}之间选择，\l哪只适合抓来陪我？$"

gText_ApprenticeMonThanks11::
	.string "你说{STR_VAR_1}，嘿，嘿！\n我这就去抓一只！\p如果需要建议，{PLAYER}，\n你的话我永远牢记！$"

gText_ApprenticeWhichMon12::
	.string "哦，哇，这不是{PLAYER}吗！\p怎么办？要你的建议？\n为什么不呢？反正都聊上了！\p好久不见。让我打破沉默。\p我也在寻求建议！\n收到我的信号了吗？\l你收到了！\p我的宝可梦——该用哪只？\n{STR_VAR_1}还是{STR_VAR_2}。\l你选哪只？$"

gText_ApprenticeMonThanks12::
	.string "如果{STR_VAR_1}最棒，\n我就照你说的办！\p嗯，{PLAYER}，我得自由闯荡，\n但你可别忘了我。\p再见，我聪明的朋友！$"

gText_ApprenticeWhichMon13::
	.string "哦，嗨，{PLAYER}{KUN}……\n我头疼得厉害……\p肯定是因为太纠结\n该培育哪种宝可梦了。\p所以，情况就是这样，\n需要你替我决定。\p{PLAYER}{KUN}，如果必须在{STR_VAR_1}\n和{STR_VAR_2}之间选择，\l该选哪只？$"

gText_ApprenticeMonThanks13::
	.string "嗯，就选{STR_VAR_1}吧。\n等我好些了就去找一只。\p希望能继续这样\n向你求助。$"

gText_ApprenticeWhichMon14::
	.string "呃……嗯…\n{PLAYER}{KUN}……？\p拜托别那样看我。\n我都慌乱了……\l我……我需要你的建议。\p我……我真的很不好意思，\n但无法决定该用哪只宝可梦。\p如果选项是{STR_VAR_1}\n或{STR_VAR_2}，哪只更好？$"

gText_ApprenticeMonThanks14::
	.string "哦……好的！\n我会努力用好{STR_VAR_1}。\p希望我能全力以赴\n不手忙脚乱。\p谢谢你，{PLAYER}{KUN}。\p如果再见，\n希望你还能帮忙。$"

gText_ApprenticeWhichMon15::
	.string "嗯？你好像是{PLAYER}{KUN}……\n但真的是本人吗？\p不，不，如果是真的，那很好。\p顺便，我想征求\n你的建议。\p是关于我要用的宝可梦。\p如果选项是{STR_VAR_1}\n和{STR_VAR_2}，\l哪只更配得上我？$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}？\n你确定吗？\p明白了。如果是这样，那好吧。\p感谢你抽时间帮忙。\p希望这是连我也能\n从容应对的类型。\p让我们再见吧！$"

gText_ApprenticeWhichMove0::
	.string "哇哇！哦，{PLAYER}！\n抽泣……打嗝……\p我有个两难困境！\p我无法为我的{STR_VAR_1}\n决定招式……\p拜托，拜托，{PLAYER}。\p你能替我决定吗？\p对于我的{STR_VAR_1}，\n哪个招式更好：{STR_VAR_2}\l还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}？\n哇啊啊！\p哦！真对不起，{PLAYER}！\p你替我决定招式\n让我这么开心，我都哭了……\p抽泣……\n太感谢你了！$"

gText_ApprenticeWhichMove1::
	.string "耶！嗨，{PLAYER}！\p我又需要你的建议了！\p我想教我的{STR_VAR_1}\n1个很酷的招式。\p我喜欢{STR_VAR_2}和\n{STR_VAR_3}这2个招式。\l你有什么推荐？$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1}更好？我想是的！\n好的，我就用那个！\p如果我们在这里再见，请再教我\n点别的，老师！$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}，你好！\p是关于我的{STR_VAR_1}，\n但我担心它的招式。\p你看，是{STR_VAR_2}\n和{STR_VAR_3}这2个招式。\p哪个更强、更适合\n我的{STR_VAR_1}？$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1}是你的选择？\n好的，明白了！\p我马上去教我的宝可梦\n{STR_VAR_1}！\p下次见！$"

gText_ApprenticeWhichMove3::
	.string "哦哦，{PLAYER}……\p我没救了，真的！\p我决定培育一只宝可梦，\n但现在连该让它学什么\l招式都无法决定……\p我知道这对你毫无意义，\n{PLAYER}。\p但对我意义重大……\p拜托，{PLAYER}，你能为我的\n{STR_VAR_1}选个招式吗？\p如果你能在{STR_VAR_2}\n和{STR_VAR_3}之间选择……$"

gText_ApprenticeMoveThanks3::
	.string "我明白了！\p但它会愿意为我学\n{STR_VAR_1}吗……\l不！我会尽力的！\p谢谢你！$"

gText_ApprenticeWhichMove4::
	.string "哦，{PLAYER}{KUN}！\p我正希望能见到你！\p我在想什么招式\n适合我的{STR_VAR_1}。\p我无法决定，所以你能\n替我决定吗？\p比如说……招式{STR_VAR_2}\n和{STR_VAR_3}怎么样？\l哪个更好？$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}？太棒了！\p知道是你做的决定，\n{PLAYER}{KUN}，就算我输了\l也不会太难过。\p好的，我会再来向你请教。\n再见！$"

gText_ApprenticeWhichMove5::
	.string "怎么能这么忙？\p嘿，这不是{PLAYER}{KUN}吗！\l最近怎么样？\p从今天早上起床，我做了\n慢跑、游泳和烹饪！\p你无法想象我有多忙！\p我甚至无法决定我的{STR_VAR_1}\n该学什么招式！\p{STR_VAR_2}看起来不错，是吧？\n但{STR_VAR_3}也挺好。\p{PLAYER}{KUN}，\n给我些好建议吧！\p哪招适合我？$"

gText_ApprenticeMoveThanks5::
	.string "好的，知道了。\p我会在日程中安排时间\n教那个招式。\p我很高兴遇到你这样的好导师。\n谢谢！回头见！$"

gText_ApprenticeWhichMove6::
	.string "哦！幸运！\p又遇到你了，{PLAYER}！\l今天又需要请教你了。\p请鼓掌！\n我的问题是……\p对于我的{STR_VAR_1}，\n{STR_VAR_2}和{STR_VAR_3}中\l哪招最适合？$"

gText_ApprenticeMoveThanks6::
	.string "啊！\n{STR_VAR_1}，你说！\l感谢这个超酷的回答！\p我想今天要问的就这些了。\p让我们在这里再见，好吗？\n谢谢！$"

gText_ApprenticeWhichMove7::
	.string "哦，你好，{PLAYER}。\p我相信你一切都好？\p我得再次请教你。\p是关于我最亲爱的{STR_VAR_1}。\p对我的可爱的{STR_VAR_1}来说，\n理想的招式是什么？\l{STR_VAR_2}还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1}！\n我马上教那个！\p谢谢你，{PLAYER}。\p希望我能再次依靠你。\l请保重！$"

gText_ApprenticeWhichMove8::
	.string "呀！{PLAYER}！又见到你了！\p我……我太高兴了！\p每当我需要时，你总是在\n那里帮我，{PLAYER}！\p今天，我想让你推荐\n一招给我！\p请为我的{STR_VAR_1}选个招式！\p哪招更好，\n{STR_VAR_2}还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks8::
	.string "哦——哦——哦！谢谢你！\p{STR_VAR_1}！\p完全明白了！\p希望下次你愿意\n再教我些东西。$"

gText_ApprenticeWhichMove9::
	.string "你好，{PLAYER}{KUN}，好！\p我希望今天能再听听\n你的睿智建议！\p对我的{STR_VAR_1}来说，\n最好的招式是什么？\p应该是那种能让我\n轻松获胜的招式！\p会是{STR_VAR_2}吗？\n还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks9::
	.string "嗯哼，{STR_VAR_1}！\n好的，行！\l我会教它，就像，砰！\p好了，一如既往地感谢！\n再见！$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}，完全疯了！\p我的宝可梦！\n它学会了6个招式！\p当然我是骗你的！\p哇哈哈哈！\p不过这不是骗人的。\p我不太擅长为我的宝可梦\n选择招式。\p所以，不如替我决定\n该教哪种招式？\p{STR_VAR_2}或{STR_VAR_3}——哪招\n最适合我的{STR_VAR_1}？$"

gText_ApprenticeMoveThanks10::
	.string "好的，所以你选了{STR_VAR_1}？\n那我就选另一招！\p开玩笑的！\p我会听从你的教导，师父！\p谢谢师父！\p希望你继续教导我！$"

gText_ApprenticeWhichMove11::
	.string "A——H——O——Y！\n拼出来就是Ahoy，嗨！\p说唱水手就是我！\p我总是很在行，别问我为什么。\p今天，我有个招式问题\n需要你的建议！\p{STR_VAR_2}和{STR_VAR_3}是备选招式。\p对我的{STR_VAR_1}来说，\n哪招最好让它能秀起来？$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}，你说，嘿，嘿！\n我马上去教那招！\p如果我需要建议，\n{PLAYER}，你的话我永远听从！$"

gText_ApprenticeWhichMove12::
	.string "哦，耶，{PLAYER}！\p我该怎么办？再问你一次？\n为什么不呢？我已经在问你了！\p{PLAYER}，你对我感到惊讶吗？\p我想要你的建议，\n你明白吗？\p你收到我的信号了吗？\l你收到了！\p我的{STR_VAR_1}——该用什么招式？\n是{STR_VAR_2}还是{STR_VAR_3}，\l你选哪招？$"

gText_ApprenticeMoveThanks12::
	.string "如果{STR_VAR_1}是最好的，\n我会照你说的做！\p嗯，{PLAYER}，我必须自由漫游，\n但别忘了我。\p再见，我聪明的朋友！$"

gText_ApprenticeWhichMove13::
	.string "咳！咳！哦，{PLAYER}{KUN}……\p我得了重感冒……\p我想为我的宝可梦\n想个很酷的招式。\p它让我大受启发，让我哭了，\n现在我的鼻子流个不停……\p所以，事已至此，\n我需要你替我决定，{PLAYER}{KUN}。\p当我赢了比赛时，\n该说什么？$"

gText_ApprenticeMoveThanks13::
	.string "{STR_VAR_1}\p…… …… ……这不错。\p不，太震撼了！\l它让我热泪盈眶！\p但尽管我流泪流鼻涕，\n我会用那句台词的！\p我已经没有问题了，\n{PLAYER}{KUN}。\p从现在起，我们是劲敌了！\p感谢你所做的一切！$"

gText_ApprenticeWhichMove14::
	.string "呃……嗯……\n{PLAYER}{KUN}……？\p拜托，别那样看着我。\p我很紧张……\p我……我再次需要你的建议。\p虽然这是我最后一次……\p真的很不好意思问，\p但如果我赢了比赛，\n该说什么？$"

gText_ApprenticeMoveThanks14::
	.string "{STR_VAR_1}\p哦……好的！\p我会试着说那个！\p我可能会紧张得说不出来……\p谢谢你，{PLAYER}{KUN}。\p我现在得说再见了。\p{PLAYER}{KUN}，\n我会遵守你所有的教导，\l尽我所能做到最好。$"

gText_ApprenticeWhichMove15::
	.string "嗯？你似乎是{PLAYER}{KUN}……\n但你真的存在吗？\p也许是个聪明的{PLAYER}玩偶？\p哦，不不不，别担心！\p如果你是真的，请原谅\n我的无礼。\p不必这么生气。我只想要\n更多你的好建议。\p是关于一句话的。\p更准确地说，如果我赢了比赛，\n该说什么？$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}\p…… …… …… …… …… ……\p当我赢了比赛时……\p{STR_VAR_1}\p……你是认真的吗？\p明白了。如果你是认真的，那好吧。\p谢谢你的时间。\p我确实希望即使我也能\n好好利用那句台词。\p我似乎已经没什么建议需要了。\p我相信是时候告别你，\n独自出发了。\p谢谢你，我的导师！\p我为我的怀疑道歉！$"

gText_ApprenticePickWinSpeech0::
	.string "哦… {PLAYER}？\n是{PLAYER}啊！\l哦！抽泣……呜咽… 请听我说！\p我… 在对战时，我会紧张得不得了，\n就算赢了也忍不住哭出来……\p我真希望赢的时候\n能说点帅气的话……\p求求你，{PLAYER}！\n能不能教我一句赢了之后说的\l酷酷的话，这样我就不会哭了？$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p太棒了！帅呆了！呜哦哦！\n这真的很酷！\p哦……对不起……\n我太高兴了，又哭了……\p抽鼻子… {PLAYER}！\n真的非常感谢你为我做的一切！\p为了你，{PLAYER}，\n我会尽我所能去战斗的！\p{PLAYER}……\n下次… 我们来对战吧！$"

gText_ApprenticePickWinSpeech1::
	.string "耶！是{PLAYER}！你好！\n我有件事想问你！\p我想在赢得比赛时说点酷酷的话。\n你有什么推荐的帅气台词吗？$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p哦，哇！这太酷了！\n好的，我就说这句了！\p谢谢你一直以来的教导！\n从今以后，无论走到哪里，\l我都会全力以赴的！\p等我们再见面时，\n就来一场对战吧！$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}，你好！\p我和我的宝可梦已经准备好\n迎接任何挑战了，除了一件事。\p我觉得如果我赢了之后\n能喊点什么就好了。\p你能帮我想一句\n适合说的话吗？$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p……酷！\n我就用这句了！\p我要去各地旅行战斗了。\p说不定有一天，\n我还能和你对战呢，{PLAYER}。\p下次，我们在对战之地再见吧！$"

gText_ApprenticePickWinSpeech3::
	.string "你好，{PLAYER}……\n抱歉打扰你，但我真是没救了……\p即使是……\n即使我赢了，我也说不出\l什么特别的话来……\p我知道这对你来说\n可能不算什么，{PLAYER}。\p但对我来说意义重大……\p求你了，{PLAYER}，\n如果我赢了比赛，该说什么好呢？$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p这话真有水平……\p呃……像我这样的人\n说这个真的合适吗？\p不！我会努力的！\p{PLAYER}，真的非常感谢你\n一直这么包容我……\p我保证从现在开始会尽最大努力。\p我知道你大概很快就会\n忘掉我这样的人，但我们一定\l要在某个地方再见面！$"

gText_ApprenticePickWinSpeech4::
	.string "哦，{PLAYER}{KUN}。\n有件事想请你听听。\p我知道我说话\n有时听起来不太友善或礼貌……\p赢了比赛时，\n我觉得自己显得有点傲慢。\p我不想让人讨厌，\n所以我想对被我打败的人\l说点好话。\p但我就是想不出什么好词！\n你能帮我想一句吗？$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p不错嘛！\n嗯，我就用这句了！\p我要踏上旅程，把从你那里学到的\n东西记在脑海里、放在心里，\l尽我所能去做。\p很抱歉我一直对你这么缠人！\p下次，我们来对战吧，好吗？\n再见！$"

gText_ApprenticePickWinSpeech5::
	.string "哦，我简直忙得不可开交！\n哦，嘿，我正找你呢，{PLAYER}{KUN}。\p你还好吗？\n我还是老样子。\p我要跑步、打架、画地图。\p为什么我这么忙？\p但即使再忙，赢了之后\n一句话不说转身就走也太失礼了。\p所以，有什么酷酷的台词\n能在我结束战斗、潇洒离开时，\l衬托出我的帅气呢？{PLAYER}{KUN}，帮帮我！$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p好的，明白了。\n我总能挤出时间说这句的！\p说实话，能遇到你这样的好导师\n真是太好了。\p我会想办法挤出时间\n去好好对战的。\p谢谢你做的一切，{PLAYER}{KUN}！\n总有一天，我们一定要对战一场！$"

gText_ApprenticePickWinSpeech6::
	.string "我又走运了！\n{PLAYER}！见到你太高兴了！\l和往常一样，我需要你的建议！\p请击鼓助兴！\n我要问的最后一个问题是……\p如果我赢了比赛，想用一句\n酷炫的结束语收尾，\l我该说什么？$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p这句……这句太棒了！\n既体面又帅气！我宣布这句归我了！\p……听着，我觉得我现在\n还挺像样的了，对吧？\p所以，我打算从现在开始\n挑战其他训练家了。\p{PLAYER}，你的建议真的帮了我大忙。\p也许有一天，\n就是我们交手的时候了！\p感谢你所做的一切！$"

gText_ApprenticePickWinSpeech7::
	.string "哦，{PLAYER}。\n真高兴能遇见你！\p关于我的宝可梦，\n我已经没有任何顾虑了。\p让我担心的是我自己……\p你知道训练家赢了比赛后\n会说些什么吗？\p毫无疑问，我也希望能那样做！\p求你了，赢了比赛后\n我该说什么好呢？$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p啊！这句话！它让我神清气爽，\n仿佛重获新生！\p我必须马上就用上这句！\p那么现在，我必须告辞了，\n{PLAYER}……\p我会去和很多人对战，\l但永远不会忘记你的教导。\p也许有一天……\n再会了！$"

gText_ApprenticePickWinSpeech8::
	.string "呀！我看到{PLAYER}了！\n我……我见到你太高兴了！\p哦——哦——哦！有件事\n我非问你不可！\p不久前，我赢了一场对战。\n那部分让我飘飘然！\p但它让我太高兴了，\n我激动得说不出话来！\p所以现在，{PLAYER}，拜托了，\n我想让你帮我想一句\l赢了之后退场的台词！$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p哇啊啊啊！\n我要说这句？！\l我……我高兴得快疯了！\p谢——谢——谢谢你！\n我现在没有遗憾了！\p我现在要去旅行了，\n要和各种各样的人对战。\p这一切，都归功于你，{PLAYER}。\n真的，真的，谢谢你！\p我得走了，但总有一天\n我们要在战场上见！$"

gText_ApprenticePickWinSpeech9::
	.string "喂，你好！\n{PLAYER}{KUN}！\p你知道吗，\n我有点想去各地旅行对战了。\p但在那之前，我还想\n再请教你一次，拜托了！\p如果我赢了比赛，\n有什么好的炫耀词\l可以对战败的训练家对手说呢？$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p嗯哼，这话真棒！\nSi, bueno！嗯哼，\l我会试着这么说，就像，火腿！\p那么，是时候说再见了！\n感谢你为我做的一切！\p改天和我对战一场，好吗？\n再见！$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}，出大麻烦了！\p我赢了比赛后，\n至少要吹嘘一个小时！\p当然我是骗你的！\n哇哈哈哈！\p不过这不是骗人的。\n我不太擅长聊天。\p所以，不如你替我决定一下\n赢了比赛后该说什么吧，\l师父？$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p这就是我该说的，是吗？\n那么，我会远离那句的！\p开个玩笑啦！\n我会遵从您的教诲的，师父！\p谢谢您一直以来的教导，\n师父！\p我终于开始明白\n身为训练家意味着什么了。\p我要出去和任何训练家对战\n并赢得胜利。\p也许有一天会是你，师父！\p就这样吧！\n再见了，我的师父！$"

gText_ApprenticePickWinSpeech11::
	.string "A——H——O——Y！\n就是Ahoy，嗨的拼法！\p我就是那个说唱水手！\n这将是我最后的问题，\l你可别哭！\p这是个寻求你建议的\n台词问题！\p如果我赢了比赛，\n该怎么说才显得超酷？$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p完美！我就用这句了。\n让你选果然是对的！\p那么现在，我想是时候\n让我展翅高飞了！\p谢谢你教会我的一切。\n我要出发去大干一场了！\pB——O——N——V——O——Y——\nA——G——E！\l就是Bon voyage的拼法，\l以此向你致敬！$"

gText_ApprenticePickWinSpeech12::
	.string "哦，耶，{PLAYER}！\n今天又找到你了！\p我该怎么办？再问你一次？\n为什么不呢？反正我都在问了！\p总之，{PLAYER}……\n你收到我的信号了吗？\l你收到了！\l我需要再要点建议！\p是关于我该喊什么的。\n战斗顺利结束时\l该喊点什么酷酷的话。\p来吧，我想听你说出来！$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p好极了，好极了！\n我就用这句了，因为它太赞了！\p我已经没东西问你了。\n只剩下挥手告别了。\p但也许有一天我们会相遇，\n其中一人注定要败北。\p不过，真的该说再见了。\p嗯，{PLAYER}，我得自由闯荡了，\n但你可别忘了我！\p保重，{PLAYER}！\n爱你哟！$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}，我完了……\n我的鼻涕止不住地流……\p我刚才在努力想\n赢了比赛时该说的酷酷台词。\p它太让我激动了，我哭了，\n现在我的鼻涕就停不下来……\p所以，情况就是这样，\n我需要你帮我决定，{PLAYER}{KUN}。\p我赢了比赛后，\n该说什么呢？$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p…… …… ……这句不错。\n不，是令人惊叹！\l它让我又热泪盈眶了！\p但尽管我泪流满面、鼻涕直流，\n我也会用这句台词的！\p我已经没东西问你了，\n{PLAYER}{KUN}。\p从现在起，我们是劲敌了！\p感谢你为我做的一切！$"

gText_ApprenticePickWinSpeech14::
	.string "呃……嗯…\n{PLAYER}{KUN}……\p拜托，别那样看着我。\n你让我好紧张。\p我……我又需要你的建议了。\n不过这是最后一次了……\p问这个真的很不好意思，\n但如果我赢了比赛呢？\l我该说什么？$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p哦……好的！\n我会试着说这句的！\l我可能会紧张得说不出来……\p谢谢你，{PLAYER}{KUN}。\n我现在得说再见了。\p我会遵从你教给我的一切，\n{PLAYER}{KUN}，尽我所能做到最好。$"

gText_ApprenticePickWinSpeech15::
	.string "嗯？你好像是{PLAYER}{KUN}……\n但你真的是吗？\l或许是个聪明的{PLAYER}人偶？\p哦，不不不，别担心！\n如果你是真的，请忘了\l我的无礼吧。\p没必要这么生气。我所希望的\n只是更多你宝贵的建议。\p是关于一句台词的。\p更确切地说，如果我赢了比赛，\n我该说什么？$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p…… …… …… …… …… …\n当我赢了比赛时……\p{STR_VAR_1}\p……你是认真的吗？\p我明白了。\n如果你是认真的，那好吧。\l感谢你抽空帮我。\p我希望连我也能\n好好利用这句台词。\p我似乎已经想不出\n还需要什么建议了。\p我想是时候向你告别，\n独自出发了。\p谢谢你，我的导师！\n我为我的怀疑向你道歉！$"
