FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "欢迎来到对战帐篷\n秋叶镇分址！\p我是您的三回合定胜负\n锦标赛的向导！$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "要挑战三回合定胜负锦标赛吗？$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "随时恭候您再次挑战！$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "在秋叶镇对战帐篷中，\n我们将举办三回合定胜负锦标赛。\p所有的参赛者用3只宝可梦\n组成的队伍参加比赛。\p这3只宝可梦需要按照\n想要出场的顺序排列好。\p对战时，宝可梦会按照事先\n安排好的顺序依次出场。\p一旦宝可梦进入到对战，\n就需要持续战斗至比赛结束。\p如果比赛在3回合内未能决出胜负，\n将由裁判进行判定。\p如果您在挑战途中\n想要暂停的话，\p请确保在退出前完好地写下了记录。\n否则我们将视挑战为无效。\p如果您能成功击败3个训练家的话，\n我们将向您呈上精美奖品。$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "在挑战对战帐篷之前\n要先写入记录，可以吗？$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "我们提供2个级别的比赛，\nLv. 50级和自由等级\l您要参加哪个？$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "好的，请选择\n3只宝可梦。$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "这位客人！\p您能够参加对战的\n宝可梦不满3只。\p您需要准备3只等级50以内的\n不同种类的宝可梦，\p且让它们分别携带不同道具\n才可参加对战。\p此外，蛋{STR_VAR_1}无法参加对战！\p请在准备就绪之后，\n再来参加吧！$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "这位客人！\p您能够参加对战的\n宝可梦不满3只。\p您需要准备3只\n不同种类的宝可梦，\p且让它们分别携带不同道具\n才可参加对战。\p此外，蛋{STR_VAR_1}无法参加对战！\p请在准备就绪之后，\n再来参加吧！$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "我现在带您\n进入对战帐篷。$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "这位客人！\p您在上次结束时\n没有写入记录吧？\p非常遗憾，没有写入记录的\n挑战我们将视其为无效。\p当然，您可以随时开始\n一次新的挑战。$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "太棒了！您连续打败了\n3位训练家！$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "正在写入记录……请稍候。$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "为纪念您取得3连胜，\n特此为您颁发这份奖品。$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER}得到了\n{STR_VAR_1}。$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "哎？\n包包已经满了。\p请把包包整理好之后\n再来领取吧。$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "辛苦了！\p正在写入记录……请稍候。$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "随时恭候您再次挑战！$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "我们一直恭候\n您的到来。\p在带您进入对战帐篷之前，\n需要先写入记录。请稍候。$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "欢迎来到对战帐篷\n绿茵镇分址！\p训练家对宝可梦的信赖\n将在此接受考验。$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "要挑战绿茵镇对战帐篷吗？$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "在绿茵镇对战帐篷中，\n需要遵守一条关键规则——\p训练家只能替换\n自己的宝可梦，\p禁止对它们下达\n任何战斗指令。\p宝可梦将完全凭借自己的\n本能战斗，\p您需要完全信赖您的宝可梦，\n在一边旁观它们对战。\p如果您能成功地连续\n打败7个训练家，\l我们将向您呈上精美奖品。\p如果您在挑战途中\n想要暂停的话，\p请确保在退出前完好地写下了记录。\n否则我们将视挑战为无效。$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "当您的心灵与您的宝可梦都变得\n更强的时候，再回到这里来吧。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "有2个级别，\nLv. 50级和自由等级。\l您要挑战哪个？$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "唉……\p您能够参加对战的\n宝可梦不满3只。\p您需要准备3只等级50以内的\n不同种类的宝可梦，\p且让它们分别携带不同道具\n才可参加对战。\p此外，蛋{STR_VAR_1}无法参加对战！\p请在准备就绪之后，\n再来参加吧！$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "唉……\p您能够参加对战的\n宝可梦不满3只。\p您需要准备3只\n不同种类的宝可梦，\p且让它们分别携带不同道具\n才可参加对战。\p此外，蛋{STR_VAR_1}无法参加对战！\p请在准备就绪之后，\n再来参加吧！$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "好的。现在请您选择\n3只宝可梦。$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "在进入对战帐篷之前需要\n先写入记录，可以吗？$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "很好。\n那么，请随我来。$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "很荣幸能观赏到\n您的宝可梦的英姿。\p正在记录比赛成绩，\n请稍候。$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "您达成了3连胜……\p看来您的心灵与宝可梦之间的\n牵绊已经坚不可摧。$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "正在记录比赛成绩，\n请稍候。$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "为纪念您取得3连胜，\n特此为您颁发这份奖品。$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "欢迎来到对战帐篷\n凯那市分址！\p我是您的交换式对战\n锦标赛的向导。$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "要挑战交换式对战\n锦标赛吗？$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "这里是凯那市对战帐篷，\n这里举办的比赛是只能使用租借的\l宝可梦进行的交换式对战。\p首先，您将获得3只专门为本次比赛\n提供的租借宝可梦。\p您需要用这些提供的租借宝可梦，\n进行一场单打对战。\p如果获胜，您可以将其中1只\n租借宝可梦交换掉。\p如此反复进行战斗与交换——\n如果您能连续获胜3次，\l我们将向您呈上精美奖品。\p如果您在挑战途中\n想要暂停的话，\p请确保在退出前完好地写下了记录。\n否则我们将视挑战为无效。$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "我们期待您的再次光临。$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "您要挑战哪个等级？\nLv. 50级还是100级？$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "在挑战前需要先写入记录，\n可以吗？$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "好的，我会替您保管\n宝可梦。$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "这边请。$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "辛苦了！\p我将把您的宝可梦还给您\n并换回租借宝可梦。\p并且需要写入对战记录。\n请稍等。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "我要将您的宝可梦还给您\n并且收回我们借给您的宝可梦。$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "恭喜您！\n您获得了3连胜！\p我将把您的宝可梦还给您\n并换回租借宝可梦。\p并且需要写入对战记录。\n请稍等。$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "为纪念您取得3连胜，\n特此为您颁发这份奖品。$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "哎？\n包包已经满了。\p请把包包整理好之后\n再来领取吧。$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "我们已经恭候多时了！\p在您继续战斗之前，\n需要先写入记录。$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "很抱歉地告诉您。\p由于您在上次结束时\n没有写入记录，\p因此您本次的挑战\n我们将视其为无效。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "我们将归还您的宝可梦。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER}得到奖品\n{STR_VAR_1}。$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "交换式对战规则已经列出。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "要读哪一部分的说明？$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "在交换式对战中，\n您只能用3只宝可梦。\p无论是租借还是交换得到的，\n您的队伍中里不能出现2只\l或以上相同种类的宝可梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "您只能与刚击败过的训练家\n交换宝可梦。\p您只能交换到该训练家\n所使用的宝可梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "每获胜1场战斗后，\n您可以选择交换对手的1只宝可梦。\p第3位训练家\n不可进行交换。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "在交换宝可梦时有2个\n需要注意的地方。\p第一，交换时您无法查看目标\n宝可梦的具体能力。\p第二，队伍中的宝可梦的排列顺序\n按租用时的顺序固定。\p交换后该顺序仍保持不变。$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "在凯那市对战帐篷中\n使用的宝可梦都是租借的。\p所有租借的宝可梦\n等级均为30。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "绿茵镇对战帐篷的\n规则已经列出$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "要读哪一部分的说明？$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "在绿茵镇对战帐篷，\n宝可梦需要独立\l思考并战斗。\p不像在野外，宝可梦和人类一起生存\n由于自然环境不同\l行为也不同。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "由于它所处自然环境，宝可梦可能\n会不知原因的攻击。\p另外的宝可梦可能会\n保护自己免受伤害。\p有的还喜欢干扰\n和迷惑自己的敌人。\p由于它所处的自然环境，宝可梦可能\n有它所最喜欢的招式\l并且可以熟练使用。\p它也有可能存在不喜欢的招式\n于是不擅长使用。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "有攻击招式可以\n对敌人造成直接伤害。\p有防守招式\n用来防御敌人的攻击\l或用来恢复HP等等。\p也有一些有点怪异的招式\n可以使得敌人变得无力和带来\l其他问题，例如中毒和麻痹。\p宝可梦可能会考虑在\n这3种招式中选择使用。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "当没有听从训练家的命令时\n宝可梦可能不会有效的使用特定招式。\p宝可梦不擅长使用\n任何它不喜欢的招式。\p如果宝可梦仅仅知道些\n不符合其性格的招式，\l那么它就不会展示它的潜能。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "根据其性格，\n当陷入麻烦时，宝可梦可能会开始\l使用一些并不符合性格的招式。\p如果宝可梦开始变得行为怪异，\n您就有必要仔细查看了。$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "在对战帐篷中，对手的宝可梦等级会\n根据您的宝可梦等级进行调整。\p但是，训练家所持有的宝可梦\n最低不会低于等级30。$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "上面列出了绿茵镇对战帐篷的规则。$"
