gText_Birch_Welcome::
	.string "哎呀——让你久等啦！\p欢迎来到宝可梦的世界！\p我的名字是小田卷。\p不过大家都叫我\n宝可梦博士。\p$"

gText_Birch_Pokemon::
	.string "这就是被我们称为“宝可梦”的生物。$"

gText_Birch_MainSpeech::
	.string "这个世界上叫做宝可梦的\n生物随处可见。\p人们和宝可梦友好相处、共同生活，\n有时作为玩伴一起玩耍，\l有时作为同伴协力工作。\p也有时候，我们指挥宝可梦并肩而战，\n与其他人彼此对战切磋。\p尽管如此亲密，\n我们仍未了解宝可梦的一切。\p事实上，宝可梦身上的秘密\n依然数不胜数！\p为了揭开宝可梦的秘密，\n我倾注了毕生心血进行研究。\l这就是我一直在做的事。\p$"

gText_Birch_AndYouAre::
	.string "对了，你是……$"

gText_Birch_BoyOrGirl::
	.string "男孩？\n还是女孩？$"

gText_Birch_WhatsYourName::
	.string "好的。\n能告诉我你的名字吗？$"

gText_Birch_SoItsPlayer::
	.string "是{PLAYER}{KUN}吗？$"

gText_Birch_YourePlayer::
	.string "……原来如此！\p你就是即将搬到\n未白镇来的{PLAYER}{KUN}啊！\l我知道了！\p$"

gText_Birch_AreYouReady::
	.string "好，准备好了吗？\p只属于你的冒险\n即将展开！\p鼓起勇气，迈进充满梦想、冒险与\n邂逅的宝可梦世界吧！\p之后在研究所见吧！\n我在那里等着你！\p$"
