BerryBlender_Text_BlendWithTheBlendMaster:
	.string "混合名人：没错！\n我就是传说中的混合名人！\p与我共舞吧，你将亲眼见证\n我登峰造极的混合技艺！$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "混合名人：嗯！你想亲眼\n见识我的独门技艺？$"

BerryBlender_Text_TooBusyNowIsee:
	.string "嗯！\p看来你现在很忙啊！\p不过别担心！\n我会在这里待一整天！\l快去快回吧！$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "嗯！\p你连一颗树果都没有！\p我会在这里待一整天！\n快去摘些树果回来！$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "当然！\n这还用说！\p顺便问一句……\n你知道怎么用树果制作\l宝可方块吧？$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "嗯！\p其实过程很简单！\p当混合器的箭头转到\n你的标记时，按下A键就行。\p就这么简单。\p等你见识到我精准按下A键的功力，\n就会明白其中奥妙了。$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "很好！\p那我们就开始吧！\p与混合名人一起，\n开始树果混合吧！$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "嗯！\p你好像还没拿到\n宝可方块盒啊！\p我会在这里待一整天！\n快去拿个宝可方块盒再回来！$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "嗯！\p你的宝可方块盒好像满了！\p我会在这里待一整天！\n先用掉些宝可方块再回来吧！$"

BerryBlender_Text_WhoaAwesome:
	.string "哇！\n太厉害了！"

BerryBlender_Text_WickedlyFast:
	.string "真是快得惊人！$"

BerryBlender_Text_WhatAnExpert:
	.string "真是专家啊！$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "和名人一起混合，\n我们做出了超棒的宝可方块！$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "如机器般精准追踪箭头的双眼……\p如钟表般精确按下A键的巧手……\p拥有这些特质，\n才成就了真正的混合名人。$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "据说混合名人常年在深山中\n磨练他的技艺。\p有时他会来到水静市，\n混合树果一整天。$"
