@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "我是宝可梦育儿屋的大叔。\p"
	.string "我专门帮训练家照料\n"
	.string "珍贵的宝可梦。\p"
	.string "如果你想让我帮你\n"
	.string "培育宝可梦，请跟我妻子说。$"

DayCare_Text_DoYouWantEgg::
	.string "啊，是你啊！\p"
	.string "我们正在帮你照料宝可梦，\n"
	.string "结果发现了一件大事！\p"
	.string "你的宝可梦产了一颗蛋！\p"
	.string "我也不知道是怎么回事，\n"
	.string "但它确实产了一颗蛋。\p"
	.string "你要这颗蛋吗？$"

DayCare_Text_YourMonIsDoingFine::
	.string "啊，是你啊！好久不见。\n"
	.string "你的{STR_VAR_1}状态很好。$"

DayCare_Text_IllKeepIt::
	.string "好的，那我就留下它了。\n"
	.string "谢谢！$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "你没有空间了……\n"
	.string "请整理后再来。$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER}从育儿屋大叔\n"
	.string "那里收到了那颗蛋。$"

DayCare_Text_TakeGoodCareOfIt::
	.string "好好爱护它哦。$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.string "啊，是你啊！你的{STR_VAR_1}和\n"
	.string "{STR_VAR_2}状态都很好。$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "我确实会留下它。\n"
	.string "你真的要吗？$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "我是育儿屋的大婶。\p"
	.string "我们可以帮你培育宝可梦。\p"
	.string "要让我们帮你培育吗？$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "你要寄养哪只宝可梦？$"

DayCare_Text_WellRaiseYourMon::
	.string "好的，我们帮你培育{STR_VAR_1}\n"
	.string "一段时间。\p"
	.string "之后再来领回它吧。$"

DayCare_Text_WeCanRaiseOneMore::
	.string "我们可以帮你培育两只宝可梦。\p"
	.string "还要再寄养一只宝可梦吗？$"

DayCare_Text_HusbandWasLookingForYou::
	.string "我丈夫在找你。$"

DayCare_Text_FineThenComeAgain::
	.string "哦，好的。\n"
	.string "欢迎再来。$"

DayCare_Text_NotEnoughMoney::
	.string "你的钱不够……$"

DayCare_Text_TakeOtherOneBackToo::
	.string "另一只你也要带走吗？$"

DayCare_Text_ComeAgain::
	.string "好的。\n"
	.string "欢迎再来。$"

DayCare_Text_GoodToSeeYou::
	.string "啊，是你啊！\n"
	.string "好久不见。\p"
	.string "你的宝可梦们\n"
	.string "都很有活力！$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "你的{STR_VAR_1}的等级\n"
	.string "差不多提高了{STR_VAR_2}级。$"

DayCare_Text_YourPartyIsFull::
	.string "你的同行宝可梦队伍满了。\n"
	.string "请整理后再来找我。$"

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.string "要带走你的{STR_VAR_1}，\n"
	.string "需要支付¥{STR_VAR_2}。$"

DayCare_Text_HeresYourMon::
	.string "好的！\n"
	.string "这是你的宝可梦。$"

DayCare_Text_TookBackMon::
	.string "{PLAYER}从育儿屋大婶那里\n"
	.string "领回了{STR_VAR_1}。$"

DayCare_Text_YouHaveJustOneMon::
	.string "哦？你只有一只\n"
	.string "宝可梦。\p"
	.string "下次再来吧。$"

DayCare_Text_TakeYourMonBack::
	.string "你要带走你的宝可梦吗？$"

DayCare_Text_WhatWillYouBattleWith::
	.string "如果你把那只宝可梦留下，\n"
	.string "你用什么来对战呢？\p"
	.string "下次再来吧。$"

DayCare_Text_Huh::
	.string "啊？$"
