gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}大木宝可梦研究所$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}制作一本关于世界上\n"
	.string "所有宝可梦的完整图鉴……\p"
	.string "那是我的梦想！$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}大木博士看上去可能不起眼，\n"
	.string "但他是宝可梦方面的权威。\p"
	.string "许多宝可梦训练家\n"
	.string "都对他非常敬重。$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说大木博士与他的\n"
	.string "孙子{RIVAL}和孙女黛西同住。$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我听说大木对你很感兴趣，孩子。\p"
	.string "那个老头子从前强壮又英俊。\p"
	.string "但那是几十年前的事了。\n"
	.string "他已经今非昔比了。$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}大木博士很快就要\n"
	.string "拥有自己的广播节目了。\p"
	.string "节目名叫大木博士的\n"
	.string "宝可梦讲座。$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}如果你把宝可梦给黛西看，\n"
	.string "她能告诉你宝可梦有多喜欢你。\p"
	.string "偶尔她还会帮\n"
	.string "你的宝可梦梳理毛发。$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}不过我觉得最受\n"
	.string "宝可梦喜爱的人是黛西。$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}她在温柔地给宝可梦梳理毛发……\n"
	.string "她真是个小天使。\p"
	.string "那个小女孩的名字……\n"
	.string "我想应该叫黛西。$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说大木博士与他的\n"
	.string "孙子{RIVAL}和孙女黛西同住。$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}来自真红城市的女孩黛西，\n"
	.string "每天都爱喝茶。\p"
	.string "她会去玉百货\n"
	.string "购买茶叶。$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}春季宝可梦大赛的\n"
	.string "总冠军是来自真红城市的\l"
	.string "大木黛西！$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}尼比城宝可梦道馆\n"
	.string "馆主：小刚\l"
	.string "坚如磐石的宝可梦训练家！$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我如岩石般坚硬的意志\n"
	.string "体现在我的宝可梦身上。\p"
	.string "我的宝可梦都坚如磐石，\n"
	.string "拥有坚韧不拔的精神。\p"
	.string "没错——我的宝可梦\n"
	.string "全都是岩石属性！$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}这里没有多少认真的\n"
	.string "宝可梦训练家。\p"
	.string "他们都像抓虫高手一样，\n"
	.string "只是业余爱好者而已。\p"
	.string "但尼比道馆的小刚\n"
	.string "完全不一样。$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}小刚很帅气。他不只是强而已。\n"
	.string "大家都喜欢他、尊敬他。\p"
	.string "我也想成为像他一样的\n"
	.string "道馆馆主。$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}你好，我在月亮山地下\n"
	.string "挖掘化石。\p"
	.string "有时候，尼比道馆的小刚\n"
	.string "会来帮我的忙。$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说小刚很少笑，\n"
	.string "但一旦开始就停不下来。$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}华砺城宝可梦道馆\n"
	.string "馆主：小霞\l"
	.string "假小子美人鱼！$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我的方针是\n"
	.string "用水属性宝可梦全力进攻！$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}小霞是一个会不断进步的\n"
	.string "训练家。\p"
	.string "她不会输给你这样的人的！$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}在这附近经常能看到\n"
	.string "强大的训练家和水系宝可梦。\p"
	.string "据说华砺道馆的小霞\n"
	.string "就在这里训练。$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}这个海角是著名的约会胜地。\p"
	.string "道馆馆主小霞对\n"
	.string "这个地方抱有很高的期望。$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说小霞非常崇拜\n"
	.string "四天王的菊子。$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}朱红城市宝可梦道馆\n"
	.string "馆主：马志士\l"
	.string "雷电之美国人！$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我告诉你，孩子，\n"
	.string "电系宝可梦在战争中救了我！$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我当兵的时候，马志士是\n"
	.string "我严格的上司。\p"
	.string "他是个严苛的长官。$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}马志士在军队里\n"
	.string "一向以谨慎著称。$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}马志士亲自在道馆里\n"
	.string "安装了陷阱。\p"
	.string "他在各处都设置了双重锁。$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说马志士在美国老家\n"
	.string "曾是一名飞行员。\p"
	.string "他用宝可梦产生的电力\n"
	.string "为飞机提供动力。$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}玉城宝可梦道馆\n"
	.string "馆主：莉佳\l"
	.string "热爱自然的公主！$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我是一名插花艺术的学生。\p"
	.string "我的宝可梦\n"
	.string "全都是草属性的。$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我们的馆主莉佳虽然沉默寡言，\n"
	.string "但她在这附近很有名。$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我们道馆只使用草属性宝可梦。\p"
	.string "为什么？因为我们也用它们\n"
	.string "来插花！$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}如果宝可梦不美丽，\n"
	.string "我是绝对不会收集它们的。$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说如果你偷偷往玉道馆里看，\n"
	.string "经常能看到\l"
	.string "莉佳在打盹。$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}赤焰城宝可梦道馆\n"
	.string "馆主：阿桔\l"
	.string "毒液忍者高手$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}在毒属性宝可梦\n"
	.string "令人毛骨悚然的恐惧中绝望吧！$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}即使我失败了，我也会\n"
	.string "继续按照我的忍者师父\l"
	.string "阿桔的教导训练。$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我父亲是这个城市的道馆馆主。\p"
	.string "我正在训练，目标是\n"
	.string "毒系宝可梦用得和父亲一样好。$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说阿桔对医学有\n"
	.string "深入的了解。\p"
	.string "他甚至会亲自调配药物\n"
	.string "来治愈他的宝可梦。$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}狩猎区很大，对吧？\p"
	.string "赤焰城的道馆馆主阿桔 \n"
	.string "时不时会在这里巡逻。\p"
	.string "多亏了他，我们才能\n"
	.string "安心地在这里玩耍。$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}黄金城宝可梦道馆\n"
	.string "馆主：娜姿\l"
	.string "超能力宝可梦大师！$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}你知道黄金城有个\n"
	.string "女道馆馆主吗？\p"
	.string "她用超能力属性宝可梦，\n"
	.string "对吧？$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我从小就拥有超能力。\p"
	.string "最初是我随手扔出一把汤匙，\n"
	.string "它弯曲了。$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我不喜欢对战，\n"
	.string "但如果你想，我会展示我的力量！$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说娜姿能在对战中\n"
	.string "不用说话就与她的宝可梦\l"
	.string "沟通。$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}娜姿刚刚击败了\n"
	.string "隔壁的格斗道馆馆主。$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}红莲岛宝可梦道馆\n"
	.string "馆主：卡苟\l"
	.string "火暴的益智问答大师！$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我的火系宝可梦\n"
	.string "个个热气腾腾、蓄势待发！\p"
	.string "它们会将所有挑战者烧成灰烬！$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我们的馆主卡苟曾经在\n"
	.string "山里彻底迷了路。\p"
	.string "夜幕降临时，一只火焰鸟\n"
	.string "宝可梦出现了。\p"
	.string "它的光芒让卡苟得以\n"
	.string "安全找到下山的路。$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}红莲道馆的卡苟是个\n"
	.string "相当奇特的人。\p"
	.string "他住在这个岛上的时间\n"
	.string "比研究所建立还早。$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}这是卡苟和\n"
	.string "富士老爷爷的合影。\p"
	.string "两人肩并肩，\n"
	.string "笑得合不拢嘴。$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说卡苟只有在\n"
	.string "想新的益智问题时\l"
	.string "才会摘下深色眼镜。$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我是四天王菊子。$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}说到冰系宝可梦，\n"
	.string "没有人能胜过我。$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人在哪里出生？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}这座岛上出了一位\n"
	.string "伟大而强大的训练家。\p"
	.string "我敢打赌你也认识她。\n"
	.string "就是四天王菊子！$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}以冷静、沉着、冷酷的\n"
	.string "对战风格著称，菊子\l"
	.string "却有一个令人惊讶的秘密！$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}你知道菊子有\n"
	.string "好多好多毛绒玩偶吗？\p"
	.string "每次她回到四之岛，\n"
	.string "她的收藏都会增加！$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}她的拉普拉斯，\n"
	.string "我猜那是她小时候遇到的那只。\p"
	.string "我想她是在冰瀑洞里\n"
	.string "抓到它的。\p"
	.string "也许那只宝可梦\n"
	.string "从那以后就一直陪着她。$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我是四天王西布！$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我和我的格斗宝可梦\n"
	.string "一起生活、一起训练！$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说西布加入四天王\n"
	.string "是出于与最强训练家\l"
	.string "对战的强烈抱负。$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}比我资深的西布\n"
	.string "偶尔会来温泉。\p"
	.string "他来是为了康复疗养，\n"
	.string "他自己和宝可梦的伤都要照顾。$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}他是四天王之一。\n"
	.string "他叫西布。\p"
	.string "他发现愤怒糖果棒\n"
	.string "已经全部售罄后\l"
	.string "失望地离开了。$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}就连西布……\n"
	.string "他以前曾经与一个\l"
	.string "叫阿博的家伙一起训练过。$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我是四天王菊里。$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}菊里的幽灵属性宝可梦\n"
	.string "强大得令人毛骨悚然。$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}那个老太太脾气也非常火爆。\p"
	.string "不需要什么原因，\n"
	.string "那个可怕的老太太就会大喊大叫。$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}年轻时，菊里和大木博士\n"
	.string "是互相争夺训练家\l"
	.string "最强宝座的对手。$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我听说大木对你很感兴趣，孩子。\p"
	.string "那个老头子从前强壮又英俊。\p"
	.string "但那是几十年前的事了。\n"
	.string "他已经今非昔比了。$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}就以菊里为例吧。\p"
	.string "她创造了成为四天王中\n"
	.string "年龄最大成员的记录。$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我是四天王的首领。\p"
	.string "你可以叫我龙属性\n"
	.string "训练家阿渡。$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}你知道龙是传说中的宝可梦。\p"
	.string "它们难以捕捉和培育，\n"
	.string "但它们的力量无与伦比。\p"
	.string "它们几乎无法被击败。\n"
	.string "对付它们没有什么妙招。$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}他代表正义！\n"
	.string "他冷酷，却又充满热情！\l"
	.string "他是最棒的，阿渡！$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我们有个顾客叫阿渡，\n"
	.string "他偶尔会来光顾。\p"
	.string "他每次都买斗篷。\p"
	.string "我在想……他家里\n"
	.string "有很多一模一样的斗篷吗？$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}阿渡的祖父据说是\n"
	.string "一个著名的龙系训练家\l"
	.string "家族的长老。$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据我所知，阿渡有\n"
	.string "一个表亲是很远地方的\l"
	.string "道馆馆主。$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}毕竟蔡德作为宝可梦狂热者\n"
	.string "举世闻名。\p"
	.string "他还发明了电脑上的\n"
	.string "宝可梦保管系统。$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}蔡德有好多宝可梦！\n"
	.string "他还收集稀有的宝可梦！$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}他是我的孙子！\p"
	.string "他从小就喜欢收集东西！$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}蔡德是宝可梦狂热者，\n"
	.string "所以他喜欢所有种类的宝可梦。\p"
	.string "据说他抓到的第一只\n"
	.string "宝可梦是凯西。$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}蔡德的老家是金黄市，\n"
	.string "他的家人至今还住在那里。\p"
	.string "我听说那是一个\n"
	.string "非常热闹繁华的城市。$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}据说蔡德完全\n"
	.string "喝不了牛奶。$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}他非常善良。\p"
	.string "他照顾被遗弃的\n"
	.string "和孤儿宝可梦。$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}这个老头子径直走进\n"
	.string "我们的基地。\p"
	.string "然后他开始喋喋不休地说\n"
	.string "火箭队虐待宝可梦的事。\p"
	.string "所以我们只是\n"
	.string "像大人一样谈判。$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}宝可梦迷杂志\n"
	.string "每月大奖抽签！\p"
	.string "申请表是……\p"
	.string "没了！被剪掉了。\n"
	.string "一定有人已经申请了。$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}有个传言……\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我听说富士老爷爷\n"
	.string "原本也不是这里的人。$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}这是卡苟和\n"
	.string "富士老爷爷的合影。\p"
	.string "两人肩并肩，\n"
	.string "笑得合不拢嘴。$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}编辑：腼腆的富士老爷爷\n"
	.string "拒绝了我们的采访请求。\p"
	.string "他是一位善良的人，\n"
	.string "在紫苑镇深受爱戴和尊敬。$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}火箭队从世界各地\n"
	.string "捕捉宝可梦。\p"
	.string "它们是维持我们犯罪事业\n"
	.string "运转的重要工具。\p"
	.string "我就是首领，坂木！$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}喜欢什么宝可梦？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}那些占领了我们大楼的流氓……\p"
	.string "他们的老大说\n"
	.string "他在寻找强大的宝可梦。$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人如何？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}火箭队的老大极其残忍！\p"
	.string "对他来说，宝可梦\n"
	.string "只不过是被利用的工具。$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}欢迎来到我的基地！\p"
	.string "在我能让火箭队恢复\n"
	.string "昔日荣耀之前，这里是我的据点。$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}这个人做什么？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}真惊人！坂木曾经是\n"
	.string "常磐城的道馆馆主？$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}家人和朋友？\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}你……你不会是坂木的孩子吧？\p"
	.string "不，那不可能是真的。\n"
	.string "坂木的孩子是红头发。$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}大木博士$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：大木博士\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}为什么宝可梦会为你\n"
	.string "如此努力地竞争和对战？\p"
	.string "那是因为它们能感受到\n"
	.string "你对宝可梦的爱与信任。\l"
	.string "永远不要忘记这一点。$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}黛西$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：黛西\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}在我悠闲地享用茶歇的时候，\n"
	.string "你已经变得非常\l"
	.string "出色和强大了。\p"
	.string "希望你继续做我弟弟的\n"
	.string "好对手。$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}小刚$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：小刚\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}在我们这个广阔的世界里，\n"
	.string "一定有很多强大的训练家。\p"
	.string "让我们都继续训练，\n"
	.string "让自己变得更强大吧！$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}小霞$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：小霞\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我要继续在这个道馆训练。\p"
	.string "等我变得更强，\n"
	.string "我很想踏上旅途、四处旅行。$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}马志士$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：马志士\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}嘿，孩子！\n"
	.string "你在我们的对战中让我热血沸腾！\p"
	.string "我不知道有像你这样\n"
	.string "胆子大的训练家。\p"
	.string "这让我对你刮目相看了！$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}莉佳$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：莉佳\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}有像你这样强大的训练家，\n"
	.string "我真的很高兴。\p"
	.string "光是这种意识就能\n"
	.string "激励我更加努力。\p"
	.string "请再来找我。\n"
	.string "Zzz……$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}阿桔$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：阿桔\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}你和我，我们都必须\n"
	.string "志存高远，努力迎接\l"
	.string "我们的挑战。\p"
	.string "现在，我必须去训练我的女儿了。$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}娜姿$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：娜姿\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}你对宝可梦的爱……\p"
	.string "那是一种力量，\n"
	.string "从未被我的超能力所胜。$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}卡苟$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：卡苟\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我的火系宝可梦！\n"
	.string "它们将变得更加强大！\p"
	.string "现在，来个测验。\n"
	.string "火属性宝可梦有多少种？$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}菊子$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：菊子\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我需要感谢你的帮助。\p"
	.string "但那与我们的对战\n"
	.string "毫无关系。\p"
	.string "下次你最好小心点！$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}西布$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：西布\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}你和你的宝可梦的超强力量\n"
	.string "我已经亲身体验过了。\p"
	.string "下次，也许我该教教你\n"
	.string "如何锻炼自己。$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}菊里$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：菊里\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}等你长大了，\n"
	.string "千万别像那个老糊涂大木一样软掉！\p"
	.string "要像我一样，\n"
	.string "继续战斗下去！$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}阿渡$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：阿渡\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我在考虑回老家。\p"
	.string "我想重新训练我的\n"
	.string "龙属性宝可梦，让它们更强大。\p"
	.string "我希望有一天能邀请你\n"
	.string "到我的老家来。$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}蔡德$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：蔡德\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}嘿，你好！\n"
	.string "塞里尔对你赞不绝口。\p"
	.string "听到这个消息让我很高兴。\p"
	.string "等你抓到稀有宝可梦，\n"
	.string "来给我看看，好吗？说好了！$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}富士老爷爷$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：富士老爷爷\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}与其只希望你的宝可梦幸福……\p"
	.string "……能请你也祈愿\n"
	.string "所有宝可梦的幸福吗？$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}坂木$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}发件人：坂木\n"
	.string "收件人：{PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}我没有什么想对你说的。\p"
	.string "我将专注于\n"
	.string "提升自己，没有其他。$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "真红城市$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "常磐城$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "朱红城市$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "水上迷宫$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "常磐城$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "玉大楼$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "四之岛$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "尼比城$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "尼比道馆$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "尼比城$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "4号道路$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "月亮山$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "尼比博物馆$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "华砺城$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "华砺道馆$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "华砺道馆$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "冰柱岛$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "华砺岬$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "华砺城$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "朱红城市$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "朱红道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "朱红道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "朱红道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "朱红道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "朱红城市$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "玉城$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "玉道馆$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "玉道馆$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "玉道馆$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "玉道馆$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "玉大楼$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "赤焰城$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "赤焰道馆$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "赤焰道馆$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "赤焰城$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "赤焰城$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "狩猎区$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "黄金城$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "三之岛$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "黄金道馆$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "黄金道馆$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "黄金城$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "黄金道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "红莲岛$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "红莲岛$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "豪华岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "四之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "五之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "四之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "四之岛$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "黄金城$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "火焰山温泉$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "二之岛$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "七之岛峡谷$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "常青高原$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "常青高原$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "七之岛$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "六之岛$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "黄金城$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "玉百货$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "常青高原$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "常青高原$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "华砺城$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "华砺城$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "赤焰城$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "一之岛$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "一之岛$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "一之岛$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "宝可梦之塔$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "红莲岛$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "火箭队基地$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "西尔芙公司$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "西尔芙公司$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "常磐道馆$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "常磐道馆$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "火箭队仓库$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "大木博士$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "菊里$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "女士$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "男士$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "老奶奶$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "小刚$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "年轻男士$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "男孩$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "男士$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "小霞$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "年轻男士$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "女士$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "马志士$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "莉佳$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "莉佳$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "阿桔$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "男士$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "年轻男士$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "娜姿$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "娜姿$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "卡苟$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "女士$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "照片$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "菊子$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "菊子$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "老爷爷$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "老奶奶$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "西布$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "西布$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "搏击者$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "女士$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "搏击者$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "菊里$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "搏击者$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "搏击者$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "菊里$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "老奶奶$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "阿渡$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "阿渡$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "女士$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "年轻男士$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "小男孩$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "老爷爷$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "塞里尔$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "塞里尔$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "塞里尔$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "火箭队$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "杂志$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "男士$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "照片$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "宝可梦杂志$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "坂木$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "研究员$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "研究员$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "坂木$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "男士$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "宝可梦杂志\p"
	.string "特别专题：尼比道馆\n"
	.string "馆主小刚！\p"
	.string "据说小刚很少笑，\n"
	.string "但一旦开始就停不下来。$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "宝可梦杂志\p"
	.string "特别专题：华砺道馆\n"
	.string "馆主小霞！\p"
	.string "据说小霞非常崇拜\n"
	.string "四天王的菊子。$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "宝可梦杂志\p"
	.string "特别专题：朱红道馆\n"
	.string "馆主马志士！\p"
	.string "据说马志士在美国老家\n"
	.string "曾是一名飞行员。\p"
	.string "他用宝可梦产生的电力\n"
	.string "为飞机提供动力。$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "宝可梦杂志\p"
	.string "特别专题：玉道馆\n"
	.string "馆主莉佳！\p"
	.string "据说如果你偷偷往玉道馆里看，\n"
	.string "经常能看到\l"
	.string "莉佳在打盹。$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "宝可梦杂志\p"
	.string "特别专题：赤焰道馆\n"
	.string "馆主阿桔！\p"
	.string "据说阿桔对医学有\n"
	.string "深入的了解。\p"
	.string "他甚至会亲自调配药物\n"
	.string "来治愈他的宝可梦。$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "宝可梦杂志\p"
	.string "特别专题：黄金道馆\n"
	.string "馆主娜姿！\p"
	.string "据说娜姿能在对战中\n"
	.string "不用说话就与她的宝可梦\l"
	.string "沟通。$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "宝可梦杂志\p"
	.string "特别专题：红莲道馆\n"
	.string "馆主卡苟！\p"
	.string "据说卡苟只有在\n"
	.string "想新的益智问题时\l"
	.string "才会摘下深色眼镜。$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "宝可梦杂志\p"
	.string "特别专题：\n"
	.string "四天王菊子！\p"
	.string "以冷静、沉着、冷酷的\n"
	.string "对战风格著称，菊子\l"
	.string "却有一个令人惊讶的秘密！$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "宝可梦杂志\p"
	.string "特别专题：\n"
	.string "四天王西布！\p"
	.string "据说西布加入四天王\n"
	.string "是出于与最强训练家\l"
	.string "对战的强烈抱负。$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "宝可梦杂志\p"
	.string "特别专题：\n"
	.string "四天王菊里！\p"
	.string "年轻时，菊里和大木博士\n"
	.string "是互相争夺训练家\l"
	.string "最强宝座的对手。$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "宝可梦杂志\p"
	.string "特别专题：\n"
	.string "四天王阿渡！\p"
	.string "阿渡的祖父据说是\n"
	.string "一个著名的龙系训练家\l"
	.string "家族的长老。$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "宝可梦杂志\p"
	.string "特别专题：宝可梦研究者\n"
	.string "大木博士！\p"
	.string "据说大木博士与他的\n"
	.string "孙子{RIVAL}和孙女黛西同住。$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "这是一本多年前的\n"
	.string "宝可梦杂志……\p"
	.string "宝可梦杂志\n"
	.string "大赛特别报道！\p"
	.string "春季宝可梦大赛的\n"
	.string "总冠军是来自真红城市的\l"
	.string "大木黛西！$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "宝可梦杂志\p"
	.string "特别专题：\n"
	.string "宝可梦之家的富士老爷爷！\p"
	.string "编辑：腼腆的富士老爷爷\n"
	.string "拒绝了我们的采访请求。\p"
	.string "他是一位善良的人，\n"
	.string "在紫苑镇深受爱戴和尊敬。$"
