Trade_Text_LookingForMonWannaTradeForMon::
	.string "我正在寻找宝可梦\n"
	.string "{STR_VAR_1}！\p"
	.string "能用你的{STR_VAR_1}换\n"
	.string "我的{STR_VAR_2}吗？$"

Trade_Text_AwwOhWell::
	.string "哎！\n"
	.string "唉，没关系……$"

Trade_Text_WhatThatsNoMon::
	.string "什么？\n"
	.string "这不是{STR_VAR_1}！$"

Trade_Text_HeyThanks::
	.string "嘿，谢谢！$"

Trade_Text_IsntMyOldMonGreat::
	.string "我原来的{STR_VAR_2}很厉害吧？$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "你好！你有{STR_VAR_1}吗？\p"
	.string "愿意用你的{STR_VAR_1}和\n"
	.string "我的{STR_VAR_2}交换吗？$"

Trade_Text_WellIfYouDontWantTo::
	.string "如果你不想交换的话……$"

Trade_Text_ThisIsntMon::
	.string "嗯？\n"
	.string "这不是{STR_VAR_1}。\p"
	.string "如果你得到了，请来找我。$"

Trade_Text_Thanks::
	.string "谢谢！$"

Trade_Text_HasTradedMonGrownStronger::
	.string "我交换给你的{STR_VAR_2}，\n"
	.string "它变强了吗？$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "你好！\n"
	.string "你有{STR_VAR_1}吗？\p"
	.string "要用你的{STR_VAR_1}换\n"
	.string "我的{STR_VAR_2}吗？$"

Trade_Text_ThatsTooBad::
	.string "太可惜了。$"

Trade_Text_ThisIsNoMon::
	.string "……这不是{STR_VAR_1}。\p"
	.string "如果你有的话，来和我交换吧。$"

Trade_Text_ThanksYoureAPal::
	.string "谢谢，你真好！$"

Trade_Text_HowIsMyOldMon::
	.string "我原来的{STR_VAR_2}怎么样了？\n"
	.string "我的{STR_VAR_1}过得很好！$"
