MatchCall_WildBattleText1::
	.string "嗨！{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}。\p刚才我遇到了{STR_VAR_2}！\n但是没能捉到它。\p就差一点点！\n好了，下次见！$"

MatchCall_WildBattleText2::
	.string "你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p不久前我试着捕捉一只\n很棒的{STR_VAR_2}。\p但它还是跑掉了。\n真的好失望啊！\p好了，再见！$"

MatchCall_WildBattleText3::
	.string "你好啊，{PLAYER}！\n是我呀，{STR_VAR_1}。\p我刚才试着捕捉这只\n{STR_VAR_2}，但是给它逃掉了。\p差一点就成功了！\p今天算是倒霉……\n好了，下次见！$"

MatchCall_WildBattleText4::
	.string "嗨，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\p你知道宝可梦{STR_VAR_2}吗？\n我差点就捕捉到一只。\p就在刚才，\n我以为已经捕捉到了，\l但它还是跑了。\p如果再让我看见它，\n一定要捕捉到！\p好，回头见。$"

MatchCall_WildBattleText5::
	.string "你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\l最近捕捉到什么宝可梦了吗？\p刚才我差一点捕捉到一只，\n但是它逃掉了。\p好，多保重！$"

MatchCall_WildBattleText6::
	.string "嘿，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l最近有捕捉到什么宝可梦吗？\p前几天我差点捕捉到了一只。\n但是不知怎么它跑掉了。\p多保重。$"

MatchCall_WildBattleText7::
	.string "……嗯，{PLAYER}{KUN}？\n是我，{STR_VAR_1}。\p哦，等等！等等！\n我能捕捉到这只{STR_VAR_2}……\p啊啊！给他逃了！\n只差一点点啊！$"

MatchCall_WildBattleText8::
	.string "哦，{PLAYER}{KUN}，最近如何？\n我是{STR_VAR_1}。\p你捕捉宝可梦还顺利吗？\p不久前我差点抓到一只。\n但目标还是逃掉了。\p我还得再加把劲啊！\n下次见！$"

MatchCall_WildBattleText9::
	.string "哦，{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}！\p怎么样？有捕捉到\n更多宝可梦吗？\p我最近好倒霉，\n它们全都逃走了！\p再见！$"

MatchCall_WildBattleText10::
	.string "哦，{PLAYER}{KUN}，你好……\n我是{STR_VAR_1}。\p听着，我几乎马上就能捉到\n这只{STR_VAR_2}了……\p但是，它还是溜掉了……\p我得再加把劲。\n回头见。$"

MatchCall_WildBattleText11::
	.string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l最近怎么样？\p我刚才想捕捉只野生的{STR_VAR_2}，\n但是它成功逃走了。\p感觉好失败……$"

MatchCall_WildBattleText12::
	.string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还在捕捉宝可梦吗？\p我自己也在试着捕捉。\n但是真的好不容易呀。\p宝可梦的世界真是深奥啊！$"

MatchCall_WildBattleText13::
	.string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l你捕捉到宝可梦了吗？\p我自己也努力试着捕捉，\n但没什么成果。\p宝可梦的世界真是深奥啊！$"

MatchCall_WildBattleText14::
	.string "哦嗨，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\p刚才我试着捕捉一只可爱的\n{STR_VAR_2}。\p但它还是逃走了！\n哦，我真是失望极了！\p再见！$"

MatchCall_WildBattleText15::
	.string "嘿，{PLAYER}！\n我是{STR_VAR_1}！\p我正在考虑捕捉\n一两只宝可梦。\p但一只都找不到。\n这真是个难题啊！\p我完全想不到办法！\n以后再见！$"

MatchCall_NegativeBattleText1::
	.string "嗨！{PLAYER}{KUN}，好啊！\n我是{STR_VAR_1}。\p我试着挑战了另一个训练家，\n但是我输了。\p好失望。\n好了，以后再聊！$"

MatchCall_NegativeBattleText2::
	.string "你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p在我们对战后，\n我又挑战了别人。\p我差点就赢了，但是最后\n还是输了。唉，算了！$"

MatchCall_NegativeBattleText3::
	.string "嘿你好，{PLAYER}！\n是我，{STR_VAR_1}。\p我刚刚在对战中惨败。\p看来我得再训练\n一下我的队伍！$"

MatchCall_NegativeBattleText4::
	.string "嘿，{PLAYER}。\n是我，{STR_VAR_1}。\p我昨天又对战了一场，\n可还是没能赢。\p我的队伍还需要再练练。\nOK，以后再聊。$"

MatchCall_NegativeBattleText5::
	.string "嘿嘿，{PLAYER}！\n我是{STR_VAR_1}。\p最近怎么样？\p我一直在对战，\n但很少能赢。\p完全找不到感觉。\n好了，保重！$"

MatchCall_NegativeBattleText6::
	.string "嘿，{PLAYER}。\n我是{STR_VAR_1}呢。\p最近还好吗？\p我最近拼命对战，\n但没什么成果。\p完全找不到节奏。\n你多保重！$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1}。\n最近还顺利吗？\p我昨天又输了，\n一直在想这件事。\p我得想个对策……\n再见。$"

MatchCall_NegativeBattleText8::
	.string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}呀。\p你的宝可梦怎么样？\n前几天我又输了一场对战。\p我要更努力些！\n再见！$"

MatchCall_NegativeBattleText9::
	.string "喂，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p听着，听着，你一定要\n听听这个！\p我刚才来了场宝可梦对战，\n我在最后一秒的时候被打败了。\p哦哦，气死我了！$"

MatchCall_NegativeBattleText10::
	.string "喂，{PLAYER}{KUN}，你好……\n我是{STR_VAR_1}。\p不久前，我打了一场对战。\n结果我输了。\p我得在继续训练我的宝可梦。\n再见。$"

MatchCall_NegativeBattleText11::
	.string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l你的宝可梦怎么样？\p我又输掉了一场对战。\p哦，再见！$"

MatchCall_NegativeBattleText12::
	.string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还在努力对战吗？\p我的话，最近刚输了一场，\n所以我重新训练我的队伍。\p下次见吧！$"

MatchCall_NegativeBattleText13::
	.string "喂，你好啊，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\p我希望你一切顺利。\p我刚刚结束了一场对战。\p{PLAYER}{KUN}，要像我这样活跃哦！\n再见！$"

MatchCall_NegativeBattleText14::
	.string "喂，你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p最近还好吗？\p不过要记得常回家看看哦。\p再见！$"

MatchCall_PositiveBattleText1::
	.string "嗨！{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}！\p我和其他训练家来了场对战。\n我赢啦！赢啦！\p我的{STR_VAR_2}真的干得很漂亮！\n太棒了！$"

MatchCall_PositiveBattleText2::
	.string "你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\p我昨天对战了一场，\n而且赢了！太棒了！$"

MatchCall_PositiveBattleText3::
	.string "你好，{PLAYER}！\n我是{STR_VAR_1}！\l你战况如何？\p我前些天对战了一场，\n我的{STR_VAR_2}表现超级棒！\p下次再遇到你，\n{PLAYER}，输的就不是我了！$"

MatchCall_PositiveBattleText4::
	.string "嘿，{PLAYER}。\n是我{STR_VAR_1}。\p刚刚我有一场对战。\n我尽全力取胜了，但其实很险。\p我的{STR_VAR_2}可真是\n上演了一出好戏。$"

MatchCall_PositiveBattleText5::
	.string "嘿呀，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p最近怎么样？\n战绩如何？\p我刚刚赢了一场！\n我的{STR_VAR_2}太出色了！\p等着瞧，我一定会打败你的！\n好啦，保重！$"

MatchCall_PositiveBattleText6::
	.string "嘿，{PLAYER}{KUN}。\n是我{STR_VAR_1}。\p一切顺利吗？\p我最近势头正猛！\n我刚刚可就赢了一场对战。\p等我们下次交手时，\n我肯定不会输了！$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}？\n是我{STR_VAR_1}。\p我的{STR_VAR_2}超级厉害的！\n我刚刚又赢了一场！\p我真想现在就和你\n再比试一场。$"

MatchCall_PositiveBattleText8::
	.string "哦，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}呀。\p我希望你一切都好。\n我想告诉你我刚刚赢了。\p我的{STR_VAR_2}为了赢得对战，\n表现得非常努力！\p下次见！$"

MatchCall_PositiveBattleText9::
	.string "哦，{PLAYER}{KUN}，好啊！\n我是{STR_VAR_1}！\p你的宝可梦最近怎样？\n我刚刚赢了一场！\p不得不说我的{STR_VAR_2}\n真的是太出色了！\p我希望你也能看看！\n以后见！$"

MatchCall_PositiveBattleText10::
	.string "哦，{PLAYER}{KUN}，好啊……\n我是{STR_VAR_1}。\p最近过得好吗？\p我的宝可梦现在\n充满了力量。\p我刚刚与它们一同\n获得了胜利。以后见。$"

MatchCall_PositiveBattleText11::
	.string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p最近有在对战吗？\n我今天又战胜了一个！\p势不可挡！哈哈哈哈！\n好了，回见！$"

MatchCall_PositiveBattleText12::
	.string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\p你过得还好吧？\n我依然充满了活力！\p刚刚又赢了一场。\n我可不会轻易输给\l你们年轻人！！$"

MatchCall_PositiveBattleText13::
	.string "啊，好啊，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\p希望你一切安好。\n我依然精力充沛！\p刚才又赢了一场。\n我可不会轻易输给年轻人呢！\p再见！$"

MatchCall_PositiveBattleText14::
	.string "哦，嗨，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我最近在对战时，\n我的{STR_VAR_2}表现超群！\p真希望你能看到呢，\n{PLAYER}{KUN}。再见！$"

MatchCall_SameRouteBattleRequestText1::
	.string "嗨！{PLAYER}，你好！\n这里是{STR_VAR_1}。\p嗯？等一下，你在\n{STR_VAR_2}附近？\p哇哦，那我们得来场对战！\n我等着你！待会见！$"

MatchCall_SameRouteBattleRequestText2::
	.string "你好，{PLAYER}！\n我是{STR_VAR_1}。\p啊？你说正在\n{STR_VAR_2}这里？\p我们来对战一场好吗？\n我等你啊！待会见！$"

MatchCall_SameRouteBattleRequestText3::
	.string "嗨你好，{PLAYER}！\n是我，{STR_VAR_1}。\p哦，嘿，你就在\n{STR_VAR_2}这里？\p我们现在来对战\n一场怎么样？\p我不会再输了！\n我等你！快来吧！$"

MatchCall_SameRouteBattleRequestText4::
	.string "嘿，{PLAYER}{KUN}。\n是我{STR_VAR_1}。\p你在哪里？\n啥？{STR_VAR_2}？\p现在要和我对战吗？\n我等你。待会见！$"

MatchCall_SameRouteBattleRequestText5::
	.string "嘿呀，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\l最近如何？\p你在哪里？\n{STR_VAR_2}？\p那我们现在立刻\n再战一场如何？\p我会留意你的。\n马上见！$"

MatchCall_SameRouteBattleRequestText6::
	.string "嘿，{PLAYER}{KUN}。\n是我{STR_VAR_1}。\l你的宝可梦还好吗？\p哦真的？你就在{STR_VAR_2}这里？\n那我们得再对战一场啊。\p我会等着你。\n待会见！$"

MatchCall_SameRouteBattleRequestText7::
	.string "……呃，{PLAYER}{KUN}？\n是我{STR_VAR_1}……\p哦，你正好在\n{STR_VAR_2}附近？\p那么，来对战吧。\n我是说，现在。\p我会给你看看我的宝可梦。\n我等着你。$"

MatchCall_SameRouteBattleRequestText8::
	.string "哦，{PLAYER}{KUN}，你还好吗？\n我是{STR_VAR_1}呀。\p希望你一切都好。\n哦，你就在{STR_VAR_2}这里啊。\p那么，你想来跟我\n来一场对战吗？\p我等着你。\n等下见！$"

MatchCall_SameRouteBattleRequestText9::
	.string "嗯，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p一切都好吗？\n哦，你就在{STR_VAR_2}附近？\p哦，那你不觉得应该与我\n来一场对战吗？\p别让我久等！$"

MatchCall_SameRouteBattleRequestText10::
	.string "哦，{PLAYER}{KUN}，你好……\n这里是{STR_VAR_1}。\p过得顺利吗？\n哦，你就在{STR_VAR_2}这里。\p那么我们应该来场对战。\p我已经准备好了。\n快点过来！$"

MatchCall_SameRouteBattleRequestText11::
	.string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p啊，你现在正在\n{STR_VAR_2}？\p既然如此，我们之间一定得\n来一场对战，不是吗？\p我在这里等你！\n马上见！$"

MatchCall_SameRouteBattleRequestText12::
	.string "喂，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你现在在哪儿呢？\p{STR_VAR_2}？\n离我很近啊！\p你说我们现在来一场\n对战如何？\p我会等你的。\n等会见！$"

MatchCall_SameRouteBattleRequestText13::
	.string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\p希望你一切顺利。\n哦，你在{STR_VAR_2}附近？\p既然离得不远，\n来和我对战一场吧。\p我等你，\n先这样吧。$"

MatchCall_SameRouteBattleRequestText14::
	.string "哦，嗨，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p你在哪儿？……{STR_VAR_2}？\n那很近啊。\p你不觉得我们应该\n来一场对战吗？\p我会等你的！\n拜拜！$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "嗨！{PLAYER}，你好！\n我是{STR_VAR_1}。\p想和我对战一场吗？\p我就在\n{STR_VAR_2}等你！$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "你好啊，{PLAYER}！\n我是{STR_VAR_1}。\p你想不想再和我比试一场？\p你能在{STR_VAR_2}\n这边找到我。我等着你！$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "你好啊，{PLAYER}！\n是我，{STR_VAR_1}。\p我的宝可梦比起之前\n成长了许多。\p我想看看它们和你的\n宝可梦比起来谁更强，{PLAYER}。\p我们对战吧！\p我就在{STR_VAR_2}这里等你。$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "嘿，{PLAYER}{KUN}。\n是我{STR_VAR_1}。\l你还好吗？\p我的宝可梦最近\n变得很厉害了。\p嘿，你想再和我\n来一场对战吗？\p我们在{STR_VAR_2}见面，\n好吗？$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "嘿，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p我的宝可梦这些天\n成长了不少。\p真的好想和你\n再对战一次。\p我会在{STR_VAR_2}这里等你！\n回头见！$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "嘿，{PLAYER}{KUN}。\n是我{STR_VAR_1}。\l希望你一切顺利。\p我想能和你再来一场对战。\n你觉得呢？\p如果你想就来{STR_VAR_2}这里吧。\p再见！$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "……呃，{PLAYER}{KUN}？\n是我{STR_VAR_1}……\l所以，你的宝可梦成长了吗？\p我的肯定变强了。\n想给你看一看。\p我会在{STR_VAR_2}附近。\n来找我对战吧。\p以后见。$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "哦，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\p希望你一切都好。\n我的宝可梦十分活跃。\p如果你在附近的话，\n和我再对战一次吧。\p我就在{STR_VAR_2}。\n不见不散，再见！$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "哦，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\l你的宝可梦还好吗？\p我的宝可梦越来越强了。\n想让你见识一下，{PLAYER}{KUN}。\p我现在就在{STR_VAR_2}这里，\n如果你在附近的话，\l那么我们就来场对战吧。\p希望很快能见到你！$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "哦，{PLAYER}{KUN}，你好……\n我是{STR_VAR_1}。\l啊，最近还好吗？\p我的宝可梦可是比\n以前要强得多了。\p我很想和你再对战一次，\n{PLAYER}{KUN}。\p现在我在{STR_VAR_2}。\n如果方便的话就来吧。$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l你现在会在哪里呢？\p我的宝可梦现在充满活力。\n它们好像很想再见一见\l你的宝可梦，{PLAYER}{KUN}。\p我现在就在{STR_VAR_2}这里。\n希望你能来找我们。$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "喂，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\p我想告诉你，我的宝可梦已经\n成长了很多很多。\p想看看它们和你对战的表现，\n{PLAYER}{KUN}。\p我们会在{STR_VAR_2}附近。\n随时欢迎来找我们！$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l你的宝可梦都好吗？\p我的宝可梦非常健康，\n看起来不会输给你！\p我很想再和你对战一场。\p如果你在{STR_VAR_2}附近，\n一定要来找我们。$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "哦，好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l一切都好吧。\p哦，对了！我的宝可梦已经\n比以前强大了不少。\p你不觉得我们应该\n再战一场吗，{PLAYER}{KUN}？\p我会在{STR_VAR_2}\n等着你的。\p随时来找我们，好吗？$"

MatchCall_PersonalizedText1::
	.string "是我啊，热爱大山的\n{STR_VAR_1}！\p那个，上次见过以后，你是不是\n也开始喜欢群山了呢？\p我很少在山里看见你呀……\p下一次，让我们在\n{STR_VAR_2}碰头吧。$"

MatchCall_PersonalizedText2::
	.string "我是{STR_VAR_1}。\n你好。\p我刚刚告诉了一个新人训练家\n有关你的事。\p我告诉她有一个强大的训练家\n用爱心培育他的宝可梦。\p我希望你能成为一个\n人人称赞的训练家。\p希望能再见到你！$"

MatchCall_PersonalizedText3::
	.string "你好！我是{STR_VAR_1}。\p我爱上我所在的地方了。\n多么怡人的芳香！\p我想有人种下了些树果，\n它们正在开花。\p再见！$"

MatchCall_PersonalizedText4::
	.string "你好！具有30年经验的探险家，\n{STR_VAR_1}为你服务！\p看上去你正在充满干劲的\n走东闯西呢。\p你发现了什么新的遗迹吗？\n如果有的话要告诉我！\p现在恕我失陪，\n我还要去探索遗迹。$"

MatchCall_PersonalizedText5::
	.string "我是{STR_VAR_1}！\p知道我正在做什么吗？\n我正在海边看海浪！\p啊……海浪闪闪发光。\n这里真是看海的好地方啊。\l我有点饿了，再见了！$"

MatchCall_PersonalizedText6::
	.string "嗯嗯……\n哦，嗨，我是{STR_VAR_1}。\l我喜欢在海滩上吃东西。\p我的宝可梦和我都好得很。\n我们充满活力！\l我要去游个泳了。再见！$"

MatchCall_PersonalizedText7::
	.string "你好，我是{STR_VAR_1}……\p最近对“精英训练家”这个\n头衔有点厌倦了……\p每个人都认为我是完美的训练家，\n因此我不得不按照别人期望而活。\p不过这可能就是精英训练家\n的宿命吧。\p我得继续咬牙坚持……\n微笑着承受一切。\p这些话我只\n对你一个人说。\p但下次见面时别担心，\n我不会抱怨的！$"

MatchCall_PersonalizedText8::
	.string "哟吼，我是{STR_VAR_1}！\n你好吗？\p我现在正在训练我的宝可梦，\n你是我的目标哦。\p下次遇见你的时候\n我不会再输了。\p有个训练家朋友可真好啊！\n再见啦！$"

MatchCall_PersonalizedText9::
	.string "我是{STR_VAR_1}……\n现在，在你的身后……\l不觉得那里有东西吗……？\p那是沉睡在送神山的\n宝可梦之大能……\p它正向我诉说你的一切……\p赶快离开这里，\n而且千万不要回头……\p嘻嘻……\n再见……$"

MatchCall_PersonalizedText10::
	.string "我是{STR_VAR_1}。\n最近好吗？\p能够远距离通话\n真是方便呢！\p之前如果我想和谁聊聊的话，\n只能叫我爸开车载我去……\p差不多该挂啦。\n很高兴和你聊天。$"

MatchCall_PersonalizedText11::
	.string "我是{STR_VAR_1}！\n听我说个事！\p我很喜欢狩猎地带，\n但每次去都会迷路！\p到处是高高的杂草！\n而且地方也太大了！\p说出来舒服多啦！\p我要再次向狩猎地带出发了！\n回见！$"

MatchCall_PersonalizedText12::
	.string "你好，是我{STR_VAR_1}。\n嗯，没错，我还是那么有钱。\p我要告诉你，我的财富在上次\n见面后又增加了不少。\p而且，我的宝可梦\n也变得更强了。\p我不得不开始怀疑\n地球是围着我转的！\p哦，无需多言！\n事实就在眼前！\p哦，抱歉要先失陪了，我得去\n参加一场重要的晚宴了。$"

MatchCall_PersonalizedText13::
	.string "呼呼呼……\n是我，{STR_VAR_1}……\p能猜到我在看什么吗？\n一对{STR_VAR_2}正在打架。\p也许我应把胜利者捕捉了……\n呼呼呼……\p我……要去忙了。\n我走了。$"

MatchCall_PersonalizedText14::
	.string "哦，我是{STR_VAR_1}！\p我已经开始觉得呆在被\n遗弃的海船里有些无聊了。\p但既然我来了，\n而且还想赢你一次，\l那就再多呆一会吧。\p有兴趣的话，\n不妨来找我？\p我想今天终于可以和\n隔壁的大叔来场对战了。\p再见！$"

MatchCall_PersonalizedText15::
	.string "我是{STR_VAR_1}！\n大海的男儿！\p你知道我在想啥吗？\p从大海中来的训练家\n才是强者中的强者呀！\p你应该向我学着\n在大海中修炼……\p哦哦，有巨浪涌起！\p这是多么好的训练机会啊！\n抱歉，我先闪了！$"

MatchCall_PersonalizedText16::
	.string "在下是{STR_VAR_1}！\n听着，我一直在传授空手道\l给我的宝可梦。\p它们现在已经比我厉害了！\n我一直在输给它们！\p但就算输给了宝可梦，\n我也绝不会输给训练家的！\p我们再战一场吧！\n呜哇！$"

MatchCall_PersonalizedText17::
	.string "是我，{STR_VAR_1}。\n旅行还顺利吗？\p……哇，真的？\n听起来超刺激啊！\p我想我都能把你\n的故事写成歌了。\p……哦，灵感来了。\n我的脑海里已经有旋律了。\p我得赶紧把曲子记下来，\n嗯，得走了！下次见！$"

MatchCall_PersonalizedText18::
	.string "我是{STR_VAR_1}……\n听听我的新歌吧。\p啦啦啦，{STR_VAR_2}，{STR_VAR_2}！\n为什么你是{STR_VAR_2}？\l为什么我不能成为你，{STR_VAR_2}？\l啦啦，{STR_VAR_2}和{STR_VAR_1}，\l{STR_VAR_1}和{STR_VAR_2}……\p重复副歌，淡出……$"

MatchCall_PersonalizedText19::
	.string "我是{STR_VAR_1}，你知道的，\n野营专家！\p上次对战输给你很正常。\p毕竟我的专长是露营。\p无论结果如何，\n我都喜欢在露营时对战。\p再来对战吧，怎么样？\n一起去露营也行哦！$"

MatchCall_PersonalizedText20::
	.string "是我呀，我，{STR_VAR_1}！\p说实话，我想去爬其他的山。\p但是我不确定其他山的美女\n会不会像烟囱山里的一样多。\p如果你知道哪座山美女\n多的话，记得告诉我！\p哎嘿嘿，回见啦！$"

MatchCall_PersonalizedText21::
	.string "…… …… ……\n…… …… ……\l我是{STR_VAR_1}……\p…… …… ……\n…… …… ……\l今天就这样……$"

MatchCall_PersonalizedText22::
	.string "我是{STR_VAR_1}。\n今天有预感会和你通话。\p想打败你的心情与日俱增。\p你也有这样的劲敌吧？\n希望那个人是我……\p很高兴你能听我说这些。\n再见！$"

MatchCall_PersonalizedText23::
	.string "我是{STR_VAR_1}。\p附近有强大训练家时，\n我总能感应到。\p刚才是你经过吗，{PLAYER}{KUN}？\n说不定就是你呢。\p期待你的来访。\n再见！$"

MatchCall_PersonalizedText24::
	.string "你好，我是{STR_VAR_1}。\n听起来你还不错，{PLAYER}{KUN}。\p虽然周游了世界，\n但我特别喜欢这个地区。\p我打算多待一阵子。\n也许我们应该再见一见？\p我还记得你精彩的对战技巧。\p我真的希望能再切磋一次。$"

MatchCall_PersonalizedText25::
	.string "呜咽……我是……{STR_VAR_1}……\n……吸……\p今天在课上被杜娟训了。\p但是我并讨厌她。\p杜娟直接指出了我的错误，\n这样我能吃一堑长一智。\p明天我绝对还要去\n训练师学校！\p回头见！$"

MatchCall_PersonalizedText26::
	.string "我是{STR_VAR_1}！\p昨天，杜娟答应和我对战了。\p结果吗……\n不用问也知道很惨。\p但能挑战她我就超开心！\p我现在更崇拜她了！\p我会加倍努力的！\n先走啦！$"

MatchCall_PersonalizedText27::
	.string "嗨，我是美穗！我今天还是和我的\n后辈搭档里子在一起。\p我超喜欢照顾里子\n和宝可梦。它们太可爱了！\p真希望我可以像对待\n弟弟妹妹一样宠它们！\p——哦，里子！\n面包买到了吗？\p什么？没有，才没有把你\n当成私家仆人使唤！\p你输了对战，所以就要罚你\n跑腿帮我买面包！\p我不会把你当作私家仆人的，\n里子对我可是特别的存在！\p现在得走啦，\n点心时间到！$"

MatchCall_PersonalizedText28::
	.string "我喜欢宝可梦！我是来自宝可梦\n发烧友俱乐部的{STR_VAR_1}！\p快听我说！\n我家宝贝宝可梦……\p呼呼！哈哈哈哈！\n不能再多说了！这是秘密！\l简直可爱到词穷！\p哦，我可爱的{STR_VAR_2}\n正撒娇要宝可方块！\p简直是可爱的代名词！\p抱歉现在没空聊了！\n下次一定要听我说啊！$"

MatchCall_PersonalizedText29::
	.string "哦吼吼！\p我是{STR_VAR_1}！迫不及待想\n分享我家可爱宝可梦的趣事！\p拜托了，一定要听我说。\n是关于我亲爱的{STR_VAR_2}。\p只要被人抱起来，\n它就会立刻跳回我怀里！\p哦……哦……\n还有比这更幸福的感觉吗？\p啊，我仿佛身处天堂！\p很高兴能和你\n分享这份快乐！\p现在得走啦，\n拜拜！$"

MatchCall_PersonalizedText30::
	.string "我是……{STR_VAR_1}。\n尽管人们都叫我达人。\p但是我清楚一件事——\n我无法仅凭一己之力成为达人。\p只有与宝可梦同心协力，\n训练家方能成为达人。\p哼！可能我说得有些\n过于深奥了！\p我应该给你留份好心情的！$"

MatchCall_PersonalizedText31::
	.string "我是{STR_VAR_1}。\n很高兴和你聊天！\p泡在温泉里的我\n现在神清气爽。\p自上次我们交手以后，我又和不少\n年轻的训练家对战过，但是你仍是\l他们之中的佼佼者。\p我能想象等你到了我这个岁数\n也会成为一个达人的！呵呵呵……$"

MatchCall_PersonalizedText32::
	.string "耶！我是{STR_VAR_1}！\n猜怎么着？\p不知道是不是错觉，\n每次打赢对战，我的短裤\l材质好像都会变得更高级，\p那是什么意思？\n有点难以形容，\l怎么说呢……？\l好像触感更丝滑了！\p但是和你对战的时候，{PLAYER}{KUN}，\n短裤触感就会变得糙糙的。\p…… …… ……\n你不会当真吧？\l哎嘿嘿，就这样吧！拜拜！$"

MatchCall_PersonalizedText33::
	.string "咳咳！\n是我{STR_VAR_1}！\p和平常一样，\n正疯狂钓鱼中！\p除了大海和河流，\n还有其他地方能捕鱼吗？\p我现在无论看哪里\n都好想甩上一竿！\p哦，糟糕，见鬼！\n我的线缠住了！\p我走了！\n记得帮我找新钓点啊！$"

MatchCall_PersonalizedText34::
	.string "嘿，你好！我是{STR_VAR_1}。\n最近过得悠闲吗？\p从我还是个孩子开始，要知道，\n我都生活得都很平静，是吧？\p我那时从来没有\n遇到过巨大的压力和刺激的事情。\p但是你不知道吧，\n我现在是个铁人三项选手了。\p你无法预见命运会把你带到哪里，\n如果你像我一样漂泊的话。\p你目前是个训练家，但是\n谁知道未来会怎样呢，是吧？\p想想看自己将成为一个导师，\n或是一个艺术家。酷，是吧？\p但是，嘿，冷静点。放轻松。\n再见了。$"

MatchCall_PersonalizedText35::
	.string "我是{STR_VAR_1}！\n我在骑自行车呢。\p我喜欢游泳和跑步，\n但是自行车是我的最爱！\p我感觉整个人好像\n都和风融为一体了。\p好像随风飞行一样，\n感觉太棒了！\p好了！今天，我要创造一个\n自行车公路赛的新纪录！\p你也可以来挑战一下！\n再见！$"

MatchCall_PersonalizedText36::
	.string "哟，我是{STR_VAR_1}！\n正在铁人三项赛中！\p不过，嘿，\n总有时间聊天的！\p和宝可梦一起训练超棒！\p无需言语就能心灵同步。\p多美妙啊！\p呃……边跑边聊……\n上气不接下气了……\l呼……我……必须……挂了……$"

MatchCall_PersonalizedText37::
	.string "嗨，我是{STR_VAR_1}。\n如果你想增强耐力，\l那么就来参加高原训练！\p来山顶上跑步吧。\n你可能马上就喘不上气了！\p我也感到有点缺氧了！\n再见！$"

MatchCall_PersonalizedText38::
	.string "哦，我是{STR_VAR_1}，你好。\p我已经游了很久了，\n可看起来还是到不了彩悠市。\p我不会在兜圈子吧。\p不，那绝对不可能啦。\n哇哈哈哈。\l保重！$"

MatchCall_PersonalizedText39::
	.string "嘿，我是{STR_VAR_1}……\n哎呀！\p扑通！\p咕噜——咕噜——\n咕噜——咕噜……\p哗啦！\p呼——呼！呼——呼！\p嘿！不好意思啊！\n我刚刚在抹防晒油。\p结果我手滑了一下，\n宝可导航一下子掉到水里了！\p不过，得文的宝可导航\n还真是结实啊。\p泡到水里都没事！\p总之，我要晒日光浴了，\n改日再聊吧。$"

MatchCall_PersonalizedText40::
	.string "你好，我是{STR_VAR_1}。\p铁人三项赛里面，\n我最喜欢游泳了。\p但要是泡海里太久，\n皮肤会不会皱成梅干啊？\p哦，铁人三项赛真是对\n人类耐力的严酷考验啊！再见！$"

MatchCall_PersonalizedText41::
	.string "你好，{PLAYER}{KUN}。\n是我{STR_VAR_1}。\p你的宝可梦还好吗？\p我的龙宝可梦看起来\n状态绝佳。先这样吧。$"

MatchCall_PersonalizedText42::
	.string "是我{STR_VAR_1}。\p我的{STR_VAR_2}可是要比上一次\n的时候强多了。\p我绝不会再输给你了。\n等着瞧吧！\p再见了！$"

MatchCall_PersonalizedText43::
	.string "我是{STR_VAR_1}。\p我一直在继续钻研\n精进隐匿之术。\p但似乎太成功了——\n现在根本没人能找到我了。\l成功的代价是孤独啊……\p我如烟般消散吧！\n告辞！$"

MatchCall_PersonalizedText44::
	.string "我是{STR_VAR_1}。\n上次见面以后我一直在修炼。\p我的{STR_VAR_2}变得很厉害了。\p海滩特训果然有效，\n和预料中的一样。再见！$"

MatchCall_PersonalizedText45::
	.string "你好吗？\n我是{STR_VAR_1}。\p我在想这烦人的火山灰\n要下到什么时候？\p如果再这样下去，我遮阳伞\n上的图案都要被盖住了……\p约好下次再见啦！$"

MatchCall_PersonalizedText46::
	.string "嗨，是我{STR_VAR_1}。\p你知道吗？浮在海水里\n比浮在泳池里简单很多呢。\p只要放松躺着，\n你的身体会自己飘起来。\p但如果你漂浮的时间太长，\n要注意别被海流冲得太远啊。\p……呃我现在是到哪了？\n我得挂了！$"

MatchCall_PersonalizedText47::
	.string "喂，{PLAYER}{KUN}，好啊！\n我是{STR_VAR_1}。\l我正在山上呢。\p但这地面一点也不平整。\n我不能在这里搭帐篷……\p哦，灵光一闪！\p也许我能用宝可梦\n来踏平地面！\p这就去试试看！\n再见！$"

MatchCall_PersonalizedText48::
	.string "喂，嗨，嗨，我是{STR_VAR_1}！\p我正在和留美一起培育宝可梦！\n我们超努力的！\p如果我们再努力些，\n会成为第一吗？再见！$"

MatchCall_PersonalizedText49::
	.string "我是{STR_VAR_1}！\p尽管是个水手，\n但是现在并不在船上。\p我很好奇应该如何称呼\n一个在陆地上的水手呢？\p这就是我经常在远航时\n常常在想的问题。\p好了，下次见！$"

MatchCall_PersonalizedText50::
	.string "我是{STR_VAR_1}。\n捕捉新的宝可梦了吗？\p如果捕捉到了，\n你一定要来给我看看。\p保证不缠着你要，说到做到。\n我等着你，会见！$"

MatchCall_PersonalizedText51::
	.string "这里是{STR_VAR_1}。\p你有在用最优方式\n培育宝可梦吗？\p我这里的空气超清新，\n对于培育宝可梦来说\l简直是完美环境。\p要专注培育宝可梦的话，\n强烈推荐来{STR_VAR_2}。多保重啦！$"

MatchCall_PersonalizedText52::
	.string "嗨，我是{STR_VAR_1}。\p我给我的{STR_VAR_2}吃了个宝可方块。\n它看上去非常喜欢。\p原来宝可梦对宝可方块\n也有口味偏好呢。\p真有趣！\n多保重呀！$"

MatchCall_PersonalizedText53::
	.string "我是{STR_VAR_1}。\p只要和宝可梦协作，\n野外生活也能很舒适。\p真希望更多人明白这点，\n多多和宝可梦合作啊。\p我真的这么想！\p我觉得你做得就很好！\n改天见！$"

MatchCall_PersonalizedText54::
	.string "嗨，我是时刻准备的\n训练家{STR_VAR_1}！\p{PLAYER}{KUN}，带够道具了吗？\n宝可梦状态如何？\p随时保持万全准备才是\n保持长久冒险的秘诀！\p我也得去检查行李了，\n时刻留意！$"

MatchCall_PersonalizedText55::
	.string "我是{STR_VAR_1}！\n我是{STR_VAR_1}！\p{STR_VAR_2}是交通要道，\n所以我每天都能挑战\l到各种训练家。\p我今天5胜3败！\p你的战绩呢？\n下次告诉我吧，好吗？$"

MatchCall_PersonalizedText56::
	.string "是我，{STR_VAR_1}。\p我是因为虫系宝可梦多\n才受关注的对吧？\p今天我带了一堆最爱的\n虫宝可梦去学校。\p结果我喜欢的女孩子被吓哭了！\n你想笑就笑吧。\p我得想办法让她明白\n虫系宝可梦的魅力！\p呜呜……\n再见！$"

MatchCall_PersonalizedText57::
	.string "呼！呼！呼！呼！\p嗨！我是{STR_VAR_1}！呼！呼！\p尝试……\n登山的时候聊天……\l是多么困难的训练啊……呼！呼！\p哇！呜……\n山峰真陡峭……\l我们要改日……再谈了……\l呼！呼！哇！$"

MatchCall_PersonalizedText58::
	.string "哦，嗨！\p我依然和夏一起\n寻找财宝！\p也许这里其实什么\n财宝都没有……\p但是对我来说和夏\n一起搜索才重要。\p哦嘿，夏！\n为……为什么那么生气？\p我没有忽略你，宝贝！\n你就是我的唯一！\p……{PLAYER}，我得挂了，再见！$"

MatchCall_PersonalizedText59::
	.string "我是{STR_VAR_1}！\p我又去武斗镇的道馆训练了。\p道馆馆主藤树，\n看上去更强大了。\p看起来巨浪的确能磨炼人……\p说来他还一如既往地帅气。\n女粉丝们可崇拜他了！\l说实话，真让人羡慕啊。\p我很好奇……他的朋友希巴会是个\n和藤树差不多的人吗？\p你知道的，浑身汗味，\n还喜欢叫别人“巨浪”之类的。\p不过这种嫉妒心理\n是不是不太好啊？\p就当我什么都没说吧，\n怎么样？再见啦！$"

MatchCall_PersonalizedText60::
	.string "我很高兴能和你这样的\n年轻训练家交流。\p我想无论你多大年纪都会\n继续享受宝可梦的乐趣。\p如果你能像我们这样拥有\n伴侣不是很好吗？\p当然，{PLAYER}{KUN}，你现在已经\n拥有了宝可梦的信任与陪伴。\p你已经具备建立长久\n关系的基础了！\p哈哈哈！\n永远不要气馁！$"

MatchCall_PersonalizedText61::
	.string "嗨，我是{STR_VAR_1}！\n我们刚刚赢了一场对战！\p尽管不是经常能赢，\n但对手是个很帅气的泳裤小伙子。\p我姐姐气坏了！\p她本来想假装弱小\n来博取关注！\p无论输赢，\n她都要数落我一顿！\p{PLAYER}{KUN}，\n下次你能帮我说说她吗？\p好了，再见！$"

MatchCall_PersonalizedText62::
	.string "我是{STR_VAR_1}，对。\n昨天我出海去了。\p我本希望能发现一个\n新的遗迹。\p但是，海流不知怎么把我\n又带回我出发的地方了。\p我的对战水平也还很弱……\n尽管笑我吧……\l但是我不会放弃。\p终有一天我会\n发现新遗迹的！\p就说这么多了！\n先告辞了！$"

MatchCall_PersonalizedText63::
	.string "喂，那啥！\n是我，{STR_VAR_1}！\l我现在正在108号水路上！\l简而言之还是在老地方！\p今天，有位超级美丽的\n比基尼姐姐从我身旁游过！\p我就大喊一声吓了她一跳！\p结果她狠狠瞪了我一眼！\p以上都发生在108号水路！\n由{STR_VAR_1}为你报道！$"

MatchCall_PersonalizedText64::
	.string "我是{STR_VAR_1}！\p虽然有点忙，\n但觉得应该告诉你，\l我今天又打败了五个训练家。\p如果保持这种势头，\n下次大概就能赢你了。\p我想，你和我，会成为好对手的，\n再见了！$"

MatchCall_BattleFrontierStreakText1::
	.string "嗨！我是{STR_VAR_1}。\n听说消息了！\p他们说你在{STR_VAR_2}\n表现超棒。\p一下子就连赢了{STR_VAR_3}场？\n真了不起！再见！$"

MatchCall_BattleFrontierStreakText2::
	.string "你好，我是{STR_VAR_1}！\n听说你的事了！\p他们说你在{STR_VAR_2}\n一下子取得了{STR_VAR_3}连胜。\p太厉害了！我也要努力！\n再见！$"

MatchCall_BattleFrontierStreakText3::
	.string "喂你好，{PLAYER}！\n是我，{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n势不可挡！\p一个漂亮的{STR_VAR_3}连胜……\n这是个新纪录，对吧？\p我也要努力了！\n以后联系！$"

MatchCall_BattleFrontierStreakText4::
	.string "喂，{PLAYER}{KUN}。\n是我{STR_VAR_1}，最近怎样？\p有传言说你在{STR_VAR_2}\n取得了{STR_VAR_3}连胜。\p我也要加油啊。\n再见！$"

MatchCall_BattleFrontierStreakText5::
	.string "喂，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n取得{STR_VAR_3}连胜？\l真厉害啊！\p我也要多加训练宝可梦了。\n回见！$"

MatchCall_BattleFrontierStreakText6::
	.string "喂，{PLAYER}{KUN}。\n是我{STR_VAR_1}。你好吗？\p对了，我听说你在{STR_VAR_2}\n完成了{STR_VAR_3}场连胜的壮举。\p这激励我要更\n专注于培养队伍了。$"

MatchCall_BattleFrontierStreakText7::
	.string "……呃，{PLAYER}{KUN}？\n是我{STR_VAR_1}……\p哦对了，你之前在\n{STR_VAR_2}，对吧？\p并且还取得了{STR_VAR_3}连胜。\p哎呀，这里有只稀有的宝可梦！\n我要走了！$"

MatchCall_BattleFrontierStreakText8::
	.string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l希望你一切顺利。\p不过你好像的确很顺利。\n我听说你在{STR_VAR_2}\l取得了{STR_VAR_3}连胜。\p真是让人震惊！\n祝你继续保持成功。$"

MatchCall_BattleFrontierStreakText9::
	.string "哦，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}取得了\n{STR_VAR_3}连胜！\p太酷了！\n我也要加油！$"

MatchCall_BattleFrontierStreakText10::
	.string "喂，{PLAYER}{KUN}，你好……\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n取得了{STR_VAR_3}连胜？\p真是了不起的成就。\n我要努力了。$"

MatchCall_BattleFrontierStreakText11::
	.string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p听说你在{STR_VAR_2}所向披靡？\p你取得了，多少，\n{STR_VAR_3}连胜？\p你真厉害啊你。\n不知道我能赢几场？$"

MatchCall_BattleFrontierStreakText12::
	.string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还好吗？\p有些人在谈论你。\n说你在{STR_VAR_2}\l连胜了{STR_VAR_3}场？\p真是精彩的故事。\n回见！$"

MatchCall_BattleFrontierStreakText13::
	.string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l希望你一切都好。\p他们说你在{STR_VAR_2}\n取得了{STR_VAR_3}连胜。\p真佩服你的活力！\n再见了。$"

MatchCall_BattleFrontierStreakText14::
	.string "喂，嗨，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我听说你的事了！\n你是不是刚在{STR_VAR_2}\l取得了{STR_VAR_3}连胜？\p真是鼓舞人心！\n再见！$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "嗨！我是{STR_VAR_1}。\n听说消息了！\p他们说你在{STR_VAR_2}\n表现超棒。\p一下子就连赢了{STR_VAR_3}场？\n真了不起！再见！$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "你好，我是{STR_VAR_1}！\n听说你的事了！\p他们说你在{STR_VAR_2}\n一下子取得了{STR_VAR_3}连胜。\p太厉害了！我也要努力！\n再见！$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "喂你好，{PLAYER}！\n是我，{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n势不可挡！\p一个漂亮的{STR_VAR_3}连胜……\n这是个新纪录，对吧？\p我也要努力了！\n以后联系！$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "喂，{PLAYER}{KUN}。\n是我{STR_VAR_1}，最近怎样？\p有传言说你在{STR_VAR_2}\n取得了{STR_VAR_3}连胜。\p我也要加油啊。\n再见！$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "喂，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n取得{STR_VAR_3}连胜？\l真厉害啊！\p我也要多加训练宝可梦了。\n回见！$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "喂，{PLAYER}{KUN}。\n是我{STR_VAR_1}。你好吗？\p对了，我听说你在{STR_VAR_2}\n完成了{STR_VAR_3}场连胜的壮举。\p这激励我要更\n专注于培养队伍了。$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "……呃，{PLAYER}{KUN}？\n是我{STR_VAR_1}……\p哦对了，你之前在\n{STR_VAR_2}，对吧？\p并且还取得了{STR_VAR_3}连胜。\p哎呀，这里有只稀有的宝可梦！\n我要走了！$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l希望你一切顺利。\p不过你好像的确很顺利。\n我听说你在{STR_VAR_2}\l取得了{STR_VAR_3}连胜。\p真是让人震惊！\n祝你继续保持成功。$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "哦，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}取得了\n{STR_VAR_3}连胜！\p太酷了！\n我也要加油！$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "喂，{PLAYER}{KUN}，你好……\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n取得了{STR_VAR_3}连胜？\p真是了不起的成就。\n我要努力了。$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "啊，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p听说你在{STR_VAR_2}所向披靡？\p你取得了，多少，\n{STR_VAR_3}连胜？\p你真厉害啊你。\n不知道我能赢几场？$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还好吗？\p有些人在谈论你。\n说你在{STR_VAR_2}\l连胜了{STR_VAR_3}场？\p真是精彩的故事。\n回见！$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l希望你一切都好。\p他们说你在{STR_VAR_2}\n取得了{STR_VAR_3}连胜。\p真佩服你的活力！\n再见了。$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "喂，嗨，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我听说你的事了！\n你是不是刚在{STR_VAR_2}\l取得了{STR_VAR_3}连胜？\p真是鼓舞人心！\n再见！$"

MatchCall_BattleDomeText1::
	.string "嗨！{PLAYER}？\n你好，我是{STR_VAR_1}！\l我听说你了！\p你在{STR_VAR_2}达成了\n{STR_VAR_3}连冠？\p太棒了！我也得加把劲！\n再见啦！$"

MatchCall_BattleDomeText2::
	.string "你好，我是{STR_VAR_1}！\n我听说了你的事！\p他们说你在{STR_VAR_2}\n取得了{STR_VAR_3}连冠。\p真厉害！我在想自己\n能不能也成为冠军呢？$"

MatchCall_BattleDomeText3::
	.string "嘿，你好，{PLAYER}！\n是我啊，{STR_VAR_1}。\l最近怎么样？\p我听说你在{STR_VAR_2}\n取得了{STR_VAR_2}连冠！\p再接再厉啊！\n回头见！$"

MatchCall_BattleDomeText4::
	.string "嘿，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p听说你在{STR_VAR_2}\n获得了{STR_VAR_3}连冠？\p看来你很努力啊。\n我也得跟上你的步伐！$"

MatchCall_BattleDomeText5::
	.string "喂，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n取得了{STR_VAR_2}连冠！\p我也要加油啊！\n再见啦！$"

MatchCall_BattleDomeText6::
	.string "嘿，{PLAYER}{KUN}？\n我是{STR_VAR_1}。你还好吗？\p对了，听说你在{STR_VAR_2}\n获得了{STR_VAR_2}连冠。\p我得赶紧训练我的宝可梦，\n不然你要甩开我啦。$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}？\n我是{STR_VAR_1}。\p你在{STR_VAR_2}取得了\n{STR_VAR_3}连冠？\p真不得了啊。对了，\n你有捕捉到稀有的宝可梦吗？\p哦，这样啊。\n好，再见。$"

MatchCall_BattleDomeText8::
	.string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l希望你一切顺利。\p不过你好像的确很顺利。\n我听说你在{STR_VAR_2}\l取得了{STR_VAR_3}连冠。\p我也得像你一样训练我的\n宝可梦。下次见！$"

MatchCall_BattleDomeText9::
	.string "喂，{PLAYER}{KUN}，你好啊！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}\n取得了{STR_VAR_3}连冠！\p太酷了！\n我也要努力了！$"

MatchCall_BattleDomeText10::
	.string "哦，{PLAYER}{KUN}，你好。\n我是{STR_VAR_1}。\p你在{STR_VAR_2}取得了\n{STR_VAR_3}连冠？\p真是了不起啊。\n我也要努力了。$"

MatchCall_BattleDomeText11::
	.string "哦，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p听说你在{STR_VAR_2}所向披靡？\p你现在已经实现\n{STR_VAR_3}连冠了？\p我在想自己能不能……\n也成为冠军？\p……大概不可能吧？\n好吧，再见！$"

MatchCall_BattleDomeText12::
	.string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l最近还好吗？\p你在{STR_VAR_2}取得了\n{STR_VAR_3}连冠？\p真是传奇啊。\n再见！$"

MatchCall_BattleDomeText13::
	.string "喂，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l希望你一切都好。\p据说你在{STR_VAR_2}\n取得了{STR_VAR_3}连冠？\p真是精彩的故事！\n再见！$"

MatchCall_BattleDomeText14::
	.string "喂，你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l我听说你的事了！\p你不是在{STR_VAR_2}\n取得了{STR_VAR_3}连冠吗？\p真了不起啊！\n再见！$"

MatchCall_BattlePikeText1::
	.string "嗨！{PLAYER}？\n你好，我是{STR_VAR_1}！\l我听说了！\p你是不是在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间？\p太惊人了！\n再见！$"

MatchCall_BattlePikeText2::
	.string "你好，我是{STR_VAR_1}！\n听说你的事了！\p他们说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间！\p我也要加油啊！\n再见！$"

MatchCall_BattlePikeText3::
	.string "嘿你好，{PLAYER}！\n是我，{STR_VAR_1}。\l一切还好吗？\p我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间！\p下次争取更好成绩啊！\n以后再见！$"

MatchCall_BattlePikeText4::
	.string "嘿，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n连续横扫了{STR_VAR_3}个房间。\p。我也得好好训练宝可梦\n才能跟上你！$"

MatchCall_BattlePikeText5::
	.string "你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n连续闯过了{STR_VAR_3}个房间。\p我也要多多努力！\n回见！$"

MatchCall_BattlePikeText6::
	.string "喂，{PLAYER}{KUN}？\n我是{STR_VAR_1}。你好吗？\p对了，我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间。\p我也得好好训练宝可梦\n才能跟上你！$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}？\n是我{STR_VAR_1}。\p我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间？\p真是太厉害了。\p哦，那边有只稀有的宝可梦！\n好了，再见！$"

MatchCall_BattlePikeText8::
	.string "喂，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l希望你一切顺利。\l啊，看来你确实顺利啊。\p我听说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间。\p真是让人震惊！\n我也要像你一样训练宝可梦了。\l再见。$"

MatchCall_BattlePikeText9::
	.string "喂，{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间。\p太酷了！\n我也要努力！$"

MatchCall_BattlePikeText10::
	.string "喂，{PLAYER}{KUN}，你好。\n我是{STR_VAR_1}。\p你在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间？\p真是了不起啊。\n我也要加油了。$"

MatchCall_BattlePikeText11::
	.string "喂，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p听说你在{STR_VAR_2}所向披靡？\p你通过了，多少，{STR_VAR_3}个房间？\n真是不得了啊。\p我想知道我也能\n成为冠军吗？\p……不可能吗？\n好吧，再见！$"

MatchCall_BattlePikeText12::
	.string "喂，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l最近好吗？\p你在{STR_VAR_2}连续\n通过了{STR_VAR_3}个房间？\p真是个精彩的故事。\n再见！$"

MatchCall_BattlePikeText13::
	.string "啊，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l希望你一切都好。\p据说你在{STR_VAR_2}\n连续通过了{STR_VAR_3}个房间？\p真佩服你的精力！\n再见。$"

MatchCall_BattlePikeText14::
	.string "喂，嗨，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l听说你的事了！\p你不是在{STR_VAR_2}连续\n通过了{STR_VAR_3}个房间吗？\p真是了不起！\n再见！$"

MatchCall_BattlePyramidText1::
	.string "喂！{PLAYER}？\n你好，我是{STR_VAR_1}！\l我听说了！\p你在{STR_VAR_2}里\n登上了{STR_VAR_3}层对吧？\p真是厉害啊！\n我也该试着挑战一下。$"

MatchCall_BattlePyramidText2::
	.string "你好，我是{STR_VAR_1}！\n听说你的消息了！\p他们说你在{STR_VAR_2}里\n一共登上了{STR_VAR_3}层？\p真不可思议！\n我也要去训练我的宝可梦了！$"

MatchCall_BattlePyramidText3::
	.string "嘿你好，{PLAYER}！\n是我，{STR_VAR_1}。\l最近怎么样？\p我听说你在{STR_VAR_2}里\n登上了{STR_VAR_3}层？\p下次争取做得更好啊！\n再见！$"

MatchCall_BattlePyramidText4::
	.string "嘿，{PLAYER}{KUN}。\n是我{STR_VAR_1}。\p说你在{STR_VAR_2}里\n征服了{STR_VAR_3}层？\p我也得努力训练\n才能跟上你的步伐！$"

MatchCall_BattlePyramidText5::
	.string "喂，{PLAYER}{KUN}！\n我是{STR_VAR_1}。\p听说你在{STR_VAR_2}里\n登上了{STR_VAR_3}层？\p我也得加把劲了！\n再见！$"

MatchCall_BattlePyramidText6::
	.string "喂，{PLAYER}{KUN}？\n是我{STR_VAR_1}。最近好吗？\p对了，听说你在{STR_VAR_2}里\n征服了{STR_VAR_3}层。\p我也要去训练宝可梦，\n否则要被你甩开了。$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}？\n是我{STR_VAR_1}。\p你在{STR_VAR_2}里\n征服了{STR_VAR_3}层？\p厉害啊！那里有稀有的\n宝可梦吗？\p哦，没有吗？\n好的，再见。$"

MatchCall_BattlePyramidText8::
	.string "哦，{PLAYER}{KUN}，你好吗？\n我是{STR_VAR_1}。\l希望你一切顺利。\l噢，看来你确实很顺利啊。\p听说你在{STR_VAR_2}里\n通过了{STR_VAR_3}层？\p真是不得了啊！\n我也要像你一样培育我的宝可梦。\l再见。$"

MatchCall_BattlePyramidText9::
	.string "哦，{PLAYER}{KUN}，你好！\n我是{STR_VAR_1}！\p我听说了！你在{STR_VAR_2}里\n闯过了{STR_VAR_3}层！\p太酷了！\n我也要努力！$"

MatchCall_BattlePyramidText10::
	.string "哦，{PLAYER}{KUN}，你好。\n我是{STR_VAR_1}。\p你在{STR_VAR_2}里\n征服了{STR_VAR_3}层？\p真是了不起。\n我也要加油了。$"

MatchCall_BattlePyramidText11::
	.string "喂，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\p听说你在{STR_VAR_2}所向披靡？\p你登上了，多少，{STR_VAR_3}层？\n这真是了不起啊。\p不知道我能不能\n也成为冠军？\p……基本不可能？\n好，再见！$"

MatchCall_BattlePyramidText12::
	.string "你好，{PLAYER}{KUN}。\n是我，{STR_VAR_1}。\l你还好吗？\p你在{STR_VAR_2}里\n闯过了{STR_VAR_3}层？\p真是个精彩的故事。\n再见！$"

MatchCall_BattlePyramidText13::
	.string "喂，你好，{PLAYER}{KUN}！\n我是{STR_VAR_1}！\l希望你一切都好。\p你在{STR_VAR_2}里\n征服了{STR_VAR_3}层？\p真佩服你的精力！\n再见了。$"

MatchCall_BattlePyramidText14::
	.string "喂，你好，{PLAYER}{KUN}。\n我是{STR_VAR_1}。\l听说你的事了！\p你不是在{STR_VAR_2}里\n征服了{STR_VAR_3}层吗？\p你真是我的偶像！\n再见了！$"

MatchCall_Text_Mom1::
	.string "妈妈：你们父子两个……\n大家都被宝可梦迷住了。\p宝可梦到底有什么魅力呢？\p我吗？\n我喜欢那些能帮忙\l做家务的宝可梦。$"

MatchCall_Text_Mom2::
	.string "妈妈：嗨，{PLAYER}！\n你爸爸整天把自己\l关在橙华市道馆里。\p他偶尔也会回家一趟。\n但是每次他吃光所有东西之后，\l就又立刻回道馆去了。\p我猜输给你这件事\n对他的自尊心是一个很大的打击！$"

MatchCall_Text_Mom3::
	.string "妈妈：{PLAYER}……\n别为我和家里担心。\p穿着这双跑步鞋\n直到它们彻底磨破吧！$"

MatchCall_Text_Roxanne1::
	.string "杜娟：哦，您好，{PLAYER}！\p在上次见面以后\n我一直在努力修炼。\p我还需要一点点时间\n来重新开张道馆。\p当我准备好了之后，请来我的道馆\n再战一场吧！$"

MatchCall_Text_Roxanne2::
	.string "杜娟：是{PLAYER}吗？\n恭喜您啊！\l我听说您的事了！\p我吗，我还再需要一点时间\n开重新开张道馆。\p一切就绪以后，请来我的道馆\n让我们再战一场吧！$"

MatchCall_Text_Roxanne3::
	.string "杜娟：{PLAYER}！\n我的道馆已经准备好了！\p随时欢迎你再来\n卡那兹市！$"

MatchCall_Text_Roxanne4::
	.string "杜娟：我们在卡那兹市道馆进行过的\n那场对战，{PLAYER}，\l是我引以为豪的回忆。$"

MatchCall_Text_Brawly1::
	.string "藤树：嘿，你好，{PLAYER}{KUN}！\p我在我们上次的对战中\n又学到了不少东西。\p我打算重新修行训练，\n然后重新开张道馆。\p不过在那之前\n我还需要点时间准备。\p如果我能重新开张道馆，\n我希望你能和我们比试比试。$"

MatchCall_Text_Brawly2::
	.string "藤树：嘿，{PLAYER}{KUN}！\n恭喜你！\p你的英勇事迹都已经随着\n潮风传到这里了！\p看来我还需要继续\n训练才行啊。\p我想还要些时间准备\n之后才能重开道馆。\p但如果道馆重开了，\n希望你能再来挑战。$"

MatchCall_Text_Brawly3::
	.string "藤树：嘿，{PLAYER}{KUN}！\n我的道馆已经准备好应战了！\p欢迎随时来武斗镇再战！$"

MatchCall_Text_Brawly4::
	.string "藤树：{PLAYER}{KUN}，\n和你对战真是永远都不会腻！$"

MatchCall_Text_Wattson1::
	.string "铁旋：哦，是你啊！\p你走后，\n我重新开始了修炼。\p我还需要那么一丁点时间\n才能重新开张道馆。\p你就等着吧！\n哇哈哈哈哈！$"

MatchCall_Text_Wattson2::
	.string "铁旋：哇哈哈哈哈！\p你真的做到了，对吧？\n我听说过你的事了！\p看上去我还要再多\n训练一下。\p我还需要一点点\n时间来重新开张道馆。\p你就等着吧！\n哇哈哈哈！$"

MatchCall_Text_Wattson3::
	.string "铁旋：哦，是你啊！\n我的道馆已经准备好了！\p来紫堇市吧，随时欢迎！\n哇哈哈哈哈！$"

MatchCall_Text_Wattson4::
	.string "铁旋：哇哈哈哈哈！\p和你的对战总是充满着\n电击般的震撼！$"

MatchCall_Text_Flannery1::
	.string "亚莎：{PLAYER}……\p当我们对战之后，\n我才意识到我自己的不成熟。\p但我不会就此止步！\p我要重新进行训练，\n重新开张道馆。\p到那时候，{PLAYER}，\n请务必再来挑战。$"

MatchCall_Text_Flannery2::
	.string "亚莎：你好，{PLAYER}？\n恭喜你！\p你成功的消息如同火山热浪\n似的传到了我们这里！\p我们的训练进展得\n十分顺利。\p当道馆就绪之后，\n看看你的对战寻呼列表，\l我的名字旁边会有标记。$"

MatchCall_Text_Flannery3::
	.string "亚莎：哦，{PLAYER}？\n我们的道馆已经准备好了！\p来釜炎镇泡泡温泉\n顺便挑战一下道馆吧！$"

MatchCall_Text_Flannery4::
	.string "亚莎：{PLAYER}……\n我相信你每次都能在训练中\l不断变得更强。$"

MatchCall_Text_Winona1::
	.string "娜琪：你好，{PLAYER}！\p多亏了我们的那次对战，\n我认识到了自己的弱点所在！\p当我重新开张道馆之后，\n我不会再输了！$"

MatchCall_Text_Winona2::
	.string "娜琪：你做到了，{PLAYER}！\p关于你成为新冠军的消息\n已经传到了茵郁市！\p不过……下一次你我再战，\n结果一定会有所不同。$"

MatchCall_Text_Winona3::
	.string "娜琪：是{PLAYER}吗？\n我们的道馆重新开张了！\p我们在茵郁市等你！$"

MatchCall_Text_Winona4::
	.string "娜琪：{PLAYER}……\n虽然我输了，\l但我的羽翼永远不会折断。\p对，就像你从未放弃追逐\n你的梦想一样。$"

MatchCall_Text_TateLiza1::
	.string "小枫：哦！你是……\n小南：{PLAYER}！\p小枫：我们在重新训练……\n小南：为了能重开道馆！\p小枫：当我们的道馆就绪之后……\n小南：当我们的道馆就绪之后……\p小枫：我们名字旁会有一个标志……\n小南：就在对战寻呼的列表上！$"

MatchCall_Text_TateLiza2::
	.string "小枫：{PLAYER}，祝贺你！\n小南：{PLAYER}，祝贺你！\p小枫：我们两个……\n小南：仍在训练！\p小枫：不过，再给我们一点时间……\n小南：当我们的道馆就绪之后……\p小枫：我们名字旁会有一个标志……\n小南：就在对战寻呼的列表上！$"

MatchCall_Text_TateLiza3::
	.string "小枫：{PLAYER}！\n小南：{PLAYER}！\p小枫：我们的道馆已经好了！\n小南：我们的道馆已经好了！\p小枫：请随时来……\n小南：绿岭市看看！$"

MatchCall_Text_TateLiza4::
	.string "小枫：{PLAYER}，我们之间的对战……\n小南：真是无比珍贵的经历。\p小枫：真期待能和你……\n小南：再战一场！$"

MatchCall_Text_Juan1::
	.string "亚当：嗯……\n{PLAYER}{KUN}……是你吗？\p我们的对战——\n这让我想起了第一次\l遇到米可利时候的情景。\p或许你真的是一位能够超越\n米可利的天才训练家呢！$"

MatchCall_Text_Juan2::
	.string "亚当：呵呵……{PLAYER}{KUN}……\n你终于达成了目标。\p我的识人眼光\n果然没错……\p如今的你已登顶荣耀之巅，\n我期待与你重逢的时刻。$"

MatchCall_Text_Juan3::
	.string "亚当：呵呵……{PLAYER}{KUN}……\p我们的琉璃市道馆\n终于重新开张了。\p若想见我，\n随时欢迎来访。$"

MatchCall_Text_Juan4::
	.string "亚当：{PLAYER}{KUN}……\p如同最为悦耳的乐章，\n我们的对战拨动了我心中\l的灵感之弦……\p每当我闭上双眼，\n都仿佛能看到你乘着旋律翱翔……$"

MatchCall_Text_Sidney::
	.string "花月：哟，{PLAYER}！\p如果你想跟我再战一场，\n你可以随时来宝可梦联盟找我。\p我会等你的！\n等你来战！$"

MatchCall_Text_Phoebe::
	.string "芙蓉：嗨，{PLAYER}！\p要不要抽空再来这儿看看？\p我想看看你和宝可梦的牵绊\n是否变得更加深厚了。$"

MatchCall_Text_Glacia::
	.string "波妮：您好，{PLAYER}。\p我相信您没有因实力\n强大而懈怠吧？\p如果想稍稍冷却一下激情，\n随时欢迎来宝可梦联盟……$"

MatchCall_Text_Drake::
	.string "源治：这个声音……{PLAYER}，是你吗？\n听起来状态不错……\p听说有个叫对战开拓区的设施，\n专门考验训练家的实力。\p但若追求真正的对战，\n宝可梦联盟才是最佳的选择！\p你说是吧，{PLAYER}？$"

MatchCall_Text_Wallace::
	.string "米可利：哈喽，{PLAYER}{KUN}。\n你见过大吾吗？\p他这个人啊……\n明明实力无比强大。\p但是他不常与人宝可梦对战，\n反而总是在找稀有的石头。\p是个奇特的人呢。\p我敢保证，他肯定正在某个山洞\n或者峭壁附近挖掘呢。\p不过什么石头才称得上珍稀呢？\n我能想到的也只有陨石了……$"

MatchCall_Text_MayRayquazaCall:
	.string "…… …… ……\n…… …… ……嘟嘟！\p小遥：嗨，{PLAYER}{KUN}！\p我刚才在暮水镇附近呢。\p我看见一个巨大的绿色宝可梦\n在高空翱翔。\p我……\n我从没见过这样的东西。\p真好奇它是什么？\n这是不是个重大发现？\p…… …… ……\n…… …… ……咔嚓！$"

MatchCall_Text_BrendanRayquazaCall:
	.string "…… …… ……\n…… …… ……嘟嘟！\p小悠：嗨，{PLAYER}！\n我刚才在暮水镇附近。\p我看见一个巨大的绿色\n宝可梦划过了天际。\p我从没见过这么\n震撼的东西……\p要是你也能看到就好了，\n{PLAYER}。\p…… …… ……\n…… …… ……咔嚓！$"

MatchCall_Text_May1::
	.string "小遥：嗨，{PLAYER}{KUN}！\p哈奇老人从水手的岗位上退休了，\n但是我常常见到他和\l宠物小皮一起出海。\p他果然还热爱着大海呢。$"

MatchCall_Text_May2::
	.string "小遥：嗨，{PLAYER}{KUN}！\p你知道有些小城镇，比如橙华市\n和武斗镇都设有道馆？\p而不知道为什么，\n像凯那市这样的大港口反而没有。\p等那里建好道馆之后，\n我也许去申请当个馆主！$"

MatchCall_Text_May3::
	.string "小遥：嗨，{PLAYER}{KUN}！\p你还记得叫卡那兹市里那个\n叫居合劈大叔的人吗？\l他在那里有幢小房子，有印象吗？\p我发现他的弟弟\n住在紫堇市。\p你猜猜看他的外号？\p…… …… ……\n…… …… ……\p是碎岩大叔啦！$"

MatchCall_Text_May4::
	.string "小遥：{PLAYER}{KUN}？\p卡绿隧道……这个名字取自\n它连接的卡那兹市和绿茵镇。$"

MatchCall_Text_May5::
	.string "小遥：{PLAYER}{KUN}，还好吗？\p我正在111号道路呢。\p我准备在一个老婆婆家里\n休息一下。\p她就住在沙漠的北边。$"

MatchCall_Text_May6::
	.string "小遥：嗨，{PLAYER}{KUN}！\p你知道沙漠里有座\n幻影之塔吗？\p据说它会像海市蜃楼\n一样忽隐忽现。\p好想亲眼看看啊！$"

MatchCall_Text_May7::
	.string "小遥：{PLAYER}{KUN}，呀呼！\n我正在119号道路上呢。\p这里有条大河，\n还经常下雨。\p我都被淋透了！$"

MatchCall_Text_May8::
	.string "小遥：{PLAYER}{KUN}，嗨。\p送神山是用来纪念\n逝去宝可梦的地方。\p或许是因为这个，\n里面有很多幽灵属性的宝可梦呢！$"

MatchCall_Text_May9::
	.string "小遥：嗨，{PLAYER}{KUN}！\p我本来想去釜炎镇\n泡一泡温泉。\p但是在凹凸山道上，\n我碰到一群看着不怀好意的家伙。\l一下子兴致全无！$"

MatchCall_Text_May10::
	.string "小遥：嗨，{PLAYER}{KUN}！\n看到新闻了吗？\p说是楠木馆长在水下勘探中\n发现了海底洞窟呢！$"

MatchCall_Text_May11::
	.string "小遥：嗨，{PLAYER}{KUN}！\n你不觉得这很棒吗？\p就算没有船，\n你也能用宝可梦的招式横渡大海。\p还有更厉害的呢——\p有个宝可梦招式甚至能潜到海底哦！$"

MatchCall_Text_May12::
	.string "小遥：嗨，{PLAYER}{KUN}！\n希望一切顺利！\p你在海上时有没有遇到过\n被挡住去路的情况？\p试试潜到水下深处，\n沿着海沟前进。\p到达另一边后再浮上来。\n很简单吧！$"

MatchCall_Text_May13::
	.string "小遥：嗨，{PLAYER}{KUN}！\p最近怎么样？\n还在完成宝可梦图鉴吗？\p我听说了超古代宝可梦的传闻。\l而且一共有3只呢！\p要是能亲眼见到\n哪怕就1只也好啊……$"

MatchCall_Text_May14::
	.string "小遥：{PLAYER}{KUN}！\n我听说了！\p你击败了琉璃市的\n道馆馆主？\p也就是说，\n你的目标已经近在咫尺了？$"

MatchCall_Text_May15::
	.string "小遥：现在整个丰缘地区没有\n哪个训练家不认识你了，\l{PLAYER}{KUN}！\p当我说和你是朋友时，\n{PLAYER}{KUN}，\l大家都大吃一惊呢！$"

MatchCall_Text_Brendan1::
	.string "小悠：嘿，{PLAYER}！\p哈奇老人从水手的岗位上退休了，\n但是我常常见到他和\l宠物小皮一起出海。\p看来他依然还热爱着大海啊。$"

MatchCall_Text_Brendan2::
	.string "小悠：嘿，{PLAYER}！\p我不明白为什么橙华市和\n武斗镇这样的小镇都有道馆。\p而像凯那市这样的\n大港口却没有道馆。\p等建好道馆之后，\n我应该去申请当个馆主。$"

MatchCall_Text_Brendan3::
	.string "小悠：哟，{PLAYER}！\p还记得那个住在卡那兹市的\n叫居合劈大叔的人吗？\l在那里有幢小房子的那个？\p原来他的弟弟\n就住在紫堇市。\p猜猜他叫什么？\p…… …… ……\n…… …… ……\p叫碎岩大叔！$"

MatchCall_Text_Brendan4::
	.string "小悠：这声音……是{PLAYER}吗？\p卡绿隧道名字的由来是因为\n它连接了卡那兹市和绿茵镇。\p你知道吗？$"

MatchCall_Text_Brendan5::
	.string "小悠：{PLAYER}，最近怎样？\p我正在111号道路呢。\p我打算在一个老婆婆家里\n稍作休息，她家就在沙漠的北边。\p你要是路过，\n也应该来看看她。$"

MatchCall_Text_Brendan6::
	.string "小悠：嘿，{PLAYER}！\p你知道沙漠里的\n幻影之塔吗？\p据说它像海市蜃楼\n一样时隐时现。\p真想亲眼看看！$"

MatchCall_Text_Brendan7::
	.string "小悠：谁啊？哦，{PLAYER}？\n你猜怎么着？\l我正在119号道路呢。\p这里有条大河，\n而且天天下雨。\p我都被彻底淋透了！$"

MatchCall_Text_Brendan8::
	.string "小悠：{PLAYER}！\p送神山是纪念逝去的\n宝可梦的地方。\p说不定正是因为这样，\n里面才有很多幽灵属性宝可梦出没！$"

MatchCall_Text_Brendan9::
	.string "小悠：你好，{PLAYER}。\p我本来想去釜炎镇\n泡温泉的。\p但是在凹凸山道，\n我撞上了一帮不怀好意的家伙。\p这群家伙……\n我想他们是熔岩队。$"

MatchCall_Text_Brendan10::
	.string "小悠：嗨，{PLAYER}！\n看新闻了吗？\p听说楠木馆长在水下勘探中\n发现了海底洞窟。$"

MatchCall_Text_Brendan11::
	.string "小悠：你好，{PLAYER}！\n不觉得这很棒吗？\p即使没有船，\n你也能利用宝可梦招式\l来渡过大海。\p有种宝可梦招式甚至还能\n让你潜入海底呢。\p宝可真是梦无所不能啊！$"

MatchCall_Text_Brendan12::
	.string "小悠：嗨，{PLAYER}！\n最近还好吗？\p在海上有遇到过被挡住\n去路的情况吗？\p试试看潜到水下深处，\n沿着海底的沟壑前进。\p到达另一边后，\n再浮上水面。简单吧！$"

MatchCall_Text_Brendan13::
	.string "小悠：你好啊，{PLAYER}！\p最近怎么样？\n还在完成宝可梦图鉴吗？\p我听说有关于超古代、n宝可梦的传闻。\l而且不止1只——是3只！\p我好想捕获哪怕1只……$"

MatchCall_Text_Brendan14::
	.string "小悠：{PLAYER}！\n我听说了！\p你打倒了琉璃市道馆的\n馆主？真厉害！\p只有一步之遥了！$"

MatchCall_Text_Brendan15::
	.string "小悠：现在整个丰缘地区没有训练家\n不认识你了，{PLAYER}！\p我和大家说你是我的朋友时，\n{PLAYER}，他们都羡慕坏了！$"

MatchCall_Text_Wally1::
	.string "满充：哦，{PLAYER}！\p我变得更健康了，\n体能也在变好。\p我希望能早日成为你这样的\n训练家，{PLAYER}！$"

MatchCall_Text_Wally2::
	.string "满充：{PLAYER}，你好！\p自从卡绿隧道打通之后，\n满盈姐开心多了！$"

MatchCall_Text_Wally3::
	.string "满充：哦，{PLAYER}！\p我没告诉任何人就离开了\n绿茵镇的叔叔家。\p不知道他会不会\n很生气呢……\p{PLAYER}，\n你能理解我的心情吧？$"

MatchCall_Text_Wally4::
	.string "满充：{PLAYER}？\n是我呀，满充！\p训练家的世界太棒了！\p当我带着宝可梦旅行时，\n会有各种人向我打招呼！\p好像大家都被宝可梦\n联系在一起了！$"

MatchCall_Text_Wally5::
	.string "满充：{PLAYER}？太不可思议了！还记得我们\n一起捕捉的拉鲁拉丝吗？\l它进化了，{PLAYER}！\p我或许有些天赋……\p啊，\n我不该得意忘形！\p毕竟被称赞的应该是\n宝可梦才对！$"

MatchCall_Text_Wally6::
	.string "…… …… ……\n…… …… ……\p满充似乎不在宝可导航的\n服务区内……$"

MatchCall_Text_Wally7::
	.string "满充：哦，{PLAYER}！\p在遇见你之前，\n我几乎从不出门……\p但现在，我正在和自己的\n宝可梦一起冒险呢……\p{PLAYER}……\n谢谢你……$"

MatchCall_Text_Scott1::
	.string "亚希达：嗨，{PLAYER}{KUN}！\p你知道宝可梦\n无处不在吗？\p在山里，海里，\n在草丛里？\p像宝可梦一样，\n训练家也是满地都是。\p我也只好到处奔波了。\n忙得很啊！$"

MatchCall_Text_Scott2::
	.string "亚希达：我正在119号道路上呢。\n这里到处都是训练家！\p这里也到处都是草丛，\n长得特别茂密。\p穿短裤在这里走，\n草挠得腿好痒啊！$"

MatchCall_Text_Scott3::
	.string "亚希达：嗨，嗨，{PLAYER}{KUN}！\p你有没有登上过\n送神山？\p那是为了纪念逝去的\n宝可梦的地方。\p每个训练家\n都至少应该登上去一次。$"

MatchCall_Text_Scott4::
	.string "亚希达：嗨，{PLAYER}{KUN}！\p我听说最近有叫熔岩队和海洋队\n的团伙在为非作歹？\p虽然说不定里面有高手……\p但既然是恶徒……$"

MatchCall_Text_Scott5::
	.string "亚希达：哦，嗨，{PLAYER}{KUN}。\p在海底可能会有\n强大的训练家吗？\p我不能亲自一探究竟。\n首先我不会游泳。\l再说我也不培育宝可梦啊……$"

MatchCall_Text_Scott6::
	.string "亚希达：嗨，嗨，{PLAYER}{KUN}！\p你知道吧？\n当你收集到了所有的道馆徽章，\l就能够挑战宝可梦联盟啦！\p以你的实力要成为冠军\n绝非痴人说梦。\p但是你要知道，\n还有更进一步的东西……\p不过就先说这些吧，\n你可以好好期待一下。\p当你打赢宝可梦联盟，\n登入名人堂之后！$"

MatchCall_Text_Scott7::
	.string "…… …… ……\n…… …… ……\p亚希达似乎\n不在宝可导航的服务区内……$"

MatchCall_Text_Norman1::
	.string "爸爸：在卡那兹市，有一个被称作\n“居合劈大叔”的人。\p如果你在那一带，\n应该去拜访一下。$"

MatchCall_Text_Norman2::
	.string "爸爸：嗯……尽管不知不觉，\n但毫无疑问你成长得越来\l越强大了，{PLAYER}。\p而越长大，你也就会飞得离我\n和你妈妈越远……\p这种心情真是难以言表。$"

MatchCall_Text_Norman3::
	.string "爸爸：知道了……\n你已经收集了4个道馆徽章……\p看起来是时候兑现之前\n我们的对战约定了。\p随时来吧！\n我们都会一直等你！$"

MatchCall_Text_Norman4::
	.string "爸爸：{PLAYER}！\n常回去看看妈妈。\p我会留在这里\n再继续加倍训练。\p战斗之道，深邃而无情！$"

MatchCall_Text_Norman5::
	.string "爸爸：哦，{PLAYER}！\p什么？熔岩标志？\n我不清楚那是什么。\p但是从名字来看，\n可能和火山有关！$"

MatchCall_Text_Norman6::
	.string "爸爸：嘿呀！喝哈！呜哇！\p……哦？{PLAYER}！\p你打给我的时候\n我正在和宝可梦特训！$"

MatchCall_Text_Norman7::
	.string "爸爸：{PLAYER}！\p想不到你真的成为了\n宝可梦联盟冠军……\p好！\n我也不会认输！$"

MatchCall_Text_Norman8::
	.string "爸爸：嗯？{PLAYER}？\n来得正好！\p这次，\n换我来挑战你。\p我在橙华市道馆等你。\n随时奉陪！$"

MatchCall_Text_Norman9::
	.string "爸爸：……真令我惊叹，{PLAYER}。\n你究竟能飞多高呢？$"

MatchCall_Text_Steven1::
	.string "大吾：嗨，{PLAYER}{KUN}！\p你去过紫堇市了吗？\p记得去自行车商店\n弄一辆音速自行车。\p然后去彻底探索一下\n石之洞窟吧。\p你在那里\n会有新发现的。$"

MatchCall_Text_Steven2::
	.string "大吾：嗨，{PLAYER}{KUN}！\p至今为止我遇到过\n各种各样的训练家。\p但你是独一无二的。$"

MatchCall_Text_Steven3::
	.string "大吾：嗨，{PLAYER}{KUN}！\p和宝可梦一起冒险时，\n你在想些什么呢？\p会把它们看作\n强大的伙伴吗？\p还是会看作\n有趣的旅伴呢？\p你不同的想法，\n会让旅途变得截然不同。$"

MatchCall_Text_Steven4::
	.string "大吾：喂？\n{PLAYER}{KUN}？\p我在宇宙中心里\n遇到点麻烦。\p抱歉现在不方便说话，\n再见！$"

MatchCall_Text_Steven5::
	.string "大吾：啊！\n{PLAYER}{KUN}！\p事已至此，\n无需多言了。\p相信自己，\n做正确的事吧。$"

MatchCall_Text_Steven6::
	.string "…… …… ……\p大吾似乎没有\n接电话……$"

MatchCall_Text_Steven7::
	.string "大吾：{PLAYER}{KUN}……\n恭喜你登入名人堂。\p…… …… ……\n…… …… ……\p希望我们后会有期！$"

MatchCall_Text_BirchRegisterCall:
	.string "小田卷博士：哦，{PLAYER}{KUN}！\n我已经听说了！\p你的宝可导航已经升级了\n对战寻呼功能对吧？\p我也来登记一下！\p这样你在外面时我也可以检查\n你的宝可梦图鉴进度了！\p…… …… ……$"

MatchCall_Text_RegisteredBirch:
	.string "将小田卷博士的信息\n登录进宝可导航。$"

MatchCall_Text_UnusedProfBirch:
	.string "小田卷博士：同时拥有宝可梦图鉴\n和宝可导航的话，研究宝可梦会\l更有趣吧？$"

MatchCall_Text_MrStone1::
	.string "兹伏奇：哦？{PLAYER}{KUN}！\p既然你给我打电话，那说明\n宝可导航正常工作！\p其他人的信息也可以登录，\n试着联系他们吧！\p好！好！\n你看上去很开心嘛！\p嗯……\n我是怎么知道的？\p因为我正从办公室的窗户里\n往外看着你呢！\p哇哈哈哈！\n回头见！$"

MatchCall_Text_MrStone2::
	.string "兹伏奇：哦？{PLAYER}{KUN}！\p怎么了？\n难道忘记我拜托你的事了吗？\p我想请你帮我送信给\n武斗镇的大吾那里。\p之后再把那个包裹送给\n凯那市的楠木馆长。\p还记得吧？\p身为忙碌的社长，\n我得先挂了！再见！$"

MatchCall_Text_MrStone3::
	.string "兹伏奇：哦！{PLAYER}{KUN}！\p你已经见过大吾了吧！\n我得给你报酬才行！\p等你下次再来卡那兹市时，\n记得来我的办公室找我。\p我等着你！$"

MatchCall_Text_MrStone4::
	.string "兹伏奇：哦！{PLAYER}{KUN}！\p你知道得文正在挖掘\n卡绿隧道的事吗？\p但为了保护那里的宝可梦，\n我们停止了工程。\p这是理所当然的。\p比起人类的便利，\n宝可梦能安稳地生活更为重要。$"

MatchCall_Text_MrStone5::
	.string "兹伏奇：你好，{PLAYER}{KUN}！\p我听从橙华市来的人说\n你是千里的孩子！\p果然是\n虎父无犬子！$"

MatchCall_Text_MrStone6::
	.string "兹伏奇：什么？\p你和自己的父亲对战\n并获得了胜利？\p太了不起了！\p我从没想到能交到像你这样\n特别的朋友！哇哈哈！$"

MatchCall_Text_MrStone7::
	.string "您好！\n这里是得文公司……\l哦，你好，{PLAYER}！\p我们社长刚刚还在这里，\n但是现在外出了。\p我们社长是很忙的，不过你好像\n也一样忙啊，{PLAYER}。$"

MatchCall_Text_MrStone8::
	.string "……啊？……什么？\p固拉……什么？……多？\p断断续续的……\n……听不清……\p沙沙沙……$"

MatchCall_Text_MrStone9::
	.string "……啊？……怎么了？\p海底……是吗？……洞窟……？\p怎么断断续续的……\n……听不见……\p嘶嘶嘶嘶……$"

MatchCall_Text_MrStone10::
	.string "兹伏奇：{PLAYER}{KUN}！是我！\p听说你经历了许多事，\n但我太忙了，\l很多详情都不清楚！\p无论如何，\n我希望你坚持自己相信的道路。\p我会永远支持你！\n保重！$"

MatchCall_Text_MrStone11::
	.string "兹伏奇：…… …… ……\n是{PLAYER}{KUN}吗？\p你的声音充满了自信，\n我一时都没听出来！\p嗯！有空一定要再来\n得文做客啊！$"
