MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "这个招式只能教你1次，\n这样可以吗？$"

MoveTutor_Text_SwaggerTeach:
	.string "嗨！看我的宝可梦多完美！\n它比所有其它宝可梦都酷！\p我总是像这样虚张声势，\n结果被会长训了一顿。\p现在我没法虚张声势了。\p如果你愿意，我会教你的1只宝可梦\n学习虚张声势。$"

MoveTutor_Text_SwaggerDeclined:
	.string "什么？不行？\n你就不能配合一下？$"

MoveTutor_Text_SwaggerWhichMon:
	.string "很好，想让哪只宝可梦\n学习虚张声势？$"

MoveTutor_Text_SwaggerTaught:
	.string "我今后不会再虚张声势地\n培育我的宝可梦了。$"

MoveTutor_Text_RolloutTeach:
	.string "你知道怎样从这儿朝着一个\n方向不变地走出去很远吗？\p我说不定可以滚动着\n走完这段路呢。\p你觉得你的宝可梦也\n很想滚动，对吗？\p如果你想学滚动\n我可以教你。$"

MoveTutor_Text_RolloutDeclined:
	.string "你不要害羞嘛。\n让我们滚起来！$"

MoveTutor_Text_RolloutWhichMon:
	.string "哦呵呵，当然！你的宝可梦\n变得像我一样就好了。$"

MoveTutor_Text_RolloutTaught:
	.string "在草里打滚使我\n非常快乐。来吧，让我们滚起来！$"

MoveTutor_Text_FuryCutterTeach:
	.string "这是一个你连续使用\n就会变得更强大的招式。\p这是一个虫属性的招式，\n并且是很酷的招式。\p这个招式叫做连斩。\n想让我教你的宝可梦吗？$"

MoveTutor_Text_FuryCutterDeclined:
	.string "我们合不来。$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "耶！\n把要学习的宝可梦交给我。$"

MoveTutor_Text_FuryCutterTaught:
	.string "当我连续击中对手时\n就会觉得很兴奋！$"

MoveTutor_MimicTeach:
	.string "啊，孩子！\p我也是个小孩子，\n但我在这个模仿这个镇子里的\l大人们的言谈举止。\p你说什么，小朋友？\n如果我能教你模仿\l你就能承认我？$"

MoveTutor_MimicDeclined:
	.string "嘘！我要让你的宝可梦\n学会模仿！$"

MoveTutor_Text_MimicWhichMon:
	.string "噗噗！我当然能！\n让我看看你想要\l学会招式的宝可梦。$"

MoveTutor_Text_MimicTaught:
	.string "模仿是个伟大而深奥的招式。\p你能像我一样\n运用自如吗……？$"

MoveTutor_Text_MetronomeTeach:
	.string "我什么东西都想要！\n但是我把钱都花光了……\p如果要是有个能够让你\n一挥指就会出现钱的\l魔法岂不美哉？\p如果你想，我能让你的宝可梦\n学会挥指。\p钱不会出现，但你的宝可梦\n将会摇动手指。好吗？$"

MoveTutor_Text_MetronomeDeclined:
	.string "好的。等你改变主意了\n再来找我。$"

MoveTutor_Text_MetronomeWhichMon:
	.string "好的！我来教你！\n想让哪只宝可梦学习？$"

MoveTutor_Text_MetronomeTaught:
	.string "当宝可梦使用\n挥指时，各种各样的好事情\l都会发生。\p我们使用它不是也很棒吗？$"

MoveTutor_Text_SleepTalkTeach:
	.string "嗯！我老伴依靠觉醒力量\n来保持清醒。\p她明明可以像我一样打个盹，\n然后说梦话的。\p我能让你的宝可梦学会梦话。\n有兴趣吗？$"

MoveTutor_Text_SleepTalkDeclined:
	.string "哦，好吧……\n你也想用觉醒力量来保持清醒……$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "啊，多有眼光的孩子呀！\n你想让我教哪只宝可梦？$"

MoveTutor_Text_SleepTalkTaught:
	.string "我从来都猜不对我老伴的\n硬币把戏。\p要是我能在梦话里说中了\n感觉也挺不错的。$"

MoveTutor_Text_SubstituteTeach:
	.string "当我在屋顶上看着\n这广阔的世界时……\p我在想如果这个世界如果\n有不止一个自己该多有趣啊，\l那样我就能体验各种各样的人生了。\p当然这是不可能的。\n嘿嘿……\p明白了！\n不如让你的宝可梦学习替身吧？$"

MoveTutor_Text_SubstituteDeclined:
	.string "噢，不？\p宝可梦可是能用这个招式\n再复制出一个自己的。$"

MoveTutor_Text_SubstituteWhichMon:
	.string "嘿嘿……\n你想让哪只宝可梦\l学会替身？$"

MoveTutor_Text_SubstituteTaught:
	.string "我们人类更应该尽情\n享受我们自己的人生！\p我希望你能够如此！$"

MoveTutor_Text_DynamicPunchTeach:
	.string "我没办法继续！\p这一点用也没有！\p我是一名格斗属性训练家，\n所以无论我怎么努力尝试\l也不能在绿岭市道馆获胜！\p啊啊啊啊！打！打！打！\n打！打！打！\p什么，别那样看我！\n我只是在打地面！\p还是说你想让我教你的\n宝可梦学习爆裂拳？$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "可恶！你也来取笑我吗？\n打！打！打！$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "什么？你想学？你真是个好人啊！\n想要我教哪只宝可梦？$"

MoveTutor_Text_DynamicPunchTaught:
	.string "我希望你能用爆裂拳\n在绿岭市道馆获胜！$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "唉……\p琉璃市道馆馆主可真是\n太让人敬爱不已了。\p但这也意味着会有很多同样被\n他吸引的人做我的竞争对手。\p他的魅力就像舍身冲撞\n一样有利有弊。\l他根本都注意不到我。\p那么，让我教你的宝可梦\n学习舍身冲撞！$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "噢……\n连你都拒绝我……$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "好的，你希望哪只宝可梦\n能学会舍身冲撞？$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "我不再为爱而活着！\n我要更加坚强！$"

MoveTutor_Text_ExplosionTeach:
	.string "我可没打算一直呆在\n这乡下一事无成。\p等着瞧吧，总有一天我会闯进大城市\n成为大明星。\p说真的，我绝对会引发\n一场流行大爆炸！\p既然你听到了，我就破例教你的\n宝可梦学会大爆炸吧！$"

MoveTutor_Text_ExplosionDeclined:
	.string "怎么？你拒绝我是因为\n我住在乡下？$"

MoveTutor_Text_ExplosionWhichMon:
	.string "好的！这就是大爆炸！\n哪只宝可梦要学？$"

MoveTutor_Text_ExplosionTaught:
	.string "长时间以来，我一直在教宝可梦\n如何使用大爆炸，但是我自己\l还没能引发大爆炸……\p也许内心深处，\n我更想留在这儿……$"
