MoveRelearner_Text_WouldLearnNewMoves:
	.string "大家都叫我\n宝可梦招式爱好者！\p宝可梦成长过程中能学会的\n所有招式我都一清二楚。\p要把招式教给你的宝可梦吗？$"

MoveRelearner_Text_LevelUpMoves:
	.string "升级招式$"

MoveRelearner_Text_EggMoves:
	.string "蛋招式$"

MoveRelearner_Text_TMMoves:
	.string "学习器招式$"

MoveRelearner_Text_TutormoveMoves:
	.string "教授招式$"

MoveRelearner_Text_SeeYa:
	.string "再见！$"

MoveRelearner_Text_AnythingElse:
	.string "还有其他要做的事吗？$"

MoveRelearner_Text_ChoosePkmn:
	.string "要选择哪只宝可梦？$"

MoveRelearner_Text_HaveNoPkmn:
	.string "你没有同行的宝可梦！$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "嗯……\p蛋应该没法学习招式吧？$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "抱歉……\p我看来没有能够教给\n这只宝可梦的招式。$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "升级招式$"

MoveRelearner_Text_EggMoveLWR::
	.string "蛋招式$"

MoveRelearner_Text_TMMoveLWR::
	.string "学习器招式$"

MoveRelearner_Text_TutorMoveLWR::
	.string "教授招式$"

MoveRelearner_Text_MoveLWR::
	.string "move$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "要学习哪个{STR_VAR_3}？$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "想让宝可梦学习招式时再过来吧。$"
