gOtherText_NewName::
	.string "新名字$"

gNameChoice_Green::
	.string "GREEN$"

gNameChoice_Red::
	.string "RED$"

gNameChoice_Leaf::
	.string "LEAF$"

gNameChoice_Fire::
	.string "FIRE$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "KAZ$"

gNameChoice_Toru::
	.string "TORU$"

gNameChoice_Ash::
	.string "ASH$"

gNameChoice_Kene::
	.string "KENE$"

gNameChoice_Geki::
	.string "GEKI$"

gNameChoice_Jak::
	.string "JAK$"

gNameChoice_Janne::
	.string "JANNE$"

gNameChoice_Jonn::
	.string "JONN$"

gNameChoice_Kamon::
	.string "KAMON$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "TAYLOR$"

gNameChoice_Oscar::
	.string "OSCAR$"

gNameChoice_Hiro::
	.string "HIRO$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "KAY$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "ROAK$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "JODI$"

gNameChoice_Amanda::
	.string "AMANDA$"

gNameChoice_Hillary::
	.string "HILLARY$"

gNameChoice_Makey::
	.string "MAKEY$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PAULA$"

gNameChoice_June::
	.string "JUNE$"

gNameChoice_Cassie::
	.string "CASSIE$"

gNameChoice_Rey::
	.string "REY$"

gNameChoice_Seda::
	.string "SEDA$"

gNameChoice_Kiko::
	.string "KIKO$"

gNameChoice_Mina::
	.string "MINA$"

gNameChoice_Norie::
	.string "NORIE$"

gNameChoice_Sai::
	.string "SAI$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUZI$"

gControlsGuide_Text_Intro::
	.string "接下来将按照重要顺序\n"
	.string "说明各个按键的功能。$"

gControlsGuide_Text_DPad::
	.string "移动主角。\n"
	.string "也可用于选择\n"
	.string "各种数据项目。$"

gControlsGuide_Text_AButton::
	.string "用于确认选择、查看事物、\n"
	.string "交谈以及滚动文字。$"

gControlsGuide_Text_BButton::
	.string "用于退出、取消选择\n"
	.string "以及取消某种模式。$"

gControlsGuide_Text_StartButton::
	.string "按下此键可打开\n"
	.string "菜单。$"

gControlsGuide_Text_SelectButton::
	.string "用于整理物品以及\n"
	.string "使用注册的物品。$"

gControlsGuide_Text_LRButtons::
	.string "如果需要游戏帮助\n"
	.string "或操作指引，\n"
	.string "请按L键或R键。$"

gOakSpeech_Text_AskPlayerGender::
	.string "告诉我，你是男孩？\n"
	.string "还是女孩？$"

gPikachuIntro_Text_Page1::
	.string "在你即将踏入的这个世界里，\n"
	.string "你将以主角身份踏上\n"
	.string "一段宏大的冒险之旅。\n"
	.string "\n"
	.string "无论走到何处，城镇、道路、\n"
	.string "还是洞窟，都要多与人交流、\n"
	.string "多检查周围的事物。\n"
	.string "从各处收集信息与提示。$"

gPikachuIntro_Text_Page2::
	.string "帮助有困难的人、克服重重挑战、\n"
	.string "解开重重谜题，\n"
	.string "新的道路将随之展开。\n"
	.string "\n"
	.string "有时你会遭到他人挑战，\n"
	.string "或受到野生生物的攻击。\n"
	.string "勇敢面对，勇往直前。$"

gPikachuIntro_Text_Page3::
	.string "在冒险途中，\n"
	.string "希望你能与各种各样的人相遇，\n"
	.string "从中得到成长。\n"
	.string "这是我们最大的心愿。\n"
	.string "\n"
	.string "按下A键，让你的\n"
	.string "冒险开始吧！$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "你好！\n"
	.string "很高兴认识你！\p"
	.string "欢迎来到宝可梦的世界！\p"
	.string "我叫大木博士。\p"
	.string "大家都亲切地称呼我为\n"
	.string "宝可梦博士。\p$"

gOakSpeech_Text_ThisWorld::
	.string "这个世界……$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "……四处栖居着\n"
	.string "被称为宝可梦的生物。\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "对某些人来说，宝可梦是宠物。\n"
	.string "也有人用它们来对战。\p"
	.string "至于我……\p"
	.string "研究宝可梦是我的职业。\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "不过首先，请告诉我\n"
	.string "一些关于你自己的事。\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "先从你的名字说起。\n"
	.string "你叫什么名字？\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "好的……\n"
	.string "原来你叫{PLAYER}。$"

gOakSpeech_Text_WhatWasHisName::
	.string "这是我的孙子。\p"
	.string "从你们出生起，\n"
	.string "他就一直是你的对手。\p"
	.string "……唔，他叫什么名字来着？$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "你的对手，他叫什么来着？$"

gOakSpeech_Text_ConfirmRivalName::
	.string "……唔，是{RIVAL}吗？$"

gOakSpeech_Text_RememberRivalsName::
	.string "对了！我想起来了！\n"
	.string "他叫{RIVAL}！\p$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER}！\p"
	.string "你专属的宝可梦传说\n"
	.string "即将展开！\p"
	.string "梦想与冒险的宝可梦世界\n"
	.string "在等着你！出发吧！$"
