gText_WouldYouLikeToRestYourPkmn::
	.string "辛苦了！\n这里是宝可梦中心。\p在这里可以\n回复宝可梦的体力。\p要让您的宝可梦休息一下吗？$"

gText_IllTakeYourPkmn::
	.string "那么，就交给我吧！$"

gText_RestoredPkmnToFullHealth::
	.string "久等了！\p交给我的宝可梦们\n全都变得精力充沛了哦！$"

gText_WeHopeToSeeYouAgain::
	.string "欢迎下次再来！$"

gText_WelcomeCutShort::
	.string "辛苦了！\n这里是宝可梦中心。\p在这里，\n可以回复宝可梦的体力。\p要让您的宝可梦……$"

gText_NoticesGoldCard::
	.string "那、那张卡！？\p那个颜色！！\n那星星的数量！！\p至今为止我也见过几位\n拥有白银卡的训练家。\p但是拥有比这更厉害的\n训练家卡的客人，\l您还是第一位！\p先让您的宝可梦休息一下吧！$"

gText_YouWantTheUsual::
	.string "辛苦了！\n要像往常一样吗？$"

gText_IllTakeYourPkmn2::
	.string "那就交给我吧！$"

gText_ThankYouForWaiting::
	.string "让您久等了！$"

gText_WeHopeToSeeYouAgain2::
	.string "欢迎您随时再来！$"
