gBirchDexRatingText_AreYouCurious::
	.string "小田卷博士：啊，{PLAYER}{KUN}！\p你想知道你的宝可梦图鉴\n是什么水平吗？$"

gBirchDexRatingText_Cancel::
	.string "嗯，你收集的宝可梦还不够多，\n没什么太大的价值啊。$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "唔唔……\p见过了{STR_VAR_1}只宝可梦，\n捕捉了{STR_VAR_2}只宝可梦……$"

gBirchDexRatingText_LessThan10::
	.string "多去草丛里转转，\n仔细寻找宝可梦吧。$"

gBirchDexRatingText_LessThan20::
	.string "看来你已经掌握诀窍了，\n但是从现在开始，收集将越来越困难。$"

gBirchDexRatingText_LessThan30::
	.string "有些宝可梦只在\n特定的地域出现，\l你必须坚持去寻找。$"

gBirchDexRatingText_LessThan40::
	.string "啊，现在看上去比较\n像一个宝可梦图鉴了，\l但还有很大的发展空间。$"

gBirchDexRatingText_LessThan50::
	.string "看起来挺好的，\n继续加油吧。$"

gBirchDexRatingText_LessThan60::
	.string "你用过钓竿吗？\n海里有很多宝可梦的。$"

gBirchDexRatingText_LessThan70::
	.string "除了捕捉宝可梦，\n让它们进化也是个不错的主意。$"

gBirchDexRatingText_LessThan80::
	.string "看着它，我就想说，\n真是不错的宝可梦图鉴！$"

gBirchDexRatingText_LessThan90::
	.string "已经收集这么多了……\n你一定有这方面的天赋！$"

gBirchDexRatingText_LessThan100::
	.string "你去过狩猎地带了吗？\p听说有些宝可梦\n只有在那里才能捕捉到。$"

gBirchDexRatingText_LessThan110::
	.string "已经超过100种了，\n很棒的宝可梦图鉴！$"

gBirchDexRatingText_LessThan120::
	.string "使用碎岩也有可能\n找到宝可梦哦。$"

gBirchDexRatingText_LessThan130::
	.string "你可以和其他人交换\n来得到更多的宝可梦。$"

gBirchDexRatingText_LessThan140::
	.string "听说有些宝可梦如果非常\n喜欢自己的训练家，\l它们就会进化。$"

gBirchDexRatingText_LessThan150::
	.string "没想到丰缘地区\n会有这么宝可梦种类。$"

gBirchDexRatingText_LessThan160::
	.string "有的时候宝可梦们会\n成群结队地出现，\l不要错过这样的机会。$"

gBirchDexRatingText_LessThan170::
	.string "看了你的宝可梦图鉴，\n基本就可以了解丰缘地区的\l宝可梦的情况了。$"

gBirchDexRatingText_LessThan180::
	.string "要我说，你已经可以\n被称作宝可梦专家了，\l而且是个优秀的专家！$"

gBirchDexRatingText_LessThan190::
	.string "有了这么完整的宝可梦图鉴，\n你可以成为一个真正的专家了！$"

gBirchDexRatingText_LessThan200::
	.string "我有很强烈的预感，\n你的宝可梦图鉴很快就能完成了！$"

gBirchDexRatingText_DexCompleted::
	.string "恭喜你！\n你做成了完美的宝可梦图鉴！$"

gBirchDexRatingText_OnANationwideBasis::
	.string "唔唔……\n从全国来看……\p见过了{STR_VAR_1}只宝可梦，\n捕捉了{STR_VAR_2}只宝可梦……$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "大木：很高兴见到你！\n"
	.string "你的宝可梦图鉴收集得怎么样了？\p"
	.string "来，让我看看。$"

PokedexRating_Text_SeenXOwnedY::
	.string "你在宝可梦图鉴上的\n"
	.string "进展情况如下：\p"
	.string "见过{STR_VAR_1}只宝可梦，\n"
	.string "捕捉了{STR_VAR_2}只宝可梦。\p"
	.string "{FONT_NORMAL}大木博士的评价：$"

PokedexRating_Text_LessThan10::
	.string "你还有很多事情要做。\p"
	.string "去每一片草丛里找找，\n"
	.string "多寻找宝可梦吧！$"

PokedexRating_Text_LessThan20::
	.string "看来你已经走上正轨了！\p"
	.string "我已经把一个闪光技能机\n"
	.string "交给了我的助手。\n"
	.string "记得去领取！$"

PokedexRating_Text_LessThan30::
	.string "你的宝可梦图鉴\n"
	.string "还需要充实一些！\p"
	.string "试着捕捉其他种类的\n"
	.string "宝可梦吧！$"

PokedexRating_Text_LessThan40::
	.string "很好，你显然在努力！\p"
	.string "我已经把一个探物器\n"
	.string "交给了我的助手。\n"
	.string "记得去领取！$"

PokedexRating_Text_LessThan50::
	.string "你的宝可梦图鉴\n"
	.string "收集得相当不错！\p"
	.string "我已经把一个幸运蛋\n"
	.string "交给了我的助手。\n"
	.string "记得去领取！$"

PokedexRating_Text_LessThan60::
	.string "啊，你终于突破50种了！\p"
	.string "我已经把一个学习装置\n"
	.string "交给了我的助手。\n"
	.string "记得去领取！$"

PokedexRating_Text_LessThan70::
	.string "哦哦！这已经是相当\n"
	.string "出色的宝可梦图鉴了！$"

PokedexRating_Text_LessThan80::
	.string "非常好！\p"
	.string "我想你可以通过钓鱼\n"
	.string "收集更多宝可梦！$"

PokedexRating_Text_LessThan90::
	.string "太棒了！我猜……你\n"
	.string "喜欢收集东西，对吧？$"

PokedexRating_Text_LessThan100::
	.string "令人印象深刻！\n"
	.string "这一定很困难吧！$"

PokedexRating_Text_LessThan110::
	.string "你终于突破100种了！\n"
	.string "你真是太厉害了！$"

PokedexRating_Text_LessThan120::
	.string "你甚至拥有宝可梦的\n"
	.string "进化后的形态！太棒了！$"

PokedexRating_Text_LessThan130::
	.string "出色！和朋友交换\n"
	.string "来获得更多吧！$"

PokedexRating_Text_LessThan140::
	.string "非凡！\n"
	.string "你已经成为这方面的真正高手了！$"

PokedexRating_Text_LessThan150::
	.string "我已经无话可说了！\n"
	.string "你现在就是宝可梦博士！$"

PokedexRating_Text_Complete::
	.string "你的宝可梦图鉴完全完成了！\n"
	.string "恭喜！！$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "你的全国宝可梦图鉴：\p"
	.string "见过{STR_VAR_1}只宝可梦，\n"
	.string "捕捉了{STR_VAR_2}只宝可梦。$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "我期待看到你\n"
	.string "完成全国宝可梦图鉴！$"

PokedexRating_Text_YouveCompletedDex::
	.string "终于……\p"
	.string "你终于完成了\n"
	.string "宝可梦图鉴！\p"
	.string "太壮观了！\n"
	.string "真的，这是一项了不起的成就！$"

PokedexRating_Text_Wroooaaarrr::
	.string "哦啊啊啊啊啊！$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "谢谢你，{PLAYER}！\n"
	.string "真心地，谢谢你！\l"
	.string "你让我的梦想成为了现实！$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "大木：啊，欢迎！\p"
	.string "告诉我，你的宝可梦图鉴\n"
	.string "收集得怎么样了？\p"
	.string "哇哈哈！\p"
	.string "其实我已经知道了，但我\n"
	.string "还是很喜欢看！\p"
	.string "让我看看……$"
