	.align 2
gText_ConfirmSave::
	.string "要保存目前为止的\n"
	.string "冒险记录吗？$"

gText_AlreadySavedFile::
	.string "需要覆盖写入上次的\n"
	.string "保存记录，可以吗？$"

gText_SavingDontTurnOff::
	.string "正在写入记录……\n"
	.string "请勿切断电源。$"

gText_PlayerSavedGame::
	.string "{PLAYER}\n"
	.string "完好地写下了记录！$"

gText_DifferentSaveFile::
	.string "注意！！\p"
	.string "在“从记录继续”的选项里\n"
	.string "已经有了一个先前保存的\l"
	.string "冒险进度了！\p"
	.string "这样做的话，先前的冒险进度\n"
	.string "及所有已得到的宝可梦和道具\l"
	.string "全部都会消失……\p"
	.string "确定要将原来的记录\n"
	.string "从头覆盖掉吗？$"

gText_SaveError::
	.string "无法写入记录！\p"
	.string "请更换卡带的存档用\n"
	.string "记忆电池或电子基板！$"

gText_SavingDontTurnOffPower::
	.string "正在写入记录……\n"
	.string "请勿切断电源。$"
