SecretBase_Text_Trainer0Intro:
	.string "你已经做了秘密基地了吗？\p"
	.string "在选定这个地方之前，\n我已经走了不知多少地方。\p"
	.string "既然你来了，\n我们对战怎么样？$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "好！\n来吧！$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "哎？\n啊，现在不行啊……$"

SecretBase_Text_Trainer0Defeated::
	.string "哇啊啊！你真强！\n我输掉的事……请帮我保密！$"

SecretBase_Text_Trainer0PostBattle:
	.string "我的秘密基地怎么样？\n明天也来玩吧。$"

SecretBase_Text_Trainer0PreChampion:
	.string "你已经做了秘密基地了吗？\p"
	.string "在选定这个地方之前，\n我已经走了不知多少地方。\p"
	.string "随便转转吧！$"

SecretBase_Text_Trainer5Intro:
	.string "很多地方都可以\n制造秘密基地，\p"
	.string "但这个是我最喜欢的地方。\n你也认为这地方不错吧？\p"
	.string "哦，要来一次对战吗？$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "好了，来吧！$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "啊……\n现在不行吗，也罢。$"

SecretBase_Text_Trainer5Defeated::
	.string "唔……我们输了……\n别告诉别人啊！\l这是一级机密！$"

SecretBase_Text_Trainer5PostBattle:
	.string "下次来这附近的话，\n再来我这里转转吧。$"

SecretBase_Text_Trainer5PreChampion:
	.string "很多地方都可以\n制造秘密基地，\p"
	.string "但这个是我最喜欢的地方。\n你也认为这地方不错吧？$"

SecretBase_Text_Trainer1Intro:
	.string "这个地方非常受欢迎，\n经常会有人来这里。\p"
	.string "啊！你也想要\n这个地方吗？\p"
	.string "那好，如果你能打败我，\n这地方就归你了。$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "好的！\n我要保护我的秘密基地！$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "呃？是吗？\n你对这里不感兴趣？$"

SecretBase_Text_Trainer1Defeated::
	.string "我不行了！\n我放弃！$"

SecretBase_Text_Trainer1PostBattle:
	.string "好，等我有一天我搬走之后，\n这个地方就是你的了！$"

SecretBase_Text_Trainer1PreChampion:
	.string "这个地方非常受欢迎，\n经常会有人来这里。\p"
	.string "我一直在等它打开，\n我一定要得到它！$"

SecretBase_Text_Trainer6Intro:
	.string "欢迎来到我的精灵研究所，\n"
	.string "我在调查秘密的对战。\p"
	.string "想试试我有多么强吗？$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "我会全力以赴的！$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "啊，\n那么下次吧！$"

SecretBase_Text_Trainer6Defeated::
	.string "嗯……我还有很多不足，\n还得继续学习啊。$"

SecretBase_Text_Trainer6PostBattle:
	.string "谢谢你和我对战，\n明天也来玩吧。$"

SecretBase_Text_Trainer6PreChampion:
	.string "欢迎来到我的宝可梦研究所，\n"
	.string "我在暗中进行对战研究。$"

SecretBase_Text_Trainer2Intro:
	.string "拥有一座宅邸当然好，\n但我更喜欢这样的地方，\p"
	.string "因为各种各样的人\n都会来我这里做客。\p"
	.string "那么，来场对战怎么样？$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "就是这样！$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "准备好的话就叫我吧！$"

SecretBase_Text_Trainer2Defeated::
	.string "啊噢！挂了！\n但我还是喜欢对战！$"

SecretBase_Text_Trainer2PostBattle:
	.string "哎，不管怎么说，我还得\n去买些家具和装饰物品。\p"
	.string "希望我的秘密基地能成为\n大家都喜欢的地方。$"

SecretBase_Text_Trainer2PreChampion:
	.string "拥有一座宅邸当然好，\n但我更喜欢这样的地方，\p"
	.string "因为各种各样的人\n都会来我这里做客。$"

SecretBase_Text_Trainer7Intro:
	.string "我非常喜欢逛商店\n买家具和装饰物品，\p"
	.string "也同样喜欢\n培育宝可梦。\p"
	.string "如果你愿意的话，\n跟我的宝可梦对战怎么样？$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "谢谢，\n开始吧？$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "啊，\n真遗憾……$"

SecretBase_Text_Trainer7Defeated::
	.string "我认输……$"

SecretBase_Text_Trainer7PostBattle:
	.string "真高兴！\n现在我该去买东西了！$"

SecretBase_Text_Trainer7PreChampion:
	.string "我非常喜欢逛商店\n买家具和装饰物品，\p"
	.string "也同样喜欢\n培育宝可梦。$"

SecretBase_Text_Trainer3Intro:
	.string "有些人把秘密基地\n建在别人很难找到的地方，\l"
	.string "是因为想低调行事吗？\p"
	.string "不过你找到了我这里，\n来对战如何？$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "我不会被你轻易打败的！$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "哦……是因为你找来\n这个地方很累吗？$"

SecretBase_Text_Trainer3Defeated::
	.string "我失败了……$"

SecretBase_Text_Trainer3PostBattle:
	.string "我失败了……"
	.string "你的秘密基地在哪儿？\n我也会去拜访你的。$"

SecretBase_Text_Trainer3PreChampion:
	.string "有些人把秘密基地\n建在别人很难找到的地方，\l"
	.string "是因为想低调行事吗？$"

SecretBase_Text_Trainer8Intro:
	.string "人们说有很多得到\n装饰物品的方式，\p"
	.string "我们来比赛谁能得到\n更好的家具和装饰吧！\p"
	.string "不过同时，想对战吗？$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "这里是我的秘密基地，\n我是不会输的！$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "我随时愿意跟你对战。$"

SecretBase_Text_Trainer8Defeated::
	.string "哎？\n我刚刚输掉了？$"

SecretBase_Text_Trainer8PostBattle:
	.string "收集装饰物品我是不会输给你的，\n下次再来玩！$"

SecretBase_Text_Trainer8PreChampion:
	.string "人们说有很多得到\n装饰物品的方式，\p"
	.string "我们来比赛谁能得到\n更好的家具和装饰吧！$"

SecretBase_Text_Trainer4Intro:
	.string "我寻找一个中意的地点，\n然后用喜欢的装饰物品来装点它。\p"
	.string "我培育自己喜欢的宝可梦，\n并与它一同成长。\p"
	.string "这是我的生活。\n要和我对战吗？$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "让我看看你的本事吧！$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "我想有时候你\n也没有兴趣。$"

SecretBase_Text_Trainer4Defeated::
	.string "我已经领教了你的本领了。$"

SecretBase_Text_Trainer4PostBattle:
	.string "我们都可以变得更强，\n一起加油吧！$"

SecretBase_Text_Trainer4PreChampion:
	.string "我寻找一个中意的地点，\n然后用喜欢的装饰物品来装点它。\p"
	.string "我培育自己喜欢的宝可梦，\n并与它一同成长。\p"
	.string "每一天都是最好的一天。$"

SecretBase_Text_Trainer9Intro:
	.string "通过观察人们拥有的装饰物品的\n种类和摆放它们的方法，\l"
	.string "就可以了解到很多关于\l"
	.string "这个人的个性和品位的事情。\p"
	.string "你看出我的品味如何了吗？\n无话可说了吗？\p"
	.string "要不要再看看我的对战品味？$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "不能退缩！$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "我很乐意随时向你\n展示我的风格。$"

SecretBase_Text_Trainer9Defeated::
	.string "你拥有至高的天份！\n你的力量是无限大的……$"

SecretBase_Text_Trainer9PostBattle:
	.string "觉得我的风格怎么样？\n我一直在不断完善！$"

SecretBase_Text_Trainer9PreChampion:
	.string "通过观察人们拥有的装饰物品的\n种类和摆放它们的方法，\l"
	.string "就可以了解到很多关于\l"
	.string "这个人的个性和品位的事情。\p"
	.string "你看出我的品味如何了吗？\n无话可说了吗？$"
