Route102_Text_CalvinIntro:
	.string "如果你随身带着宝可梦，\n那么你就是个正式的宝可梦训练家！\l你不能拒绝我的挑战！$"

Route102_Text_CalvinDefeated:
	.string "呃啊，我败了……\n我还缺乏锻炼啊……$"

Route102_Text_CalvinPostBattle:
	.string "听着，如果你很强，\n那你应该事先告诉我！$"

Route102_Text_CalvinRegister:
	.string "自从上次遇见你，\n我就很努力的锻炼。\p我想再和你战一场，\n所以让我在宝可导航里登记吧？$"

Route102_Text_CalvinRegisterShort:
	.string "我想和你日后再战，\n你能在宝可导航里登记我吗？$"

Route102_Text_CalvinRematchIntro:
	.string "自从上次输给你，\n我拼命地特训我的宝可梦。\l不准拒绝我的挑战！$"

Route102_Text_CalvinRematchDefeated:
	.string "呃啊，我败了……\n难道是我的训练不对吗？$"

Route102_Text_CalvinRematchPostBattle:
	.string "如果你要变强，\n那我也会变强的。$"

Route102_Text_AllenIntro:
	.string "你刚刚成为训练家吗？\n我们都是新手啊！$"

Route102_Text_AllenDefeated:
	.string "我喊你过来，\n是因为我想要打败你……$"

Route102_Text_AllenPostBattle:
	.string "我还一次都没有赢过……\n真希望我能早点赢……$"

Route102_Text_RickIntro:
	.string "哈哈！四目相对！\n我要用虫宝可梦打败你！$"

Route102_Text_RickDefeated:
	.string "嗷！倒下了！$"

Route102_Text_RickPostBattle:
	.string "如果你和一个训练家对视，\n那你必须挑战他！这是规矩！$"

Route102_Text_TianaIntro:
	.string "我要保持连胜，\n我的目标是最强训练家。\p让我的生涯再多一个战果吧！$"

Route102_Text_TianaDefeated:
	.string "我成了你生涯的战果……$"

Route102_Text_TianaPostBattle:
	.string "要想保持连胜，\n我发现得捕捉更多的宝可梦。$"

Route103_Text_DaisyIntro:
	.string "你感觉到我们抚慰心灵\n的芬芳了吗？$"

Route103_Text_DaisyDefeated:
	.string "你并没有迷失在芳香中……$"

Route103_Text_DaisyPostBattle:
	.string "芳香治疗是一种用香气\n来治疗的精神疗法。$"

Route103_Text_AmyIntro:
	.string "久美：我是久美。\n这是我的妹妹留美。\l我们并肩战斗！$"

Route103_Text_AmyDefeated:
	.string "久美：啊，我们输了。$"

Route103_Text_AmyPostBattle:
	.string "久美：在同时面对两个训练家\n的时候，你必须考虑到\l所有可能发生的情况。$"

Route103_Text_AmyNotEnoughPokemon:
	.string "久美：啊——哦，\n你身上只带了1只宝可梦。\l你没法和我们对战。$"

Route103_Text_LivIntro:
	.string "留美：我们是作为\n一个小队战斗的。$"

Route103_Text_LivDefeated:
	.string "留美：哦，姐姐，我们输了……$"

Route103_Text_LivPostBattle:
	.string "留美：我和我的姐姐，\n配合天衣无缝……\p但怎么还是输了……$"

Route103_Text_AmyLivRegister:
	.string "留美：真的，我们能做得更好……\n真的！下一次你就会看到的！$"

Route103_Text_LivNotEnoughPokemon:
	.string "留美：如果你想和我们对战，\n那你必须有2只宝可梦！\l否则就不公平！$"

Route103_Text_AmyRematchIntro:
	.string "久美：我是久美。\n这是我的妹妹留美。\l我们并肩作战！$"

Route103_Text_AmyRematchDefeated:
	.string "久美：啊，呜！\n我们还是赢不了……$"

Route103_Text_AmyRematchPostBattle:
	.string "久美：在同时面对两个训练家\n的时候，你必须考虑到\l所有可能发生的情况。$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "久美：啊哦，\n你身上只带了1只宝可梦。\l你没法和我们对战。$"

Route103_Text_LivRematchIntro:
	.string "留美：我们是作为一个小队\n战斗的。$"

Route103_Text_LivRematchDefeated:
	.string "留美：啊哟喂，我们又输了……\n姐姐……$"

Route103_Text_LivRematchPostBattle:
	.string "留美：我和我的姐姐，\n配合天衣无缝……\p但是我们怎么又输了？$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "留美：如果你想和我们对战\n那你必须有2只宝可梦！\l否则就不公平！$"

Route103_Text_AndrewIntro:
	.string "嘎！我的钓鱼线乱成一团！\n我什么都没钓到，知道后果吗！\l没错！来对战吧！$"

Route103_Text_AndrewDefeated:
	.string "嘎！输了！\n我更生气了啊！$"

Route103_Text_AndrewPostBattle:
	.string "嘎，我还是好生气……\n呼呼……$"

Route103_Text_MiguelIntro:
	.string "我的宝可梦是多么可爱啊！\n别害羞——我给你看看！$"

Route103_Text_MiguelDefeated:
	.string "哦，天哪！\n我心爱的宝可梦！$"

Route103_Text_MiguelPostBattle:
	.string "我的宝可梦啊，\n就连昏厥的样子都那么可爱！$"

Route103_Text_MiguelRegister:
	.string "一定要多来看看我的\n那些百看不厌的宝贝宝可梦呀！$"

Route103_Text_MiguelRematchIntro:
	.string "嗨，你！我那亲爱的宝贝\n宝可梦变得越来越可爱了！$"

Route103_Text_MiguelRematchDefeated:
	.string "哦！\n我心爱的宝可梦！$"

Route103_Text_MiguelRematchPostBattle:
	.string "和它相处的时间越久，\n我的宝可梦就变得越来越可爱。$"

Route103_Text_PeteIntro:
	.string "这点距离……\n游过去就行啦！$"

Route103_Text_PeteDefeated:
	.string "哦，好极了！$"

Route103_Text_PetePostBattle:
	.string "哦，\n原来如此啊。\p如果我也有那么可靠的宝可梦，\n我也想骑着它冲浪啊！$"

Route103_Text_IsabelleIntro:
	.string "小心前面！\n我们要相撞了！$"

Route103_Text_IsabelleDefeated:
	.string "呜啊……$"

Route103_Text_IsabellePostBattle:
	.string "我不太会游泳，所以我在练习……\n很抱歉差点撞上你。$"

Route103_Text_RhettIntro:
	.string "哇！\n你怎么挤进这么点地方的？$"

Route103_Text_RhettDefeated:
	.string "哇！\n这孩子真厉害！$"

Route103_Text_RhettPostBattle:
	.string "你喜欢呆在这么\n狭窄的地方吗？$"

Route103_Text_MarcosIntro:
	.string "你是被我狂野的吉他声吸引来的？$"

Route103_Text_MarcosDefeated:
	.string "我的个人演出完蛋了……$"

Route103_Text_MarcosPostBattle:
	.string "我开始演奏的时候，\n附近几乎没有人，但是我的\l粉丝很快聚集起来了。\p嘿，也许我应该当个专业吉他手。$"

Route104_Text_GinaIntro:
	.string "奈绪：好吧，和我们的\n宝可梦来场对战吧！$"

Route104_Text_GinaDefeat:
	.string "奈绪：失败让我很难过！$"

Route104_Text_GinaPostBattle:
	.string "奈绪：你很强！\n我们还要好好修行啊！$"

Route104_Text_GinaNotEnoughMons:
	.string "奈绪：哦？就1只宝可梦？\n那么，我们不和你打了。\p如果就只有1只宝可梦，\n会孤零零的，那不太好。$"

Route104_Text_MiaIntro:
	.string "美绪：我们是双胞胎，和\n我们的宝可梦对战吧。$"

Route104_Text_MiaDefeat:
	.string "美绪：我们并肩作战，\n还是输了……$"

Route104_Text_MiaPostBattle:
	.string "美绪：我们会好好训练宝可梦的，\n变得和你一样强。$"

Route104_Text_MiaNotEnoughMons:
	.string "美绪：你想与我们对战？\p如果没有2只宝可梦的话，\n那可不行。\l那对你来说我们太强了！$"

Route104_Text_IvanIntro:
	.string "为什么要保密？\n我就是水属性宝可梦专家！\p啊？\n你不认识我？$"

Route104_Text_IvanDefeat:
	.string "要说的话，我原以为我还不错，\n但是看来算不上……唉……$"

Route104_Text_IvanPostBattle:
	.string "我太醉心钓鱼了。\n我都忘了要培育宝可梦……$"

Route104_Text_BillyIntro:
	.string "在沙上踩脚印\n真有意思！$"

Route104_Text_BillyDefeat:
	.string "啊！我的鞋里进沙了！\n沙子好硬啊！$"

Route104_Text_BillyPostBattle:
	.string "我想在沙上到处留上我的脚印，\n但是它们很快就消失了。$"

Route104_Text_HaleyIntro:
	.string "我对战……\n还是不对战？\p好吧，当然，我会对战！$"

Route104_Text_HaleyDefeat:
	.string "我就不该对战的……$"

Route104_Text_HaleyPostBattle:
	.string "如果你面对决择的时候，\n让别人替你做决定。\l你会对事情的\l结果后悔的。$"

Route104_Text_HaleyRegister1:
	.string "你很强，但是我是不是应该把你登记到\n我的宝可导航里？\l也许我不应该……\p好吧，当然，我会登记你的！$"

Route104_Text_HaleyRegister2:
	.string "你很强，但是我是不是应该把你登记到\n我的宝可导航里？\l也许我不应该……\p好吧，当然，我会登记你的！$"

Route104_Text_HaleyRematchIntro:
	.string "来吧，和我对战！$"

Route104_Text_HaleyRematchDefeat:
	.string "啊……\n我以为我会赢……$"

Route104_Text_HaleyPostRematch:
	.string "我已下决心对战，\n所以我可以坦然接受失败。\p但失败仍然让我很难过！$"

Route104_Text_WinstonIntro:
	.string "哦，是的，我会接受你的挑战。\n我有的是钱。$"

Route104_Text_WinstonDefeat:
	.string "为什么我赢不了？$"

Route104_Text_WinstonPostBattle:
	.string "金钱不是万能的，\n也有钱买不到的东西。\l那就是宝可梦……$"

Route104_Text_WinstonRegister1:
	.string "呜？\n啊，你拿着的是宝可导航。\p我很愿意登记你。\n毕竟，我有的是钱。$"

Route104_Text_WinstonRegister2:
	.string "呜？\n啊，你拿着的是宝可导航。\p我很愿意登记你。\n毕竟，我有的是钱。$"

Route104_Text_WinstonRematchIntro:
	.string "在我输给你之后，\n我学到很多关于宝可梦的事。$"

Route104_Text_WinstonRematchDefeat:
	.string "我又输了？\n为什么我总是赢不了？$"

Route104_Text_WinstonPostRematch:
	.string "我很富有，但是我就是\n赢不了宝可梦对战……\p宝可梦的世界，太深奥了……$"

Route104_Text_CindyIntro:
	.string "我们的相遇一定是命运的安排。\n可以请你和我对战吗？$"

Route104_Text_CindyDefeat:
	.string "哦，天哪！$"

Route104_Text_CindyPostBattle:
	.string "“你好”是“再见”的开端。\n希望我们可以再见。$"

Route104_Text_CindyRegister1:
	.string "你好，又见面了。\p我们好像很有缘。让我们互相在\n宝可导航里登记吧。$"

Route104_Text_CindyRegister2:
	.string "我们应该纪念\n一下我们的缘分。\p让我们互相在宝可导航里登记吧。$"

Route104_Text_CindyRematchIntro:
	.string "你好，我们又见面了。\n可以请你再和我对战吗？$"

Route104_Text_CindyRematchDefeat:
	.string "哦，天……\n我已经尽全力了……$"

Route104_Text_CindyPostRematch:
	.string "“你好”是“再见”的开端。\n希望我们可以再见。$"

Route104_Text_DarianIntro:
	.string "我钓到了一个看起来很强的宝可梦！\p它身上有种神奇的魔力！\n它的确看上去很强，\l绝对错不了！$"

Route104_Text_DarianDefeat:
	.string "什么……$"

Route104_Text_DarianPostBattle:
	.string "嘿！鲤鱼王，\n你真是辜负了你的名字，不是吗？$"

Route105_Text_FosterIntro:
	.string "那里应该有一个神秘的\n石头在这周围。\l你知不知道？$"

Route105_Text_FosterDefeated:
	.string "关于那个石头我想太多了，\n并且我的宝可梦也不够强……$"

Route105_Text_FosterPostBattle:
	.string "我可以不厌其烦的盯着\n这个石头几个小时。$"

Route105_Text_LuisIntro:
	.string "唉呀！我看到你还担心\n有孩子会溺水呢。\p看起来你没事，\n所以要不要来场对战？$"

Route105_Text_LuisDefeated:
	.string "咕嘟……咕嘟……$"

Route105_Text_LuisPostBattle:
	.string "如果你要溺水了，\n对着海滩挥动手臂就是信号。$"

Route105_Text_DominikIntro:
	.string "在深蓝色的海里畅游……\n感觉真的很棒！$"

Route105_Text_DominikDefeated:
	.string "我输了……\n现在我很忧郁……$"

Route105_Text_DominikPostBattle:
	.string "为什么大海是蓝色的？\p我在凯那市的博物馆学过，\n不过我忘了。$"

Route105_Text_BeverlyIntro:
	.string "我的身体在水中感到变轻盈了。\n就好像我体重变轻了！$"

Route105_Text_BeverlyDefeated:
	.string "我在漂……$"

Route105_Text_PostBattle:
	.string "你的体重在水里\n就只有平时的10分之1。\p那么我的体重是……\n哎哟！我不会告诉你的！$"

Route105_Text_ImaniIntro:
	.string "蓝蓝的天空……\n辽阔的的大海……\l好宁静……$"

Route105_Text_ImaniDefeated:
	.string "我还在走神时就输掉了！$"

Route105_Text_ImaniPostBattle:
	.string "我希望别人认为和\n我相处很放松。咯咯。$"

Route105_Text_AndresIntro:
	.string "我相信大海中一定还有\n秘密瞒着我们。$"

Route105_Text_AndresDefeated:
	.string "是的……\n我对对战不是很在行……$"

Route105_Text_AndresPostBattle:
	.string "我肯定在大海中\n还有很多秘密等着被发现。\p我要把它们全部找出来！$"

Route105_Text_AndresRegister:
	.string "啊？我这么弱，你还愿意\n把我登记到你的宝可导航吗？$"

Route105_Text_AndresRematchIntro:
	.string "我已经说过了我很弱……\n你确定你还想这样做？$"

Route105_Text_AndresRematchDefeated:
	.string "是的……\n我不觉得自己能赢。$"

Route105_Text_AndresRematchPostBattle:
	.string "也许我不擅长对战，\n不过我的探险精神是不会被打败的。\p我会去全世界的\n大海中旅行！$"

Route105_Text_JosueIntro:
	.string "我累了，快游不动了。\n我只是还不太习惯。\p我需要一场对战来换换心情！$"

Route105_Text_JosueDefeated:
	.string "我输了因为是在海里对战。$"

Route105_Text_JosuePostBattle:
	.string "是啊，对我来说，在天空中对战要比\n在大海好很多。$"

Route106_Text_ElliotIntro:
	.string "你喜欢在小溪中钓鱼\n还是在大海中钓鱼？$"

Route106_Text_ElliotDefeated:
	.string "就像在深海中钓鱼，\n我输的一塌糊涂！$"

Route106_Text_ElliotPostBattle:
	.string "钓鱼最棒了，不管在海里\n还是在小溪里。\l你同意的吧？$"

Route106_Text_ElliotRegister:
	.string "钓鱼是很棒，对战也是。\n如果你不介意，我们可不可以再见面？$"

Route106_Text_ElliotRematchIntro:
	.string "我钓到了很多宝可梦。\n我让你见识一场精彩的对战！$"

Route106_Text_ElliotRematchDefeated:
	.string "我又输的一塌糊涂！$"

Route106_Text_ElliotRematchPostBattle:
	.string "无论输赢，宝可梦都是最棒的！\n你同意的吧？$"

Route106_Text_NedIntro:
	.string "当人们想去厕所的\n时候该怎么办？\p如果我在厕所时鱼竿钓到了大鱼\n该怎么办？我根本去不了……$"

Route106_Text_NedDefeated:
	.string "我输了，因为我在努力忍着\n不去厕所……$"

Route106_Text_NedPostBattle:
	.string "哦，不！我有种感觉，\n我会钓到一条大鱼！$"

Route106_Text_DouglasIntro:
	.string "哈哈哈哈！我虽然跑步很差劲，\n但在水里你是抓不到我的！$"

Route106_Text_DouglasDefeated:
	.string "我放弃了！$"

Route106_Text_DouglasPostBattle:
	.string "在游泳比赛中我不会输的……$"

Route106_Text_KylaIntro:
	.string "大海是我的后院。我不会因为\n你是小孩而懈怠的！$"

Route106_Text_KylaDefeated:
	.string "你有没有对我放水？$"

Route106_Text_KylaPostBattle:
	.string "随着海浪漂流……\n我好喜欢，你为什么不试试？$"

Route107_Text_DarrinIntro:
	.string "哈欠……\p我肯定是海浪里漂流时睡着了。$"

Route107_Text_DarrinDefeated:
	.string "哈哈哈，我输了……\n我想我还是先睡一会儿吧……$"

Route107_Text_DarrinPostBattle:
	.string "在海浪上漂浮并摇晃着——\n就像睡在一张舒服的床上。$"

Route107_Text_TonyIntro:
	.string "大海是我的后院。\n对战吧！$"

Route107_Text_TonyDefeated:
	.string "我在自己的地盘输了……\n我很震惊！$"

Route107_Text_TonyPostBattle:
	.string "我满怀梦想在大海中\n畅游……\p这是一首歌！\n总之，我还要多游一会。$"

Route107_Text_TonyRegister:
	.string "你让我震惊不已！\n好，这样你就不会忘记我了……$"

Route107_Text_TonyRematchIntro:
	.string "在宽广的大海中游泳，\n我的宝可梦已经变得更强了！$"

Route107_Text_TonyRematchDefeated:
	.string "真是令人震惊！\p我的宝可梦已经变得更强了，\n但作为训练家，我还很弱！$"

Route107_Text_TonyRematchPostBattle:
	.string "你在对战中学到的东西\n会让你成为更强大的训练家。\l这是海浪教给我的。$"

Route107_Text_DeniseIntro:
	.string "你知道一个叫\n武斗镇的小镇吗？$"

Route107_Text_DeniseDefeated:
	.string "我讨厌这样！$"

Route107_Text_DenisePostBattle:
	.string "一个奇怪的流行语正在\n武斗镇大厅流传着。$"

Route107_Text_BethIntro:
	.string "你想和我对战吗？\n我乐意奉陪！$"

Route107_Text_BethDefeated:
	.string "我比不上你。$"

Route107_Text_BethPostBattle:
	.string "我认为你会越来越好。\n我也会努力的！$"

Route107_Text_LisaIntro:
	.string "由美：我们作为姐弟\n来挑战你！$"

Route107_Text_LisaDefeated:
	.string "由美：有一套。\n你现在不是一般的强。$"

Route107_Text_LisaPostBattle:
	.string "由美：你有没有朋友\n愿意和你一起去海滩？$"

Route107_Text_LisaNotEnoughPokemon:
	.string "由美：如果你想和我们对战的话，\n多带点宝可梦来。$"

Route107_Text_RayIntro:
	.string "真：我和姐姐经常进行\n宝可梦对战，\p我老是输，但是我们可以一起\n2对2打败你！$"

Route107_Text_RayDefeated:
	.string "真：喔，你的水平\n比我们要高！$"

Route107_Text_RayPostBattle:
	.string "真：我的姐姐给了我这只宝可梦。\n是我养大了它，现在是我很重要的\l拍档！$"

Route107_Text_RayNotEnoughPokemon:
	.string "真：如果你想和我们对战，\n去多带点宝可梦吧！$"

Route107_Text_CamronIntro:
	.string "我正在参加三项全能运动比赛，\n但我完全不累！$"

Route107_Text_CamronDefeated:
	.string "这下我精疲力尽……$"

Route107_Text_CamronPostBattle:
	.string "在这之后，我还有游泳和跑步\n要完成。\p我还行不行呢？$"

Route108_Text_JeromeIntro:
	.string "我的梦想是游过世界的\n七大海洋！$"

Route108_Text_JeromeDefeated:
	.string "就像这样我无法游过世界的\n七大海洋……$"

Route108_Text_JeromePostBattle:
	.string "和海洋宝可梦一起玩是\n游泳的一大乐趣！$"

Route108_Text_MatthewIntro:
	.string "喂，那边的人！\n你也要去那艘废弃的船吗？$"

Route108_Text_MatthewDefeated:
	.string "我在下沉！\n咕噜……咕噜……$"

Route108_Text_MatthewPostBattle:
	.string "有些人甚至走进了那个\n那艘废弃的船。$"

Route108_Text_TaraIntro:
	.string "我的那个爱说谎的男友告诉我\n我穿比基尼好看极了……$"

Route108_Text_TaraDefeated:
	.string "哦，嘘！$"

Route108_Text_TaraPostBattle:
	.string "即使知道是说谎，\n我也喜欢别人说我很漂亮……\l我们女孩子真是太复杂了……$"

Route108_Text_MissyIntro:
	.string "我爱大海！\n当我游泳的时候就会忘记一切烦恼！$"

Route108_Text_MissyDefeated:
	.string "当我输掉对战时，\n我变得很有压力！$"

Route108_Text_MissyPostBattle:
	.string "游泳能用来排除压力！\n非常健康！$"

Route108_Text_CoryIntro:
	.string "我喜欢水属性宝可梦。\n我也喜欢其他属性的宝可梦！$"

Route108_Text_CoryDefeated:
	.string "哇！我输了！\n哇！哇！$"

Route108_Text_CoryPostBattle:
	.string "大喊大叫对我有好处！\n让我振奋！$"

Route108_Text_CoryRegister:
	.string "我也喜欢强大的训练家！\n在你的宝可导航里登记我吧！$"

Route108_Text_CoryRematchIntro:
	.string "无论输赢，我都喜欢在大海里对战！$"

Route108_Text_CoryRematchDefeated:
	.string "哇！我又输了！\n哇！哇！$"

Route108_Text_CoryRematchPostBattle:
	.string "如果你面临挑战，\n试着对大海大喊大叫！$"

Route108_Text_CarolinaIntro:
	.string "我以我的宝可梦为豪。\n见识一下我们的速战速决！$"

Route108_Text_CarolinaDefeated:
	.string "那一点也不可爱。$"

Route108_Text_CarolinaPostBattle:
	.string "既然我在海上，我不介意穿上\n一件粉红色带镶褶边的泳衣……$"

Route109_Text_DavidIntro:
	.string "你好！看看我轮廓分明的腹肌！\n简直是所谓的“居合劈”！$"

Route109_Text_DavidDefeated:
	.string "啊呀！\n糟了！$"

Route109_Text_DavidPostBattle:
	.string "嗨呀！\p我努力锻炼的腹肌和\n宝可梦对战没有关系！$"

Route109_Text_AliceIntro:
	.string "你做好防晒措施了吗？$"

Route109_Text_AliceDefeated:
	.string "哎呦！哎呦，哎呦！$"

Route109_Text_AlicePostBattle:
	.string "脸颊最容易晒伤了！$"

Route109_Text_HueyIntro:
	.string "我去过世界各地的港口，\n但是凯那市是最好的。$"

Route109_Text_HueyDefeated:
	.string "你是最棒的！$"

Route109_Text_HueyPostBattle:
	.string "在最好的港口有最好的\n训练家……$"

Route109_Text_EdmondIntro:
	.string "不是吧……\n对战？和我？$"

Route109_Text_EdmondDefeated:
	.string "哦……哇哇哇哇……\n啊啊啊啊啊……$"

Route109_Text_EdmondPostBattle:
	.string "我平时要比这要强！\n我晕船晕得厉害！\p我是一个水手，但是……$"

Route109_Text_RickyIntro:
	.string "我很渴……我要去大海之家\n喝点劲爽汽水……$"

Route109_Text_RickyDefeated:
	.string "呃啊……$"

Route109_Text_RickyPostBattle:
	.string "我快饿坏了……我的救生圈看起来\n就像一个巨大的甜甜圈……$"

Route109_Text_RickyRegister:
	.string "等我不那么渴的时候，\n你可不可以再和我比一场？$"

Route109_Text_RickyRematchIntro:
	.string "我很饿，但是我还是有勇气\n来场对战的！$"

Route109_Text_RickyRematchDefeated:
	.string "我输了……\n正因为我饿了……$"

Route109_Text_RickyRematchPostBattle:
	.string "当你在海滩上吃东西的时，\n一切似乎都变得更美味了。$"

Route109_Text_LolaIntro:
	.string "不觉得在海滩上的伞\n看起来像一朵巨大的花？$"

Route109_Text_LolaDefeated:
	.string "妈咪！$"

Route109_Text_LolaPostBattle:
	.string "如果你从天空上看这个海滩，\n它看起来就像一个大花园！$"

Route109_Text_LolaRegister:
	.string "我？\n我每天都在！$"

Route109_Text_LolaRematchIntro:
	.string "我不会再输给你了！\n这就是为什么我有救生圈！$"

Route109_Text_LolaRematchDefeated:
	.string "妈咪！$"

Route109_Text_LolaRematchPostBattle:
	.string "如果有救生圈，我和我的宝可梦的\n可爱度就会大大提升！$"

Route109_Text_AustinaIntro:
	.string "没有救生圈我就不能游泳了，\n但是我不会输在宝可梦上的！$"

Route109_Text_AustinaDefeated:
	.string "是不是我输了就是因为我有\n救生圈？$"

Route109_Text_AustinaPostBattle:
	.string "我的救生圈是新潮的东西。\n没有它别人就不会注意我了。$"

Route109_Text_GwenIntro:
	.string "嗨，大训练家。\n愿意和我对战吗？$"

Route109_Text_GwenDefeated:
	.string "哦，你很强。$"

Route109_Text_GwenPostBattle:
	.string "你是怎么变得那么强的？$"

Route109_Text_CarterIntro:
	.string "哇哇！老哥我就要钓到\n一条大鱼了！$"

Route109_Text_CarterDefeated:
	.string "老哥我刚刚丢了一条……$"

Route109_Text_CarterPostBattle:
	.string "老哥我认为你是一个大人物。\n不，你是一个明日之星！$"

Route109_Text_PaulIntro:
	.string "理树：好吧，这里有位电灯泡。\p我希望你没有打扰我们\n在一起的宝贵时光。$"

Route109_Text_PaulDefeated:
	.string "理树：好吧，我放弃。$"

Route109_Text_PaulPostBattle:
	.string "理树：对了，别告诉任何人\n我们在这。\l这就是我们两个人的世界！$"

Route109_Text_PaulNotEnoughPokemon:
	.string "理树：我们真的深深地相爱着。\n这就是为什么我们要让我们的宝可梦\l在一起对战。$"

Route109_Text_MelIntro:
	.string "志木：我们完全坠入爱河了。\n我们火热的爱情正感染着整个丰缘！$"

Route109_Text_MelDefeated:
	.string "志木：我们输了，都是我的错！\n理树会恨我的！$"

Route109_Text_MelPostBattle:
	.string "志木：嗯，理树，你在生我的气吗？\n不要生气了，好不好。$"

Route109_Text_MelNotEnoughPokemon:
	.string "志木：我们真的深深地相爱着。\n这就是为什么我们要让我们的宝可梦\l在一起对战。$"

Route109_Text_ChandlerIntro:
	.string "当当当！看？\n我的救生圈是圆的！$"

Route109_Text_ChandlerDefeated:
	.string "哦，哦！\n太糟了！$"

Route109_Text_ChandlerPostBattle:
	.string "我都给你看我圆圆的\n救生圈了……$"

Route109_Text_HaileyIntro:
	.string "我不会游泳，\n所以我在装游泳。$"

Route109_Text_HaileyDefeated:
	.string "我也这样认为！\n我看我们赢不了。$"

Route109_Text_HaileyPostBattle:
	.string "当我学会游泳时，\n我想我的宝可梦会变的更强。$"

Route109_Text_ElijahIntro:
	.string "对我这样有男子气概的人，\n这种宝可梦和我简直是绝配！$"

Route109_Text_ElijahDefeated:
	.string "即使被打败了我也很酷，是吧？$"

Route109_Text_ElijahPostBattle:
	.string "对我这样有男子气概的人，\n一个港口是完美的落脚地！\p看来我要前往凯那市了。$"

Route110_Text_JacobIntro:
	.string "哇喔！小心！\n我猜你还不习惯自行车比赛吧。$"

Route110_Text_JacobDefeated:
	.string "哇喔！\n我的刹车坏了！$"

Route110_Text_JacobPostBattle:
	.string "爆胎和刹车问题会\n导致严重的伤害！\l检查你的自行车看看有没有问题！$"

Route110_Text_AnthonyIntro:
	.string "哟，你好！\n你能跟上我的速度吗？$"

Route110_Text_AnthonyDefeated:
	.string "一败涂地！$"

Route110_Text_AnthonyPostBattle:
	.string "只靠速度是赢不了对战的。\n我得重新考虑一下……$"

Route110_Text_BenjaminIntro:
	.string "如果你的自行车越来越快！\n不要惊慌！$"

Route110_Text_BenjaminDefeated:
	.string "我不应该在宝可梦\n的对战中惊慌……$"

Route110_Text_BenjaminPostBattle:
	.string "用不着惊慌和紧张。\n放轻松，有的是时间。$"

Route110_Text_BenjaminRegister:
	.string "我会放轻松后继续前进。\n要是你准备好了就叫我一声。$"

Route110_Text_BenjaminRematchIntro:
	.string "是不是太快了些？\n放轻松然后让我们对战吧。$"

Route110_Text_BenjaminRematchDefeated:
	.string "我没有惊慌，可是还是输了……$"

Route110_Text_BenjaminRematchPostBattle:
	.string "用不着惊慌和紧张。\n放轻松，有的是时间。$"

Route110_Text_AbigailIntro:
	.string "三项全能运动越到后面越困难。\p你必须完成\n游泳，骑车和跑步。$"

Route110_Text_AbigailDefeated:
	.string "宝可梦对战也很困难！$"

Route110_Text_AbigailPostBattle:
	.string "我累坏了，所以需要休息一下。\n适当的休息是非常重要的。$"

Route110_Text_AbigailRegister:
	.string "你知道吗，我欣赏你！\n让我们在自行车道再赛一次吧。$"

Route110_Text_AbigailRematchIntro:
	.string "一边骑车一边对战是不是\n很棒？$"

Route110_Text_AbigailRematchDefeated:
	.string "哇……\n你怎么会这么强？$"

Route110_Text_AbigailRematchPostBattle:
	.string "你是不是想刷新纪录？\p耽误你了，真抱歉！$"

Route110_Text_JasmineIntro:
	.string "我一直在不停的骑车。\n我的腿像灌了铅！$"

Route110_Text_JasmineDefeated:
	.string "我很担心肌肉抽筋……$"

Route110_Text_JasminePostBattle:
	.string "哦，你有做道馆徽章？\n难怪你很强！$"

Route110_Text_EdwardIntro:
	.string "我已经看穿你的意图！\n我不可能输！$"

Route110_Text_EdwardDefeated:
	.string "我无法预言我自己的灭亡！$"

Route110_Text_EdwardPostBattle:
	.string "我看到了你的将来……\p嗯……\n我看见一道闪耀的光芒……$"

Route110_Text_JaclynIntro:
	.string "哈哈哈哈哈！\n我会用我的奇迹来让你眼花缭乱！$"

Route110_Text_JaclynDefeated:
	.string "我居然输了！$"

Route110_Text_JaclynPostBattle:
	.string "你会赢仅仅是应为\n那是一个奇迹！是的，一个奇迹！\l你别认为你可以一直赢！$"

Route110_Text_EdwinIntro:
	.string "我可以看你的宝可梦吗？\n就一下，拜托了？$"

Route110_Text_EdwinDefeated:
	.string "我想完成我的收藏……$"

Route110_Text_EdwinPostBattle:
	.string "当我看到一个没见过的宝可梦时，\n我作为收藏家的热情就会燃烧！$"

Route110_Text_EdwinRegister:
	.string "我还喜欢收集对战寻呼\n登记目录……$"

Route110_Text_EdwinRematchIntro:
	.string "你捕捉到新的宝可梦了吗？\p我可以看看你的宝可梦吗？\n就看一眼，可以吗？$"

Route110_Text_EdwinRematchDefeated:
	.string "你的宝可梦……\n好羡慕啊……$"

Route110_Text_EdwinRematchPostBattle:
	.string "啊，真希望所有珍稀的\n宝可梦都是我的啊！$"

Route110_Text_DaleIntro:
	.string "喂！\n不要突然站在我背后！$"

Route110_Text_DaleDefeated:
	.string "输了\n真不甘心！$"

Route110_Text_DalePostBattle:
	.string "钓鱼是要很专心的。\n你必须一直关注着浮标的动静。$"

Route110_Text_IsabelIntro:
	.string "哈哈！我要走遍全世界来\n炫耀我那可爱的宝可梦。$"

Route110_Text_IsabelDefeated:
	.string "噢，天哪，这可不行。$"

Route110_Text_IsabelPostBattle:
	.string "比起对战，我想我还是应该到\n宝可梦发烧友俱乐部\l去炫耀我的宝可梦。$"

Route110_Text_IsabelRegister:
	.string "我还完全没能好好炫耀自己的宝可梦\n呢！我要让你成为我的常驻观众！$"

Route110_Text_IsabelRematchIntro:
	.string "哈哈！不管多少次，我都乐意\n向你炫耀我的宝可梦！$"

Route110_Text_IsabelRematchDefeated:
	.string "噢，天哪，这可不行。$"

Route110_Text_IsabelRematchPostBattle:
	.string "我永远不会停止炫耀我的\n宝可梦的。\p不过，我也很喜欢对战！$"

Route110_Text_TimmyIntro:
	.string "我发现附近的草里发现了很帅\n的宝可梦！$"

Route110_Text_TimmyDefeated:
	.string "只是帅是赢不了的……$"

Route110_Text_TimmyPostBattle:
	.string "用刚捕捉到的宝可梦\n对战实在太难了。$"

Route110_Text_AlyssaIntro:
	.string "我从自行车道上掉下来了……\p好丢人……\n我要跟你对战来雪耻！$"

Route110_Text_AlyssaDefeated:
	.string "啊！我竟然输了！$"

Route110_Text_AlyssaPostBattle:
	.string "掉下来……又输了……\n这对我来说真是太丢脸了！$"

Route110_Text_JosephIntro:
	.string "好的！全速前进！\n如果你不能跟上节奏，\l你就会被甩在后面！$"

Route110_Text_JosephDefeated:
	.string "你的状态真好……$"

Route110_Text_JosephPostBattle:
	.string "我不会就这样倒下的！\n失败只会让我更坚强！$"

Route110_Text_KalebIntro:
	.string "可爱的宝可梦在互相帮助……\n这便是世界上最美妙的景象啊！$"

Route110_Text_KalebDefeated:
	.string "你难道都没有同情心的吗？$"

Route110_Text_KalebPostBattle:
	.string "够了够了，\n你们已经尽力了，宝贝们！$"

Route111_Text_DrewIntro:
	.string "哦！GOGO护目镜真适合你。\n不过肯定更适合我。\p让我们用对战来决定\n它们更适合谁吧！$"

Route111_Text_DrewDefeat:
	.string "拜GOGO护目镜所赐，\n我没法看清周围的状况了。$"

Route111_Text_DrewPostBattle:
	.string "有了GOGO护目镜就可以\n穿越沙尘暴了。\l真让人高兴！$"

Route111_Text_HeidiIntro:
	.string "我正在沙漠野餐呢。\p这里到处都有训练家，\n所以我也很喜欢在这里对战！$"

Route111_Text_HeidiDefeat:
	.string "啊！你好卑鄙！$"

Route111_Text_HeidiPostBattle:
	.string "你在沙暴中对战时，\n一定要注意宝可梦的HP。\p不注意的话它可能会昏厥的！$"

Route111_Text_BeauIntro:
	.string "装备上这些GOGO护目镜，\n感觉就跟超级英雄一样。\l现在，谁也赢不了我了！$"

Route111_Text_BeauDefeat:
	.string "只有热情的话，我是赢不了的……$"

Route111_Text_BeauPostBattle:
	.string "总有一天我会成为真正的英雄。\n我会更加努力，让我和我的宝可梦\l变得更强。$"

Route111_Text_BeckyIntro:
	.string "听说沙漠里有很多化石。\n会是在哪儿呢？$"

Route111_Text_BeckyDefeat:
	.string "没能做到……$"

Route111_Text_BeckyPostBattle:
	.string "如果他们能在沙漠找到化石，\n那从前那里一定是个大海。$"

Route111_Text_DustyIntro:
	.string "我已经找了30年的遗迹！\n要向这样的我挑战吗？$"

Route111_Text_DustyDefeat:
	.string "虽然我找过遗迹，\n却从没找过强大的宝可梦。$"

Route111_Text_DustyPostBattle:
	.string "我已经找了30年的遗迹！\p等等，是已经找了40年了吗？\n现在是哪一年？$"

Route111_Text_DustyRegister:
	.string "我从没找过任何强力的\n宝可梦。\p不过不知道为什么，\n我真的很喜欢宝可导航。$"

Route111_Text_DustyRematchIntro:
	.string "我已经找了30年的遗迹！\p等等，是已经找了40年了吗？\n总之要向这样的我挑战吗？$"

Route111_Text_DustyRematchDefeat:
	.string "我还没找到过任何遗迹，\n也没找到过强大的宝可梦……$"

Route111_Text_DustyPostRematch:
	.string "我已经找了30年的遗迹！\n等等，是已经找了40年了吗？\p嗯……肯定还没到50年……\n我到底找了多久了？$"

Route111_Text_TravisIntro:
	.string "我现在很有活力！\n我的宝可梦也跟我一样！$"

Route111_Text_TravisDefeat:
	.string "我的宝可梦没活力了……$"

Route111_Text_TravisPostBattle:
	.string "遇到有活力的训练家时，\n我总是会忍不住多看几眼。$"

Route111_Text_IreneIntro:
	.string "虽然我不知道你要去哪里，\n但是要来场对战吗？$"

Route111_Text_IreneDefeat:
	.string "噢，你可真是强得离谱！$"

Route111_Text_IrenePostBattle:
	.string "我是很想去烟囱山，\n不过这里的风景也不错。$"

Route111_Text_DaisukeIntro:
	.string "为了锻炼自己，\n我向所有遇到的人挑战！$"

Route111_Text_DaisukeDefeat:
	.string "我投降！$"

Route111_Text_DaisukePostBattle:
	.string "我能做的，就是一直努力\n训练，直到我能打败像你\l这样强的训练家。$"

Route111_Text_WiltonIntro:
	.string "让我看看，你到底把你的\n宝可梦训练到什么地步了！$"

Route111_Text_WiltonDefeat:
	.string "原来如此，确实已经\n训练到一定程度了呢！$"

Route111_Text_WiltonPostBattle:
	.string "宝可梦和训练家\n会在对战中不断进步。\p重要的是即便输了，\n也永远不要放弃。$"

Route111_Text_WiltonRegister:
	.string "你的训练方式确实让我获益良多。\n可以的话，我想跟你再比一次。$"

Route111_Text_WiltonRematchIntro:
	.string "我们都是为了更进一步\n而在这里修行着。\l你也跟我们一起修行吧！$"

Route111_Text_WiltonRematchDefeat:
	.string "噢，你做得真不错啊！$"

Route111_Text_WiltonPostRematch:
	.string "既然你这么强，\n应该以挑战宝可梦联盟为目标。$"

Route111_Text_BrookeIntro:
	.string "啊，你的宝可梦\n看起来相当强啊。\l请一定要跟我比一比好吗？$"

Route111_Text_BrookeDefeat:
	.string "不只是看起来很强，\n是真的很强啊！$"

Route111_Text_BrookePostBattle:
	.string "我以为我已经把我的\n宝可梦训练得很强了，\l但我错了，我还很长的路要走。$"

Route111_Text_BrookeRegister:
	.string "我真希望能跟更多\n像你这么强的人交朋友！$"

Route111_Text_BrookeRematchIntro:
	.string "你教给宝可梦的招式，\n会决定它们是变弱，\l还是变强。\p你的宝可梦学会了\n什么样的招式呢？$"

Route111_Text_BrookeRematchDefeat:
	.string "你教给它们的招式真不错！$"

Route111_Text_BrookePostRematch:
	.string "也许我应该等我的\n宝可梦学到更好的\l招式之后再让它们进化……$"

Route111_Text_CeliaIntro:
	.string "我就不该来这种地方\n野餐的！$"

Route111_Text_CeliaDefeat:
	.string "啊啊！\n我真不该来的！$"

Route111_Text_CeliaPostBattle:
	.string "在这样的沙暴里，\n即便装备着我的GOGO护目镜\l也没办法野餐啊……$"

Route111_Text_BryanIntro:
	.string "你到底有多强？\n让我们来揭开谜底吧！$"

Route111_Text_BryanDefeat:
	.string "哦！你的实力高深莫测啊！$"

Route111_Text_BryanPostBattle:
	.string "这个沙漠还潜藏着\n非常多的秘密！$"

Route111_Text_BrandenIntro:
	.string "如果你输了，\n我就给你一些我的三明治。$"

Route111_Text_BrandenDefeat:
	.string "切！我以为用我的\n三明治就可以贿赂你的……$"

Route111_Text_BrandenPostBattle:
	.string "我的穿山鼠也很喜欢\n吃我的三明治。$"

Route111_Text_TyronIntro:
	.string "这是我最喜欢的宝可梦！$"

Route111_Text_TyronDefeat:
	.string "等一下！\n你认真看过我的宝可梦了吗？$"

Route111_Text_TyronPostBattle:
	.string "在对战的时候炫耀自己的宝可梦\n真是其乐无穷。\p我打赌每个人在参与对战后\n都会有这样的感受！$"

Route111_Text_CelinaIntro:
	.string "哦～\n要怎么样才能让我兴奋起来呢？$"

Route111_Text_CelinaDefeat:
	.string "哦……我的天……\n太刺激了。$"

Route111_Text_CelinaPostBattle:
	.string "我到现在还心跳不止啊。\n你真的是个惊人的训练家啊。$"

Route111_Text_HaydenIntro:
	.string "你要是我一样饥饿的话，\n也就没有功夫同情别人了！$"

Route111_Text_HaydenDefeat:
	.string "呃啊……$"

Route111_Text_HaydenPostBattle:
	.string "我的肚子咕咕叫！\n也许我该烧烤些树果了……$"

Route111_Text_BiancaIntro:
	.string "你是从紫堇市来的吗？\n那你的体力应该很充沛！$"

Route111_Text_BiancaDefeat:
	.string "啊啦啦！还真强啊！$"

Route111_Text_BiancaPostBattle:
	.string "这前面的路还很长呢！$"

Route112_Text_BriceIntro:
	.string "哈哈哈！\n和我来场对战怎么样？\l就你和我！\l哈哈哈！$"

Route112_Text_BriceDefeat:
	.string "我输了！\n哈哈哈！$"

Route112_Text_BricePostBattle:
	.string "哈哈哈！有东西飞进我鼻子了！\n哈哈哈——阿嚏！$"

Route112_Text_TrentIntro:
	.string "经过上山下山的艰苦训练，\n我的腿可结实得很。\p它们不会那么轻易就屈服的，\n朋友！$"

Route112_Text_TrentDefeat:
	.string "哎呦！我的腿抽筋了！$"

Route112_Text_TrentPostBattle:
	.string "试着去徒步旅行吧，我的意思是\n背着一大包的东西在\l山上进行徒步旅行。\p我的朋友，那样会让你身体\n变得很好的。$"

Route112_Text_TrentRegister:
	.string "啊，我的腿抽筋了。\n能从我的包包里拿些\l绷带给我吗？\p哦不，那个是我的宝可导航！\n好吧，我会登记上你的。$"

Route112_Text_TrentRematchIntro:
	.string "我一直通过爬山来保持健康。\n力气绰绰有余！$"

Route112_Text_TrentRematchDefeat:
	.string "我在力气上被打败了？$"

Route112_Text_TrentRematchPostBattle:
	.string "我听说一些很有实力的\n训练家已经登到了烟囱山顶。\p我打算登上去挑战他们！$"

Route112_Text_LarryIntro:
	.string "我很坚强。\n输了也不会哭的。$"

Route112_Text_LarryDefeat:
	.string "哇哇哇！$"

Route112_Text_LarryPostBattle:
	.string "我哭是因为我想我妈妈了！\n抽泣……$"

Route112_Text_CarolIntro:
	.string "当你在野炊的时候，\n为什么不唱首歌呢！\l来吧，和我一起唱吧！$"

Route112_Text_CarolDefeat:
	.string "哦，你太厉害了！$"

Route112_Text_CarolPostBattle:
	.string "你是不是擅长唱歌或者\n培育宝可梦，这都不重要。\p只要乐在其中就是胜利！$"

Route112_Text_BryantIntro:
	.string "我在烈焰小径里捉到了火热的宝可梦！\n来看看吧！$"

Route112_Text_BryantDefeat:
	.string "多么崎岖的山路啊！$"

Route112_Text_BryantPostBattle:
	.string "我喜欢你的战斗方式。\n看起来很有特色。$"

Route112_Text_ShaylaIntro:
	.string "你不就是那个可爱的训练家吗！\n来吧，我要一场浪漫的对战！\l我也还算有点水准！$"

Route112_Text_ShaylaDefeat:
	.string "你太强了！\n你让我太震惊了！$"

Route112_Text_ShaylaPostBattle:
	.string "你现在很忙吗？\n我在想我们现在能不能再\l来一场对战……\l如果你忙的话就算了。$"

Route113_Text_JaylenIntro:
	.string "你知道这儿为什么\n这么凉快吗？$"

Route113_Text_JaylenDefeat:
	.string "呜！好臭！$"

Route113_Text_JaylenPostBattle:
	.string "火山灰遮住了阳光，\n所以这里不怎么热。\p对于我来说太棒了\n——我可受不了热！$"

Route113_Text_DillonIntro:
	.string "火山的爆发证明了\n大地是活着的。$"

Route113_Text_DillonDefeat:
	.string "你还真是强啊！$"

Route113_Text_DillonPostBattle:
	.string "嗷！我看不见了！\n我的睫毛上“净”是灰“烬”！\pGet到了吗？\p好吧，看来不怎么样……$"

Route113_Text_MadelineIntro:
	.string "我用这把阳伞为我亲爱的呆火驼\n挡一挡那些肮脏的\l火山灰。$"

Route113_Text_MadelineDefeat:
	.string "喘……喘……\n我太累了……$"

Route113_Text_MadelinePostBattle:
	.string "你很擅长这个啊。\n不得不说的确令我印象深刻！$"

Route113_Text_MadelineRegister:
	.string "来，躲进我的阳伞下吧。\n让我把你登记到我的导航器里。$"

Route113_Text_MadelineRematchIntro:
	.string "哦，你好，很久不见了吧？\n能和我来场对战吗？$"

Route113_Text_MadelineRematchDefeat:
	.string "噢，太棒了！$"

Route113_Text_MadelinePostRematch:
	.string "你还是很擅长这个啊。\n不得不说的确令我印象深刻！$"

Route113_Text_LaoIntro:
	.string "我从灰尘中一跃而出！\n我要向你挑战！$"

Route113_Text_LaoDefeat:
	.string "我光荣地承认败北！$"

Route113_Text_LaoPostBattle:
	.string "我必须要精进隐匿之术。\n再会吧。$"

Route113_Text_LaoRegister:
	.string "哇哈！见识一下古代的\n导航器登记之忍术吧！$"

Route113_Text_LaoRematchIntro:
	.string "我跳出了那些灰尘！\n我要和你挑战！$"

Route113_Text_LaoRematchDefeat:
	.string "我光荣地承认败北！$"

Route113_Text_LaoPostRematch:
	.string "我娴熟的隐匿之术因为我\n不成熟的战斗技术而失败了……\p再会吧。$"

Route113_Text_LungIntro:
	.string "谢谢你找到了我！\n但我们还是要来场对战！$"

Route113_Text_LungDefeat:
	.string "我要使用忍术了……\n“火山灰漩涡斗篷”！\p……什么？\n已经结束了？$"

Route113_Text_LungPostBattle:
	.string "你知道躲起来最糟糕的事什么吗？\n如果没有人来找的话，是很孤独的。$"

Route113_Text_ToriIntro:
	.string "奈奈：我们都在收集火山灰，\n我们也都在对战。$"

Route113_Text_ToriDefeat:
	.string "奈奈：我们输了……真是太无聊了\n我们要去收集更多的火山灰了。$"

Route113_Text_ToriPostBattle:
	.string "奈奈：我们有多少火山灰了？\n希望够做白色玻璃哨了。$"

Route113_Text_ToriNotEnoughMons:
	.string "奈奈：我们来个2对2的对战吧。\n如果不的话我们就输了！$"

Route113_Text_TiaIntro:
	.string "宁宁：我们都在收集火山灰，\n我们也都在对战。$"

Route113_Text_TiaDefeat:
	.string "宁宁：我们输了……真是太无聊了\n我们要去收集更多的火山灰了。$"

Route113_Text_TiaPostBattle:
	.string "宁宁：我们有多少火山灰了？\n应该够做白色玻璃哨了吧。$"

Route113_Text_TiaNotEnoughMons:
	.string "宁宁：我们来个2对2的对战吧。\n如果不的话我们就输了！$"

Route113_Text_CobyIntro:
	.string "用这些翅膀我就能把你\n扫开！$"

Route113_Text_CobyDefeat:
	.string "什……什么？$"

Route113_Text_CobyPostBattle:
	.string "我那么轻易就被你打败了，\n都不知道该说什么了……$"

Route113_Text_SophieIntro:
	.string "这儿的热天气让我昏昏欲睡。\n和我对战吧，让我保持清醒。$"

Route113_Text_SophieDefeat:
	.string "我很确定……\n这绝对是一场梦。$"

Route113_Text_SophiePostBattle:
	.string "失败让我心烦意乱……\n我要在这里睡觉了！\lZzz！$"

Route113_Text_LawrenceIntro:
	.string "你是不是也在收集\n火山灰呢？$"

Route113_Text_LawrenceDefeat:
	.string "呵呵。\n我们被打得干净利落。$"

Route113_Text_LawrencePostBattle:
	.string "我应该也藏在灰尘里的。$"

Route113_Text_WyattIntro:
	.string "你、你想和我对战吗？\n明明我才刚捕捉到宝可梦？$"

Route113_Text_WyattDefeat:
	.string "你、赢了很开心吗？\n尽管只是赢了我？$"

Route113_Text_WyattPostBattle:
	.string "你想对一个失败者\n说些什么呢？\p你不是最酷的吗？\n哼！$"

Route114_Text_LennyIntro:
	.string "嘛咿呀呼！\p……\p你要回应我“嘛咿呀呼”，\n因为这里没有回声！$"

Route114_Text_LennyDefeat:
	.string "嘛咿呀呼！$"

Route114_Text_LennyPostBattle:
	.string "当我还很小的时候，\n我真的一直相信有人在远处\l模仿我大喊“嘛咿呀呼”。$"

Route114_Text_LucasIntro:
	.string "如果你还有没有准备好的话，\n你就不应该上山！$"

Route114_Text_LucasDefeat:
	.string "山是无情的……$"

Route114_Text_LucasPostBattle:
	.string "在冬天，山上由于雪崩和\n暴风雪会变得非常危险。$"

Route114_Text_ShaneIntro:
	.string "露营真好玩！可以钓鱼、烤棉花糖，\n还可以讲鬼故事！\p但是最棒的还是\n来场宝可梦对战了！$"

Route114_Text_ShaneDefeat:
	.string "太强了！$"

Route114_Text_ShanePostBattle:
	.string "我能和我的宝可梦\n一起来露营真是太棒了。$"

Route114_Text_NancyIntro:
	.string "吃饭后我需要一些运动。\n让我们来个对战吧！$"

Route114_Text_NancyDefeat:
	.string "哦，不！$"

Route114_Text_NancyPostBattle:
	.string "我刚刚美餐了一顿。\n我好像有点困了……$"

Route114_Text_SteveIntro:
	.string "呃……\n想和我的宝可梦对战吗？$"

Route114_Text_SteveDefeat:
	.string "我的，我的宝可梦……$"

Route114_Text_StevePostBattle:
	.string "庞大而坚硬的身体，\n巨大的犄角，以及凶猛的獠牙……\p呜呼呼呼……\n我希望能有只那样的宝可梦……$"

Route114_Text_SteveRegister:
	.string "不要忘记你对我做过的事！\n我不会让你忘记的！$"

Route114_Text_SteveRematchIntro:
	.string "呜呼呼呼……\n来吧，和我的宝可梦对战……$"

Route114_Text_SteveRematchDefeat:
	.string "能看到你的宝可梦我感觉\n自己非常幸运……$"

Route114_Text_StevePostRematch:
	.string "呜呼呼呼……\p每当我看到宝可梦们对战时，\n我都浑身颤抖……$"

Route114_Text_BernieIntro:
	.string "如果你要点营火，\n请先确认你边上有水。$"

Route114_Text_BernieDefeat:
	.string "谢谢你帮我灭火！$"

Route114_Text_BerniePostBattle:
	.string "在森林里，不管是什么火\n你都千万要小心处理。\p千万不要小看火的威力。$"

Route114_Text_BernieRegister:
	.string "你让我热血沸腾。\n让我们互相登记吧！$"

Route114_Text_BernieRematchIntro:
	.string "你已经知道在营火时要\n准备好水了吗？$"

Route114_Text_BernieRematchDefeat:
	.string "在我燃起之前，\n就被浇灭了。$"

Route114_Text_BerniePostRematch:
	.string "在森林里，不管是什么火\n你都千万要小心处理。\p千万不要小看火的威力。$"

Route114_Text_ClaudeIntro:
	.string "如果是钓鱼，\n你根本不是我的对手。\l用你的宝可梦来决胜负吧！$"

Route114_Text_ClaudeDefeat:
	.string "如果是比钓鱼，我就赢了……$"

Route114_Text_ClaudePostBattle:
	.string "我想我该试试到流星瀑布\n能不能钓一条大鱼。\p我确信那里一定有什么东西。$"

Route114_Text_NolanIntro:
	.string "我很喜欢钓鱼，\n不过我也很喜欢对战！\p谁要挑战我，我都会接受，\n哪怕我还正在钓鱼。$"

Route114_Text_NolanDefeat:
	.string "我喜欢对战，但这并不\n代表我擅长对战……$"

Route114_Text_NolanPostBattle:
	.string "这次我一定能赢！\p我总是这么想，所以一直\n没有办法放弃钓鱼和对战。$"

Route114_Text_TyraIntro:
	.string "佳代：是啊。\n我心情正好，就教你一点\l关于宝可梦的东西好了。$"

Route114_Text_TyraDefeat:
	.string "佳代：真是一场漂亮的对战！$"

Route114_Text_TyraPostBattle:
	.string "佳代：我在教我的后辈依代\n关于宝可梦的事。$"

Route114_Text_TyraNotEnoughMons:
	.string "佳代：呵呵……要跟我们对战，\n只有1只宝可梦是不够的！$"

Route114_Text_IvyIntro:
	.string "依代：是谁教你宝可梦的事情的？$"

Route114_Text_IvyDefeat:
	.string "依代：真是一场漂亮的对战！$"

Route114_Text_IvyPostBattle:
	.string "依代：我会开始训练宝可梦\n就是因为有我的前辈佳代\l在教我！$"

Route114_Text_IvyNotEnoughMons:
	.string "依代：你只有1只宝可梦吗？\n我想它一定很寂寞。$"

Route114_Text_KaiIntro:
	.string "我钓到了一条大鱼！\n真的是很大的鱼！$"

Route114_Text_KaiDefeat:
	.string "咦？\n我的在大小上输了吗？$"

Route114_Text_KaiPostBattle:
	.string "好啊！\n那我就钓一条更大的！$"

Route114_Text_CharlotteIntro:
	.string "我！\n我可不只是长得可爱而已！$"

Route114_Text_CharlotteDefeat:
	.string "那一点也不可爱！$"

Route114_Text_CharlottePostBattle:
	.string "我不想要只是可爱的宝可梦。\p我喜欢长得可爱并且\n还有那么一两个怪癖的！$"

Route114_Text_AngelinaIntro:
	.string "你把你的宝可梦\n进化得怎么样了？$"

Route114_Text_AngelinaDefeat:
	.string "哦……\n原来如此啊。$"

Route114_Text_AngelinaPostBattle:
	.string "有些宝可梦进化后\n变化非常大，很惊人！$"

Route115_Text_TimothyIntro:
	.string "嗯……\n你确实有点能力的样子……\l来当我的对手吧！$"

Route115_Text_TimothyDefeat:
	.string "你比我想象中更强！$"

Route115_Text_TimothyPostBattle:
	.string "世上根本没有什么天才，\n一切都是努力的结果！\l我是这么相信着的……$"

Route115_Text_TimothyRegister:
	.string "嗯……\n好久没输得这么惨了。\p可以的话，我希望你能\n再一次当我的对手。$"

Route115_Text_TimothyRematchIntro:
	.string "嗯……还是跟以前一样，\n你的能力足以说明一切。\l继续当我的对手吧！$"

Route115_Text_TimothyRematchDefeat:
	.string "一如既往地强啊！$"

Route115_Text_TimothyPostRematch:
	.string "一切都是因为努力！\p我会输就是因为我\n还不够努力！$"

Route115_Text_KoichiIntro:
	.string "你！\p我的腕力！\p要跟你对战！$"

Route115_Text_KoichiDefeat:
	.string "痛痛痛！$"

Route115_Text_KoichiPostBattle:
	.string "我的腕力们！\p只要它们还想变强，\n我就会跟它们一起变强！$"

Route115_Text_NobIntro:
	.string "我最强的招式就是\n用我的前额碎砖头！$"

Route115_Text_NobDefeat:
	.string "呜哇哇！\n我的前额被撞碎了！$"

Route115_Text_NobPostBattle:
	.string "我一直在教我的宝可梦空手道。\p感觉它们会变得比我强得多。\n真期待那天的到来啊！$"

Route115_Text_NobRegister:
	.string "你真让我佩服！\n等我重新训练后，再跟我比一次吧！$"

Route115_Text_NobRematchIntro:
	.string "自从输给了你之后，\n我们就努力训练，提高技术。\l来吧，再较量一次吧！$"

Route115_Text_NobRematchDefeat:
	.string "呜哇哇！\n我们又输了！$"

Route115_Text_NobPostRematch:
	.string "我的宝可梦会变得更强的！\n我也会加倍训练的！$"

Route115_Text_CyndyIntro:
	.string "这个海滩是我秘密训练基地！\n不要随便进来！$"

Route115_Text_CyndyDefeat:
	.string "修行还不够啊……！$"

Route115_Text_CyndyPostBattle:
	.string "这些沙子就像软垫一样\n可以缓冲，预防受伤。\l真是完美的修行地啊！$"

Route115_Text_CyndyRegister:
	.string "好吧，你可以随时来这里。\n作为交换，就拜托你再次\l当我的对手了。$"

Route115_Text_CyndyRematchIntro:
	.string "那么，我们开始对战吧！$"

Route115_Text_CyndyRematchDefeat:
	.string "我是可以对战，\n但我的宝可梦……$"

Route115_Text_CyndyPostRematch:
	.string "虽然输了，我还是很开心，\n大概是因为我真的很喜欢\l宝可梦吧。$"

Route115_Text_HectorIntro:
	.string "我有一只珍稀宝可梦！\n要不要看看？$"

Route115_Text_HectorDefeat:
	.string "你……\n很想要我的宝可梦吧？$"

Route115_Text_HectorPostBattle:
	.string "我能拥有这么珍稀的宝可梦，\n已经很知足了。$"

Route115_Text_KyraIntro:
	.string "我会一边跑一边进行对战！\n一定要跟上我！$"

Route115_Text_KyraDefeat:
	.string "呼，呼……$"

Route115_Text_KyraPostBattle:
	.string "一边跑一边对战果然是个错误！\n我应该跑一跑来平静一下……$"

Route115_Text_JaidenIntro:
	.string "接招吧！\n忍法——终极宝可梦之术！$"

Route115_Text_JaidenDefeat:
	.string "哇！策略失败了！$"

Route115_Text_JaidenPostBattle:
	.string "不过我的宝可梦\n确实是终极宝可梦吧？$"

Route115_Text_HeleneIntro:
	.string "我的宝可梦可是黑带级的！$"

Route115_Text_HeleneDefeat:
	.string "太不甘心了！$"

Route115_Text_HelenePostBattle:
	.string "我几乎都没遇到过\n比我强的人……\p我知道了！\n你是道馆馆主吧？$"

Route115_Text_AlixIntro:
	.string "你我目光交汇！\n现在别想逃掉！$"

Route115_Text_AlixDefeat:
	.string "可恶……不错嘛！$"

Route115_Text_AlixPostBattle:
	.string "哦，好吧。\n我想我还是瞬间移动回家吧。$"

Route115_Text_MarleneIntro:
	.string "你妨碍了我的冥想……\n接受惩罚吧。$"

Route115_Text_MarleneDefeat:
	.string "你害我分心了！$"

Route115_Text_MarlenePostBattle:
	.string "我常在这里跟宝可梦一起\n冥想。但这里始终不太平静……$"

Route116_Text_ClarkIntro:
	.string "隧道过不去的话，\n我就从山顶上过去吧。$"

Route116_Text_ClarkDefeat:
	.string "呼……呼……\n输了啊，好累哦……$"

Route116_Text_ClarkPostBattle:
	.string "没有隧道也没什么大不了的嘛。\n对于我们登山男，山就是路！$"

Route116_Text_JoeyIntro:
	.string "我的宝可梦运用！\n你就好好瞧瞧吧！$"

Route116_Text_JoeyDefeat:
	.string "好痛！有伤口了！\n我得赶紧缠上绷带！$"

Route116_Text_JoeyPostBattle:
	.string "绷带也是坚强的标志！\n我又得到了一个！$"

Route116_Text_JoseIntro:
	.string "我的虫宝可梦是很强的！\n来对战吧！$"

Route116_Text_JoseDefeat:
	.string "我输了……！\n我还以为能赢的……！$"

Route116_Text_JosePostBattle:
	.string "虫宝可梦进化速度很快。\n所以也很快变强。$"

Route116_Text_JaniceIntro:
	.string "就让你瞧瞧我可爱的\n宝可梦有多强吧！$"

Route116_Text_JaniceDefeat:
	.string "你比我强了一大截……$"

Route116_Text_JanicePostBattle:
	.string "我觉得，同时拥有强大和可爱的\n宝可梦才是最完美的。$"

Route116_Text_JerryIntro:
	.string "我们从训练家学校\n学到了不少东西。\p我想通过实战来确认一下！$"

Route116_Text_JerryDefeat:
	.string "学习太松懈……\n就是我输的原因。$"

Route116_Text_JerryPostBattle:
	.string "我得去训练家学校\n重修一些课程。\l不然杜娟会生气的。$"

Route116_Text_JerryRegister1:
	.string "我从训练家学校学到\n宝可导航可以登记训练家。\p我不是太明白这是什么意思，\n可以让我试一下吗？$"

Route116_Text_JerryRegister2:
	.string "我从训练家学校学到\n宝可导航可以登记训练家。\p我不是太明白这是什么意思，\n可以让我试一下吗？$"

Route116_Text_JerryRematchIntro:
	.string "那次之后我就很认真地在\n训练家学校学习了。\l我不会再像上次那样输掉了。$"

Route116_Text_JerryRematchDefeat:
	.string "啊？\n我都那么努力学习了。$"

Route116_Text_JerryPostRematch:
	.string "我会在训练家学校\n重新学习一些课程。\l不然杜娟会生气的。$"

Route116_Text_KarenIntro:
	.string "我在学校学习，\n在回家的路上也学习！$"

Route116_Text_KarenDefeat:
	.string "震惊——我输了？$"

Route116_Text_KarenPostBattle:
	.string "噢，我永远也不可能成为像\n杜娟那样优雅的训练家！$"

Route116_Text_KarenRegister1:
	.string "啊！那不是宝可导航吗？\n我也有一个，来登记吧！$"

Route116_Text_KarenRegister2:
	.string "啊！那不是宝可导航吗？\n我也有一个，来登记吧！$"

Route116_Text_KarenRematchIntro:
	.string "自从遇到你以后我学到了很多啊。\n你应该来看看我的成就！$"

Route116_Text_KarenRematchDefeat:
	.string "我震惊了。\n我又输了？$"

Route116_Text_KarenPostRematch:
	.string "你已经打败了杜娟？\n这么说我现在不是你的对手。$"

Route116_Text_SarahIntro:
	.string "你知道吗？我从来没有在\n任何事情上被人打败过。$"

Route116_Text_SarahDefeat:
	.string "哦，天哪。\n这对于我来说真是前所未有的经历。$"

Route116_Text_SarahPostBattle:
	.string "我奢华的生活为我提供了\n很多我想要的东西。\p但是，在宝可梦面前，\n我的金钱毫无意义。$"

Route116_Text_DawsonIntro:
	.string "当你在观察宝可梦那华丽的外表的\n时候，他们的美丽就会让你无力！$"

Route116_Text_DawsonDefeat:
	.string "哦宝贝，不应该是这样啊！$"

Route116_Text_DawsonPostBattle:
	.string "哦不不不不不！\n你把我的宝可梦的毛发弄乱了！\l你还弄乱了我的发型！\l我要去找我的时装设计师了！$"

Route116_Text_DevanIntro:
	.string "我们会让你兴奋不已！$"

Route116_Text_DevanDefeat:
	.string "啊啊啊！\n不对战了！$"

Route116_Text_DevanPostBattle:
	.string "我应该尝试不同属性的宝可梦，\n这就是我应该做的。$"

Route116_Text_JohnsonIntro:
	.string "看起来好像是条死路，真无聊。\n我们能来场对战吗？$"

Route116_Text_JohnsonDefeat:
	.string "尽管我输了，但是还是很有趣啊。$"

Route116_Text_JohnsonPostBattle:
	.string "你想留下来陪我吗？$"

Route117_Text_IsaacIntro:
	.string "听着，你能和我培育的宝可梦\n来场对战吗？$"

Route117_Text_IsaacDefeat:
	.string "你把宝可梦培育得真好……$"

Route117_Text_IsaacPostBattle:
	.string "宝可梦的意义并不是只是强大。\p钻研每一只的独特之处\n也是享受宝可梦的一种方式。$"

Route117_Text_IsaacRegister:
	.string "我还要再继续训练。\n你还会再来吗？$"

Route117_Text_IsaacRematchIntro:
	.string "我培育的宝可梦看起来很不错，\n就像以前一样。$"

Route117_Text_IsaacRematchDefeat:
	.string "你知道怎么样才是正确的培育方法。\n说不定你有开培育屋的本领……$"

Route117_Text_IsaacPostRematch:
	.string "你的宝可梦长得真不错！\n你应让他们去参加华丽大赛。$"

Route117_Text_LydiaIntro:
	.string "请让我看看\n你培育宝可梦的方式是否合适。$"

Route117_Text_LydiaDefeat:
	.string "是的，他们看起来都很棒。$"

Route117_Text_LydiaPostBattle:
	.string "试着多根据宝可梦不同的\n性格特征去培育他们。$"

Route117_Text_LydiaRegister:
	.string "很高兴遇到了你这样优秀的训练家。\n希望下次还能见到你。$"

Route117_Text_LydiaRematchIntro:
	.string "请允许我再看看\n你的宝可梦培育得怎么样。$"

Route117_Text_LydiaRematchDefeat:
	.string "是的，他们看起来都非常棒。$"

Route117_Text_LydiaPostRematch:
	.string "宝可梦对宝可方块的喜好各有不同，\n这和他们的性格有关。$"

Route117_Text_DylanIntro:
	.string "虽然我还在训练中，\n但是我们还是来一场对战吧！$"

Route117_Text_DylanDefeat:
	.string "我没力气了！$"

Route117_Text_DylanPostBattle:
	.string "我好像搞砸了……\p我可能在对战的时候\n掉到最后了……$"

Route117_Text_DylanRegister:
	.string "宝可梦要变得更强壮不是吗？\n我想让你帮我训练！$"

Route117_Text_DylanRematchIntro:
	.string "虽然我还在比赛中，\n但是我遥遥领先。\l让我们速战速决吧！$"

Route117_Text_DylanRematchDefeat:
	.string "我又没力气了！$"

Route117_Text_DylanPostRematch:
	.string "我非常的擅长游泳和自行车，\n但是我在宝可梦方面\l还没多大信心。$"

Route117_Text_MariaIntro:
	.string "我和我的宝可梦一起训练，\n所以现在对于我的速度我很有信心了。$"

Route117_Text_MariaDefeat:
	.string "我想我还需要多加练习。$"

Route117_Text_MariaPostBattle:
	.string "只有当你一直坚持训练的时候\n才会起到作用。\p我要恢复训练了！\n明天起！$"

Route117_Text_MariaRegister:
	.string "你看起来已经训练得很棒了……\n如果可以的话我想以后再对战！$"

Route117_Text_MariaRematchIntro:
	.string "你有一直坚持训练吗？\n我当然有！\l让我给你看看证据！$"

Route117_Text_MariaRematchDefeat:
	.string "我想我还需要多加练习。$"

Route117_Text_MariaPostRematch:
	.string "明天我就恢复训练了！\n我们下次再对战吧！$"

Route117_Text_DerekIntro:
	.string "从前的捕虫少年！\n现在的昆虫狂！\p但我对宝可梦的爱\n始终如一！$"

Route117_Text_DerekDefeat:
	.string "我的无力也始终如一……$"

Route117_Text_DerekPostBattle:
	.string "我一直做自己喜欢的事，\n现在他们叫我昆虫狂……\p我也算是虫属性宝可梦专家，\n所以他们叫我昆虫狂\l也理所当然。$"

Route117_Text_AnnaIntro:
	.string "美穗：我和我的漂亮的初中\n学妹。我一定会做好的！$"

Route117_Text_AnnaDefeat:
	.string "美穗：我和我的漂亮的初中\n学妹！我们会胜利的！$"

Route117_Text_AnnaPostBattle:
	.string "美穗：你的宝可梦也有着\n很不错的配合。\p可以说仅次于我们！$"

Route117_Text_AnnaAndMegRegister:
	.string "美穗：我们不能就这么认输！\n你还会回来的，对吧？$"

Route117_Text_AnnaNotEnoughMons:
	.string "美穗：如果想和我们对战的话，\n就带上2只宝可梦吧。$"

Route117_Text_MegIntro:
	.string "里子：我将和我的高中学姐\n一起和你对战的！$"

Route117_Text_MegDefeat:
	.string "里子：哦不！\n真对不起，美穗！我连累了你……$"

Route117_Text_MegPostBattle:
	.string "里子：我连累美穗了……\n如果不是我的话她会赢的！$"

Route117_Text_MegNotEnoughMons:
	.string "里子：你只有1只宝可梦吗？\n那么我们就不能和你对战了。\p我们需要的是2对2的对战。$"

Route117_Text_AnnaRematchIntro:
	.string "美穗：我不能在我的同伴\n面前输不是吗？$"

Route117_Text_AnnaRematchDefeat:
	.string "美穗：我没能进入状态。$"

Route117_Text_AnnaPostRematch:
	.string "美穗：你的宝可梦也有着\n很不错的配合。\p可以说仅次于我们！$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "美穗：如果想和我们对战的话，\n就带上2只宝可梦吧。$"

Route117_Text_MegRematchIntro:
	.string "里子：我将会带上我的高中学姐\n一起和你对战的！$"

Route117_Text_MegRematchDefeat:
	.string "里子：太强了！$"

Route117_Text_MegPostRematch:
	.string "里子：我和我的高中学姐一起\n对战但是我们还是输了……\p太让人沮丧了……$"

Route117_Text_MegRematchNotEnoughMons:
	.string "里子：你只有1只宝可梦吗？\n那么我们就不能和你对战了。\p我们需要的是2对2的对战。$"

Route117_Text_MelinaIntro:
	.string "那不是很好吗？一边看美丽的花\n一边对战？$"

Route117_Text_MelinaDefeat:
	.string "太难忘了！$"

Route117_Text_MelinaPostBattle:
	.string "看花的时候进行慢跑\n不是很有趣吗？$"

Route117_Text_BrandiIntro:
	.string "让我给你看看隐藏在深处的\n超能力宝可梦的力量吧！$"

Route117_Text_BrandiDefeat:
	.string "太令人吃惊了！$"

Route117_Text_BrandiPostBattle:
	.string "超能力宝可梦是很复杂的，\n你应该试着捕捉几只。$"

Route117_Text_AishaIntro:
	.string "集中精神取得胜利。\n这就是我的战斗理念！$"

Route117_Text_AishaDefeat:
	.string "我不会在我的失败上\n浪费力气的——我要加紧训练了。$"

Route117_Text_AishaPostBattle:
	.string "我觉得越害怕失败，\n就越容易失败。$"

Route118_Text_RoseIntro:
	.string "花香好像有一种神奇的力量，\n它能净化我们的身心。$"

Route118_Text_RoseDefeat:
	.string "哦，天哪。\n我好像又输了。$"

Route118_Text_RosePostBattle:
	.string "花朵……宝可梦……\n我喜欢任何好闻的气味。\p臭的话……\n就算了。$"

Route118_Text_RoseRegister:
	.string "闻……这个气味不是导航器吗！\n我们要互相登记！$"

Route118_Text_RoseRematchIntro:
	.string "你被甜甜香气吸引过来了吗？$"

Route118_Text_RoseRematchDefeat:
	.string "香气的力量……\n似乎没什么作用。$"

Route118_Text_RosePostRematch:
	.string "如果你使用甜甜香气，\n就会马上遇到宝可梦。$"

Route118_Text_PerryIntro:
	.string "鸟类宝可梦能够优雅地\n在天空中飞翔……他们是最棒的！$"

Route118_Text_PerryDefeat:
	.string "呃……\n我坠落了……$"

Route118_Text_PerryPostBattle:
	.string "你的宝可梦真棒。\n我会把我的训练得更好的。$"

Route118_Text_ChesterIntro:
	.string "飞吧！\n我的鸟类宝可梦！$"

Route118_Text_ChesterDefeat:
	.string "它们的确飞走了……$"

Route118_Text_ChesterPostBattle:
	.string "如果它们变得更强大的话，\n就能够自由地飞翔了……$"

Route118_Text_BarnyIntro:
	.string "我是垂钓者但也是训练家。\n我的宝可梦都是我自己捉的。$"

Route118_Text_BarnyDefeat:
	.string "我原以为我的训练\n已经足够了……$"

Route118_Text_BarnyPostBattle:
	.string "当我在钓鱼的时候对战\n当然会输了……\p我会半途而废吗？$"

Route118_Text_WadeIntro:
	.string "对于一个垂钓者，装备是关键。\p但是对于训练家来说最重要的\n就是和宝可梦之间的沟通！$"

Route118_Text_WadeDefeat:
	.string "我被打败了？$"

Route118_Text_WadePostBattle:
	.string "仔细想想，钓鱼不就是垂钓者\n和宝可梦之间的战斗吗？$"

Route118_Text_DaltonIntro:
	.string "让我的音乐震撼你的灵魂吧！$"

Route118_Text_DaltonDefeat:
	.string "啦啦啦啦……$"

Route118_Text_DaltonPostBattle:
	.string "一把电吉他并非\n只能制造噪音……\p它也可以弹奏出如此\n这种振奋人心的乐曲……$"

Route118_Text_DaltonRegister:
	.string "我创作出更好的乐曲时，\n你一定要来听听看，好吗？$"

Route118_Text_DaltonRematchIntro:
	.string "来自我的宝可梦和我的旋律……\n让我们把它传递到你的心灵吧。$"

Route118_Text_DaltonRematchDefeat:
	.string "啦啦啦啦……$"

Route118_Text_DaltonPostRematch:
	.string "我演奏时，我的感情便会随着我的\n电吉他传达给你……$"

Route118_Text_DeandreIntro:
	.string "冲，冲，冲！\n宝可梦1、2、3！$"

Route118_Text_DeandreDefeat:
	.string "来吧，宝可梦！准备好了吗？\n宝可梦1、2、3？！$"

Route118_Text_DeandrePostBattle:
	.string "我有一支宝可梦战队，\n是不是很酷呢？\p你可以模仿我——我不介意！$"

Route119_Text_BrentIntro:
	.string "我们是模仿者协会的！\n你做什么，我们就模仿什么！$"

Route119_Text_BrentDefeat:
	.string "可恶！\n我输了！$"

Route119_Text_BrentPostBattle:
	.string "模仿的乐趣在哪里？\p嘿嘿嘿……\n你是永远也不会明白的……$"

Route119_Text_DonaldIntro:
	.string "我们终于遇上了！\n我要让你见识一下我的虫宝可梦！$"

Route119_Text_DonaldDefeat:
	.string "真希望我们从没相遇过……$"

Route119_Text_DonaldPostBattle:
	.string "我想再模仿你一些。\n你可以快点动起来吗？$"

Route119_Text_TaylorIntro:
	.string "如果你向前走，我们也会向前走。\p如果你向右转，我们也会跟着转……$"

Route119_Text_TaylorDefeat:
	.string "但如果你赢了，我就输了……$"

Route119_Text_TaylorPostBattle:
	.string "我没办法模仿你赢得对战。\n这根本不可能……\l这真让我觉得懊恼……$"

Route119_Text_DougIntro:
	.string "啊，你终于抓到我了！\n还是说你本来是要躲着我的？$"

Route119_Text_DougDefeat:
	.string "啊，那是一场精彩的对战！$"

Route119_Text_DougPostBattle:
	.string "我们是模仿者协会！\n希望你们喜欢我们的表演。$"

Route119_Text_GregIntro:
	.string "你不知道我是谁吧？\p我也不认识你。\n所以，我们来对战吧！$"

Route119_Text_GregDefeat:
	.string "你真的很强！$"

Route119_Text_GregPostBattle:
	.string "在你离开之前，我们一直会\n模仿你的每个动作。$"

Route119_Text_KentIntro:
	.string "模仿者协会是许多\n喜欢模仿的人组成的。\p我们相遇的瞬间，对战就开始了！$"

Route119_Text_KentDefeat:
	.string "我放弃！$"

Route119_Text_KentPostBattle:
	.string "你不加入我们模仿者协会吗？$"

Route119_Text_JacksonIntro:
	.string "谁有生存的知识和技巧？\n宝可梦巡护员！$"

Route119_Text_JacksonDefeat:
	.string "我没有足够的宝可梦\n知识……$"

Route119_Text_JacksonPostBattle:
	.string "脱离文明的束缚，\n唤醒内心的野性！\p那就是我们的理想。$"

Route119_Text_JacksonRegister:
	.string "希望你不要嘲笑我知识匮乏，\n再跟我对战一次吧。$"

Route119_Text_JacksonRematchIntro:
	.string "我要通过跟宝可梦在一起\n再重拾我内心的野性。$"

Route119_Text_JacksonRematchDefeat:
	.string "你还是很强！$"

Route119_Text_JacksonPostRematch:
	.string "相信你的宝可梦。\n相信你自己。\p路就在你前方。$"

Route119_Text_CatherineIntro:
	.string "哦，看看你。\p对于在冒险的人来说，\n你还真是轻装旅行呢。$"

Route119_Text_CatherineDefeat:
	.string "当你还没准备好的时候，\n意外就会发生！$"

Route119_Text_CatherinePostBattle:
	.string "虽然是轻装而行，\n你却已经拥有了所需的一切。\p无论是精神上还是身体上，\n你都已经熟练掌握了许多东西。$"

Route119_Text_CatherineRegister:
	.string "你有宝可导航吗？\n对于任何一个训练家来说，\l它都是必须的工具。\p哦，你有一个！\n那么我们互相登记吧！$"

Route119_Text_CatherineRematchIntro:
	.string "你跟你的宝可梦\n的旅程进行得如何？$"

Route119_Text_CatherineRematchDefeat:
	.string "我好像还缺了点什么……$"

Route119_Text_CatherinePostRematch:
	.string "作为一个训练家，你依赖你的宝可梦，\n你的宝可梦也同样依赖你。$"

Route119_Text_HughIntro:
	.string "辽阔的天空有着未知的希望！\p没有什么比得上\n飞行的纯粹乐趣！$"

Route119_Text_HughDefeat:
	.string "坠落了！$"

Route119_Text_HughPostBattle:
	.string "我的鸟类宝可梦\n让我的飞行梦想成为了现实！$"

Route119_Text_PhilIntro:
	.string "我会让你看看我真正的潜力，\n还有我的鸟类宝可梦！$"

Route119_Text_PhilDefeat:
	.string "我们缺乏潜力……$"

Route119_Text_PhilPostBattle:
	.string "从我小时候开始，我就一直\n很羡慕鸟类宝可梦……$"

Route119_Text_YasuIntro:
	.string "躲藏在阴影里，生活在黑暗中……\n这就是我的命运。\p我出现就是要挑战你！$"

Route119_Text_YasuDefeat:
	.string "我认输！$"

Route119_Text_YasuPostBattle:
	.string "那些在对战中的失败者只能\n静静地撤回到阴影里。\l那，也是命运……$"

Route119_Text_TakashiIntro:
	.string "如果你不提高警惕，\n你迟早会付出代价！$"

Route119_Text_TakashiDefeat:
	.string "你真是出奇地强啊！$"

Route119_Text_TakashiPostBattle:
	.string "我的偷袭失败了……$"

Route119_Text_HideoIntro:
	.string "想藏一棵树，就把它放到森林里！$"

Route119_Text_HideoDefeat:
	.string "我愿承认你的优越。$"

Route119_Text_HideoPostBattle:
	.string "想隐藏一棵树，就把它放到森林里！\n想隐藏宝可梦，就用宝可梦！\p这并没什么深刻的含义。$"

Route119_Text_ChrisIntro:
	.string "你跟我说话……\n也就是说你想挑战我！\p好啊！我也想试试在冲浪时\n捕捉到的宝可梦！$"

Route119_Text_ChrisDefeat:
	.string "我还是不知道胜利\n的诀窍是什么。$"

Route119_Text_ChrisPostBattle:
	.string "骑上我的宝可梦去冲浪……\p然后在它的背上钓鱼……\p那真是难以形容的美妙时刻！$"

Route119_Text_FabianIntro:
	.string "用强烈的和弦来打我吧！\n胜利是属于我的！\l我们闪光的时候到了，哦耶！$"

Route119_Text_FabianDefeat:
	.string "你让我明白了谁才是老大！\n我们不得不接受失败。哦，不！$"

Route119_Text_FabianPostBattle:
	.string "再用一波强烈的和弦来打我吧！\n别管我！\l你要用胜利来偿还！$"

Route119_Text_DaytonIntro:
	.string "吼吼吼！\n我喜欢小训练家！\l来一场精彩的对决吧！$"

Route119_Text_DaytonDefeat:
	.string "你实在太厉害了！\n吼吼吼！$"

Route119_Text_DaytonPostBattle:
	.string "吼吼吼！\n我会努力像你这样的\l小训练家一样拥有激情和活力的！$"

Route119_Text_RachelIntro:
	.string "无论什么时候，在哪里，\n我都会带上我的小阳伞。$"

Route119_Text_RachelDefeat:
	.string "哦，但是……\n那不公平。$"

Route119_Text_RachelPostBattle:
	.string "你问我的阳伞会不会很重？\n你包里的垃圾比我带过的\l所有东西都要重。$"

Route120_Text_ColinIntro:
	.string "你有什么招式可以打到\n飞着的宝可梦？$"

Route120_Text_ColinDefeat:
	.string "你的实力远在我之上！$"

Route120_Text_ColinPostBattle:
	.string "飞翔这招真方便啊，\n你觉得呢？\p当宝可梦飞起来时，\n几乎没什么什么可以打中它。$"

Route120_Text_RobertIntro:
	.string "我的宝可梦很强的！\n你的呢？$"

Route120_Text_RobertDefeat:
	.string "你的宝可梦更强……$"

Route120_Text_RobertPostBattle:
	.string "你可以信赖一只\n稳定成长的宝可梦。$"

Route120_Text_RobertRegister:
	.string "你会变得更强的。\n我想把你登记到我的宝可导航上！$"

Route120_Text_RobertRematchIntro:
	.string "你可以信赖一只\n稳定成长的宝可梦。$"

Route120_Text_RobertRematchDefeat:
	.string "你的宝可梦真的很强。$"

Route120_Text_RobertPostRematch:
	.string "我的宝可梦越来越强了。\n我也要变得更强才行。$"

Route120_Text_LorenzoIntro:
	.string "我要检查一下你的宝可梦，\n看看它们适不适合在户外活动。$"

Route120_Text_LorenzoDefeat:
	.string "有那么强的宝可梦，\n你已经完全不需要救援了！$"

Route120_Text_LorenzoPostBattle:
	.string "跟宝可梦一起到所有\n心里想去的地方……\l那就是作为一个训练家的乐趣。$"

Route120_Text_JennaIntro:
	.string "你的身体状况如何？\n如果状况不好，\l那你很可能会陷入危机。$"

Route120_Text_JennaDefeat:
	.string "我完全身体状况很好，但……$"

Route120_Text_JennaPostBattle:
	.string "健身训练是我每天的习惯。\n我一直跟我的宝可梦一起跑步。$"

Route120_Text_JeffreyIntro:
	.string "…… …… ……\n…… …… ……\l想对战吗？$"

Route120_Text_JeffreyDefeat:
	.string "我输了……$"

Route120_Text_JeffreyPostBattle:
	.string "…… …… ……\n…… …… ……\l我会更努力的……$"

Route120_Text_JeffreyRegister:
	.string "…… …… ……\n…… …… ……\l你有宝可导航吗……？$"

Route120_Text_JeffreyRematchIntro:
	.string "…… …… ……\n…… …… ……\l想再次对战吗？$"

Route120_Text_JeffreyRematchDefeat:
	.string "…… …… ……\n我又输了……$"

Route120_Text_JeffreyPostRematch:
	.string "…… …… ……\n…… …… ……\l我会更努力的……\l和我珍贵的虫宝可梦一起……$"

Route120_Text_JenniferIntro:
	.string "宝可梦有许多特性。\n如果你想成为一流的\l训练家，就好好学吧。$"

Route120_Text_JenniferDefeat:
	.string "你很明显是在思考。$"

Route120_Text_JenniferPostBattle:
	.string "宝可梦的特性\n会改变战斗的风格。$"

Route120_Text_ChipIntro:
	.string "你是谁？\p你是不是在寻找传说中\n可能存在的一个\l古代遗迹？$"

Route120_Text_ChipDefeat:
	.string "多可耻的挫败啊……$"

Route120_Text_ChipPostBattle:
	.string "那个巨大的岩石……\n我很确信那里面就是古代遗迹。\l但我没发现有入口。$"

Route120_Text_ClarissaIntro:
	.string "为什么我要带着这把阳伞？\p如果你赢得了我我就告诉你。$"

Route120_Text_ClarissaDefeat:
	.string "阳伞是没办法抵抗宝可梦\n的攻击的……$"

Route120_Text_ClarissaPostBattle:
	.string "我觉得强烈的阳光对我的\n宝可梦是没好处的。\l所以我用阳伞来帮它们遮挡。$"

Route120_Text_AngelicaIntro:
	.string "我，宝可梦，和我的阳伞……\p缺少其中任何一个，\n那完美的画面就毁了。$"

Route120_Text_AngelicaDefeat:
	.string "你已经完全地毁了我的完美……$"

Route120_Text_AngelicaPostBattle:
	.string "阳伞一点也不适合你。\p像这样的东西只会成为\n你的累赘。$"

Route120_Text_KeigoIntro:
	.string "我要借鉴宝可梦的动作，\n创造出新的忍术。$"

Route120_Text_KeigoDefeat:
	.string "创造新的忍术只不过\n是一个遥远的梦想……$"

Route120_Text_KeigoPostBattle:
	.string "也许我该找个忍者老师\n学习一下。$"

Route120_Text_RileyIntro:
	.string "我们忍者是用伪装斗篷\n来隐藏自己的。\l我肯定你不知道我在哪里！$"

Route120_Text_RileyDefeat:
	.string "我输了！\n我应该伪装我的羞愧！$"

Route120_Text_RileyPostBattle:
	.string "我们的伪装斗篷都是\n手工做的。$"

Route120_Text_CallieIntro:
	.string "你要不是小心一点的话，\n你会受伤的！$"

Route120_Text_CallieDefeat:
	.string "哎哟！\n受伤的是我。$"

Route120_Text_CalliePostBattle:
	.string "我想知道……我应该让我的宝可梦\n进化吗？他们现在都很可爱啊。$"

Route120_Text_LeonelIntro:
	.string "你的宝可梦同伴……\n你还有其他属性的吗？$"

Route120_Text_LeonelDefeat:
	.string "我知道你的策略已经奏效了！$"

Route120_Text_LeonelPostBattle:
	.string "你跟你最喜欢的宝可梦一起战斗能有\n如此实力，实在是太了不起了。$"

Route121_Text_VanessaIntro:
	.string "你能跟我这可爱漂亮的\n宝可梦一起玩玩吗？$"

Route121_Text_VanessaDefeat:
	.string "我不是这个意思！$"

Route121_Text_VanessaPostBattle:
	.string "我要去参加水静市的一个华丽大赛。\p我的宝可梦要横扫大师级\n应该是没问题的。$"

Route121_Text_WalterIntro:
	.string "我已经跟我的宝可梦一起\n去遍了世界的各个角落。\p我对我的能力还是有点信心的。$"

Route121_Text_WalterDefeat:
	.string "啊，做的不错。$"

Route121_Text_WalterPostBattle:
	.string "我想再跟我的宝可梦\n环游世界一次。$"

Route121_Text_WalterRegister:
	.string "你的宝可梦的实力非凡。\n请允许我登记下你，以作纪念。$"

Route121_Text_WalterRematchIntro:
	.string "我已经跟我的宝可梦一起\n去遍了世界的各个角落。\p我对我的能力还是有点信心的。$"

Route121_Text_WalterRematchDefeat:
	.string "啊，做的不错。$"

Route121_Text_WalterPostRematch:
	.string "你和你的宝可梦……\p你们合在一起的力量\n即便在外国也是非常强的。$"

Route121_Text_TammyIntro:
	.string "世界上有许多\n我们不知道的力量……$"

Route121_Text_TammyDefeat:
	.string "我输了……$"

Route121_Text_TammyPostBattle:
	.string "送神山……\n那里有一股神秘的力量\l在运作着……$"

Route121_Text_KateIntro:
	.string "真奈：只要我们在一起，就没有什么\n可怕的！我们会证明我们有多强！$"

Route121_Text_KateDefeat:
	.string "真奈：我竟然在我的学妹\n搭档面前输了……$"

Route121_Text_KatePostBattle:
	.string "真奈：每当有人想依赖我的时候，\n我总是很想在他们面前表现得\l很酷……$"

Route121_Text_KateNotEnoughMons:
	.string "真奈：如果你只有1只宝可梦，\n那我们不能跟你对战。\p那样太欺负人了。$"

Route121_Text_JoyIntro:
	.string "由依：只要我们在一起，就没有什么\n可怕的！我们会证明我们有多强！$"

Route121_Text_JoyDefeat:
	.string "由依：真奈，请原谅我！$"

Route121_Text_JoyPostBattle:
	.string "由依：呵呵，我要再跟我的\n学姐搭档真奈多练习联系了。$"

Route121_Text_JoyNotEnoughMons:
	.string "由依：如果你想挑战我们，\n你至少需要2只宝可梦！$"

Route121_Text_JessicaIntro:
	.string "站住！好好看看我珍贵的\n宝可梦！$"

Route121_Text_JessicaDefeat:
	.string "噢，你怎么……\n别这么认真！$"

Route121_Text_JessicaPostBattle:
	.string "也许我应该在狩猎地带\n多捕捉几只宝可梦。$"

Route121_Text_JessicaRegister:
	.string "这次是我小看你了！\n但下次绝不会是这样了！$"

Route121_Text_JessicaRematchIntro:
	.string "我宝贵的宝可梦成长了！\n仔细看看！$"

Route121_Text_JessicaRematchDefeat:
	.string "噢，你怎么……\n你还是太认真了！$"

Route121_Text_JessicaPostRematch:
	.string "也许我应该在狩猎地带\n多捕捉几只宝可梦。$"

Route121_Text_CristinIntro:
	.string "我有个习惯，\n就是每天打败5个训练家。\l猜到了吗？你就是第5个！$"

Route121_Text_CristinDefeat:
	.string "不！\n你太可怕了！$"

Route121_Text_CristinPostBattle:
	.string "我从没想过会这么简单就输了……\n下次我一定会赢的！$"

Route121_Text_CristinRegister:
	.string "简直是奇耻大辱！\n我不会忘记你的……\l把你的宝可导航交出来！$"

Route121_Text_CristinRematchIntro:
	.string "我有了一个新习惯，\n就是每天打败10个训练家。\l猜到了吗？你就是第10个！$"

Route121_Text_CristinRematchDefeat:
	.string "等一下！那太卑鄙了吧！\n我要求重新对战！$"

Route121_Text_CristinPostRematch:
	.string "一个我无法打败的对手……\n泣……\l真难以置信会这样……$"

Route121_Text_CaleIntro:
	.string "你没看到我现在\n拿着这么多东西吗？\p即便这样，你也坚持\n要跟我对战？$"

Route121_Text_CaleDefeat:
	.string "当然是我输了！\n毕竟我两只手都在拿东西！$"

Route121_Text_CalePostBattle:
	.string "我在水静百货买了太多东西了。\p那家店就在这条路前面。\n真想有一个像你的那样的包包。$"

Route121_Text_MylesIntro:
	.string "我最喜欢的事情莫过于\n看看别人的宝可梦了！$"

Route121_Text_MylesDefeat:
	.string "超级棒！$"

Route121_Text_MylesPostBattle:
	.string "你的宝可梦太棒了！\n你是怎么培育它们的？$"

Route121_Text_PatIntro:
	.string "真想让每个人都看看\n我培育的宝可梦！$"

Route121_Text_PatDefeat:
	.string "哇！\n太妙了！$"

Route121_Text_PatPostBattle:
	.string "我对每一只宝可梦都给予了同等\n的爱和关怀。不会特别偏爱一只。$"

Route121_Text_MarcelIntro:
	.string "我的宝可梦还没有尝过失败的滋味！\n它们再赢一次后，我就让它们去参加\l华丽大赛。$"

Route121_Text_MarcelDefeat:
	.string "发生什么事了？$"

Route121_Text_MarcelPostBattle:
	.string "也许在进入华丽大赛之前\n我该再多训练一下它们。$"

Route123_Text_WendyIntro:
	.string "想知道你有多强？\n我来帮你测试吧！$"

Route123_Text_WendyDefeat:
	.string "你以优异的成绩通过了测试！$"

Route123_Text_WendyPostBattle:
	.string "即便跟我比起来……\n你的实力也还是太强了！$"

Route123_Text_BraxtonIntro:
	.string "你好像收集了很多\n道馆徽章嘛。\p让我看看你是不是真的有\n和那些徽章相称的实力吧！$"

Route123_Text_BraxtonDefeat:
	.string "哦，你的确是有实力。$"

Route123_Text_BraxtonPostBattle:
	.string "在那样的对战中获得徽章\n是你的骄傲。$"

Route123_Text_VioletIntro:
	.string "人们说，美好的时光总是\n充满着美好的香气。$"

Route123_Text_VioletDefeat:
	.string "哦……\n我闻到了痛苦的苦涩气味……$"

Route123_Text_VioletPostBattle:
	.string "树果名人的花园充满了\n振奋人心的香气。$"

Route123_Text_CameronIntro:
	.string "要做超能力者需要有意志力。\p我的意志力已经不会输给任何人了。\n这让我十分强大！$"

Route123_Text_CameronDefeat:
	.string "我很难过……$"

Route123_Text_CameronPostBattle:
	.string "要做超能力者需要有意志力。\n我以为我不会输给你的……$"

Route123_Text_CameronRegister:
	.string "我感觉到了！\n我们会再度对战的！\l虽然我没办法保证我会赢……\p把你的宝可导航拿出来吧。$"

Route123_Text_CameronRematchIntro:
	.string "我已经向自己保证过不会再失败了。\n这让我变得更强了！$"

Route123_Text_CameronRematchDefeat:
	.string "我好难过……$"

Route123_Text_CameronPostRematch:
	.string "我应该到送神山训练……\n这样下去我永远赢不了你。$"

Route123_Text_JackiIntro:
	.string "如果你的宝可梦获得了超能力，\n不要太高兴。\p要让它们派上用场，\n你还得精心培育。$"

Route123_Text_JackiDefeat:
	.string "一败涂地！$"

Route123_Text_JackiPostBattle:
	.string "我们都有超能力。\n我们只是忘了要怎么使用。$"

Route123_Text_JackiRegister:
	.string "我想再次面对你。\n你愿意接受吗？$"

Route123_Text_JackiRematchIntro:
	.string "你已经唤醒你心中的\n超能力了吗？$"

Route123_Text_JackiRematchDefeat:
	.string "令人震惊！$"

Route123_Text_JackiPostRematch:
	.string "你相信宝可梦的力量……\n可能也是一种超能力。$"

Route123_Text_MiuIntro:
	.string "美雨：你好，训练家。\n希望你的宝可梦输了之后不会哭泣。$"

Route123_Text_MiuDefeat:
	.string "美雨：呃，我们输了。$"

Route123_Text_MiuPostBattle:
	.string "美雨：训练家，你的宝可梦之所以强\n是因为你们是朋友。$"

Route123_Text_MiuNotEnoughMons:
	.string "美雨：如果你没有2只以上的\n宝可梦，那就没什么对战的意思了。$"

Route123_Text_YukiIntro:
	.string "雪：好的！\n我们会打败那个训练家的宝可梦的！$"

Route123_Text_YukiDefeat:
	.string "雪：呃，我们输了。$"

Route123_Text_YukiPostBattle:
	.string "雪：你怎么会这么强？\n我们以前从没输过。$"

Route123_Text_YukiNotEnoughMons:
	.string "雪：如果你没有2只以上的\n宝可梦，那就没什么对战的意思了。$"

Route123_Text_KindraIntro:
	.string "送神山……\n宝可梦的灵魂休眠的地方……\l你的宝可梦也会休眠吗？$"

Route123_Text_KindraDefeat:
	.string "活力十足……$"

Route123_Text_KindraPostBattle:
	.string "送神山……\n宝可梦的灵魂休眠的地方……\l它一定充满着安抚灵魂的力量……$"

Route123_Text_FernandoIntro:
	.string "当我奏起这首曲子的时候，\n你的希望就全部落空了！$"

Route123_Text_FernandoDefeat:
	.string "喂，等一下！\n我才刚开始前奏！$"

Route123_Text_FernandoPostBattle:
	.string "你很厉害。\n我要为你写一首曲子。$"

Route123_Text_FernandoRegister:
	.string "下一次，\n你可以听完整首曲子吗？$"

Route123_Text_FernandoRematchIntro:
	.string "终于到了这一天了。\n在我唱完我的歌之前，\l我会打败你的！$"

Route123_Text_FernandoRematchDefeat:
	.string "喂，等一下！\n我还没到副歌呢！$"

Route123_Text_FernandoPostRematch:
	.string "我以为你会被我的曲子迷住，\n然后输掉的。$"

Route123_Text_DavisIntro:
	.string "这就是我超棒的虫宝可梦！\n我大哥帮我捕捉到的。$"

Route123_Text_DavisDefeat:
	.string "哇啊！\n你这坏蛋！$"

Route123_Text_DavisPostBattle:
	.string "别告诉我哥哥我输了。\n你要把它当做秘密！$"

Route123_Text_JazmynIntro:
	.string "打败一个明显很强的人之后，\n我的信心就会爆涨。$"

Route123_Text_JazmynDefeat:
	.string "我的自信就这么没了……$"

Route123_Text_JazmynPostBattle:
	.string "人们都说\n人不可貌相。\p但外貌往往不会说谎……$"

Route123_Text_FrederickIntro:
	.string "你好啊，小朋友。\n能给我点时间吗？$"

Route123_Text_FrederickDefeat:
	.string "啊，真是个有能力的小朋友。\n我来给你一点奖励吧。$"

Route123_Text_FrederickPostBattle:
	.string "奖励？\n奖金还不够吗？$"

Route123_Text_AlbertoIntro:
	.string "我要告诉你，我已经被\n鸟类宝可梦深深迷住了！\p鸟类宝可梦太酷了！\n它们是最棒的！$"

Route123_Text_AlbertoDefeat:
	.string "即便被打败了，\n鸟类宝可梦还是很酷！$"

Route123_Text_AlbertoPostBattle:
	.string "我一直在收集鸟类宝可梦\n在战斗中散落的羽毛。\p我想用鸟类宝可梦\n的羽毛来用一顶帽子。$"

Route123_Text_EdIntro:
	.string "附近没有训练家的时候，\n我就让我的宝可梦各自对打。\l然后我就在一边看着。$"

Route123_Text_EdDefeat:
	.string "我有点喜欢你的宝可梦。$"

Route123_Text_EdPostBattle:
	.string "呵呵，我正在偷学你的战斗技巧。\n我想它们会让我有所提高的。$"

Route123_Text_JonasIntro:
	.string "我设了个埋伏，\n有个训练家落入了陷阱！$"

Route123_Text_JonasDefeat:
	.string "如果你不失败，\n那我扮忍者还有什么意思？$"

Route123_Text_JonasPostBattle:
	.string "下次我一定会埋伏一个\n看起来比较弱的训练家。$"

Route123_Text_KayleyIntro:
	.string "我刚刚买了这把阳伞。\n我的可爱也能上升3分之1了吧。$"

Route123_Text_KayleyDefeat:
	.string "你比我厉害5倍！$"

Route123_Text_KayleyPostBattle:
	.string "巧妙搭配是流行\n时尚背后的秘密。$"

Route124_Text_SpencerIntro:
	.string "你在大海里迷失方向了吗？\p如果你能赢得了我的宝可梦，\n我就帮你引路。$"

Route124_Text_SpencerDefeat:
	.string "战斗中我迷失了方向！$"

Route124_Text_SpencerPostBattle:
	.string "很多人都会在大海里迷失方向。\p如果你也是那种类型，那你应该\n仰仗一下宝可导航的地图。$"

Route124_Text_RolandIntro:
	.string "啊！你竟然坐在宝可梦上，\n不用自己游泳……\p太让人羡慕了！$"

Route124_Text_RolandDefeat:
	.string "噢！\n我不能……$"

Route124_Text_RolandPostBattle:
	.string "我快被冻僵了……\n我在水里呆太久了……\p我真想像你一样骑着宝可梦……$"

Route124_Text_JennyIntro:
	.string "如果就像这样在海里漂浮着，\n宝可梦也会过来一起玩的。$"

Route124_Text_JennyDefeat:
	.string "噢，糟糕。\n我输了。$"

Route124_Text_JennyPostBattle:
	.string "在游泳的时候，我注意到有些\n宝可梦会攻击，而有些只是旁观。\p我想宝可梦\n也有着它们自己的个性吧。$"

Route124_Text_JennyRegister:
	.string "虽然只是一时兴起，也许你可以\n把我登记到你的宝可导航里。$"

Route124_Text_JennyRematchIntro:
	.string "如果你就像这样在海里漂着，\n训练家会向你挑战的！$"

Route124_Text_JennyRematchDefeat:
	.string "好奇怪……\n我又输了……$"

Route124_Text_JennyPostRematch:
	.string "虽然没什么理由，\n也许我会去戏法屋逛逛。$"

Route124_Text_GraceIntro:
	.string "我游泳游得有些厌倦了……\n来一场对战如何？$"

Route124_Text_GraceDefeat:
	.string "没想到你竟然这么强！$"

Route124_Text_GracePostBattle:
	.string "你会这么强，\n一定是你一直以来努力的结果。$"

Route124_Text_ChadIntro:
	.string "嘿嘿，我可以潜到\n很深的水底下。\l深度就是我的优势！$"

Route124_Text_ChadDefeat:
	.string "咕，咕，咕……\n我快沉下去了……$"

Route124_Text_ChadPostBattle:
	.string "我绝对可以确定这附近\n有个潜水点。\p这让我又有了潜水\n的冲动了……$"

Route124_Text_LilaIntro:
	.string "佳子：唉……\p我来海边玩，可你猜陪我的人是谁？\n居然是我弟弟！\p我们对战一局吧，免得我总\n想着这件事！$"

Route124_Text_LilaDefeat:
	.string "佳子：小勇！都是因为你才输的！\n看我回家后怎么收拾你！$"

Route124_Text_LilaPostBattle:
	.string "佳子：唉……\p如果陪在我旁边的不是我\n弟弟，而是男朋友该多好……$"

Route124_Text_LilaNotEnoughMons:
	.string "佳子：你想和我们对战？\n除非你有2只宝可梦。$"

Route124_Text_RoyIntro:
	.string "小勇：我姐姐可是宝可梦高手！\p输了的话可别哭鼻子！$"

Route124_Text_RoyDefeat:
	.string "小勇：啊——哦……\n我姐姐饶不了我的……$"

Route124_Text_RoyPostBattle:
	.string "小勇：我姐姐生气的时候\n真的很可怕。\p所以她才找不到\n男朋友。$"

Route124_Text_LilaRoyRegister:
	.string "小勇：你下次能不能再和我们对战一局？\n但一定要手下留情，好吗？$"

Route124_Text_RoyNotEnoughMons:
	.string "小勇：想和我们对战？\n那就带2只宝可梦过来。$"

Route124_Text_LilaRematchIntro:
	.string "佳子：唉……\p我来海边玩，可你猜陪我的人是谁？\n居然是我弟弟！\p哦，喂，好久不见了\n我们对战一局吧，\l免得我总想着这件事！$"

Route124_Text_LilaRematchDefeat:
	.string "佳子：小勇！\n这次又输了，还不都是因为你！\p过一会我们要进行一次特训！$"

Route124_Text_LilaPostRematch:
	.string "佳子：唉……\p如果我有个男朋友，\n爱情的力量将会战胜一切……$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "佳子：你想和我们对战？\n除非你有2只宝可梦。$"

Route124_Text_RoyRematchIntro:
	.string "小勇：如果我们输了，\n我肯定不会被轻饶的。\p我要全力以赴了！$"

Route124_Text_RoyRematchDefeat:
	.string "小勇：啊——哦……\n我姐姐不可能饶了我的。$"

Route124_Text_RoyPostRematch:
	.string "小勇：我姐姐生气的时候\n真的很可怕。\p她过一会要让我\n进行宝可梦特训……$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "小勇：想和我们对战？\n那就带2只宝可梦过来。$"

Route124_Text_DeclanIntro:
	.string "我独自一人在这片广阔优美\n的海上游泳。\p没有别的词汇形容这种感觉，\n真是太悲哀了！$"

Route124_Text_DeclanDefeat:
	.string "我真的好忧郁。\n就如同这蓝天一般忧郁……$"

Route124_Text_DeclanPostBattle:
	.string "我应该和美女游泳者聊聊天\n并且邀请她们一同游泳。$"

Route124_Text_IsabellaIntro:
	.string "我不会输给漂在\n海上的训练家。$"

Route124_Text_IsabellaDefeat:
	.string "只是汗水流进眼里了！\n我没哭！$"

Route124_Text_IsabellaPostBattle:
	.string "你在这附近可以找到许多\n色彩鲜艳的碎片。$"

Route125_Text_NolenIntro:
	.string "我听到你要来了，\n于是就在附近等你！$"

Route125_Text_NolenDefeat:
	.string "我投降！$"

Route125_Text_NolenPostBattle:
	.string "声音在水中的传播速度\n比在空气中要快。$"

Route125_Text_StanIntro:
	.string "嘿，你！\n见识一下我可爱的宝可梦吧！$"

Route125_Text_StanDefeat:
	.string "我错了……$"

Route125_Text_StanPostBattle:
	.string "我被墨海马的魅力所倾倒，\n所以也开始游泳了。$"

Route125_Text_TanyaIntro:
	.string "我已经不想游泳了。\n想和我对战吗？$"

Route125_Text_TanyaDefeat:
	.string "你太强了！$"

Route125_Text_TanyaPostBattle:
	.string "呼……\n去绿岭市是哪条路？$"

Route125_Text_SharonIntro:
	.string "想不想和我养的\n水属性宝可梦对战？$"

Route125_Text_SharonDefeat:
	.string "输了……$"

Route125_Text_SharonPostBattle:
	.string "你的力量……你是真正的高手。\n我服了！$"

Route125_Text_ErnestIntro:
	.string "喂！我是个强悍的水手！\n全世界的海洋我都去过！$"

Route125_Text_ErnestDefeat:
	.string "哇啊啊啊！\n我赢不了！$"

Route125_Text_ErnestPostBattle:
	.string "在浅滩洞穴中的\n潮水时涨时退。\p顺便说一句，从涨潮到退潮要经过\n6小时的时间。你知道吗？$"

Route125_Text_ErnestRegister:
	.string "把我存入你的宝可导航，\n我会跟你讲些有趣的事。$"

Route125_Text_ErnestRematchIntro:
	.string "该是和你算总帐的\n时候了！我们做个了断吧！$"

Route125_Text_ErnestRematchDefeat:
	.string "我赢不了！\n根本就赢不了！$"

Route125_Text_ErnestRematchPostBattle:
	.string "浅滩洞穴……\p根据潮水的涨退\n你可以到达不同的地方。\p顺便说一句，从涨潮到退潮要经过\n6小时的时间。可别忘了！$"

Route125_Text_KimIntro:
	.string "真穗：听说有一个\n怪老头住在浅滩洞穴里。\l你也想去见他吗？$"

Route125_Text_KimDefeat:
	.string "真穗：我以为我们能赢的。$"

Route125_Text_KimPostBattle:
	.string "真穗：有一个怪老头住在\n浅滩洞穴里，对不对？\p我们去见见他吧，奈穗！$"

Route125_Text_KimNotEnoughMons:
	.string "真穗：不，不，不！你需要2只宝可梦，\n不然没法打！$"

Route125_Text_IrisIntro:
	.string "奈穗：真穗，能说一下\n我们到底在找什么吗？$"

Route125_Text_IrisDefeat:
	.string "奈穗：哦，就差一点了。$"

Route125_Text_IrisPostBattle:
	.string "奈穗：真穗，我们真的要去\n浅滩洞穴吗？\l衣服会被弄湿了。$"

Route125_Text_IrisNotEnoughMons:
	.string "奈穗：哦，我们绝对不会\n2挑1的。$"

Route125_Text_PresleyIntro:
	.string "为什么我这种养鸟人\n会来海边？$"

Route125_Text_PresleyDefeat:
	.string "好吧。\n我就告诉你我为什么来这里。$"

Route125_Text_PresleyPostBattle:
	.string "我把一张纸条塞进瓶子里\n扔到海中。\p我肯定一个美女游泳者\n会看到它的！$"

Route125_Text_AuronIntro:
	.string "嘿！是你往海里\n乱扔垃圾的吧？$"

Route125_Text_AuronDefeat:
	.string "哦，看来垃圾\n不是你扔的。$"

Route125_Text_AuronPostBattle:
	.string "刚才我在海浪中\n发现一个难看的瓶子。\p居然有人污染大海\n气死我了！$"

Route126_Text_BarryIntro:
	.string "游泳可以锻炼身体全身的部位！\n你会变得更健康的！$"

Route126_Text_BarryDefeat:
	.string "我认输！\n你赢了！$"

Route126_Text_BarryPostBattle:
	.string "多亏我每天都游泳……\n瞧瞧我这身肌肉！$"

Route126_Text_DeanIntro:
	.string "这座高耸的白色岩山\n就是琉璃市。$"

Route126_Text_DeanDefeat:
	.string "我输了？$"

Route126_Text_DeanPostBattle:
	.string "我找不到通往琉璃市\n的入口。它到底在哪里？$"

Route126_Text_NikkiIntro:
	.string "呵呵！\n我是美人鱼！$"

Route126_Text_NikkiDefeat:
	.string "我的幻想像泡沫一样消失了！\n像泡沫一样……$"

Route126_Text_NikkiPostBattle:
	.string "你击败了我……\n我只想在绝望的浪潮中消亡……$"

Route126_Text_BrendaIntro:
	.string "嘿，小子！\n想和我对战吗？$"

Route126_Text_BrendaDefeat:
	.string "哦，不——！$"

Route126_Text_BrendaPostBattle:
	.string "我很喜欢和宝可梦\n在海中嬉戏！$"

Route126_Text_PabloIntro:
	.string "瞧瞧这体格！\n我比黑带还强！$"

Route126_Text_PabloDefeat:
	.string "哇！太强了！\n不错！真不错！$"

Route126_Text_PabloPostBattle:
	.string "我的失败更加刺激了我！\n我要更努力地训练我和我的宝可梦！$"

Route126_Text_PabloRegister:
	.string "嗯，你确实不错！\n我想进一步了解你！$"

Route126_Text_PabloRematchIntro:
	.string "看看这优美的体型！\n我比游泳者还要匀称！$"

Route126_Text_PabloRematchDefeat:
	.string "哇！真的是太强了！\n不错！真不错！$"

Route126_Text_PabloPostRematch:
	.string "我要更努力地锻炼自己！\n你就是我的动力！\l你以后一定要再来啊！$"

Route126_Text_LeonardoIntro:
	.string "去年我都不会游泳，\n但现在我已经是一名不错的游泳者了。\p看来我什么事都能办到。$"

Route126_Text_LeonardoDefeat:
	.string "切，人太贪心\n就是不好啊。$"

Route126_Text_LeonardoPostBattle:
	.string "只要多练习，\n水平肯定会提高。\p你还年轻——\n不要害怕尝试！$"

Route126_Text_IsobelIntro:
	.string "如果鼻子里进了海水，\n你不觉得难受吗？$"

Route126_Text_IsobelDefeat:
	.string "啊！你，居然……\n哇！$"

Route126_Text_IsobelPostBattle:
	.string "哦，我被海水呛到了！\n又苦又咸！！$"

Route126_Text_SiennaIntro:
	.string "我现在可是\n十分认真的！$"

Route126_Text_SiennaDefeat:
	.string "你比我更认真！$"

Route126_Text_SiennaPostBattle:
	.string "我要冷静一下……\n还是去潜水吧。$"

Route127_Text_CamdenIntro:
	.string "我从你的表情看出\n你想挑战我。$"

Route127_Text_CamdenDefeat:
	.string "啊哇哇哇哇……$"

Route127_Text_CamdenPostBattle:
	.string "一场精彩的对战让我感到\n神清气爽，心绪平静。$"

Route127_Text_DonnyIntro:
	.string "你有没有什么对手\n是你不想输给的？$"

Route127_Text_DonnyDefeat:
	.string "啊！\n我痛恨失败！$"

Route127_Text_DonnyPostBattle:
	.string "如果你有了对手\n你不觉得应该\l不断精进自己吗？$"

Route127_Text_JonahIntro:
	.string "通过钓鱼，\n我已经达到了心平气和的境界……\p请允许我展示一下吧……$"

Route127_Text_JonahDefeat:
	.string "虽然我输了，可我的心情\n依然平静……$"

Route127_Text_JonahPostBattle:
	.string "钓不到东西并不要紧。\n钓鱼线始终在水里……$"

Route127_Text_HenryIntro:
	.string "啊！我难道钓到了\n一只冲浪中的宝可梦？$"

Route127_Text_HenryDefeat:
	.string "我撑不住了！$"

Route127_Text_HenryPostBattle:
	.string "我要是钓到了你的宝可梦\n可就麻烦了！$"

Route127_Text_RogerIntro:
	.string "嘿！这可是一场\n宝可梦迷和钓鱼迷之间的较量！$"

Route127_Text_RogerDefeat:
	.string "不！我的线都缠在一起了！\n全完了！$"

Route127_Text_RogerPostBattle:
	.string "我的钓鱼线在跳舞！\n多美的探戈！啊哈哈！$"

Route127_Text_AidanIntro:
	.string "鸟类宝可梦视野比较开阔。\n它们从高处能够迅速发现猎物。$"

Route127_Text_AidanDefeat:
	.string "啊……我放弃。$"

Route127_Text_AidanPostBattle:
	.string "这一片海域有\n许多潜水点。\p这些潜水点的颜色较深\n你从空中一眼就能看出来。$"

Route127_Text_KojiIntro:
	.string "赤脚奔跑吧。\n这样可以锻炼你的脚底！$"

Route127_Text_KojiDefeat:
	.string "啊！\n我的趾甲里进了一块石子！$"

Route127_Text_KojiPostBattle:
	.string "赤着脚走感觉确实舒服。\n不过你的跑鞋也很酷。$"

Route127_Text_KojiRegister:
	.string "我向来是这样对待击败我的人！\n希望以后还能再来一次。$"

Route127_Text_KojiRematchIntro:
	.string "我现在仍然每天赤着脚奔跑。\n我的脚板更硬了！$"

Route127_Text_KojiRematchDefeat:
	.string "啊！\n石子硌到我的脚了！$"

Route127_Text_KojiPostRematch:
	.string "想不想赤着脚走走？\n好让我试试你的跑步鞋？$"

Route127_Text_AthenaIntro:
	.string "我们应该打一场\n具有策略性的对战。$"

Route127_Text_AthenaDefeat:
	.string "你根本就没给我\n分析局势的时间。$"

Route127_Text_AthenaPostBattle:
	.string "当我被大海和蓝天包围的时候，\n我感觉时间的流逝变得缓慢了。$"

Route128_Text_IsaiahIntro:
	.string "到彩悠市还有很长\n一段距离……$"

Route128_Text_IsaiahDefeat:
	.string "我的首胜离我似乎也有\n很长一段距离……$"

Route128_Text_IsaiahPostBattle:
	.string "我一生都在屡败屡战，\n但我绝不放弃！$"

Route128_Text_IsaiahRegister:
	.string "我知道我现在还不行，\n但我最终肯定能够取得胜利。\p请在宝可导航登记我。$"

Route128_Text_IsaiahRematchIntro:
	.string "我现在仍然感觉良好。\n我会一直游到彩悠市。$"

Route128_Text_IsaiahRematchDefeat:
	.string "我仍然没有尝到首胜的滋味……$"

Route128_Text_IsaiahPostRematch:
	.string "我最终一定会到达彩悠市\n并且取得胜利……$"

Route128_Text_KatelynIntro:
	.string "铁人三项包括\n游泳，骑车和马拉松。\p这种包含三项的比赛\n十分艰难。$"

Route128_Text_KatelynDefeat:
	.string "宝可梦对战也很艰难……$"

Route128_Text_KatelynPostBattle:
	.string "我接下来要骑自行车，可是……\n我想放弃了……$"

Route128_Text_KatelynRegister:
	.string "嗯，我还是尽力而为吧。\n希望以后还能再比一次。$"

Route128_Text_KatelynRematchIntro:
	.string "铁人三项很漫长。但我觉得\n通往宝可梦冠军的道路\l同样漫长艰辛。$"

Route128_Text_KatelynRematchDefeat:
	.string "宝可梦对战真的是\n残酷激烈啊……$"

Route128_Text_KatelynPostRematch:
	.string "你应该认真考虑一下\n挑战冠军之路。$"

Route128_Text_AlexaIntro:
	.string "为了能够挑战宝可梦联盟\n我们已经十分努力了……\p怎么能在这种时候输掉呢！$"

Route128_Text_AlexaDefeat:
	.string "哦！\n怎么可能？！$"

Route128_Text_AlexaPostBattle:
	.string "我已经拼到这里了，\n一个挫折不可能动摇我的决心。$"

Route128_Text_RubenIntro:
	.string "没有比我更强的训练家！$"

Route128_Text_RubenDefeat:
	.string "不可能！$"

Route128_Text_RubenPostBattle:
	.string "或许没有比你\n更强的训练家了！$"

Route128_Text_WayneIntro:
	.string "我想去彩悠，于是就捉了一只会攀瀑的\n宝可梦以便我登上瀑布。$"

Route128_Text_WayneDefeat:
	.string "我好沮丧！$"

Route128_Text_WaynePostBattle:
	.string "啊啊啊啊！\p我的宝可梦会攀瀑，\n可是我却没有琉璃市道馆徽章！$"

Route128_Text_HarrisonIntro:
	.string "你看上去真强。\n不知道我能不能赢。$"

Route128_Text_HarrisonDefeat:
	.string "哎哟！\n看来是不可能赢了。$"

Route128_Text_HarrisonPostBattle:
	.string "在彩悠市附近\n有许多很强的训练家。\p我和他们是不是不在\n一个等级上？$"

Route128_Text_CarleeIntro:
	.string "这里的阳光似乎\n更强烈一些。$"

Route128_Text_CarleeDefeat:
	.string "阳光太刺眼了，\n我什么都看不清。$"

Route128_Text_CarleePostBattle:
	.string "我得回去了。\n我要再抹一些防晒霜。$"

Route129_Text_ChaseIntro:
	.string "这是我第一次参加铁人三项。\n紧张死了！$"

Route129_Text_ChaseDefeat:
	.string "啊啊啊啊！\n我没能赢！$"

Route129_Text_ChasePostBattle:
	.string "我如果太紧张的话，\n就无法发挥全部实力了。$"

Route129_Text_AllisonIntro:
	.string "我正在参加铁人三项，\n不过我们为什么不来场对战呢？$"

Route129_Text_AllisonDefeat:
	.string "我还以为肯定能赢呢！$"

Route129_Text_AllisonPostBattle:
	.string "你知道参加铁人三项\n最大的好处是什么吗？\p就是测试自己力量的\n极限以及对自然的耐力！$"

Route129_Text_ReedIntro:
	.string "嘿，嘿！\n我们来吧！$"

Route129_Text_ReedDefeat:
	.string "我，我输了。\n就这样结束了！$"

Route129_Text_ReedPostBattle:
	.string "输了的话什么都得不到。\n我该回家了。$"

Route129_Text_TishaIntro:
	.string "为什么那么急？\n不要着急，慢慢来吧。$"

Route129_Text_TishaDefeat:
	.string "噢，天哪，\n我想再休息一会儿……$"

Route129_Text_TishaPostBattle:
	.string "想想看，在急急忙忙做事的\n时候突然犯了点错误的话，\l就会觉得很心烦吧？\p所以我做事一直\n尽力放慢脚步。$"

Route129_Text_ClarenceIntro:
	.string "冲浪并不像看上去\n那么简单，不是吗？$"

Route129_Text_ClarenceDefeat:
	.string "要想赢当然没那么简单。$"

Route129_Text_ClarencePostBattle:
	.string "你的目标是宝可梦\n联盟？努力加油吧！$"

Route130_Text_RodneyIntro:
	.string "让我吃了一惊呢！\n没想到在大海中也能碰见训练家！\p来对战吧！$"

Route130_Text_RodneyDefeat:
	.string "这个孩子真强啊……$"

Route130_Text_RodneyPostBattle:
	.string "你的眼神看上去就像那经历过\n艰苦的试炼并最终取得胜利的人一样。\l很适合你！$"

Route130_Text_KatieIntro:
	.string "身处深邃的蓝色大海之中，\n我忧郁而破碎的心\l在海浪之间找到了归宿。$"

Route130_Text_KatieDefeat:
	.string "宝可梦的世界比之人们的想象\n更加广袤而邈远，\l就像这无垠的大海一样。$"

Route130_Text_KatiePostBattle:
	.string "世界上的孩子们都\n梦想着有一天能够成为\l宝可梦冠军。$"

Route130_Text_SantiagoIntro:
	.string "像这样漂浮在宽广的大海上……\n心里感觉无比宁静。$"

Route130_Text_SantiagoDefeat:
	.string "我的心过于宁静了！$"

Route130_Text_SantiagoPostBattle:
	.string "像这个样子游泳和对战……\n心里感觉特别快乐……$"

Route131_Text_RichardIntro:
	.string "大海中到处都是宝可梦。\n告诉你，在海里游泳可不容易。$"

Route131_Text_RichardDefeat:
	.string "训练家培育的宝可梦\n真的非常强大……$"

Route131_Text_RichardPostBattle:
	.string "呼……呼……\n我输掉了……\p来的时候很简单，\n麻烦的是怎么回去。\l我还有力气往回走吗？$"

Route131_Text_HermanIntro:
	.string "大海……大海……大海……\n放眼望过去全都是海！\l我开始受够大海了！$"

Route131_Text_HermanDefeat:
	.string "呀啊！$"

Route131_Text_HermanPostBattle:
	.string "我受够了海，\n但我还会继续游下去。\p我是为了游泳而生的！\n这就是我！$"

Route131_Text_SusieIntro:
	.string "嗨，亲，稍等一下！\n来对战吧，你我两人！$"

Route131_Text_SusieDefeat:
	.string "和看上去的不一样，\n你真的很强！$"

Route131_Text_SusiePostBattle:
	.string "你见到附近那个整天抱怨\n说他讨厌大海的家伙了吗？\p他只是说说，\n他已经无可救药地爱上大海了！$"

Route131_Text_KaraIntro:
	.string "男人为什么都喜欢泳装？\p他们都在盯着我看！$"

Route131_Text_KaraDefeat:
	.string "我赢不了！$"

Route131_Text_KaraPostBattle:
	.string "也许吸引了别人的目光的不是\n我的泳装，而是我的美貌啊！$"

Route131_Text_ReliIntro:
	.string "亚美：我们两个会\n齐心协力对付你的！$"

Route131_Text_ReliDefeat:
	.string "亚美：就算齐心协力，\n我们还是赢不了……$"

Route131_Text_ReliPostBattle:
	.string "亚美：暮水镇的人们\n从出生的那一刻就一直跟\l大海和宝可梦为伴。$"

Route131_Text_ReliNotEnoughMons:
	.string "亚美：你没带足2只宝可梦？\n真可惜，这样就不能对战了。$"

Route131_Text_IanIntro:
	.string "胜：我要努力地和姐姐\n一起战斗！$"

Route131_Text_IanDefeat:
	.string "胜：我和姐姐都努力了，\n但我们还是输了……$"

Route131_Text_IanPostBattle:
	.string "胜：你知道那个被称作\n漂浮的小镇的暮水镇吗？\p凡是有大海的地方，\n都是暮水镇的一部分！$"

Route131_Text_IanNotEnoughMons:
	.string "胜：假如你有2只宝可梦，\n我们就可以和你对战了！$"

Route131_Text_TaliaIntro:
	.string "你能打败我的话，\n我就告诉你一些好事情。$"

Route131_Text_TaliaDefeat:
	.string "哦？\n我输了？$"

Route131_Text_TaliaPostBattle:
	.string "这附近有一个奇怪的地方，\n那里有一座巨大的塔。\l不想去看看吗？$"

Route131_Text_KevinIntro:
	.string "暮水镇居民\n是爱好和平的。\p他们从来不生气。\n我也一样。$"

Route131_Text_KevinDefeat:
	.string "呀啊！$"

Route131_Text_KevinPostBattle:
	.string "嘁！……啊，不，\n我没有生气，真的！\p不过，你还真强！\n哈哈哈！$"

Route132_Text_GilbertIntro:
	.string "我小的时候经常感冒，\n但开始学习游泳之后，\l就再也没生过病。$"

Route132_Text_GilbertDefeat:
	.string "我的力量还不够……$"

Route132_Text_GilbertPostBattle:
	.string "训练家旅行中要经常\n翻山越岭，他们一定也很健康。$"

Route132_Text_DanaIntro:
	.string "我尽量不去海流\n比较急的地方游泳。$"

Route132_Text_DanaDefeat:
	.string "啊，不要，不！$"

Route132_Text_DanaPostBattle:
	.string "要是被冲走的话，\n我肯定会找不到方向的……$"

Route132_Text_RonaldIntro:
	.string "不去尝试一下的话，\n你永远不知道你会输还是会赢！$"

Route132_Text_RonaldDefeat:
	.string "哇啊啊！\n我被打败了！$"

Route132_Text_RonaldPostBattle:
	.string "我决不去打稳操胜券的对战，\n我喜欢那种胜败悬于一线间的感觉！$"

Route132_Text_KiyoIntro:
	.string "我每天24小时都在\n思考关于宝可梦的事情，\l你认为你能打败我吗？$"

Route132_Text_KiyoDefeat:
	.string "我承认，我输了。$"

Route132_Text_KiyoPostBattle:
	.string "呃……\n你也是个宝可梦迷吗？\p你一定也是每天24小时都在\n思考关于宝可梦的事情吧？$"

Route132_Text_MakaylaIntro:
	.string "我一直都和老头子在一起，\n但就算他不在，我也一样能赢。$"

Route132_Text_MakaylaDefeat:
	.string "啊，我想我还不够强。$"

Route132_Text_MakaylaPostBattle:
	.string "那边那个年轻人\n和老头子年轻的时候真像啊。\l看得我脸红啊！$"

Route132_Text_JonathanIntro:
	.string "好像有人一直在盯着我看，\n是你吗？$"

Route132_Text_JonathanDefeat:
	.string "哇！真强啊！$"

Route132_Text_JonathanPostBattle:
	.string "我总是摆脱不掉那种\n被人盯着的感觉。\p没办法集中精力啊！$"

Route132_Text_PaxtonIntro:
	.string "老太婆去哪儿了呢？\n我一直都和她在一起的，\l不知道没有她我还能不能赢。$"

Route132_Text_PaxtonDefeat:
	.string "哎，只有我一个人\n终归是赢不了啊。$"

Route132_Text_PaxtonPostBattle:
	.string "老太婆一定在找我吧，\n我也得赶紧去找她了。$"

Route132_Text_DarcyIntro:
	.string "我喜欢自己一个人在这里训练，\n但总有人在这里转来转去！$"

Route132_Text_DarcyDefeat:
	.string "好吧，别人来这里\n我不抱怨就是了。$"

Route132_Text_DarcyPostBattle:
	.string "我想我大概可以和那边的\n老爷爷组队一起挑战别人。$"

Route133_Text_FranklinIntro:
	.string "你也是被海流冲到这儿来的吗？\n这一定就是命运了。\l对战吧！$"

Route133_Text_FranklinDefeat:
	.string "真强！\n我打不过你！$"

Route133_Text_FranklinPostBattle:
	.string "像你这么强大的训练家\n漂流到了这里，也是我的运气……\l我一定是被诅咒了吧……$"

Route133_Text_DebraIntro:
	.string "我的一生都在痛苦与悲伤中度过……\n我一直在漂流，漂流，\l最后漂到了这里……$"

Route133_Text_DebraDefeat:
	.string "再一次失败了……$"

Route133_Text_DebraPostBattle:
	.string "这漂流的一生……\n我受够了！$"

Route133_Text_LindaIntro:
	.string "欢迎！\n我一直在等你！$"

Route133_Text_LindaDefeat:
	.string "啊啊，不要！$"

Route133_Text_LindaPostBattle:
	.string "这么强的孩子……\n真让人火大啊！$"

Route133_Text_WarrenIntro:
	.string "我和别人一样想要赢，\n但我不会和别人一样去培育宝可梦。$"

Route133_Text_WarrenDefeat:
	.string "可恶！\n太大意了！$"

Route133_Text_WarrenPostBattle:
	.string "按自己的想法做事比随波逐流\n要快乐得多，\l我觉得这显而易见！$"

Route133_Text_BeckIntro:
	.string "我一直和我的鸟类宝可梦\n一同旅行。$"

Route133_Text_BeckDefeat:
	.string "你……\n你真棒！$"

Route133_Text_BeckPostBattle:
	.string "我差不多该回茵郁市去了，\n但我已经喜欢上了这个地方。$"

Route133_Text_MollieIntro:
	.string "我大概已经对战了几千次了，\n我自己都数不清了。$"

Route133_Text_MollieDefeat:
	.string "我大概已经输了几千次了，\n但现在还是在输。$"

Route133_Text_MolliePostBattle:
	.string "就这样加油吧，年轻人，总有一天\n你也会成为我们这样的高手的。$"

Route133_Text_ConorIntro:
	.string "年轻人喜欢追随潮流，\n却没有自己的目标。$"

Route133_Text_ConorDefeat:
	.string "看来你有坚定的目标啊。$"

Route133_Text_ConorPostBattle:
	.string "不要让别人把你引离正道，\n成长的过程中不要忘记你的目标。$"

Route134_Text_JackIntro:
	.string "即使会游泳的宝可梦\n也无法逆激流而行。$"

Route134_Text_JackDefeat:
	.string "呀啊啊啊！$"

Route134_Text_JackPostBattle:
	.string "我想宝可梦大概很喜欢\n这里湍急的水流。$"

Route134_Text_LaurelIntro:
	.string "和我的爱心鱼们\n来一场愉快的对战吧！$"

Route134_Text_LaurelDefeat:
	.string "哇啊！$"

Route134_Text_LaurelPostBattle:
	.string "据说有个收藏家专门收集\n心之鳞片。$"

Route134_Text_AlexIntro:
	.string "好了好了，休息够了，伙计！\n现在要开始战斗了！$"

Route134_Text_AlexDefeat:
	.string "又累了……$"

Route134_Text_AlexPostBattle:
	.string "长途飞行的话我的鸟类宝可梦\n很快就会累……$"

Route134_Text_HitoshiIntro:
	.string "你是宝可梦训练家，\n无需多言，对战吧。$"

Route134_Text_HitoshiDefeat:
	.string "…… …… ……\n…… …… ……$"

Route134_Text_HitoshiPostBattle:
	.string "是我主动发起挑战，结果却输了，\n真是惭愧……$"

Route134_Text_AaronIntro:
	.string "在这汹涌的巨浪中训练\n能让我们比以前更强。$"

Route134_Text_AaronDefeat:
	.string "我认输。$"

Route134_Text_AaronPostBattle:
	.string "我们要回流星瀑布\n加强训练了。\p有时间的话，你也该去那里，\n肯定能让你的实力大大提升！$"

Route134_Text_KelvinIntro:
	.string "我——我们的船！\n浪把它卷走了！$"

Route134_Text_KelvinDefeat:
	.string "哇哇哇哇！\n停下，拜托，快停下！$"

Route134_Text_KelvinPostBattle:
	.string "如果我们不会冲浪，\n该怎么回家啊。\p实际上，我知道昏厥的宝可梦\n仍然能冲浪，但感觉有点奇怪吧？$"

Route134_Text_MarleyIntro:
	.string "你的宝可梦能躲过我们\n闪电般的攻击吗？$"

Route134_Text_MarleyDefeat:
	.string "我从来没见过那样的技术！\n我们彻底输掉了。$"

Route134_Text_MarleyPostBattle:
	.string "追求速度的激情还没有消失，\n我还会更努力的。$"

Route134_Text_ReynaIntro:
	.string "我的宝可梦是不会\n被轻易打败的！$"

Route134_Text_ReynaDefeat:
	.string "开玩笑吧！\n我怎么会输！$"

Route134_Text_ReynaPostBattle:
	.string "哈哈！\n好吧，你赢了！\p我要打败偶遇的每个\n训练家来重新奋起！$"

Route134_Text_HudsonIntro:
	.string "喂，你在这附近看到\n别的水手了吗？$"

Route134_Text_HudsonDefeat:
	.string "啊，真厉害！$"

Route134_Text_HudsonPostBattle:
	.string "我们的船漂到海里去了。\p我的搭档比较胆小，\n现在我很担心他。$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "电量不足。\p"
	.string "完全充满所需步数：\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "附近没有可以对战的训练家……\p"
	.string "VS雷达已关闭。{PAUSE_UNTIL_PRESS}$"


VSSeeker_Text_TrainersNotReady::
	.string "其他训练家似乎还没有准备好对战，\n"
	.string "过段时间再尝试吧。{PAUSE_UNTIL_PRESS}$"
