CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "这是宝可梦打印机！\p"
	.string "它可以将你的宝可梦\n"
	.string "印在训练家卡背面。\p"
	.string "只需¥50。\n"
	.string "你想试试吗？$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "你的钱不够。$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "请选择打印类型。$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "拍照请展示大大的笑容！\n"
	.string "三……二……一……\p"
	.string "咔嚓！$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "你的宝可梦照片打印好了！\n"
	.string "请查看你的训练家卡。$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "嘻嘻……\n"
	.string "我收集了好多贴纸哦。\l"
	.string "真想展示给大家看……$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "哦，太好了！\n"
	.string "你来对地方了！\p"
	.string "看看看！看到了吗？\n"
	.string "这些都是我的贴纸！\l"
	.string "你看我收集了多少！\p"
	.string "你一定也想要吧。\n"
	.string "我猜你想要！\p"
	.string "如果你能告诉我一件\n"
	.string "关于你自己了不起的事，\l"
	.string "我就给你一张贴纸。\p"
	.string "你要炫耀什么呢？$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "来吹嘘点什么吧。\n"
	.string "我会给你一张贴纸的。$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "哦，你来了！\n"
	.string "爱吹牛的家伙来了。\p"
	.string "今天你要吹嘘什么呢？$"

FourIsland_House2_Text_WowHoFLowest::
	.string "哦哇，你进入了\n"
	.string "殿堂名人录！\p"
	.string "很厉害嘛！\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowHoFLow::
	.string "哦哇，你多次进入了\n"
	.string "殿堂名人录！\p"
	.string "令人印象深刻！\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowHoFHigh::
	.string "哇！你进入殿堂名人录\n"
	.string "那么多次了？\l"
	.string "真的超厉害！\p"
	.string "你就是宝可梦联盟之主！\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowHoFHighest::
	.string "不会吧！你进入殿堂\n"
	.string "名人录那么多次？\p"
	.string "你简直超越了厉害的极限！\n"
	.string "就这样，我必须给你这个。$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "殿堂名人录贴纸\n"
	.string "已贴到训练家卡上了。$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "嗯……\p"
	.string "下次带个更厉害的故事来吧，\n"
	.string "好吗？$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "哦，不，不行了。\p"
	.string "你简直是一个活着的传说。\n"
	.string "我已经没有贴纸可以给了。$"

FourIsland_House2_Text_WowEggsLowest::
	.string "哦哇，还有宝可梦的蛋？\n"
	.string "我都不知道！\p"
	.string "很厉害嘛！\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowEggsLow::
	.string "你孵化了那么多蛋？\n"
	.string "你一定很喜欢蛋！\p"
	.string "令人印象深刻！\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowEggsHigh::
	.string "哇！你孵化了\n"
	.string "好多好多蛋！\p"
	.string "你简直是孵蛋机器！\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowEggsHighest::
	.string "什、什么……你孵化了那么多蛋？\p"
	.string "你对蛋的热爱从何而来？\n"
	.string "超越了厉害的极限！\p"
	.string "你实在是太厉害了。\n"
	.string "就这样，我必须给你这个。$"

FourIsland_House2_Text_EggStickerApplied::
	.string "蛋贴纸已贴到\n"
	.string "训练家卡上了。$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "嗯……\p"
	.string "下次带个更厉害的故事来吧，\n"
	.string "好吗？$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "哦，不，不行了。\p"
	.string "你简直是一个活着的传说。\n"
	.string "我已经没有贴纸可以给了。$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "哦哇，你在\n"
	.string "通信对战中获胜了？\p"
	.string "你还挺厉害的！\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "你在通信对战中\n"
	.string "赢了很多朋友呢！\p"
	.string "令人印象深刻地厉害！\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "哇！你在通信对战中\n"
	.string "赢了好多好多次！\p"
	.string "这样不会失去朋友吗？\n"
	.string "给你一张这个。$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "什、什么……超厉害！\n"
	.string "你赢了令人难以置信的次数！\p"
	.string "光是想想你有多强大\n"
	.string "就让我晕头转向了。\p"
	.string "你简直是噩梦级别的存在！\n"
	.string "就这样，我必须给你这个。$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "胜利贴纸已贴到\n"
	.string "训练家卡上了。$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "嗯……\p"
	.string "下次带个更厉害的故事来吧，\n"
	.string "好吗？$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "哦，不，不行了。\p"
	.string "你简直是一个活着的传说。\n"
	.string "我已经没有贴纸可以给了。$"
