Route4_Frlg_MapScripts::
	.byte 0

Route4_EventScript_Unused::
	end

Route4_EventScript_Woman::
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
	end

Route4_EventScript_MtMoonSign::
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
	end

Route4_EventScript_RouteSign::
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
	end

Route4_Text_TrippedOverGeodude::
	.string "哎哟！我被一只岩石宝可梦绊倒了，\n"
	.string "是小拳石啊！$"

Route4_Text_CrissyIntro::
	.string "我来月见山寻找蘑菇宝可梦。$"

Route4_Text_CrissyDefeat::
	.string "这次我一定要抓到它们！$"

Route4_Text_CrissyPostBattle::
	.string "这里应该已经没有蘑菇了。\p"
	.string "可能已经都被我采光了。$"

Route4_Text_MtMoonEntrance::
	.string "月见山\n"
	.string "山洞的入口$"

Route4_Text_RouteSign::
	.string "4号道路\n"
	.string "月见山-华蓝市$"

Text_MegaPunchTeach::
	.string "一声巨响！\p"
	.string "伴随着毁灭性的力量！\p"
	.string "在关键时刻，\n"
	.string "百万吨重拳就是最强悍的攻击！\l"
	.string "你也这么认为吧？\p"
	.string "现在！\n"
	.string "让我教你的宝可梦学会这个技能！$"

Text_MegaPunchDeclined::
	.string "当你知道百万吨重拳价值的时候，\n"
	.string "你一定会回来的。$"

Text_MegaPunchWhichMon::
	.string "很好！\n"
	.string "想要让哪只宝可梦学习？$"

Text_MegaPunchTaught::
	.string "现在，\n"
	.string "我们算是同一流派的人了！\p"
	.string "你得快点走，\n"
	.string "小心被在那边那个只知道\l"
	.string "一味训练攻击力的傻瓜发现。$"

Text_MegaKickTeach::
	.string "一次凶狠的踢击！\p"
	.string "伴随着毁灭性的力量！\p"
	.string "你若能善用百万吨重踢时，\n"
	.string "它会成为最强悍的攻击！\l"
	.string "你也这么认为吧？\p"
	.string "好的！\n"
	.string "让我教你的宝可梦使用这个技能！$"

Text_MegaKickDeclined::
	.string "当你意识到百万吨重踢的价值时，\n"
	.string "你一定会回来的。$"

Text_MegaKickWhichMon::
	.string "很好！\n"
	.string "想要让哪只宝可梦学习？$"

Text_MegaKickTaught::
	.string "现在，\n"
	.string "我们算是同一流派的人了！\p"
	.string "你得快点走，\n"
	.string "小心被在那边那个只知道\l"
	.string "一味训练攻击力的傻瓜发现。$"

Route4_Text_PeopleLikeAndRespectBrock::
	.string "哇，那是灰色徽章！\n"
	.string "你从小刚那里得到的，没错吧？\p"
	.string "小刚不仅冷静，还很坚强。\n"
	.string "人们都很喜欢他，尊敬他。\p"
	.string "我想成为像他一样的\n"
	.string "道馆馆主。$"
