Route102_MapScripts::
	.byte 0

Route102_EventScript_LittleBoy::
	msgbox Route102_Text_ImNotVeryTall, MSGBOX_NPC
	end

Route102_EventScript_RouteSignOldale::
	msgbox Route102_Text_RouteSignOldale, MSGBOX_SIGN
	end

Route102_EventScript_RouteSignPetalburg::
	msgbox Route102_Text_RouteSignPetalburg, MSGBOX_SIGN
	end

Route102_EventScript_Boy::
	msgbox Route102_Text_CatchWholeBunchOfPokemon, MSGBOX_NPC
	end

Route102_EventScript_Calvin::
	trainerbattle_single TRAINER_CALVIN_1, Route102_Text_CalvinIntro, Route102_Text_CalvinDefeated, Route102_EventScript_CalvinRegisterMatchCallAfterBattle
	specialvar VAR_RESULT, ShouldTryRematchBattle
	goto_if_eq VAR_RESULT, TRUE, Route102_EventScript_CalvinRematch
	setvar VAR_0x8004, TRAINER_CALVIN_1
	specialvar VAR_RESULT, IsTrainerRegistered
	goto_if_eq VAR_RESULT, FALSE, Route102_EventScript_CalvinTryRegister
	msgbox Route102_Text_CalvinPostBattle, MSGBOX_DEFAULT
	release
	end

Route102_EventScript_CalvinRegisterMatchCallAfterBattle::
	special PlayerFaceTrainerAfterBattle
	waitmovement 0
	goto_if_set FLAG_HAS_MATCH_CALL, Route102_EventScript_CalvinRegisterMatchCall
	release
	end

Route102_EventScript_CalvinRegisterMatchCall::
	msgbox Route102_Text_CalvinRegisterShort, MSGBOX_DEFAULT
	register_matchcall TRAINER_CALVIN_1
	release
	end

Route102_EventScript_CalvinTryRegister::
	goto_if_set FLAG_HAS_MATCH_CALL, Route102_EventScript_CalvinRegister
	msgbox Route102_Text_CalvinPostBattle, MSGBOX_DEFAULT
	release
	end

Route102_EventScript_CalvinRegister::
	msgbox Route102_Text_CalvinRegister, MSGBOX_DEFAULT
	register_matchcall TRAINER_CALVIN_1
	release
	end

Route102_EventScript_CalvinRematch::
	trainerbattle_rematch TRAINER_CALVIN_1, Route102_Text_CalvinRematchIntro, Route102_Text_CalvinRematchDefeated
	msgbox Route102_Text_CalvinRematchPostBattle, MSGBOX_AUTOCLOSE
	end

Route102_EventScript_Rick::
	trainerbattle_single TRAINER_RICK, Route102_Text_RickIntro, Route102_Text_RickDefeated
	msgbox Route102_Text_RickPostBattle, MSGBOX_AUTOCLOSE
	end

Route102_EventScript_Tiana::
	trainerbattle_single TRAINER_TIANA, Route102_Text_TianaIntro, Route102_Text_TianaDefeated
	msgbox Route102_Text_TianaPostBattle, MSGBOX_AUTOCLOSE
	end

Route102_EventScript_Allen::
	trainerbattle_single TRAINER_ALLEN, Route102_Text_AllenIntro, Route102_Text_AllenDefeated
	msgbox Route102_Text_AllenPostBattle, MSGBOX_AUTOCLOSE
	end

Route102_Text_WatchMeCatchPokemon:
	.string "满充：{PLAYER}……\n草丛里会藏着宝可梦，对吧？\p请你看看我捕捉宝可梦的\n方法对不对。\p……哇！$"

Route102_Text_WallyIDidIt:
	.string "满充：成功了……这是我的……\n我的宝可梦！$"

Route102_Text_LetsGoBack:
	.string "{PLAYER}，谢谢你！\n我们回道馆吧！$"

Route102_Text_ImNotVeryTall:
	.string "我……不是很高，所以在草丛里\n走的时候我就被草遮起来了。\p草总是戳到我的鼻子里，然后就……\n阿——阿—阿——阿……\p阿嚏！$"

Route102_Text_CatchWholeBunchOfPokemon:
	.string "我要捉一大堆\n宝可梦！$"

Route102_Text_RouteSignOldale:
	.string "102号道路\n{RIGHT_ARROW}古玫镇$"

Route102_Text_RouteSignPetalburg:
	.string "102号道路\n{LEFT_ARROW}橙华市$"

Route102_EventScript_ProfOakAssistant::
	lock
	faceplayer
	checkflag FLAG_GOT_FLIGHT_CALL
	goto_if TRUE, Route102_EventScript_ProfOakAssistant_Done

	msgbox Route102_Text_Kanto, MSGBOX_DEFAULT
	giveitem ITEM_FLIGHT_CALL, 1
	setflag FLAG_WORLD_MAP_PALLET_TOWN
	setflag FLAG_GOT_FLIGHT_CALL
	msgbox Route102_Text_ReceivedDevice, MSGBOX_DEFAULT
	msgbox Route102_Text_KantoAfterGift, MSGBOX_DEFAULT
	closemessage
	applymovement ProfOakAssistant, Route102_Movement_ProfOakAssistantWarpOut
	waitmovement 0
	setflag FLAG_HIDE_ROUTE_PROF_ASSISTANT
	hideobjectat ProfOakAssistant, MAP_ROUTE102
	releaseall
	end

Route102_EventScript_ProfOakAssistant_Done::
	releaseall
	end

Route102_Text_Kanto:
	.string "{PLAYER}！！！\n小田卷博士说你会\l经过这里的。\p大木博士在关都，\n托我来找你。\p他想把这个给你。$"

Route102_Text_ReceivedDevice:
	.string "{PLAYER}获得了\n飞行呼叫！$"

Route102_Text_KantoAfterGift:
	.string "有了那个道具，\n就可以前往关都了。\p我也该回研究所了，\n再见！$"

Route102_Movement_ProfOakAssistantWarpOut:
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	set_invisible
	step_end
