SSAnne_1F_Corridor_Frlg_MapScripts::
	.byte 0

SSAnne_1F_Corridor_EventScript_WorkerM::
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
	end

SSAnne_1F_Corridor_EventScript_Sailor::
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
	end

SSAnne_1F_Corridor_Text_LeStrongSilentType::
	.string "Good morning！\n"
	.string "我是这条船上的waiter！\p"
	.string "很高兴能为您服务！\p"
	.string "………………\n"
	.string "啊！深藏不露型的啊！$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
	.string "这么长的航行使乘客们\n"
	.string "都感到无所事事。\p"
	.string "你可能会遇到一些\n"
	.string "烦人的家伙来挑战你哦！$"

