VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "在遥远的彩悠市最深处，\n就是宝可梦联盟的所在地。\p聚集在那里的训练家\n都异乎寻常地强大。$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "我记得，宝可梦联盟规定\n你要连续跟四天王战斗，\p一旦输了，\n就得从第一个重新开始。$"

