SevenIsland_SevaultCanyon_Entrance_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Entrance_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
	.string "哈哈！\n"
	.string "我可以毫不费力地把你轰走！$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
	.string "哎哟！\n"
	.string "对我来说太强大了！$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
	.string "那是什么？\n"
	.string "我没有展现出我应有的实力吗？\p"
	.string "嘿，那是我的战术！$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
	.string "嗨！\n"
	.string "你是我的后援会的成员吗？$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
	.string "噢，这么说你不是我的粉丝……\p"
	.string "好吧，我可以改变你。\n"
	.string "让我给你唱首歌吧！$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
	.string "啦啦……\n"
	.string "我的宝可梦，我把它们送出去了，\l"
	.string "所有的女孩都在尖叫、呐喊。$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
	.string "这座岛太宽广了……\n"
	.string "这个地方不容易巡查啊。$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
	.string "啊哈……$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
	.string "他们是像你这样来自\n"
	.string "城市的训练家，当然很强。\p"
	.string "你要前往塔，\n"
	.string "是吗？$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
	.string "虐待宝可梦的人，\n"
	.string "我要好好地惩罚他们。$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
	.string "你看起来不像是一个问题训练家。$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
	.string "如果你友好地对待你的宝可梦，\n"
	.string "他们能体会到的。$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
	.string "阿夕：我要和阿高合作，\n"
	.string "一起战斗。$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
	.string "阿夕：我和阿高，我们输了。\n"
	.string "呵呵。$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
	.string "阿夕：我要和阿高一起更加努力。$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
	.string "阿夕：我想和阿高一起\n"
	.string "跟你战斗。\p"
	.string "带着两只宝可梦来，好吗？$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
	.string "阿高：当我和阿夕一起时，\n"
	.string "我觉得我们永远不会输。$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
	.string "阿高：当我和阿夕一起时，\n"
	.string "我没想过我会输的啊！$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
	.string "阿高：当我和阿夕一起时，我对\n"
	.string "我是否会赢感到很疑惑。\p"
	.string "真是不可思议！$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
	.string "阿高：如果是和阿夕一起，\n"
	.string "我会很高兴和你战斗。\p"
	.string "所以说如果可以的话，\n"
	.string "我想来一场2对2的战斗。$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
	.string "七宝溪谷入口\p"
	.string "训练家禁止\n"
	.string "毁坏溪谷的植物。$"

