CeladonCity_House1_Frlg_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
	.string "呵呵呵！\p"
	.string "老虎机就是个吸钱机，\n"
	.string "最棒的吸钱机！$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
	.string "队长！\p"
	.string "我们今天刚又运来了2000个宝可梦\n"
	.string "作为老虎机的奖品！$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
	.string "千万别去碰游戏厅的海报！\p"
	.string "那后面没有什么秘密机关！$"

