Route2_ViridianForest_NorthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
	.string "很多宝可梦只生活在\n"
	.string "森林和洞穴里。\p"
	.string "你需要持续地四处搜寻\n"
	.string "来得到不同的种类。$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
	.string "你有没有注意到路边\n"
	.string "细小的树木？\p"
	.string "我听说它们能被一种宝可梦的\n"
	.string "特殊技能斩断。$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
	.string "你知道怎么\n"
	.string "取消进化吗？\p"
	.string "当一只宝可梦正在进化的时候，\n"
	.string "你能够使它停下来。\p"
	.string "这个窍门是养育宝可梦\n"
	.string "的一种方式。$"

