TwoIsland_CapeBrink_House_Frlg_MapScripts::
	.byte 0

@ See move_tutors.inc

Text_UltimateMoveThatMon::
	.string "我终于完美的掌握了\n"
	.string "最终极的技能！\p"
	.string "但以后\n"
	.string "它能够被传承下去吗？\p"
	.string "……嗯……嗯！\p"
	.string "你的……\n"
	.string "啊，{STR_VAR_1}……$"

Text_JustMistaken::
	.string "……不……\n"
	.string "恐怕我看走眼了……$"

Text_AllowMeToTeachMonUltimateMove::
	.string "啊！这就是那个合适的人选！\n"
	.string "就是这只宝可梦！\p"
	.string "{STR_VAR_1}绝对可以\n"
	.string "掌握我的终极技能！\p"
	.string "可以吗？\p"
	.string "可以让{STR_VAR_1}\n"
	.string "学习我的{STR_VAR_2}吗？$"

Text_YouRejectIt::
	.string "哈？你不同意？！\n"
	.string "好吧……我做不了你的主……$"

Text_LetMeConferUltimateMove::
	.string "你答应了？\p"
	.string "太好了，现在我就把\n"
	.string "{STR_VAR_2}教给你的{STR_VAR_1}。\p"
	.string "哇哦-哇哦-$"

Text_TaughtMove::
	.string "哈……哈……\p"
	.string "看来这些技能\n"
	.string "注定是派不上用场了……$"

Text_MakeBestUseOfMove::
	.string "我希望你能把这个技能的威力\n"
	.string "发挥到极致，从而获得强大的力量！$"

Text_PassedOnEverythingIKnow::
	.string "哈……哈……\p"
	.string "我现在没有遗憾了。\n"
	.string "我已经把我所知道的都告诉它了。\p"
	.string "现在，我已经完成了我的使命，\n"
	.string "现在就算离开这个世界，\n"
	.string "我也没有遗憾了……$"

Text_FeelRejuvenated::
	.string "把我的知识传授给你后，\n"
	.string "我感觉我轻松了很多。\p"
	.string "事实上，我感觉我再一次充满了活力，\n"
	.string "就像是又年轻了一次！$"
