ThreeIsland_BondBridge_Frlg_MapScripts::
	.byte 0

ThreeIsland_BondBridge_EventScript_BerryForestSign::
	msgbox ThreeIsland_BondBridge_Text_BerryForestAhead, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_EventScript_BondBridgeSign::
	msgbox ThreeIsland_BondBridge_Text_BondBridgeSign, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_Text_NikkiIntro::
	.string "大海的咸湿气息……\n"
	.string "冲击着我的心灵。$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
	.string "闻啊，闻啊……\n"
	.string "我闻到了不愉快的气息……$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
	.string "也许那难闻的气味是\n"
	.string "你的宝可梦身体的气味……$"

ThreeIsland_BondBridge_Text_VioletIntro::
	.string "你这么急是要去哪儿？$"

ThreeIsland_BondBridge_Text_VioletDefeat::
	.string "你培育了一些很棒的宝可梦。$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
	.string "如果你沿着这条路一直走，\n"
	.string "你最终将到达树果森林。$"

ThreeIsland_BondBridge_Text_AmiraIntro::
	.string "我妈妈让我\n"
	.string "只能带着游泳圈游泳。$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
	.string "哇！\n"
	.string "哇！$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
	.string "今年我一定要学会\n"
	.string "如何游泳！$"

ThreeIsland_BondBridge_Text_AlexisIntro::
	.string "耶，呀！\n"
	.string "宝可梦！$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
	.string "发生了什么？$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
	.string "我刚刚赢了吗？\n"
	.string "还是输了？$"

ThreeIsland_BondBridge_Text_TishaIntro::
	.string "噢，不，不要来这儿！\n"
	.string "拜托了，离我远一点！$"

ThreeIsland_BondBridge_Text_TishaDefeat::
	.string "好的，你赢了！\n"
	.string "现在能离开了吧？$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
	.string "有一只宝可梦咬坏了我的泳衣。\p"
	.string "我现在不能从水中出来了！$"

ThreeIsland_BondBridge_Text_JoyIntro::
	.string "由井：我们要告诉你\n"
	.string "我们最喜爱的宝可梦是什么！$"

ThreeIsland_BondBridge_Text_JoyDefeat::
	.string "由井：噢……\n"
	.string "理子！$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
	.string "由井：那很有趣吧？\n"
	.string "我希望我们能再次战斗！$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
	.string "由井：我真的想和理子一起战斗。\p"
	.string "一只宝可梦是不够的。$"

ThreeIsland_BondBridge_Text_MegIntro::
	.string "理子：我们将向你展示\n"
	.string "我们最喜爱的宝可梦。$"

ThreeIsland_BondBridge_Text_MegDefeat::
	.string "理子：噢……\n"
	.string "由井！$"

ThreeIsland_BondBridge_Text_MegPostBattle::
	.string "理子：由井，那很有趣吧？$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
	.string "理子：我想和由井一起战斗。\p"
	.string "一只宝可梦是不够的。$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
	.string "前方是树果森林$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
	.string "索桥\n"
	.string "当你经过时请保持安静。\p"
	.string "前方是树果森林$"

