Route17_Frlg_MapScripts::
	.byte 0

Route17_EventScript_ItemsNotice::
	msgbox Route17_Text_WatchOutForDiscardedItems, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips1::
	msgbox Route17_Text_SameSpeciesGrowDifferentRates, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips2::
	msgbox Route17_Text_PressBToStayInPlace, MSGBOX_SIGN
	end

Route17_EventScript_RouteSign::
	msgbox Route17_Text_RouteSign, MSGBOX_SIGN
	end

Route17_EventScript_BallsNotice::
	msgbox Route17_Text_DontThrowGameThrowBalls, MSGBOX_SIGN
	end

Route17_EventScript_CyclingRoadSign::
	msgbox Route17_Text_CyclingRoadSign, MSGBOX_SIGN
	end

Route17_Text_RaulIntro::
	.string "跟小孩战斗可不是什么赚钱\n"
	.string "的捷径。$"

Route17_Text_RaulDefeat::
	.string "烧坏了！$"

Route17_Text_RaulPostBattle::
	.string "在单车路你会捡到\n"
	.string "一些好的东西。\p"
	.string "如果把它们拿去卖，\n"
	.string "能赚到不少钱。$"

Route17_Text_IsaiahIntro::
	.string "我的身体超棒的，\n"
	.string "对决吧！老兄。$"

Route17_Text_IsaiahDefeat::
	.string "呼！$"

Route17_Text_IsaiahPostBattle::
	.string "我可以把你从这儿撞飞！$"

Route17_Text_VirgilIntro::
	.string "你想去浅红？$"

Route17_Text_VirgilDefeat::
	.string "彻底失败了！$"

Route17_Text_VirgilPostBattle::
	.string "我喜欢骑下坡！$"

Route17_Text_BillyIntro::
	.string "我们是飙车族！\n"
	.string "这条路我们说了算，懂吗！$"

Route17_Text_BillyDefeat::
	.string "冒烟了！$"

Route17_Text_BillyPostBattle::
	.string "你在寻求冒险生活吗？$"

Route17_Text_NikolasIntro::
	.string "让霹雳电球电你一下！$"

Route17_Text_NikolasDefeat::
	.string "安全着陆！$"

Route17_Text_NikolasPostBattle::
	.string "我在废弃的无人发电厂\n"
	.string "遇到了我的霹雳电球。$"

Route17_Text_ZeekIntro::
	.string "我提升了我的宝可梦等级，\n"
	.string "但是它不进化，为什么？$"

Route17_Text_ZeekDefeat::
	.string "为什么，你！$"

Route17_Text_ZeekPostBattle::
	.string "也许有一些宝可梦需要用\n"
	.string "属性石来进化。$"

Route17_Text_JamalIntro::
	.string "我得练习练习！$"

Route17_Text_JamalDefeat::
	.string "唔！\n"
	.string "不错的训练！$"

Route17_Text_JamalPostBattle::
	.string "我一定就是在那儿减肥的没错！$"

Route17_Text_CoreyIntro::
	.string "成为一个逆反的人！$"

Route17_Text_CoreyDefeat::
	.string "啊啊！$"

Route17_Text_CoreyPostBattle::
	.string "准备好为你的信念而战斗！$"

Route17_Text_JaxonIntro::
	.string "漂亮的自行车！\n"
	.string "怎么入手的？$"

Route17_Text_JaxonDefeat::
	.string "可恶！$"

Route17_Text_JaxonPostBattle::
	.string "在斜坡上很难掌控它啊！$"

Route17_Text_WilliamIntro::
	.string "输了，小子！\n"
	.string "我太累了！$"

Route17_Text_WilliamDefeat::
	.string "你满意吗？$"

Route17_Text_WilliamPostBattle::
	.string "我得去打个小盹！$"

Route17_Text_WatchOutForDiscardedItems::
	.string "小提示。\p"
	.string "注意那些丢弃的物品。$"

Route17_Text_SameSpeciesGrowDifferentRates::
	.string "训练家贴士\p"
	.string "每一个宝可梦都是唯一的。\p"
	.string "就算是相同种类和等级的宝可梦，\n"
	.string "它们的能力也不是完全相同的。$"

Route17_Text_PressBToStayInPlace::
	.string "训练家贴士\p"
	.string "在斜坡上时按B键\n"
	.string "能停在原地。$"

Route17_Text_RouteSign::
	.string "17号道路\n"
	.string "玉虹市-浅红市$"

Route17_Text_DontThrowGameThrowBalls::
	.string "小提示！\p"
	.string "不要老是逃跑，\n"
	.string "扔精灵球就可以了！$"

Route17_Text_CyclingRoadSign::
	.string "单车路\n"
	.string "斜坡终止了！$"

