Route6_Frlg_MapScripts::
	.byte 0

Route6_EventScript_UndergroundPathSign::
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route6_Text_RickyIntro::
	.string "是谁？\n"
	.string "竟敢偷听我们讲话！$"

Route6_Text_RickyDefeat::
	.string "我老是赢不了！$"

Route6_Text_RickyPostBattle::
	.string "悄悄话……\n"
	.string "悄悄话……$"

Route6_Text_NancyIntro::
	.string "抱歉！\n"
	.string "我们在讲悄悄话！$"

Route6_Text_NancyDefeat::
	.string "唉！\n"
	.string "我讨厌失败。$"

Route6_Text_NancyPostBattle::
	.string "悄悄话……\n"
	.string "悄悄话……$"

Route6_Text_KeigoIntro::
	.string "这外面没有什么虫子。$"

Route6_Text_KeigoDefeat::
	.string "不！\n"
	.string "你在开玩笑吧！$"

Route6_Text_KeigoPostBattle::
	.string "我喜欢虫子，\n"
	.string "所以我要回到常青森林。$"

Route6_Text_JeffIntro::
	.string "呃？\n"
	.string "你想跟我谈谈？$"

Route6_Text_JeffDefeat::
	.string "太糟糕了……\n"
	.string "我输掉了这场对决……$"

Route6_Text_JeffPostBattle::
	.string "我要带更多的宝可梦，\n"
	.string "这样我才会有安全感。$"

Route6_Text_IsabelleIntro::
	.string "我？\n"
	.string "好的，那就来吧！$"

Route6_Text_IsabelleDefeat::
	.string "事情并没有进展……$"

Route6_Text_IsabellePostBattle::
	.string "我想变得更强。\n"
	.string "你的秘诀是什么？$"

Route6_Text_ElijahIntro::
	.string "我在这附近没见过你。\n"
	.string "你厉害吗？$"

Route6_Text_ElijahDefeat::
	.string "你太厉害了！$"

Route6_Text_ElijahPostBattle::
	.string "是我的宝可梦很弱？\n"
	.string "还是我很差劲？\l"
	.string "你觉得是哪个？$"

Route6_Text_UndergroundPathSign::
	.string "地下通道\n"
	.string "华蓝市-枯叶市$"

