Route14_Frlg_MapScripts::
	.byte 0

Route14_EventScript_RouteSign::
	msgbox Route14_Text_RouteSign, MSGBOX_SIGN
	end

Route14_Text_CarterIntro::
	.string "要想让你的宝可梦学到更强劲\n"
	.string "的技能就要善用技能机。$"

Route14_Text_CarterDefeat::
	.string "不是很好。$"

Route14_Text_CarterPostBattle::
	.string "你已经得到秘传机了吗？宝可梦不会\n"
	.string "轻易忘记从上面学得的技能。$"

Route14_Text_MitchIntro::
	.string "我的鸟类宝可梦已经\n"
	.string "备战完毕。$"

Route14_Text_MitchDefeat::
	.string "看来还是没准备好！$"

Route14_Text_MitchPostBattle::
	.string "我的鸟系宝可梦需要\n"
	.string "学习更强的技能。$"

Route14_Text_BeckIntro::
	.string "玉虹百货大楼\n"
	.string "出售技能学习机。\p"
	.string "技能学习机并不是十分稀少，\n"
	.string "但是拥有它的人也不多。$"

Route14_Text_BeckDefeat::
	.string "啊，你这家伙！$"

Route14_Text_BeckPostBattle::
	.string "让宝可梦学习与它自身属性\n"
	.string "相符的技能。\p"
	.string "这样技能的强劲会有显著提升。$"

Route14_Text_MarlonIntro::
	.string "你教过你的鸟系宝可梦\n"
	.string "如何飞翔了吗？\p"
	.string "你可以跟它一同在天空中\n"
	.string "翱翔！$"

Route14_Text_MarlonDefeat::
	.string "在火焰中击落它！$"

Route14_Text_MarlonPostBattle::
	.string "鸟系宝可梦是我最钟爱的。\n"
	.string "任何其他的宝可梦都让我兴趣索然。$"

Route14_Text_DonaldIntro::
	.string "你听说过传说中\n"
	.string "飞行的幻影吗？$"

Route14_Text_DonaldDefeat::
	.string "为什么？\n"
	.string "为什么我会输？$"

Route14_Text_DonaldPostBattle::
	.string "飞行的幻影指的是\n"
	.string "传说中的鸟系宝可梦。\p"
	.string "有三只：急冻鸟，\n"
	.string "闪电鸟和火焰鸟。$"

Route14_Text_BennyIntro::
	.string "我没有进去过，不过没关系。\n"
	.string "我们出发吧！$"

Route14_Text_BennyDefeat::
	.string "我知道它！$"

Route14_Text_BennyPostBattle::
	.string "输与赢……\n"
	.string "在宽广的天空下皆是浮云。$"

Route14_Text_LukasIntro::
	.string "来吧，开战。\n"
	.string "擂鼓，呐喊，冲锋！$"

Route14_Text_LukasDefeat::
	.string "啊啊啊！\n"
	.string "输了！我输掉了！$"

Route14_Text_LukasPostBattle::
	.string "啊？什么？怎么了？\n"
	.string "你还想干嘛？$"

Route14_Text_IsaacIntro::
	.string "我想打发点时间。\n"
	.string "少废话，开打吧。$"

Route14_Text_IsaacDefeat::
	.string "什么？\n"
	.string "你！？$"

Route14_Text_IsaacPostBattle::
	.string "培育宝可梦真是个累赘。$"

Route14_Text_GeraldIntro::
	.string "这里地方很宽敞，\n"
	.string "所以我们就骑车过来了。$"

Route14_Text_GeraldDefeat::
	.string "失败了！$"

Route14_Text_GeraldPostBattle::
	.string "你把你的宝可梦培育得这么厉害，\n"
	.string "实在太酷了。\p"
	.string "速度即是力量！\n"
	.string "看来你已经领悟到了！$"

Route14_Text_MalikIntro::
	.string "宝可梦对战？\n"
	.string "太激动了！来吧！$"

Route14_Text_MalikDefeat::
	.string "被吹走了！$"

Route14_Text_MalikPostBattle::
	.string "你知道谁是胜者，\n"
	.string "不是你就是我！$"

Route14_Text_RouteSign::
	.string "14号道路\n"
	.string "往西到浅红市$"

Route14_Text_KiriIntro::
	.string "阿雾：惠娜，我们一起试试，\n"
	.string "两个人一起胜率会更高点。$"

Route14_Text_KiriDefeat::
	.string "阿雾：呜，呜……\n"
	.string "我们输了么？$"

Route14_Text_KiriPostBattle::
	.string "阿雾：是因为我太弱的关系么？$"

Route14_Text_KiriNotEnoughMons::
	.string "阿雾：如果你有两只宝可梦\n"
	.string "我们就可以战斗啦。$"

Route14_Text_JanIntro::
	.string "惠娜：走吧，阿雾！\n"
	.string "我们得再度投入修炼！$"

Route14_Text_JanDefeat::
	.string "惠娜：不！\n"
	.string "这不公平！$"

Route14_Text_JanPostBattle::
	.string "惠娜：阿雾，别哭了！\n"
	.string "我们下次要更加努力才行。$"

Route14_Text_JanNotEnoughMons::
	.string "惠娜：你想战斗吗？\n"
	.string "你没有足够的宝可梦。$"
