SafariZone_Center_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end

SafariZone_Center_Text_WhereDidErikGo::
	.string "敦子：我的男朋友阿初到\n"
	.string "哪儿去了？$"

SafariZone_Center_Text_CatchingMonsAsGifts::
	.string "我正在抓宝可梦回家\n"
	.string "作为礼物。$"

