SSAnne_2F_Room3_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
	.string "噢，没错，我见过一些宝可梦\n"
	.string "载着人在水上穿梭！$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
	.string "小树可以用\n"
	.string "居合斩砍倒。\p"
	.string "但记住！\n"
	.string "居合斩是一个秘传机的技巧。\p"
	.string "一旦学会，\n"
	.string "它是不能轻易被遗忘的。$"

