@ Handled by data/scripts/day_care.inc

Route5_PokemonDayCare_Frlg_MapScripts::
	.byte 0

Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "我开着这家培育屋。\p"
	.string "你需要寄养一只\n"
	.string "你的宝可梦吗？$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "欢迎再来。$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "你要寄养哪只宝可梦？$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "好的。\n"
	.string "随时欢迎你再来。$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "好的，我会照顾你的\n"
	.string "{STR_VAR_1}一段时间。$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "过一会儿来见我。$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "你回来的这么快？\p"
	.string "你的{STR_VAR_1}需要和我\n"
	.string "多呆一会儿。$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "想要取回这只宝可梦的话\n"
	.string "需要支付我{STR_VAR_2}元$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "谢谢。\n"
	.string "这是你的宝可梦。$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER}从培育屋爷爷那儿 \n"
	.string "取回了{STR_VAR_1}。$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "哦？你的身上只有\n"
	.string "一只宝可梦了。$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "如果你把那只宝可梦存到我这里，\n"
	.string "你用什么来战斗呢？$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "你的{STR_VAR_1}成长了很多。\n"
	.string "嗯，说实话，真的很多。\p"
	.string "我看看……\n"
	.string "它的等级已经上升了{STR_VAR_2}。\p"
	.string "是不是很棒啊？$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "你的身上已经没有足够的空间，\n"
	.string "所以你不能把这只宝可梦取回。$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "你的钱不够。$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
	.string "きみの\n"
	.string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
	.string "わるいけど　ひでんのわざを　もった\n"
	.string "ポケモンは　あずかれないなぁ$"
