Route3_Frlg_MapScripts::
	.byte 0

Route3_EventScript_Youngster::
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
	end

Route3_EventScript_RouteSign::
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
	end

Route3_Text_TunnelFromCeruleanTiring::
	.string "呼……我最好小睡一下……\n"
	.string "呃……\p"
	.string "那条从华蓝过来的隧道\n"
	.string "省了你们很多事！$"

Route3_Text_ColtonIntro::
	.string "嘿！\n"
	.string "我在常青森林见过你！$"

Route3_Text_ColtonDefeat::
	.string "你又打败了我！$"

Route3_Text_ColtonPostBattle::
	.string "除了你在森林里看到的那些宝可梦以外，\n"
	.string "还有很多其它的宝可梦。$"

Route3_Text_BenIntro::
	.string "嗨！\n"
	.string "我喜欢短裤！\p"
	.string "短裤穿着很舒服让人心情很愉快，\n"
	.string "而且穿起来很方便！$"

Route3_Text_BenDefeat::
	.string "不敢相信！$"

Route3_Text_BenPostBattle::
	.string "你用过宝可梦中心的电脑\n"
	.string "来存放宝可梦吗？\p"
	.string "每个盒子最多可以存放30个宝可梦。$"

Route3_Text_JaniceIntro::
	.string "不好意思！\n"
	.string "你在盯着我看，我没说错吧？$"

Route3_Text_JaniceDefeat::
	.string "你可真厉害！$"

Route3_Text_JanicePostBattle::
	.string "如果你不想战斗的话，\n"
	.string "就不该盯着我看哦！$"

Route3_Text_GregIntro::
	.string "你是一个训练家吗？\n"
	.string "让我们马上对战吧！$"

Route3_Text_GregDefeat::
	.string "要不是因为我没新的宝可梦，\n"
	.string "我就赢了！$"

Route3_Text_GregPostBattle::
	.string "如果电脑里的一个宝可梦寄存箱满了，\n"
	.string "就切换到另一个盒子去。$"

Route3_Text_SallyIntro::
	.string "似乎你总在让着我……\n"
	.string "这真是太有趣了！$"

Route3_Text_SallyDefeat::
	.string "做人要厚道啊！$"

Route3_Text_SallyPostBattle::
	.string "你可以躲开训练家不让他们看到你，\n"
	.string "以此来避开战斗。$"

Route3_Text_CalvinIntro::
	.string "嘿！你没有短裤！\n"
	.string "为什么？$"

Route3_Text_CalvinDefeat::
	.string "输了！\n"
	.string "输了！输了！$"

Route3_Text_CalvinPostBattle::
	.string "我总是穿短裤，在冬天也一样。\n"
	.string "这是我做人的原则。$"

Route3_Text_JamesIntro::
	.string "我要用刚收服的宝可梦\n"
	.string "和你对战。$"

Route3_Text_JamesDefeat::
	.string "平淡无奇！$"

Route3_Text_JamesPostBattle::
	.string "训练过的宝可梦会比野生的更强。$"

Route3_Text_RobinIntro::
	.string "呀！\n"
	.string "你刚才碰到了我的身体？$"

Route3_Text_RobinDefeat::
	.string "结束了？$"

Route3_Text_RobinPostBattle::
	.string "4号道路在月见山脚下。$"

Route3_Text_RouteSign::
	.string "3号道路\n"
	.string "往前走是月见山$"

