OneIsland_TreasureBeach_Frlg_MapScripts::
	.byte 0

OneIsland_TreasureBeach_EventScript_Boy::
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
	end

OneIsland_TreasureBeach_Text_AmaraIntro::
	.string "被波浪冲刷的背部……\n"
	.string "这感觉很美妙。$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
	.string "我输了……\n"
	.string "感觉很糟糕。$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
	.string "这个地方的海水很温暖。$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
	.string "有些好的东西有时候会被\n"
	.string "海浪冲到沙滩上来。\p"
	.string "所以所以我经常来这\n"
	.string "沙滩上碰碰运气。$"

