Route15_Frlg_MapScripts::
	.byte 0

Route15_EventScript_RouteSign::
	msgbox Route15_Text_RouteSign, MSGBOX_SIGN
	end

Route15_Text_KindraIntro::
	.string "我刚刚通过交换得到了新的宝可梦。\n"
	.string "可以和你比试一下吗？$"

Route15_Text_KindraDefeat::
	.string "还差得很远！$"

Route15_Text_KindraPostBattle::
	.string "在交换中取得的宝可梦是无法\n"
	.string "改变其昵称的。\p"
	.string "只有最初得到它的训练家\n"
	.string "能改变昵称。$"

Route15_Text_BeckyIntro::
	.string "你看着软绵绵的，\n"
	.string "所以我应该能打败你。\p"
	.string "我要开始了！$"

Route15_Text_BeckyDefeat::
	.string "不，我判断错了！$"

Route15_Text_BeckyPostBattle::
	.string "我有点怕飙车族。\n"
	.string "它们看起来丑陋且卑鄙！$"

Route15_Text_EdwinIntro::
	.string "只要我吹一声口哨，\n"
	.string "就能召唤出鸟系宝可梦。$"

Route15_Text_EdwinDefeat::
	.string "噢！\n"
	.string "真是个悲剧！$"

Route15_Text_EdwinPostBattle::
	.string "可能我不擅长战斗。\n"
	.string "大概是我把属性弄错了吧。$"

Route15_Text_ChesterIntro::
	.string "嗯？我的鸟儿们在颤抖！\n"
	.string "你很强，我没说错吧？$"

Route15_Text_ChesterDefeat::
	.string "和我想像的一样！$"

Route15_Text_ChesterPostBattle::
	.string "很明显，你不会不了解的，\n"
	.string "其实……\p"
	.string "像地震和地裂这样的技能\n"
	.string "是不会对鸟系宝可梦造成伤害的。$"

Route15_Text_GraceIntro::
	.string "噢，你有一点儿讨人喜欢！\n"
	.string "就像一只可爱的宝可梦！$"

Route15_Text_GraceDefeat::
	.string "你看起来也很可爱！$"

Route15_Text_GracePostBattle::
	.string "我不会怪你。\n"
	.string "我搞得定你的。\l"
	.string "我可是个成熟的女孩。$"

Route15_Text_OliviaIntro::
	.string "我培育宝可梦是为了保护自己，\n"
	.string "因为我是一人军团。$"

Route15_Text_OliviaDefeat::
	.string "宝可梦对我的意义并不是\n"
	.string "简单的输赢。$"

Route15_Text_OliviaPostBattle::
	.string "我喜欢当我回到家时宝可梦上前\n"
	.string "迎接我的那种感觉。\p"
	.string "真的很温暖。$"

Route15_Text_ErnestIntro::
	.string "嘿，小子！来吧！\n"
	.string "这是我从废物们手里得到的战利品！$"

Route15_Text_ErnestDefeat::
	.string "有何不可？$"

Route15_Text_ErnestPostBattle::
	.string "人生苦短。\n"
	.string "当一个坏蛋是很刺激的。\l"
	.string "所以火箭队万岁！$"

Route15_Text_AlexIntro::
	.string "你要是输掉的话，\n"
	.string "就把你身上的钱都交出来，小子！$"

Route15_Text_AlexDefeat::
	.string "不会吧！$"

Route15_Text_AlexPostBattle::
	.string "我刚刚是开玩笑的。\n"
	.string "不要动我的钱呀。$"

Route15_Text_CeliaIntro::
	.string "什么事又酷又刺激？\n"
	.string "当然交换宝可梦！$"

Route15_Text_CeliaDefeat::
	.string "我是说交换！$"

Route15_Text_CeliaPostBattle::
	.string "我经常和我的朋友\n"
	.string "交换宝可梦。$"

Route15_Text_YazminIntro::
	.string "想和我的宝可梦战斗吗？$"

Route15_Text_YazminDefeat::
	.string "我太急躁了！$"

Route15_Text_YazminPostBattle::
	.string "我还是跟弱一点的人训练吧。$"

Route15_Text_RouteSign::
	.string "15号道路\n"
	.string "往西到浅红市$"

Route15_Text_MyaIntro::
	.string "阿力：你很棒。\n"
	.string "帮我训练我弟弟吧？$"

Route15_Text_MyaDefeat::
	.string "阿力：阿铁，你必须集中精力！\n"
	.string "你要专心于你正在做的事！$"

Route15_Text_MyaPostBattle::
	.string "阿力：我们要改变它。\n"
	.string "我要增加我们的训练计划。$"

Route15_Text_MyaNotEnoughMons::
	.string "阿力：你想挑战我们吗？\n"
	.string "你得有两只宝可梦才行。$"

Route15_Text_RonIntro::
	.string "阿铁：我们要是输掉了，\n"
	.string "姐姐她会变得很吓人。$"

Route15_Text_RonDefeat::
	.string "阿铁：呃，不，不……\n"
	.string "对不起姐姐！$"

Route15_Text_RonPostBattle::
	.string "阿铁：呃……\n"
	.string "我希望我有一个温柔的姐姐……$"

Route15_Text_RonNotEnoughMons::
	.string "阿铁：你想和我们姐弟战斗吗？\p"
	.string "你得有两只宝可梦。$"
