Route10_Frlg_MapScripts::
	.byte 0

Route10_EventScript_Unused::
	end

Route10_EventScript_NorthRockTunnelSign::
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
	end

Route10_EventScript_SouthRockTunnelSign::
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
	end

Route10_EventScript_PowerPlantSign::
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
	end

Route10_Text_MarkIntro::
	.string "哇，你历经磨难终于到了我这里？\n"
	.string "也许你也是一个怪兽狂对吗？\l"
	.string "想要看看我的收藏吗？$"

Route10_Text_MarkDefeat::
	.string "啊哼。\n"
	.string "我不会生气的！$"

Route10_Text_MarkPostBattle::
	.string "我还有很多稀有的宝可梦\n"
	.string "放在家里呢$"

Route10_Text_ClarkIntro::
	.string "哈哈-哈哈-啊哈哈$"

Route10_Text_ClarkDefeat::
	.string "哈-啊啊！\n"
	.string "不准笑！\l"
	.string "啊啊-发烧了！啊啊-啊嚏！$"

Route10_Text_ClarkPostBattle::
	.string "啊啊-啊嚏！\n"
	.string "啊嚏！\l"
	.string "抽鼻子，擦鼻涕。$"

Route10_Text_HermanIntro::
	.string "嘿，小子！\n"
	.string "想看我的宝可梦$"

Route10_Text_HermanDefeat::
	.string "喔，不！\n"
	.string "我的宝可梦$"

Route10_Text_HermanPostBattle::
	.string "我讨厌你。\n"
	.string "比我强的人我都不喜欢！$"

Route10_Text_HeidiIntro::
	.string "我已经在宝可梦道馆中辗转\n"
	.string "奋战多时。\p"
	.string "…可总是输多赢少。$"

Route10_Text_HeidiDefeat::
	.string "烦死了！\n"
	.string "有事等我训练完了再说！$"

Route10_Text_HeidiPostBattle::
	.string "我发现一些怪兽狂\n"
	.string "正在附近徘徊的踪迹。\p"
	.string "你想象得出来吗？\n"
	.string "从这山顶往下俯视的样子？$"

Route10_Text_TrentIntro::
	.string "哈！\n"
	.string "这山里的空气真爽！$"

Route10_Text_TrentDefeat::
	.string "它使我的心灵彻底得到了净化！$"

Route10_Text_TrentPostBattle::
	.string "这样的空气里人都像要飞起来了！$"

Route10_Text_CarolIntro::
	.string "我现在有点头晕，\n"
	.string "好久都没有登山了。$"

Route10_Text_CarolDefeat::
	.string "我实在坚持不住了。\n"
	.string "都怪我没有做好充足的准备。$"

Route10_Text_CarolPostBattle::
	.string "这座山里生活的宝可梦\n"
	.string "都是矮矮胖胖的那种……\p"
	.string "我希望能有一种宝可梦，\n"
	.string "它粉色的皮肤上有花瓣花纹！$"

Route10_Text_RockTunnelDetourToLavender::
	.string "岩山隧道\n"
	.string "绕道到紫苑镇$"

Route10_Text_RockTunnel::
	.string "岩山隧道$"

Route10_Text_PowerPlant::
	.string "无人发电厂$"

