FuchsiaCity_SafariZone_Office_Frlg_MapScripts::
	.byte 0

FuchsiaCity_SafariZone_Office_EventScript_Worker1::
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker2::
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker3::
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker4::
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
	.string "我们给园长起了个外号叫\n"
	.string "“呆呆兽”。\p"
	.string "你想象一下，他发起呆来的样子，\n"
	.string "像极了一只呆呆兽。$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
	.string "呆呆兽园长对\n"
	.string "宝可梦非常了解。\p"
	.string "他甚至还收藏了那些灭绝了的\n"
	.string "珍贵的宝可梦的化石。$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
	.string "呆呆兽园长来了这儿一趟，\n"
	.string "但是我完全听不懂他在说什么。\p"
	.string "我觉得他的语言神经出了毛病！$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
	.string "呆呆兽园长正在举办\n"
	.string "一场宣传活动。\p"
	.string "努力向野生原野区\n"
	.string "最深处进发。\p"
	.string "如果你能抵达终点，\n"
	.string "你没准会得到一件非常棒的奖品哦。$"

