Route13_Frlg_MapScripts::
	.byte 0

Route13_EventScript_TrainerTips1::
	msgbox Route13_Text_LookToLeftOfThatPost, MSGBOX_SIGN
	end

Route13_EventScript_TrainerTips2::
	msgbox Route13_Text_SelectToSwitchItems, MSGBOX_SIGN
	end

Route13_EventScript_RouteSign::
	msgbox Route13_Text_RouteSign, MSGBOX_SIGN
	end

Route13_Text_SebastianIntro::
	.string "我的飞行属性宝可梦\n"
	.string "想要和你比试！$"

Route13_Text_SebastianDefeat::
	.string "我的波波比比鸟组合\n"
	.string "居然输了？$"

Route13_Text_SebastianPostBattle::
	.string "虽然输了\n"
	.string "但我的宝可梦看起来很高兴。$"

Route13_Text_SusieIntro::
	.string "我想说我肯定比一个孩子要厉害。$"

Route13_Text_SusieDefeat::
	.string "喔！\n"
	.string "我输了！$"

Route13_Text_SusiePostBattle::
	.string "我想要成为一名强大的训练家。\n"
	.string "如你所见，我很努力的训练。$"

Route13_Text_ValerieIntro::
	.string "哇塞！\n"
	.string "你的徽章太酷了！$"

Route13_Text_ValerieDefeat::
	.string "这还不够！$"

Route13_Text_ValeriePostBattle::
	.string "你这些徽章都是从\n"
	.string "道馆馆主手里得到的，我懂的！$"

Route13_Text_GwenIntro::
	.string "我可爱的宝可梦想要和你\n"
	.string "亲热亲热。$"

Route13_Text_GwenDefeat::
	.string "干得漂亮！\n"
	.string "你赢了！$"

Route13_Text_GwenPostBattle::
	.string "要想让你的宝可梦更强大，\n"
	.string "就得在战斗中磨练它们。$"

Route13_Text_AlmaIntro::
	.string "有一次我去山洞探险的时候，\n"
	.string "捡到了一个速度增强剂。$"

Route13_Text_AlmaDefeat::
	.string "噢，太糟糕了！\n"
	.string "我弄得一团糟！$"

Route13_Text_AlmaPostBattle::
	.string "我的宝可梦速度之高便是\n"
	.string "拜速度增强剂所赐。$"

Route13_Text_PerryIntro::
	.string "风向如此之顺畅。\n"
	.string "我一定能赢你！$"

Route13_Text_PerryDefeat::
	.string "看来风向改变了！$"

Route13_Text_PerryPostBattle::
	.string "我输了。\n"
	.string "我想我要使用飞翔回家了。$"

Route13_Text_LolaIntro::
	.string "好，那开始我们的游戏吧，小甜心。$"

Route13_Text_LolaDefeat::
	.string "哎！\n"
	.string "讨厌啦你！$"

Route13_Text_LolaPostBattle::
	.string "我很好奇哪一种宝可梦会厉害一点？\n"
	.string "雄性的还是雌性的？$"

Route13_Text_SheilaIntro::
	.string "你想跟我的宝可梦战斗吗？$"

Route13_Text_SheilaDefeat::
	.string "已经结束了吗？$"

Route13_Text_SheilaPostBattle::
	.string "实际上我不知道\n"
	.string "任何关于宝可梦的知识。\p"
	.string "至于我用的这些……\n"
	.string "我抓住它们只是因为它们好看！$"

Route13_Text_JaredIntro::
	.string "你在看什么呢？$"

Route13_Text_JaredDefeat::
	.string "当！\n"
	.string "机关被卸掉了！$"

Route13_Text_JaredPostBattle::
	.string "迷路了！$"

Route13_Text_RobertIntro::
	.string "我经常和鸟系宝可梦一起。\n"
	.string "我毕生精力都倾注于此。$"

Route13_Text_RobertDefeat::
	.string "用力！$"

Route13_Text_RobertPostBattle::
	.string "我希望我能像\n"
	.string "波波和比比鸟一样飞翔……$"

Route13_Text_LookToLeftOfThatPost::
	.string "训练家贴士\p"
	.string "快看！\n"
	.string "注意左边的公告！$"

Route13_Text_SelectToSwitchItems::
	.string "训练家贴士\p"
	.string "在道具窗口按选择键\n"
	.string "设置快捷物品。$"

Route13_Text_RouteSign::
	.string "13号道路\n"
	.string "往北到寂静桥$"

