OneIsland_KindleRoad_Frlg_MapScripts::
	.byte 0

OneIsland_KindleRoad_EventScript_RouteSign::
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_EventScript_EmberSpaSign::
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_Text_MariaIntro::
	.string "天气真好！\n"
	.string "最适合战斗了！$"

OneIsland_KindleRoad_Text_MariaDefeat::
	.string "哎哟！$"

OneIsland_KindleRoad_Text_MariaPostBattle::
	.string "请不要把水花溅到我脸上！\n"
	.string "会把我的妆弄花了。$"

OneIsland_KindleRoad_Text_AbigailIntro::
	.string "我快被晒伤了……$"

OneIsland_KindleRoad_Text_AbigailDefeat::
	.string "呃，你真糟糕。$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
	.string "我喜欢你的帽子。\n"
	.string "也许我也应该戴一顶……$"

OneIsland_KindleRoad_Text_FinnIntro::
	.string "从这里望过去，灯火山的塔\n"
	.string "冲上了云霄。$"

OneIsland_KindleRoad_Text_FinnDefeat::
	.string "呃，你很强吗？$"

OneIsland_KindleRoad_Text_FinnPostBattle::
	.string "巨大的天空笼罩着四周。$"

OneIsland_KindleRoad_Text_GarrettIntro::
	.string "我是为了休息才来游泳，\n"
	.string "没想到你会来挑战我？$"

OneIsland_KindleRoad_Text_GarrettDefeat::
	.string "喂，怎么会……\n"
	.string "你真是太厉害了！$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
	.string "你也该自己下水游游，\n"
	.string "而不是一直在冲浪。$"

OneIsland_KindleRoad_Text_TommyIntro::
	.string "等等！等一下！\n"
	.string "我这一杆肯定有货！$"

OneIsland_KindleRoad_Text_TommyDefeat::
	.string "我又输了……$"

OneIsland_KindleRoad_Text_TommyPostBattle::
	.string "我不仅输了，\n"
	.string "还把那只大的放走了！$"

OneIsland_KindleRoad_Text_SharonIntro::
	.string "你能帮我我训练一下吗？$"

OneIsland_KindleRoad_Text_SharonDefeat::
	.string "你伤害了我。$"

OneIsland_KindleRoad_Text_SharonPostBattle::
	.string "显然，你很有能力。\n"
	.string "我喜欢你！$"

OneIsland_KindleRoad_Text_TanyaIntro::
	.string "今天我们也要训练！$"

OneIsland_KindleRoad_Text_TanyaDefeat::
	.string "我真愚蠢！$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
	.string "从现在起我要更努力地训练。$"

OneIsland_KindleRoad_Text_SheaIntro::
	.string "每天早上吃早饭之前，\n"
	.string "我都要到这座岛周围游泳。$"

OneIsland_KindleRoad_Text_SheaDefeat::
	.string "呼……\n"
	.string "呼……$"

OneIsland_KindleRoad_Text_SheaPostBattle::
	.string "我输了是因为\n"
	.string "我跑步跑得没有力气了……$"

OneIsland_KindleRoad_Text_HughIntro::
	.string "要穿着得体地去战斗！\n"
	.string "把那些多余的装备抛开！$"

OneIsland_KindleRoad_Text_HughDefeat::
	.string "为什么是我？！$"

OneIsland_KindleRoad_Text_HughPostBattle::
	.string "现在那些军队的艺术家们\n"
	.string "都变得很时尚了……$"

OneIsland_KindleRoad_Text_BryceIntro::
	.string "知道么？当你在野外时，\n"
	.string "每种东西尝起来都很美味。$"

OneIsland_KindleRoad_Text_BryceDefeat::
	.string "啊，呼……$"

OneIsland_KindleRoad_Text_BrycePostBattle::
	.string "火山地区的水很好喝。$"

OneIsland_KindleRoad_Text_ClaireIntro::
	.string "我们的午餐吃得很饱，\n"
	.string "你想和我们战斗帮助我们消化吗？$"

OneIsland_KindleRoad_Text_ClaireDefeat::
	.string "这让我浑身都出汗了。$"

OneIsland_KindleRoad_Text_ClairePostBattle::
	.string "我该怎么办？\n"
	.string "我又饿了。$"

OneIsland_KindleRoad_Text_KiaIntro::
	.string "阿幸：我哥哥和我\n"
	.string "是一个很可怕的组合！$"

OneIsland_KindleRoad_Text_KiaDefeat::
	.string "阿幸：啊？！\n"
	.string "我无法相信！$"

OneIsland_KindleRoad_Text_KiaPostBattle::
	.string "阿幸：怎么会有人\n"
	.string "比我哥哥更厉害？$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
	.string "阿幸：如果你想和我们战斗，\n"
	.string "你必须带着两只宝可梦。$"

OneIsland_KindleRoad_Text_MikIntro::
	.string "阿和：和阿幸一起，\n"
	.string "我不惧怕任何事情！$"

OneIsland_KindleRoad_Text_MikDefeat::
	.string "阿和：哇！\n"
	.string "够了！$"

OneIsland_KindleRoad_Text_MikPostBattle::
	.string "阿和：我和阿幸的组合\n"
	.string "怎么会输？$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
	.string "阿和：嘿，你想和我们俩战斗吗？\p"
	.string "你得带着至少两只宝可梦。$"

OneIsland_KindleRoad_Text_RouteSign::
	.string "这是热气之路。\p"
	.string "直走去灯火山。$"

OneIsland_KindleRoad_Text_EmberSpaSign::
	.string "点燃你火热的心！\n"
	.string "灯火温泉$"

